### ISSUE TITLE
App crashes if TitleBarButton params don't have a font

### ISSUE THREAD

**Issue by osadchuk** [wix/react-native-navigation#1105]
### Issue Description

App will crash if a `TitleBarButton` instance's `buttonParams.font` is null. We encountered this bug when updating the contextual menu buttons, but it would presumably happen otherwise.

### Steps to Reproduce / Code Snippets / Screenshots

In our case, the steps to reproduce were:

1. Call `showContextualMenu()` with no right buttons
1. Call `showContextualMenu()` again, this time specifying button(s) to show

Stack trace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.reactnativenavigation.params.StyleParams$Font.hasFont()' on a null object reference
at com.reactnativenavigation.views.TitleBarButton.createMenuItem(TitleBarButton.java:45)
at com.reactnativenavigation.views.TitleBarButton.addToMenu(TitleBarButton.java:34)
at com.reactnativenavigation.views.TitleBar.addButtonInReverseOrder(TitleBar.java:155)
at com.reactnativenavigation.views.ContextualMenu.addButtonsToContextualMenu(ContextualMenu.java:51)
at com.reactnativenavigation.views.ContextualMenu.setButtons(ContextualMenu.java:40)
at com.reactnativenavigation.views.ContextualMenu.<init>(ContextualMenu.java:29)
at com.reactnativenavigation.views.TopBar.showContextualMenu(TopBar.java:123)
at com.reactnativenavigation.screens.Screen.showContextualMenu(Screen.java:305)
at com.reactnativenavigation.screens.ScreenStack$15.run(ScreenStack.java:347)
at com.reactnativenavigation.screens.ScreenStack$15.run(ScreenStack.java:344)
at com.reactnativenavigation.screens.ScreenStack.performOnScreen(ScreenStack.java:381)
at com.reactnativenavigation.screens.ScreenStack.showContextualMenu(ScreenStack.java:344)
 at com.reactnativenavigation.layouts.SingleScreenLayout.showContextualMenu(SingleScreenLayout.java:275)
 at com.reactnativenavigation.controllers.Modal.showContextualMenu(Modal.java:58)
 at com.reactnativenavigation.controllers.ModalController.showContextualMenu(ModalController.java:135)
at com.reactnativenavigation.controllers.NavigationActivity.showContextualMenu(NavigationActivity.java:351)
at com.reactnativenavigation.controllers.NavigationCommandsHandler$26.run(NavigationCommandsHandler.java:413)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/Debug

We have a fix for this in our fork that also has the fix for #1095; if you'd like a PR for both let me know! Thanks!

**Comment by guyca** [comment]
Hey @osadchuk 
A pr would be great, thanks. 👍

**Comment by osadchuk** [comment]
Will do - it also has a fix to support `disableIconTint` on Android, which I'd done a while back but forgot to log as an issue. (Not sure if that's been fixed in the interim.)
