### ISSUE TITLE
Problem with SET while doing rotation

### ISSUE THREAD

**Issue by Antoine-C** [wix/react-native-navigation#1237]
Hi,

Some context before asking: 

- We're using SET with an Image
- We have two screens, let's say A and B.
- In screen "A" we have a ListView containing images.
- In screen "B" we have a fullscreen image (the one the user clicked on screen A)

Our image in screen "B" has a width/height set with the component state, the width/height change when there's a rotation but the image doesn't update its dimensions. If I remove the SharedElementTransition tag it's working as expected.

It seems like the sharedElementTransition children's dimension is calculated once and never updated.

**Screen A (everything works well in this screen)**

```javascript
[...]
<SharedElementTransition sharedElementId={`SET${Id}`} style={{flex: 1}}>
    <Image style={{height: '100%', width: '100%'}} source={{uri: 'https://facebook.github.io/react/img/logo_og.png'}} />;
</SharedElementTransition>
[...]
```

**Screen B**

```javascript
render() {
 const { width, height } = this.state; // Successfuly update on orientation changed
// Example : Portrait (width = 600, height = 900)
// Landscape (width = 900, height = 600)

 return (
  <View style={{flex:1}}>
      <SharedElementTransition
                sharedElementId={this.props.sharedImageId}
                showDuration={500}
                hideDuration={500}
                animateClipBounds={true}
                showInterpolation={{type: 'linear', easing: 'FastOutSlowIn'}}
                hideInterpolation={{type: 'linear', easing:'FastOutSlowIn'}}
              >
                <Image style={{width, height}} fadeDuration={0} source={{uri}} />
        </SharedElementTransition>
    </View>
 )
}
```

We tried a lot of things like using these styles for our image to expand to its parent boundaries

```javascript
{{flex: 1, height: null, width: null}}
```

The weird thing is even if we set a huge size like width = 1500 and height = 1500 it doesn't care about orientation change. If you start on Portrait mode and you switch to Landscape it's still keeping the portrait mode width. But the SharedElementTransition isn't ! it's adapting well to layout change.

_Here everything is good_
![portrait](https://cloud.githubusercontent.com/assets/3541876/25948595/7dbdd828-3654-11e7-8f02-a4f1d8f53c2e.png)

_Landscape mode _
![landscape](https://cloud.githubusercontent.com/assets/3541876/25948612/99130f76-3654-11e7-963e-c23dac3f88b6.png)

As you can see the white space is our SharedElementTransition and it's taking up the whole screen but its children, the Image in our case, is not updating its width/height :sigh:

Do you have any ideas ?

Thank's

---
### Environment
* React Native Navigation version: v1.1.19
* React Native version: v0.44
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device / Android 6.0 - 7.1.1 / Debug and Release

**Comment by guyca** [comment]
Hey
I notice you're running a fairly old version of rnn. Would be nice if you try upgrading just to be on the safe side.
Did you try adding `justifyContent` to the `SharedElementTransition` in Screen B?

**Comment by Antoine-C** [comment]
Hi 

Thank's for your answer, I tried using justifyContent and updating RNN to 1.1.70 and there is no improvement.

**Comment by guyca** [comment]
Could you upload an example where I can reproduce this issue? I tried the screens in the example app, the behave as expected after screen rotation.

**Comment by Antoine-C** [comment]
I'll try to reproduce my problem with the example. I'll keep you posted.

**Comment by guyca** [comment]
Thanks, appreciate it 👍

**Comment by Antoine-C** [comment]
Hi @guyca 

I've setup an example [Antoine-C/wix-react-native-navigation](https://github.com/Antoine-C/wix-react-native-navigation).

The only file that matters is [src/screens/set/HeroScreen.js](https://github.com/Antoine-C/wix-react-native-navigation/blob/master/src/screens/set/HeroScreen.js)

It's lighter than the original one so we can focus only on what's matter here, but after debugging it a bit more I found what's causing the problem. It's the [animateClipBounds={true}](https://github.com/Antoine-C/wix-react-native-navigation/blob/master/src/screens/set/HeroScreen.js#L72) props. If I remove it the image is adapting well to the screen height / width.

Is it expected behavior ?

Thank's

**Comment by guyca** [comment]
@Antoine-C very interesting. In the example app, both SET screens also use `animateClipBounds` and I didn't notice this issue. I'll clone your app and keep you posted, thanks 👍

**Comment by tafelito** [comment]
Hey Guys, I'm having an issue with SET too, not related I think, but when I use animateClipBounds={true} my app crashes.

This is the crash log

```
-19731/com.gettingstartedreactnativenav E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.gettingstartedreactnativenav, PID: 19731
java.lang.NullPointerException: Attempt to invoke interface method 'android.graphics.Matrix com.facebook.drawee.drawable.ScalingUtils$ScaleType.getTransform(android.graphics.Matrix, android.graphics.Rect, int, int, float, float)' on a null object reference
    at com.facebook.drawee.drawable.ScalingUtils$InterpolatingScaleType.getTransform(ScalingUtils.java:487)
    at com.facebook.drawee.drawable.ScaleTypeDrawable.configureBounds(ScaleTypeDrawable.java:190)
    at com.facebook.drawee.drawable.ScaleTypeDrawable.setScaleType(ScaleTypeDrawable.java:86)
    at com.facebook.drawee.generic.GenericDraweeHierarchy.setActualImageScaleType(GenericDraweeHierarchy.java:396)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementAnimatorCreator.createImageTransformAnimator(SharedElementAnimatorCreator.java:173)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementAnimatorCreator.create(SharedElementAnimatorCreator.java:66)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementAnimatorCreator.createShow(SharedElementAnimatorCreator.java:35)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementsAnimator$1.createTransitionAnimators(SharedElementsAnimator.java:61)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementsAnimator$1.createShowAnimators(SharedElementsAnimator.java:35)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementsAnimator$1.run(SharedElementsAnimator.java:22)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElements$1.run(SharedElements.java:64)
    at com.reactnativenavigation.utils.ViewUtils$1.onPreDraw(ViewUtils.java:41)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2510)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
    at android.view.Choreographer.doCallbacks(Choreographer.java:695)
    at android.view.Choreographer.doFrame(Choreographer.java:631)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7229)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)                                                                
```

and this is my SET on my second screen

```
<View
        style={{
          flex: 1,
          flexDirection: "row",
          justifyContent: "flex-end",
          backgroundColor: "#fff",
        }}
      >
        <SharedElementTransition
          sharedElementId={"SharedTextId"}
          style={{ height: 100, width: 120, }}
          animateClipBounds={true}
          showDuration={600}
          hideDuration={400}
          showInterpolation={{
            type: "path",
            controlX1: "0.5",
            controlY1: "1",
            controlX2: "0",
            controlY2: "0.5",
            easing: "FastOutSlowIn",
          }}
          hideInterpolation={{
            type: "path",
            controlX1: "0.5",
            controlY1: "0",
            controlX2: "1",
            controlY2: "0.5",
            easing: "FastOutSlowIn",
          }}
        >
          <Image
            style={{
              height: 100,
              width: 100,
            }}
            source={require("../images/puzzle-red.png")}
            fadeDuration={0}
          />
        </SharedElementTransition>
      </View>
```

Any ideas what could be the issue?

**Comment by guyca** [comment]
@tafelito please open a new issue.

**Comment by tafelito** [comment]
@guyca just did, thanks!

**Comment by Antoine-C** [comment]
Hi @guyca any chances you've had the time to look up this issue ?

Thank's
