### ISSUE TITLE
App crashes while scrolling in a collapsing header screen

### ISSUE THREAD

**Issue by Komeyl94** [wix/react-native-navigation#1248]
### Issue Description
Hi there,
I have a screen which it contains of a FlatList and a header with background image and text on top, I  implemented the collapsing header in that screen but every time I scroll the app crashes, could anyone help me on this issue?

- Also my FlatList is wrapped inside a ScrollView

### My navigatorStyle
```
static navigatorStyle = {
	drawUnderTabBar: true,
	navBarButtonColor: '#ffffff',
	navBarTextColor: '#ffffff',
	collapsingToolBarImage: require('./../img/bg2.jpg'),
	collapsingToolBarCollapsedColor: '#0f2362',
	navBarBackgroundColor: '#eeeeee'
};
```

---
### Environment
* React Native Navigation version: 1.1.65
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Android 7.1.0

**Comment by guyca** [comment]
Hey @Komeyl94 
Can you provide stack trace from adb?

**Comment by PARAGJYOTI** [comment]
Same issue here .

**Comment by guyca** [comment]
@PARAGJYOTI With out a stack trace there's not much I can do.

**Comment by jp928** [comment]
@guyca
I think most of rn developer come from Javascript background, they don't know how to monitor exceptions from java code.

**Comment by AriaEdo** [comment]
@guyca I had same issue, but not it happen just before screen showing.
`
"react-native-navigation": "^1.1.84"
`

Source

```
import React from 'react'
import { View } from 'react-native'

export default class NewsDetail extends React.Component {
    static navigatorStyle = {
        collapsingToolBarImage: require('./../../../assets/thumbnails/2.jpg'),
    }

    constructor(props) {
		super(props)
    }

    render() {
        return (
            <View>
                <Text>Test</Text>
            </View>
        )
    }
}
```

Here the log

```
E/BufferQueueCore(  173): [Starting com.mki.sukaoncom] setDefaultMaxBufferCount: setting count to 3, previous is 2 
E/Zygote  (17419): MountEmulatedStorage()
E/Zygote  (17419): v2
E/SELinux (17419): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
E/art     (17419): setrlimit(RLIMIT_CORE) failed for pid 17419: Operation not permitted
E/BufferQueueCore(  173): [com.mki.sukaoncom/com.mki.sukaoncom.MainActivity] setDefaultMaxBufferCount: setting count to 3, previous is 2 
E/SPRDHWComposer(  173): util[1784] err:L1 blending flag:100!
E/SPRDHWComposer(  173): util[1784] err:L1 blending flag:100!
E/SPRDHWComposer(  173): util[1784] err:L1 blending flag:100!
E/Vold    (  172): Failed to find mounted volume for /storage/extSdCard/Android/data/com.mki.sukaoncom/cache/
E/BufferQueueCore(  173): [Starting com.mki.sukaoncom] setDefaultMaxBufferCount: setting count to 3, previous is 2 
E/BufferQueueCore(  173): [com.mki.sukaoncom/com.reactnativenavigation.controllers.NavigationActivity] setDefaultMaxBufferCount: setting count to 3, previous is 2 
E/AndroidRuntime(17419): FATAL EXCEPTION: main
E/AndroidRuntime(17419): Process: com.mki.sukaoncom, PID: 17419
E/AndroidRuntime(17419): java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
E/AndroidRuntime(17419): 	at android.text.TextUtils.ellipsize(TextUtils.java:1124)
E/AndroidRuntime(17419): 	at android.text.TextUtils.ellipsize(TextUtils.java:1099)
E/AndroidRuntime(17419): 	at android.text.TextUtils.ellipsize(TextUtils.java:1079)
E/AndroidRuntime(17419): 	at com.reactnativenavigation.views.collapsingToolbar.CollapsingTextView.calculateText(CollapsingTextView.java:140)
E/AndroidRuntime(17419): 	at com.reactnativenavigation.views.collapsingToolbar.CollapsingTextView.calculateTextToDraw(CollapsingTextView.java:119)
E/AndroidRuntime(17419): 	at com.reactnativenavigation.views.collapsingToolbar.CollapsingTextView.onDraw(CollapsingTextView.java:110)
E/AndroidRuntime(17419): 	at android.view.View.draw(View.java:16536)
E/AndroidRuntime(17419): 	at android.widget.FrameLayout.draw(FrameLayout.java:598)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15466)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayList(View.java:15488)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
E/AndroidRuntime(17419): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
E/AndroidRuntime(17419): 	at android.view.View.updateDisplayListIfDirty(View.java:15426)
E/AndroidRuntime(17419): 	at android.view.View.getDisplayLis
E/android.os.Debug(  729): ro.product_ship = true
E/android.os.Debug(  729): ro.debug_level = 0x4f4c
E/BufferQueueCore(  173): [Application Error: com.mki.sukaoncom] setDefaultMaxBufferCount: setting count to 3, previous is 2 
E/SQLiteLog(15828): (284) automatic index on crash_info_summary(package_name_touched)
E/Vold    (  172): Failed to find mounted volume for /storage/extSdCard/Android/data/com.sec.android.app.launcher/cache/
E/Vold    (  172): Failed to find mounted volume for /storage/extSdCard/Android/data/com.sec.android.app.launcher/cache/
E/Vold    (  172): Failed to find mounted volume for /storage/extSdCard/Android/data/com.sec.android.app.launcher/cache/
E/BufferQueueCore(  173): [com.sec.android.app.launcher/com.android.launcher2.Launcher] setDefaultMaxBufferCount: setting count to 3, previous is 2 
```

**Comment by pqkluan** [comment]
I'm assuming the issue is either solved or no longer existed since there is no activity in last six months. Feel free to re-open if needed.

**Comment by nitish24p** [comment]
@pqkluan Nopes this isnt fix.. I'm on version 1.1.314 and it still persists

**Comment by nitish24p** [comment]
Stack Trace
```

02-06 17:12:57.014 10466 10466 E InputEventReceiver: Exception dispatching input event.
02-06 17:12:57.014 10466 10466 D AndroidRuntime: Shutting down VM
02-06 17:12:57.016 10466 10466 E ACRA    : ACRA caught a NullPointerException for com.kyepot.india.chitfund
02-06 17:12:57.016 10466 10466 E ACRA    : java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getScrollY()' on a null object reference
02-06 17:12:57.016 10466 10466 E ACRA    : 	at com.reactnativenavigation.views.collapsingToolbar.CollapseCalculator.saveInitialTouchY(CollapseCalculator.java:261)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at com.reactnativenavigation.views.collapsingToolbar.CollapseCalculator.updateInitialTouchY(CollapseCalculator.java:239)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at com.reactnativenavigation.views.collapsingToolbar.CollapseCalculator.calculate(CollapseCalculator.java:101)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at com.reactnativenavigation.views.collapsingToolbar.ScrollListener.onTouch(ScrollListener.java:28)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at com.reactnativenavigation.views.collapsingToolbar.CollapsingTitleBar.onTouch(CollapsingTitleBar.java:130)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.View.dispatchTouchEvent(View.java:9939)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.View.dispatchPointerEvent(View.java:10163)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6284)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6336)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:613)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:751)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.os.Looper.loop(Looper.java:154)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:6077)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
02-06 17:12:57.016 10466 10466 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
02-06 17:12:57.062  1268  1268 E SELinux : avc:  denied  { find } for service=meminfo pid=10745 uid=10135 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
```

**Comment by UADACID** [comment]
any solve this issue ?
