### ISSUE TITLE
Using `react-native-image-picker`, crash～～

### ISSUE THREAD

**Issue by Calvin92** [wix/react-native-navigation#1257]
When I select `take a photo` or `choose from library` ，App crashed～～

Error message ：
```
05-17 15:14:14.645 16467-16513/com.aotumeeting E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                                 Process: com.aotumeeting, PID: 16467
                                                                 java.lang.UnsupportedOperationException: NavigationActivity must implement OnImagePickerPermissionsCallback
                                                                     at com.imagepicker.ImagePickerModule.permissionsCheck(ImagePickerModule.java:594)
                                                                     at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:225)
                                                                     at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:203)
                                                                     at com.imagepicker.ImagePickerModule$2.onTakePhoto(ImagePickerModule.java:159)
                                                                     at com.imagepicker.utils.UI$1.onClick(UI.java:54)
                                                                     at android.support.v7.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1045)
                                                                     at android.widget.AdapterView.performItemClick(AdapterView.java:315)
                                                                     at android.widget.AbsListView.performItemClick(AbsListView.java:1193)
                                                                     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3231)
                                                                     at android.widget.AbsListView$3.run(AbsListView.java:4214)
                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                     at android.os.Looper.loop(Looper.java:207)
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                     at java.lang.Thread.run(Thread.java:818)
```

**Comment by Calvin92** [comment]
```
java.lang.UnsupportedOperationException: NavigationActivity must implement OnImagePickerPermissionsCallback
```

Which file I can modify to  implement OnImagePickerPermissionsCallback?

**Comment by jp928** [comment]
@Calvin92

Hi, this is because navigationActivity implments permssionAwareAcvitiy. the fix is quite straightfowrd. I had fork a react-native-image-picker to solve this:
https://github.com/jp928/react-native-image-picker/tree/develop/android/src/main/java/com/imagepicker

I had made a PR to them but not approved yet. if you check the imagePickerMoudule.java u might find I add an addtional check 

'''java
activity instanceof PermissionAwareActivity
'''

hope this help, cheers

**Comment by Calvin92** [comment]
@jp928 What an awesome solution!!!   It helps me a lot.

Many thanks~!
