### ISSUE TITLE
[Bug] Collapsing Header Scroll Random App Crash

### ISSUE THREAD

**Issue by IbrahimAmin** [wix/react-native-navigation#1284]
### Issue Description

Random app crashes tied to collapsing header implementation when scrolling up or down.

### Logs running "adb logcat *:E"

```
05-23 14:36:02.785 16453 16453 E AndroidRuntime: FATAL EXCEPTION: main
05-23 14:36:02.785 16453 16453 E AndroidRuntime: Process: com.myalistguest, PID: 16453
05-23 14:36:02.785 16453 16453 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.views.collapsingToolbar.CollapsingTopBarReactHeader.collapse(float)' on a null object reference
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.views.collapsingToolbar.ViewCollapser$3.onAnimationUpdate(ViewCollapser.java:76)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.views.collapsingToolbar.ViewCollapser$4.onAnimationUpdate(ViewCollapser.java:94)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:978)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:642)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:589)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.views.collapsingToolbar.ViewCollapser.fling(ViewCollapser.java:113)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.views.collapsingToolbar.ViewCollapser.fling(ViewCollapser.java:72)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.views.collapsingToolbar.CollapsingTopBar.fling(CollapsingTopBar.java:144)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.screens.CollapsingSingleScreen$3.onFling(CollapsingSingleScreen.java:86)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.views.collapsingToolbar.CollapseCalculator$1.onFling(CollapseCalculator.java:65)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:712)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.views.collapsingToolbar.CollapseCalculator.calculate(CollapseCalculator.java:102)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.views.collapsingToolbar.ScrollListener.onTouch(ScrollListener.java:28)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.views.collapsingToolbar.ScrollViewDelegate.didInterceptTouchEvent(ScrollViewDelegate.java:33)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.reactnativenavigation.views.CollapsingContentView.dispatchTouchEvent(CollapsingContentView.java:39)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2260)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2453)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1755)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2776)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2402)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9590)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4436)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4292)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3816)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3875)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3841)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3971)
05-23 14:36:02.785 16453 16453 E AndroidRuntime: 	at android.view.ViewRootImpl$In
05-23 14:36:02.787  1105  1115 E ActivityManager: App crashed! Process: com.myalistguest
```
### Code

```js
//Invoked inside a Tab in TabBasedApp
this.props.navigator.push({
            screen: 'CreateOuting',
            title: 'Create Outing',
            animated: true,
            navigatorStyle: {
                collapsingToolBarCollapsedColor: '#AE9156',
                collapsingToolBarImage: GLOBAL.BASE_URL + rowData.img
            },
            passProps: {
                selectedVenue: rowData
            }
});

//Component render function holding a simple scrollview
render() {
        return (
            <ScrollView style={Styles.container}>
                <StatusBar backgroundColor='#9F854F' />
                ...
            </ScrollView>
        );
};
```

### Video demonstrating the behavior

https://youtu.be/Uf9pGSSGty4

I tried digging and searching a little bit and i found out that it breaks here for some reason the header is returned as null so it can't perform a collapse on a null object

### ViewCollapser.java line 71

<img width="1440" alt="screen shot 2017-05-24 at 11 47 52 am" src="https://cloud.githubusercontent.com/assets/7399945/26397531/e9089f4c-4076-11e7-973b-022f137d1931.png">

---
### Environment
* React Native Navigation version: Latest
* React Native version: 0.43.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Tested on USB(HTC One_M8 dual sim - 6.0) & Emulator(Nexus_5X_API_25(AVD) - 7.1.1)

**Comment by IbrahimAmin** [comment]
Haha i guess i kinda fixed it and it looks silly cuz the ui is now working as it should and i only added an if statement to check if header is null, I don't know what to say and what causes the header to be sent as null any way but for now this did it for me

```
if(header!= null) {
        header.collapse((Float) animation.getAnimatedValue());
}
```

**Comment by guyca** [comment]
Hey @IbrahimAmin Thanks for the details report, I already looking into the issue - hope to publish a fix by tomorrow.

**Comment by nitish24p** [comment]
This thing still causes a crash on my app
```
GROUP_VIEW: {
    title: GROUP_VIEW_HEADER,
    navigatorStyle: {
      //navBarHideOnScroll: false,
      navBarBackgroundColor: '#4dbce9', 
      collapsingToolBarImage:
        'https://url.com',
      navBarTranslucent: true, 
      showTitleWhenExpended: true, 
      collapsingToolBarCollapsedColor: 'green',
      collapsingToolBarExpendedColor: 'red'
    },
    navigatorButtons: {
      leftButtons: [],
      rightButtons: []
    }
```
