### ISSUE TITLE
App crashing when using animateClipBounds={true}

### ISSUE THREAD

**Issue by tafelito** [wix/react-native-navigation#1295]
Hey guys, I'm having an issue with SET too, not related I think, but when I use animateClipBounds={true} my app crashes.

This is the crash log

```
-19731/com.gettingstartedreactnativenav E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.gettingstartedreactnativenav, PID: 19731
java.lang.NullPointerException: Attempt to invoke interface method 'android.graphics.Matrix com.facebook.drawee.drawable.ScalingUtils$ScaleType.getTransform(android.graphics.Matrix, android.graphics.Rect, int, int, float, float)' on a null object reference
    at com.facebook.drawee.drawable.ScalingUtils$InterpolatingScaleType.getTransform(ScalingUtils.java:487)
    at com.facebook.drawee.drawable.ScaleTypeDrawable.configureBounds(ScaleTypeDrawable.java:190)
    at com.facebook.drawee.drawable.ScaleTypeDrawable.setScaleType(ScaleTypeDrawable.java:86)
    at com.facebook.drawee.generic.GenericDraweeHierarchy.setActualImageScaleType(GenericDraweeHierarchy.java:396)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementAnimatorCreator.createImageTransformAnimator(SharedElementAnimatorCreator.java:173)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementAnimatorCreator.create(SharedElementAnimatorCreator.java:66)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementAnimatorCreator.createShow(SharedElementAnimatorCreator.java:35)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementsAnimator$1.createTransitionAnimators(SharedElementsAnimator.java:61)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementsAnimator$1.createShowAnimators(SharedElementsAnimator.java:35)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElementsAnimator$1.run(SharedElementsAnimator.java:22)
    at com.reactnativenavigation.views.sharedElementTransition.SharedElements$1.run(SharedElements.java:64)
    at com.reactnativenavigation.utils.ViewUtils$1.onPreDraw(ViewUtils.java:41)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2510)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
    at android.view.Choreographer.doCallbacks(Choreographer.java:695)
    at android.view.Choreographer.doFrame(Choreographer.java:631)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7229)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)                                                                
```

This is the origin SET

```
<View style={{ flex: 1, backgroundColor: "#006bd1" }}>
        <SharedElementTransition
          sharedElementId={"SharedTextId"}
          style={{ height: 100, width: 120 }}
        >
          <TouchableOpacity onPress={this.handlePress}>
            <Image
              style={{ width: 120, height: 100 }}
              source={require("../images/puzzle-red.png")}
            />
          </TouchableOpacity>
        </SharedElementTransition>
        {this._renderInput()}
      </View>
```
and this is my SET on my second screen

```
<View
        style={{
          flex: 1,
          flexDirection: "row",
          justifyContent: "flex-end",
          backgroundColor: "#fff",
        }}
      >
        <SharedElementTransition
          sharedElementId={"SharedTextId"}
          style={{ height: 100, width: 120, }}
          animateClipBounds={true}
          showDuration={600}
          hideDuration={400}
          showInterpolation={{
            type: "path",
            controlX1: "0.5",
            controlY1: "1",
            controlX2: "0",
            controlY2: "0.5",
            easing: "FastOutSlowIn",
          }}
          hideInterpolation={{
            type: "path",
            controlX1: "0.5",
            controlY1: "0",
            controlX2: "1",
            controlY2: "0.5",
            easing: "FastOutSlowIn",
          }}
        >
          <Image
            style={{
              height: 100,
              width: 100,
            }}
            source={require("../images/puzzle-red.png")}
            fadeDuration={0}
          />
        </SharedElementTransition>
      </View>
```
---
### Environment
* React Native Navigation version: 1.1.46
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Samsung S5 (device), OS 6.0.1 / Debug mode

Although when I run the example app on the same device, it does work. The example app runs RN 0.43 though, not sure if could be related

Thanks!

**Comment by guyca** [comment]
The elements you are sharing are not the same. In the first screen you wrap a `          TouchableOpacity` and in the second an `Image`. In the first screen, make the `TouchableOpacity` wrap the `SharedElementTransition`

**Comment by tafelito** [comment]
Thanks @guyca it worked! I knew it had to be something silly like this. 😬

**Comment by tafelito** [comment]
Hi @guyca, although this issue I reported before was not actually an error and its already closed, I noticed this when the origin image is bigger than the target image. 

![jun-02-2017 17-49-29](https://cloud.githubusercontent.com/assets/5973652/26746115/e7df1104-47bb-11e7-9991-bccb11d61044.gif)

It works fine when its the other way around, when the origin image is smaller

![jun-02-2017 17-50-22](https://cloud.githubusercontent.com/assets/5973652/26746146/0b0b6754-47bc-11e7-9fee-b3a6211b349f.gif)

Any ideas what could be the issue here?

Thanks
