### ISSUE TITLE
[Bug] React Native Headless Task execution forces app to start

### ISSUE THREAD

**Issue by Ibrahim-GHub** [wix/react-native-navigation#1320]
### Issue Description

Using this package "react-native-sync-adapter" i created a headlessjs task that runs every 6 hours to update my contacts and registered this task using the following code but the problem is that the app starts when the task run that wasn't the scenario before using react-native-navigation

`AppRegistry.registerHeadlessTask('TASK_SYNC_ADAPTER', () => SyncContactsTask)`

### Code

```js
//app.js

import {
    AppRegistry,
    AppState
} from 'react-native';

import {
    Navigation
} from 'react-native-navigation';

import {
    registerScreens
} from 'MyAListGuest/routes';

import SyncAdapter from 'react-native-sync-adapter';

import SyncContactsTask from 'MyAListGuest/SyncContacts';

registerScreens();

const syncInterval = 60;
const syncFlexTime = 30;

SyncAdapter.init({
    syncInterval,
    syncFlexTime
});

AppRegistry.registerHeadlessTask('TASK_SYNC_ADAPTER', () => SyncContactsTask);

Navigation.startSingleScreenApp({
    screen: {
        screen: 'PreLoader'
    },
    animationType: 'slide-down',
    appStyle: {
        navBarBackgroundColor: '#AE9156',
        navBarTextColor: 'rgba(255, 255, 255, 0.87)',
        navBarTextFontFamily: 'Roboto-Medium',
        navBarButtonColor: '#FFF'
    },
    portraitOnlyMode: true
});
```

---
### Environment
* React Native Navigation version: Latest
* React Native version: 0.43.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Tested on USB(HTC One_M8 dual sim - 6.0) & Emulator(Nexus_5X_API_25(AVD) - 7.1.1)

**Comment by Ibrahim-GHub** [comment]
Any suggestions?

**Comment by guyca** [comment]
@Ibrahim-GHub This happens because rnn starts the ui whenever the bundle is parsed. When your task runs, react parses your bundle and the ui starts. For now, if you can know the bundle is being parsed due to your background task - don't call `Navigation.start*App`

**Comment by Kabangi** [comment]
I have a similar issue

**Comment by abhishek1214** [comment]
+ 
Even i am facing the same issue, can you explain how we can work around this.

**Comment by guyca** [comment]
We're working on moving RN bootstrapping from the Activity to the Application which will decouple the bundle parsing and activity creation. Hopefully this fix will be available by next week

**Comment by abhishek1214** [comment]
Oh nice that would be great, but can you give steps on how i can override the Start activity function in the case bundle is coming from Headless task. I need to demo my app tomorrow and this is the only blocker i have so far.

**Comment by guyca** [comment]
Well, what you want to do - is conditionally call `Navigation.startApp`. If the bundle is parsed due to headless task execution - don't start app.
What you can do, is create a simple [native module](https://facebook.github.io/react-native/docs/native-modules-android.html) that checks if there is an activity. If there's no activity then it means you are running from a service and you shouldn't start your app.

**Comment by Ibrahim-GHub** [comment]
Navigation.startApp is like Navigation.startSingleScreenApp in js? or you mean something that is inside the android project

**Comment by guyca** [comment]
I meant `Navigation.startSIngleScreenApp` or `Navigation.startTabBasedApp`. I was too lazy to type these long method names...

**Comment by abhishek1214** [comment]
Well i implemented a native module, but I am not clear as to what you mean by "that checks if there is an activity". There is no activity until i run Navigation.start.

**Comment by rvrenjith1** [comment]
+1

**Comment by varungupta85** [comment]
@abhishek1214 I had to do something similar to what @guyca suggested for one my workflows. Let me try to shed some light on what you need to do. There are no set instructions for it and I think the overall code to achieve may be different for different cases. 

In your case, is the app launched even when the app is running in the background when a headless task execution starts or is it only the case when the app is not running and a headless task execution kicks in?

If it is the latter, you may be creating a new `ReactContext` that parses the your app bundle and then run headless task. What you may need to do is that when you create a new `ReactContext`, you store some state in the app that can then be read when the app starts in response to parsing the bundle (most probably in index.ios.js or index.android.js) by exposing a `ReactMethod` and if the bundle is parsed due to a headless task execution, then don't call the `startSingleScreenApp` or `startTabBasedApp`. Like I said, there are not set instructions and it will differ case by case.

**Comment by Ibrahim-GHub** [comment]
@guyca I tried to implement the module you suggested and it seemed to work only thing is after the task runs and app not started as there is no activity when i try to open the app afterwards it fails giving this exception

06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: Could not unlock surface
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: java.lang.IllegalArgumentException
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.Surface.nativeUnlockCanvasAndPost(Native Method)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.Surface.unlockSwCanvasAndPost(Surface.java:347)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.Surface.unlockCanvasAndPost(Surface.java:328)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2924)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2827)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.os.Handler.handleCallback(Handler.java:751)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.os.Looper.loop(Looper.java:154)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at android.os.HandlerThread.run(HandlerThread.java:61)
06-17 02:39:28.663  1617  1638 E ViewRootImpl[myalistguest]: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Module code**

```
protected void isActivityRunning(Callback cb)
    {
        ActivityManager activityManager = (ActivityManager) getReactApplicationContext().getSystemService(Context.ACTIVITY_SERVICE);
        List<ActivityManager.RunningTaskInfo> tasks = activityManager.getRunningTasks(Integer.MAX_VALUE);

        Boolean aRunning = false;

        for (ActivityManager.RunningTaskInfo task : tasks) {
            if(getReactApplicationContext().getPackageName().equalsIgnoreCase(task.baseActivity.getPackageName())){
                aRunning = true;
            }
        }

        cb.invoke(aRunning);
    }
```

**Usage**

MyModule.isActivityRunning((res) => {
    if (res) {
        Navigation.startSingleScreenApp({
            screen: {
                screen: 'PreLoader'
            },
            animationType: 'slide-down',
            appStyle: {
                navBarBackgroundColor: '#AE9156',
                navBarTextColor: 'rgba(255, 255, 255, 0.87)',
                navBarTextFontFamily: 'Roboto-Medium',
                navBarButtonColor: '#FFF'
            },
            portraitOnlyMode: true
        });
    }
});

**Comment by guyca** [comment]
@Ibrahim-GHub Sorry, but I don't understand the scenario you've described.

**Comment by Ibrahim-GHub** [comment]
@guyca I mean after the sync process starts the condition would stop the app from starting and that's good however when i attempt to open the app from my phone by clicking on it from the phone menu it crashes and won't start any more

**Comment by abhishek1214** [comment]
Has this been fixed in the new release. Can you please add a change log to your releases its really hard to know what has changed in each release.

**Comment by abhishek1214** [comment]
@guyca Hey I am still facing these issues and very similar to @Ibrahim-GHub , if i set a flag variable to stop pp from starting during bg service the app refuses to start henceforth. This is a real problem for my current react app, would like a resolution at the soonest.

**Comment by guyca** [comment]
Hey guys, Sorry for the delay. We took a specific approach when we tried to solve this but hit a few walls and had to put that effort on hold.

I pushed an experimental branch which I hope will resolve this issue.
https://github.com/wix/react-native-navigation/tree/appLaunchEvent
There's an in-depth description and guide here 4a07651a10637f794f82b73b6cb677e8f3fb3b91

If someone could clone the branch into node_modules and give feedback either here or on discord that would be great.

**Comment by abhishek1214** [comment]
@guyca Thanks this is working for me now. Would like to know when this can be pushed with a release build.

**Comment by guyca** [comment]
Hey guys
version 1.1.130 is published with the fix. Also updated the [docs](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=compatibility-with-headlessjs)

Thanks @abhishek1214 for the feedback 👍

**Comment by Kabangi** [comment]
@guyca, how do you stop the headlessTask to not show the ui with this approach. It's not clear to me. 

```Promise.resolve(Navigation.isAppLaunched())
  .then(appLaunched => {
    if (appLaunched) {
      startApp(); // App is launched -> show UI
    } else {
      new NativeEventsReceiver().appLaunched(startApp); // App hasn't been launched yet -> show the UI only when needed.
    }
  });```

I have implement this but when I comment out the else code block my app won't restart when the app icon is clicked. Thanks.

**Comment by Kabangi** [comment]
On further testing I have noticed it actually does work but as soon as you execute a headless task you can no longer launch the app. I think this is a bug.

> I have implement this but when I comment out the else code block my app won't restart when the app icon is clicked.

**Comment by guyca** [comment]
@Kabangi Did you follow the instructions in the [docs](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=compatibility-with-headlessjs)?

You should remove all calls to `startApp` from global context, and start call `startApp` only with the promis logic as explained in the docs.

**Comment by Kabangi** [comment]
Hey @guyca, sorry for late response I had to take a break from machines. I bet I was tired, came back today, and somehow it worked. I didn't change anything FUI.

Thanks for your help really appreciated.

**Comment by ofirmalka** [comment]
Hi, @guyca, looks like this fix breaking app restart when config changes (fontScale for example)
for now i added fontScale to manifest so i can ignore it

**Comment by guyca** [comment]
Hey @ofirmalka 
I guess we should emit the appLaunched event (`NavigationApplication.instance.getEventEmitter().sendAppLaunchedEvent();`) after [configuration change](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java#L200) as well.

**Comment by ofirmalka** [comment]
but onConfigurationChanged called only for changes that defined on the manifest and not restart the app anyway :)
