### ISSUE TITLE
App crashes sporadically just by navigating around

### ISSUE THREAD

**Issue by annelorraineuy** [wix/react-native-navigation#1344]
### Issue Description

Just by navigating around the app, it sometimes crashes. All crashes output the same error log, that says: `Error with task : undefined is not an object (evaluating 'this.viewProperties.width')`

I believe this has something to do with integrating `react-native-navigation` because we haven't had these crashes before while using JS-based `react-navigation`.

### Steps to Reproduce / Code Snippets / Screenshots

Log:
```
com.facebook.react.common.JavascriptException: TaskQueue: Error with task : undefined is not an object (evaluating 'this.viewProperties.width'), stack:
value@1017:1018
_renderValidatedComponentWithoutOwnerOrContext@194:8602
_renderValidatedComponent@194:8769
_updateRenderedComponent@194:7771
_performComponentUpdate@194:7208
updateComponent@194:6259
performUpdateIfNecessary@194:5171
performUpdateIfNecessary@187:945
s@191:832
perform@192:596
perform@192:596
perform@191:1547
U@191:1703
closeAll@192:1249
perform@192:683
batchedUpdates@203:464
l@191:1023
u@190:65
enqueueSetState@190:966
setState@18:439
value@1017:868
value@1016:828
<unknown>@1016:1129
value@1016:1096
_onViewableItemsChanged@307:1558
value@317:3022
value@317:2134
value@315:7716
_updateCellsToRender@315:19756
<unknown>@316:591
value@286:1122
o@285:371
<unknown>@53:972
callTimer@48:626
callImmediatesPass@48:1749
callImmediates@48:1865
<unknown>@46:2600
value@46:2401
value@46:2565
<unknown>@46:967
value@46:2401
value@46:913

    at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
    at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
    at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:135)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
    at java.lang.Thread.run(Thread.java:818)
```

App.js
```
...
registerScreens(Store, Provider);

Navigation.startSingleScreenApp({
    screen: {
        screen: 'root'
    },
    appStyle: {
        orientation: 'portrait'
    },
    drawer: {
        left: {
            screen: 'drawerMenu'
        },
        disableOpenGesture: true
    },
    animationType: 'fade'
});
```

registerScreens()
```
import { Navigation } from 'react-native-navigation';
...
// importing all screens here
...
export function registerScreens(store, Provider) {
    Navigation.registerComponent('root', () => RootContainer, store, Provider);
    Navigation.registerComponent('home', () => Home, store, Provider);
    Navigation.registerComponent('interstitial.freeGames', () => FreeGamesIntrstl, store, Provider);
    Navigation.registerComponent('interstitial.unlockRooOrg', () => UnlockRooOrig, store, Provider);
    Navigation.registerComponent('component.header', () => Header, store, Provider);
    Navigation.registerComponent('failedToConnect', () => FailedToConnect, store, Provider);
    // ... etc
}
```

---
### Environment
* React Native Navigation version: 1.1.88
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): ANDROID
* Device info (Simulator/Device? OS version? Debug/Release?): DEVICES - 
mipad 2 (android v. 5.1), nexus 5(android v. 6.0.1)

**Comment by trevorblades** [comment]
This is happening for me as well! Specifically, I'm noticing that my app crashes whenever I navigate *backwards* when using a `SingleScreenApp`. I'm able to `push` new views onto the navigation stack, but when I use the back button or `pop` a screen off of the stack, my app crashes.

**Comment by bjacog** [comment]
Experiencing some interesting things with pop(), especially with no params passed, are either of you using it as just pop() without passing a param like pop({})?
