### ISSUE TITLE
collapsingToolbarImage causes crash

### ISSUE THREAD

**Issue by jonarvids** [wix/react-native-navigation#1413]
### Issue Description

I'm trying to add a toolbar image using collapsingToolbarImage on one of my screens. Right now just using the code from the docs 

`   static navigatorStyle = {
      collapsingToolBarImage: "http://lorempixel.com/400/200/"
    };
`

### Steps to Reproduce / Code Snippets / Screenshots

Added `    static navigatorStyle = {
      collapsingToolBarImage: "http://lorempixel.com/400/200/"
    };
`
To my class, when entering this screen the app crashes. No error messages.

---
### Environment
* React Native Navigation version: 1.1.113
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by nitish24p** [comment]
I'm experiencing the same thing. The log cat error is as follows
```
02-05 18:56:51.963 16125 16125 E ACRA    : java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getScrollY()' on a null object reference
02-05 18:56:51.963 16125 16125 E ACRA    : 	at com.reactnativenavigation.views.collapsingToolbar.CollapseCalculator.saveInitialTouchY(CollapseCalculator.java:261)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at com.reactnativenavigation.views.collapsingToolbar.CollapseCalculator.updateInitialTouchY(CollapseCalculator.java:239)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at com.reactnativenavigation.views.collapsingToolbar.CollapseCalculator.calculate(CollapseCalculator.java:101)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at com.reactnativenavigation.views.collapsingToolbar.ScrollListener.onTouch(ScrollListener.java:28)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at com.reactnativenavigation.views.collapsingToolbar.CollapsingTitleBar.onTouch(CollapsingTitleBar.java:130)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.View.dispatchTouchEvent(View.java:9939)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.View.dispatchPointerEvent(View.java:10163)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6284)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6336)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:613)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:751)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.os.Looper.loop(Looper.java:154)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:6077)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
02-05 18:56:51.963 16125 16125 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
02-05 18:56:51.979  1549  2055 I ActivityManager: Killing 14821:com.android.printspooler/u0a67 (adj 904): empty for 1816s
```

**Comment by nitish24p** [comment]
@onarvids Make sure your screen returns a scrollview at the parent level in the render method.. That fixed it for me .
