### ISSUE TITLE
Real problem on react-native-navigation with react-native-image-picker PLEASE help me!

### ISSUE THREAD

**Issue by mrxrinc** [wix/react-native-navigation#1626]
I did all changes suggested in here :
https://github.com/react-community/react-native-image-picker/pull/580/files

but still getting this red screen error and nothing works :(

here is the logcat error:

Exception in native call
java.lang.RuntimeException: Could not invoke ImagePickerManager.launchImageLibrary
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
at android.os.Looper.loop(Looper.java:135)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
... 8 more
Caused by: java.lang.NoSuchMethodError: No virtual method requestPermissions([Ljava/lang/String;I)V in class Lcom/reactnativenavigation/controllers/NavigationActivity; or its super classes (declaration of 'com.reactnativenavigation.controllers.NavigationActivity' appears in /data/app/com.tahviler-2/base.apk)
at com.reactnativenavigation.controllers.NavigationActivity.requestPermissions(NavigationActivity.java:441)
at com.imagepicker.ImagePickerModule.permissionsCheck(ImagePickerModule.java:590)
at com.imagepicker.ImagePickerModule.launchImageLibrary(ImagePickerModule.java:298)
... 11 more

and this is screenshot:
![image](https://user-images.githubusercontent.com/10651894/28885512-6b81be46-77cb-11e7-9bed-828b518a990e.png)

I hope someone show a way to make these two modules work together, Im in real problem on this :(

Additional Information

React Native version: 0.46
Platform: Android 5.1 and above
Development Operating System: Windows
Dev tools:  using Atom with nuclide

**Comment by chaitanya0bhagvan** [comment]
Which version of android?

The stack track you posted says `requestPermissions NoSuchMethodError` . Looking at NavigationActivity requestPermissions method is available for android versions 23 and above.

**Comment by mrxrinc** [comment]
android 5.1 and above

**Comment by xmarianox** [comment]
Hi, I fix this problem

1 - Implements `OnImagePickerPermissionsCallback` in `controllers/NavigationActivity.class`

2 - implements `setPermissionListener` method
```java
    @Override
    public void setPermissionListener(@NonNull PermissionListener listener) {
        mPermissionListener = listener;
    }
```

3 - And replace `mPermissionListener = listener;` to `setPermissionListener(listener);`
```java
    @TargetApi(Build.VERSION_CODES.M)
    public void requestPermissions(String[] permissions, int requestCode, PermissionListener listener) {
        setPermissionListener(listener);
        requestPermissions(permissions, requestCode);
    }
```
Not the best solution, but it works!

**Comment by matthamil** [comment]
I'm also having problems with this. The above solution posted by @xmarianox doesn't quite work for me. @xmarianox what version of RNN and React Native are you running to get this to work?

**Comment by xmarianox** [comment]
@matthamil my `package.json`

```json
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-image-picker": "^0.26.7",
"react-native-navigation": "1.1.262",
```
