### ISSUE TITLE
App crash when click DevSettings of RN dev menu.

### ISSUE THREAD

**Issue by Coolerfall** [wix/react-native-navigation#1651]
### Issue Description

App crash when click DevSettings in RN dev menu.

### Steps to Reproduce / Code Snippets / Screenshots

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.os.Bundle.getBundle(java.lang.String)' on a null object reference
                                                                               at com.reactnativenavigation.params.AppStyle.setAppStyle(AppStyle.java:11)
                                                                               at com.reactnativenavigation.params.parsers.ActivityParamsParser.parse(ActivityParamsParser.java:14)
                                                                               at com.reactnativenavigation.controllers.NavigationCommandsHandler.parseActivityParams(NavigationCommandsHandler.java:32)
                                                                               at com.reactnativenavigation.controllers.NavigationActivity.onCreate(NavigationActivity.java:70)
                                                                               at android.app.Activity.performCreate(Activity.java:6010)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:135) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 

### Environment
* React Native Navigation version: latest
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, 7.0, DEBUG

**Comment by shubhanshusingh** [comment]
??? any solution to this?
