### ISSUE TITLE
TitleBar - Crash on adding Custom Navigation Button.

### ISSUE THREAD

**Issue by pqkluan** [wix/react-native-navigation#1758]
### Issue Description
I try to add [Custom Navigation Button](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator). But having issues on Android platform.

### Steps to Reproduce / Code Snippets / Screenshots

*Custom Navigation Button*

```jsx
import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import { Navigation } from 'react-native-navigation';

class WishlistIcon extends React.Component {

	render() {
		return (
			<TouchableOpacity
				style={[styles.container, { backgroundColor: 'tomato' }]}
				onPress={() => console.log('pressed me!')}
			>
				<View style={styles.container}>
					<Text style={{ color: 'white' }}>
						{'Hi'}
					</Text>
				</View>
			</TouchableOpacity>
		);
	}
}

const styles = StyleSheet.create({
	container: {
		overflow: 'hidden',
		width: 34,
		height: 34,
		borderRadius: 34 / 2,
		justifyContent: 'center',
		alignItems: 'center'
	}
});

Navigation.registerComponent('WishlistIcon', () => WishlistIcon);

export default WishlistIcon;
```

Add button to screen.
```jsx
class ProductsScreen extends React.Component {
	static navigatorButtons = {
		rightButtons: [
			{
				id: 'WishlistIcon',
				component: 'WishlistIcon' // This line loads our component as a nav bar button item
			}
		]
	};
}
```

*Android got crashed on launch and produce the error log*

```console
08-29 12:02:57.759 21418-21418/com.loyalty E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.loyalty, PID: 21418
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.loyalty/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.unparcel()' on a null object reference
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.unparcel()' on a null object reference
                                                                 at android.os.Bundle.putAll(Bundle.java:226)
                                                                 at com.reactnativenavigation.views.ContentView.attachToJS(ContentView.java:45)
                                                                 at com.reactnativenavigation.views.ContentView.<init>(ContentView.java:36)
                                                                 at com.reactnativenavigation.views.TitleBarButtonComponent.<init>(TitleBarButtonComponent.java:16)
                                                                 at com.reactnativenavigation.views.TitleBarButton.addToMenu(TitleBarButton.java:38)
                                                                 at com.reactnativenavigation.views.TitleBar.addButtonInReverseOrder(TitleBar.java:181)
                                                                 at com.reactnativenavigation.views.TitleBar.addButtonsToTitleBar(TitleBar.java:175)
                                                                 at com.reactnativenavigation.views.TitleBar.setRightButtons(TitleBar.java:52)
                                                                 at com.reactnativenavigation.views.TopBar.addButtons(TopBar.java:88)
                                                                 at com.reactnativenavigation.views.TopBar.addTitleBarAndSetButtons(TopBar.java:70)
                                                                 at com.reactnativenavigation.screens.Screen.addTitleBarButtons(Screen.java:145)
                                                                 at com.reactnativenavigation.screens.Screen.createTitleBar(Screen.java:131)
                                                                 at com.reactnativenavigation.screens.Screen.createViews(Screen.java:118)
                                                                 at com.reactnativenavigation.screens.Screen.<init>(Screen.java:64)
                                                                 at com.reactnativenavigation.screens.SingleScreen.<init>(SingleScreen.java:16)
                                                                 at com.reactnativenavigation.screens.ScreenFactory.create(ScreenFactory.java:23)
                                                                 at com.reactnativenavigation.screens.ScreenStack.pushInitialScreen(ScreenStack.java:95)
                                                                 at com.reactnativenavigation.layouts.BottomTabsLayout.createAndAddScreens(BottomTabsLayout.java:105)
                                                                 at com.reactnativenavigation.layouts.BottomTabsLayout.addScreenStacks(BottomTabsLayout.java:98)
                                                                 at com.reactnativenavigation.layouts.BottomTabsLayout.createLayout(BottomTabsLayout.java:77)
                                                                 at com.reactnativenavigation.layouts.BottomTabsLayout.<init>(BottomTabsLayout.java:70)
                                                                 at com.reactnativenavigation.layouts.LayoutFactory.createBottomTabsScreenLayout(LayoutFactory.java:27)
                                                                 at com.reactnativenavigation.layouts.LayoutFactory.create(LayoutFactory.java:12)
                                                                 at com.reactnativenavigation.controllers.NavigationActivity.createLayout(NavigationActivity.java:93)
                                                                 at com.reactnativenavigation.controllers.NavigationActivity.onCreate(NavigationActivity.java:74)
                                                                 at android.app.Activity.performCreate(Activity.java:6679)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

---
### Environment
* React Native Navigation version: 1.1.189
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator - Android 7.1.1 - Debug mode.

**Comment by guyca** [comment]
Hey there,
As a temporary workaround, your can add an empty props object to the button:

```js
    rightButtons: [
      {
        id: 'custom-button',
        component: 'CustomButton',
        passProps: {}
      }
    ]
```

**Comment by pqkluan** [comment]
It's work! Thank you @guyca

**Comment by ghoshabhi** [comment]
Faced the same issue, worked for me too 👍 Thanks @guyca

**Comment by dVelopment** [comment]
same issue – same solution. Thank you very much, @guyca
