### ISSUE TITLE
[v2] Unable to run playground & e2e tests

### ISSUE THREAD

**Issue by joshyhargreaves** [wix/react-native-navigation#1914]
### Issue Description
I am looking to contribute to the v2 branch & was looking to get started by running the playground & the unit tests. Unfortunately I am having issues with running the playground on both iOS and Android as well as running the tests (specifically the e2e tests) on both Android & iOS. 

#### e2e tests errors on Android & iOS simulators
![screen shot 2017-09-22 at 12 29 43 pm](https://user-images.githubusercontent.com/1807207/30743274-d4eed4ea-9f94-11e7-8dac-eec51b9ee0d1.png)

#### Output from iOS simulator log file
```
atch_queue: com.facebook.react.SourceCodeQueue[0x6180000ee080]>
2017-09-22 12:26:26.778 playground[93237:4545239] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.AccessibilityManagerQueue[0x6100000eab00]>
2017-09-22 12:26:26.778 playground[93237:4545239] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.DevLoadingViewQueue[0x6100000ea080]>
2017-09-22 12:26:26.778 playground[93237:4545239] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.PlatformConstantsQueue[0x6100000eb200]>
2017-09-22 12:26:26.778 playground[93237:4545239] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.I18nManagerQueue[0x6080000eb900]>
2017-09-22 12:26:26.780 playground[93237:4545239] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.RedBoxQueue[0x6180000ee180]>
2017-09-22 12:26:44.664 playground[94311:4555004] Crash handler setup started.
2017-09-22 12:26:44.665 playground[94311:4555004] Crash handler setup completed.
2017-09-22 12:26:44.665 playground[94311:4555004] Enabling accessibility for automation on Simulator.
2017-09-22 12:26:44.878 [info][tid:main][RCTBatchedBridge.m:77] Initializing <RCTBatchedBridge: 0x6080001b3cc0> (parent: <RCTBridge: 0x6000000ccfd0>, executor: RCTJSCExecutor)
2017-09-22 12:26:44.895 playground[94311:4555004] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.RNNEventEmitterQueue[0x6000000f5a80]>
2017-09-22 12:26:44.896 playground[94311:4555004] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.JSCExecutorQueue[0x6000000f5a00]>
2017-09-22 12:26:44.901 [warn][tid:com.facebook.react.JavaScript][RCTModuleData.mm:220] RCTBridge required dispatch_sync to load RCTDevSettings. This may lead to deadlocks
2017-09-22 12:26:44.923 playground[94311:4555004] ☣️ DETOX:: Detox Action Sent: login
2017-09-22 12:26:44.954 playground[94311:4555004] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.SettingsManagerQueue[0x6080000fa280]>
2017-09-22 12:26:44.955 playground[94311:4555004] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.SourceCodeQueue[0x6000000f3e00]>
2017-09-22 12:26:44.957 playground[94311:4555004] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.AccessibilityManagerQueue[0x6080000fa300]>
2017-09-22 12:26:44.957 playground[94311:4555004] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.DevLoadingViewQueue[0x6080000fa500]>
2017-09-22 12:26:44.958 playground[94311:4555004] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.PlatformConstantsQueue[0x6100000f5e00]>
2017-09-22 12:26:44.958 playground[94311:4555004] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.I18nManagerQueue[0x6100000f5f00]>
2017-09-22 12:26:44.961 playground[94311:4555004] ☣️ DETOX:: Detox Action Received: loginSuccess
2017-09-22 12:26:46.299 [warn][tid:com.facebook.react.JavaScript][RCTBatchedBridge.m:512] Failed to execute source code: Unhandled JS Exception: ReferenceError
2017-09-22 12:26:46.300 playground[94311:4555004] ☣️ Adding idling resource for queue: <OS_dispatch_queue: com.facebook.react.RedBoxQueue[0x6180000f3e00]>
2017-09-22 12:26:46.300 [fatal][tid:main] Unhandled JS Exception: ReferenceError
2017-09-22 12:26:46.301 playground[94311:4555004] -[RCTJSStackFrame objectForKeyedSubscript:]: unrecognized selector sent to instance 0x600000049630
```

### Steps to Reproduce / Code Snippets / Screenshots
 - Checkout `v2` branch. 
 - `npm run test-e2e-ios` ` npm run test-e2e-android`
 -  Open Xcode, build and run the project. 

---
### Environment
* React Native Navigation version: Playground version
* React Native version: Playground version
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator. iOS 10.3, Android 7.1.1

**Comment by bogobogo** [comment]
Hey @joshyhargreaves,
Did you run `npm run start`? To allow for quick development, the playground project is configured a bit differently than a normal react native project, so just running react-native run-ios won't work. Make sure you run `npm run start` and then play the project from xcode.

**Comment by joshyhargreaves** [comment]
@bogobogo sorry for the delay in getting back to you. 

Unfortunately yes I had `npm run start` and had run the project from XCode for the playground.
It was the `e2e` tests that were yielding the RSOD.

Running the playground results in my iOS simulator hanging on it hanging on the splash screen. 
<img src="https://user-images.githubusercontent.com/1807207/30862727-ed983f88-a2c6-11e7-8582-1715ac2abcca.png" height="200" />

**Comment by Cool04ek** [comment]
Hi. Have you tried running `adb reverse tcp:8081 tcp:8081`

**Comment by bogobogo** [comment]
@joshyhargreaves This is very weird and sounds like a packager issue. Are you up to date with v2? I am am looking into it now, will update if I find something that might explain it.

**Comment by joshyhargreaves** [comment]
@bogobogo. Just to further clarify, I've realised the `hanging` behavior that I mention here: https://github.com/wix/react-native-navigation/issues/1914#issuecomment-332198185 only happens when debugging in chrome, when running JS locally I see a `reference` error, same as here: https://github.com/wix/react-native-navigation/issues/1914#issue-259792961. 

Yes I just pulled the latest from the `v2` branch, which I presume is correct?

If there's any more information I can give you, be sure to let me know. I myself am a bit stumped on this!

**Comment by bogobogo** [comment]
@joshyhargreaves what is the output in xcode when you run the js locally? The logs from the first comment seem to result from running the e2e tests

**Comment by bogobogo** [comment]
@joshyhargreaves Also, could you share your scripts/start.js file?

**Comment by joshyhargreaves** [comment]
@bogobogo, the output in XCode when opening `playground/ios/playground.xcodeproj` in XCode and running the JS results in the following output in XCode: 

```
2017-09-27 13:45:45.686 [info][tid:main][RCTBatchedBridge.m:77] Initializing <RCTBatchedBridge: 0x6000001ac320> (parent: <RCTBridge: 0x6080000c82d0>, executor: RCTJSCExecutor)
2017-09-27 13:45:45.733 [warn][tid:com.facebook.react.JavaScript][RCTModuleData.mm:220] RCTBridge required dispatch_sync to load RCTDevSettings. This may lead to deadlocks
2017-09-27 13:45:46.999 [warn][tid:com.facebook.react.JavaScript][RCTBatchedBridge.m:512] Failed to execute source code: Unhandled JS Exception: ReferenceError
2017-09-27 13:45:46.999 [fatal][tid:main] Unhandled JS Exception: ReferenceError
2017-09-27 13:45:47.000 playground[22946:9487890] -[RCTJSStackFrame objectForKeyedSubscript:]: unrecognized selector sent to instance 0x60000004b520
```

**Comment by joshyhargreaves** [comment]
@bogobogo: 

scripts/start.js
```
const exec = require('shell-utils').exec;

run();

function run() {
  exec.killPort(8081);
  exec.execSync(`watchman watch-del-all || true`);
  exec.execSync(`adb reverse tcp:8081 tcp:8081 || true`);
  exec.execSync(`node ./node_modules/react-native/local-cli/cli.js start`);
}
```

**Comment by joshyhargreaves** [comment]
@bogobogo, yes it is `require('./playground/index')`

**Comment by joshyhargreaves** [comment]
Just to double check, I did a clean checkout of `react-native-navigation` and checked out the `v2` branch. Unfortunately, the same result.

**Comment by bogobogo** [comment]
@joshyhargreaves have you tried the holy combination of `watchman watch-del-all`, reinstall node modules and reset the npm cache? Also can you share your package.json?

**Comment by joshyhargreaves** [comment]
@bogobogo: 'the holy combination' 😂. 
Ah you very well may be right! 
Running `watchman watch-del-all` has given me a different error when re-running.

```
Loading dependency graph, done.
error: bundling: Error: ENOENT: no such file or directory, open '/Developer/code/react-native-navigation/old-example-redux/node_modules/react-native/Libraries/Utilities/BackAndroid.ios.js'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at Module._readSourceCode (/Developer/code/react-native-navigation/node_modules/react-native/packager/src/node-haste/Module.js:200:29)
    at Module._getCacheProps (/Developer/code/react-native-navigation/node_modules/react-native/packager/src/node-haste/Module.js:420:29)
    at Module._readFromTransformCache (/Developer/code/react-native-navigation/node_modules/react-native/packager/src/node-haste/Module.js:376:29)
    at Module.readCached (/Developer/code/react-native-navigation/node_modules/react-native/packager/src/node-haste/Module.js:363:25)
    at Promise.resolve.then (/Developer/code/react-native-navigation/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:167:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

So it looks like you're right: it must be something to do with my packager and 'staleness' of some sort. Hmm, I'm not sure where this file path could be coming from?

**Comment by bogobogo** [comment]
@joshyhargreaves Sure. if you need any help at all let me know. If you would like to join a video call where we'll explain the architecture and our current status that is also possible, we will probably do that again soon.

**Comment by joshyhargreaves** [comment]
@bogobogo thanks a lot, I'll let you know :). Yeah a call would be great! Is there also a slack somewhere?

**Comment by bogobogo** [comment]
@joshyhargreaves Yes, ping me in our discord channel and i'll send you an invite, my user name is bogo and you can find the discord channel [here](https://github.com/wix/react-native-navigation#quick-links) under 'Chat With Us'

**Comment by joshyhargreaves** [comment]
@bogobogo so resetting the `rn-packager` cache fixed the original issue. 
I think typically speaking running `npm start -- --reset-cache`, would reset the cache in a typical react-native setup, but as `package.json` specifies { start: 'scripts/start' }, you'd need to reset the cache manually with `node ./node_modules/react-native/local-cli/cli.js start --reset-cache`
