### ISSUE TITLE
Android version crash (assertNotNull) on device wake up. 

### ISSUE THREAD

**Issue by ywongweb** [wix/react-native-navigation#1924]
### Issue Description

App will crash when I start the app again after a long sleep by clicking on the app icon. 
Seem to caused by this **null reference check**. 
https://github.com/facebook/react-native/blob/b9be9a01a9fbd871956b6216628e83e42cbeca64/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L561

I am starting my app using the **Stop calling host.clear() when activity is destroyed** method from this PR
https://github.com/wix/react-native-navigation/pull/1838

### Stacktrace
```
  at com.facebook.infer.annotation.Assertions.assertNotNull (Assertions.java:28)
  at com.facebook.react.ReactInstanceManager.onHostPause (ReactInstanceManager.java:515)
  at com.reactnativenavigation.react.NavigationReactGateway.onPauseActivity (NavigationReactGateway.java:74)
  at com.reactnativenavigation.controllers.NavigationActivity.onPause (NavigationActivity.java:143)
  at android.app.Activity.performPause (Activity.java:7148)
  at android.app.Instrumentation.callActivityOnPause (Instrumentation.java:1330)
  at android.app.ActivityThread.performPauseActivityIfNeeded (ActivityThread.java:4168)
  at android.app.ActivityThread.performPauseActivity (ActivityThread.java:4145)
  at android.app.ActivityThread.performPauseActivity (ActivityThread.java:4119)
  at android.app.ActivityThread.handlePauseActivity (ActivityThread.java:4093)
  at android.app.ActivityThread.-wrap18 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1654)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
```
---
### Environment
* React Native Navigation version: 1.1.218
* React Native version: 0.48.3
* Platform(s) (iOS, Android, or both?): Android 7.0
* Device info (Simulator/Device? OS version? Debug/Release?): Release,

**Comment by guyca** [comment]
Hey @ywongweb 
Is this crash consistent? Can you reproduce it with "Do not keep activities" option from the developer menu?

**Comment by ywongweb** [comment]
@guyca 

Yes it's consistent. 

I can reliably reproduce the crash on both Android 6.0 and 7.0 with **Do not keep activities** ON,  but I need to **restart** the phone after every try. 

Without restarting the phone, I will need to wait a very long time before the next app start for the crash to happen, but it will always crash. 

###Steps (Do not keep activities: ON) :  
(After a fresh restart)
Open app.  
Minimise app, lock phone and wait a few minutes.  
Wake up phone. click on app icon to start app and it will crash.  

My app is [here](https://play.google.com/store/apps/details?id=com.busdue) if you want to test it.

**Comment by hose314** [comment]
Same for me, any progress?

**Comment by hose314** [comment]
My thoughts is issue caused by https://github.com/wix/react-native-navigation/commit/7461baedc91d8d880833c60dcb24d444b866081c#diff-daba542e16c8d30fd0147276b318c4ed
if it's breaking change i think we should make that version at least `1.2..`

**Comment by ywongweb** [comment]
It's also happening with apps that's not using the startup method in https://github.com/wix/react-native-navigation/pull/1838

**Comment by guyca** [comment]
@hose314 Didn't get around to this yet and I'm on vacation until October 14'TH. 
@ywongweb Thanks, but I don't think that's needed as this reproduces on each app. 

I'm wondering if calling `getReactInstanceManager().onHostPause();` (event though it's deprecated) will make a difference.

**Comment by ywongweb** [comment]
Thanks @guyca 

Calling `getReactInstanceManager().onHostPause();` `getReactInstanceManager().onHostDestroy();` and reverting the way I start the app to pre #1838 seem to fix the crash for me. I will need to test this overnight just to be sure. One drawback with this temp fix is that each time I launch the app, it will reboot back to it's initial state. I am not sure which I prefer. 😛

**Comment by guyca** [comment]
@ywongweb @hose314 I published v1.1.234 which should fix this issue. Please update me if it's still not resolved.

**Comment by ywongweb** [comment]
update:
The reverting fix seem to be stable after leaving the phone over night.

I'll try out 1.234😉 and report here later. Thanks again @guyca !

**Comment by sytolk** [comment]
@guyca I cannot repeat this issue with v.1.1.234 but this is my init (look for the else{ //and comment)
```
Navigation.isAppLaunched()
                .then((appLaunched) => {
                    if (appLaunched) {
                        this.registerSubscriber();
                    } else {
                        // App hasn't been launched yet -> show the UI only when needed.
                        new NativeEventsReceiver().appLaunched(this.registerSubscriber);
                    }
                    return appLaunched;
                }).catch((error) => {
                    console.log('Error while starting App:' + error);
                });
```

**Comment by gyfelton** [comment]
My app has the same issue, will report back if the fix works

**Comment by eldenskloss** [comment]
had issue at 1.1.231, still have issue at 1.1.235.  Settings "Don't keep activities" turn on, leave app, come back and crash.  

java.lang.AssertionError
                                                       at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:28)
                                                       at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:515)
                                                       at com.reactnativenavigation.react.NavigationReactGateway.onPauseActivity(NavigationReactGateway.java:74)
                                                       at com.reactnativenavigation.controllers.NavigationActivity.onPause(NavigationActivity.java:138)
                                                       at android.app.Activity.performPause(Activity.java:7115)
                                                       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1407)
                                                       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3965)
                                                       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3942)
                                                       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3916)
                                                       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3890)
                                                       at android.app.ActivityThread.-wrap15(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by guyca** [comment]
@eldenskloss I think you didn't compile after upgrading  (or perhaps got old version from npm cache) since line 74 in `NavigationReactGateway` doesn't contain a call to `onHostPause` (onHostPause was indeed called from line 74 but in previous versions)

**Comment by eldenskloss** [comment]
Exactly what happened. I did recompile...or at least I thought I did. Went
ahead and ran and uninstall and then recompiled and everything is working
great. Thanks guys!

**Comment by ywongweb** [comment]
I've encountered this assertNull crash again while fixing another issue with launching the app from the app store.  

**Launching app from app store bug:**  
1. Make sure you have the app uninstall  
2. Install your app from the Play Store or from a 3rd party distribution service like Fabric  
3. After the download has finished, launch your app from the same App Store menu  
### What happened  
Now your app will reload every time you open it.
### What is expected  
The app should open at the same screen/state where you left it.  
### How to fix  
To fix this bug I followed [this stackoverflow post](https://stackoverflow.com/questions/19545889/app-restarts-rather-than-resumes) and added a bunch of checks to determine if we need to finish the current activity.  

However with the above fix, my app is once again crashing from the same assertion (can reproduce reliably with KeepActivityOFF+restart phone technique). As a temporary fixed I've added the following an extra `activity == null` check in `NavigationReactGateWay.java`  
```
	public void onPauseActivity(Activity activity) {
        if (NavigationApplication.instance.clearHostOnActivityDestroy() || activity == null) {
            getReactInstanceManager().onHostPause();
        } else if (hasStartedCreatingContext()) {
		    getReactInstanceManager().onHostPause(activity);
        }
```  

Is this the right way to handle this?

**Comment by ywongweb** [comment]
I am still having the same issue. What's different now is that I can no longer reliably reproduce this with `keep activity OFF` like it was in pre-1.1.235  . But opening the app after a long sleep will still crash with the same assetNull error.  

#### Steps    
Run the app, minimise it to the background.  
Run a few other apps and user your phone normally.  
Let the phone enter sleep mode.  
After a long wait (randomly from a hour to sometimes over night)  
Run a few other apps and user your phone normally.  
Open the app again and it will crash.

**Comment by guyca** [comment]
@ywongweb Are you certain it's the same crash?

**Comment by ywongweb** [comment]
@guyca yes, the crash stacktrace is the same.
