### ISSUE TITLE
[Android] Crash on modal open

### ISSUE THREAD

**Issue by andybbtt11** [wix/react-native-navigation#202]
Running a showModal, code below:
```
Navigation.showModal({
      screen: 'bannerApp.LoginWebview',
      title: 'Log In',
      navigatorStyle: {},
      navigatorButtons: {
        leftButtons: [
          {
            title: 'Exit',
            id: 'exit'
          }
        ],
        rightButtons: [
          {
            title: 'Account',
            id: 'account'
          }
        ]
      },
      animationType: 'slide-up'
    });
```
Causes android to crash with the following error:

`-8441/com.exampleredux E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.exampleredux, PID: 8441
                                                                com.facebook.react.bridge.NoSuchKeyException: **couldn't find key rightButtons in dynamic object**
                                                                    at com.facebook.react.bridge.ReadableNativeMap.getArray(Native Method)
                                                                    at com.facebook.react.bridge.ReadableNativeMap.getArray(ReadableNativeMap.java:23)
                                                                    at com.reactnativenavigation.core.objects.Screen.getRightButtons(Screen.java:120)
                                                                    at com.reactnativenavigation.core.objects.Screen.getButtons(Screen.java:107)
                                                                    at com.reactnativenavigation.core.objects.Screen.<init>(Screen.java:91)
                                                                    at com.reactnativenavigation.modules.RctActivityModule$14.run(RctActivityModule.java:299)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

Am I doing something wrong?  I am using React Native .28 and latest react-native-navigation.

Thanks.

**Comment by andybbtt11** [comment]
Nevermind: fixed.  was breaking do to an invalid property (resizeMode) passed to an image.

**Comment by stevenkaspar** [comment]
@andybbtt11 Thanks for posting your solution. Made me relook at my Modal content

I had a `<View>text</View>` instead of `<View><Text>text</Text></View>` 😔
