### ISSUE TITLE
java.util.EmptyStackException

### ISSUE THREAD

**Issue by mobitar** [wix/react-native-navigation#2049]
Seeing this issue a lot in my production release. Over 55 different users affected by this over Android 7-8.

I'm not exactly sure what action they're performing to get this. But my app allows changing of themes, at which point `startSingleScreenApp` is called again to reload the interface and styles. Would this cause that? Any recommended clean up that can be done before calling `startSingleScreenApp`, or is it idempotent?

```
Stack.java:102java.util.Stack.peek	
ScreenStack.java:228com.reactnativenavigation.screens.ScreenStack.peek	
SingleScreenLayout.java:317com.reactnativenavigation.layouts.SingleScreenLayout.getCurrentScreen	
SnackbarAndFabContainer.java:70com.reactnativenavigation.views.SnackbarAndFabContainer$1.run	
FloatingActionButtonCoordinator.java:82com.reactnativenavigation.views.FloatingActionButtonCoordinator$2.onAnimationEnd	
FloatingActionButtonAnimator.java:104com.reactnativenavigation.views.FloatingActionButtonAnimator$3.onAnimationEnd	
ViewPropertyAnimator.java:1121android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd	
ValueAnimator.java:1153android.animation.ValueAnimator.endAnimation	
ValueAnimator.java:1313android.animation.ValueAnimator.doAnimationFrame	
AnimationHandler.java:146android.animation.AnimationHandler.doAnimationFrame	
AnimationHandler.java:-1android.animation.AnimationHandler.-wrap2	
AnimationHandler.java:54android.animation.AnimationHandler$1.doFrame	
Choreographer.java:872android.view.Choreographer$CallbackRecord.run	
Choreographer.java:686android.view.Choreographer.doCallbacks	
Choreographer.java:618android.view.Choreographer.doFrame	
Choreographer.java:860android.view.Choreographer$FrameDisplayEventReceiver.run	
Handler.java:751android.os.Handler.handleCallback	
Handler.java:95android.os.Handler.dispatchMessage	
Looper.java:154android.os.Looper.loop	
ActivityThread.java:6186android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
ZygoteInit.java:889com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	
ZygoteInit.java:779com.android.internal.os.ZygoteInit.main
```

---
#### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both/Both

**Comment by jslz** [comment]
Maybe we are seeing something similar.

- React Native Navigation 1.1.331
- React Native 0.51.0
- platform: Android
- device info: a real Xiaomi device, unclear if it happens on emulator.

```
EXCEPTION(most recent call first)FullRaw
EmptyStackException
java.util.Stack in peek at line 102
com.reactnativenavigation.screens.ScreenStack in hide at line 460
com.reactnativenavigation.layouts.BottomTabsLayout in hideCurrentStack at line 527
com.reactnativenavigation.layouts.BottomTabsLayout in switchTab at line 488
com.reactnativenavigation.layouts.BottomTabsLayout in onTabSelected at line 482
com.aurelhubert.ahbottomnavigation.AHBottomNavigation in updateItems at line 598
com.aurelhubert.ahbottomnavigation.AHBottomNavigation in access$000 at line 52
com.aurelhubert.ahbottomnavigation.AHBottomNavigation$2 in onClick at line 443
android.view.View in performClick at line 5647
android.view.View$PerformClick in run at line 22462
android.os.Handler in handleCallback at line 754
android.os.Handler in dispatchMessage at line 95
android.os.Looper in loop at line 163
android.app.ActivityThread in main at line 6365
java.lang.reflect.Method in invoke
com.android.internal.os.ZygoteInit$MethodAndArgsCaller in run at line 901
com.android.internal.os.ZygoteInit in main at line 791
```

**Comment by mobitar** [comment]
I was able to remedy this by checking for null in `updateFab` in `SnackbarAndFabContainer`.

```
Screen currentScreen = layout.getCurrentScreen();
if (currentScreen != null && currentScreen.getScreenInstanceId().equals(fabParams.screenInstanceId)) {
  fabCoordinator.add(fabParams);
}
```

**Comment by iswanj** [comment]
@mobitar that's working for me. Can you make a PR for that?

**Comment by varungupta85** [comment]
@mobitar I also see this error sometimes on Sentry. I am not sure if the fix that you recommended would help because you are still calling `getCurrentScreen` which throws the `EmptyStackException`. I guess a better solution could look like this

```java
Screen currentScreen = null
try {
  currentScreen = layout.getCurrentScreen();
} catch(EmptyStackException exception) {
  currentScreen = null;
}
if (currentScreen != null && currentScreen.getScreenInstanceId().equals(fabParams.screenInstanceId)) {
  fabCoordinator.add(fabParams);
}
```

**Comment by mobitar** [comment]
@varungupta85 you're right theoretically, although the exception seems to be getting caught somehow. In any case, to be on the safe side, I've added try/catch. 

@iswanj I keep a conservative fork here: https://github.com/mobitar/react-native-navigation

**Comment by varungupta85** [comment]
@mobitar I didn't see any PR from you with these changes. So, I have created a PR with this change. #2746

**Comment by steverob** [comment]
Even after this PR, I'm seeing a similar issue here - 

```
Caused by java.util.EmptyStackException
       at java.util.Stack.peek(Stack.java:102)
       at com.reactnativenavigation.screens.ScreenStack.peek(ScreenStack.java:245)
       at com.reactnativenavigation.layouts.BottomTabsLayout.getCurrentScreen(BottomTabsLayout.java:346)
       at com.reactnativenavigation.controllers.NavigationActivity.getCurrentlyVisibleEventId(NavigationActivity.java:495)
       at com.reactnativenavigation.controllers.NavigationActivity.onResume(NavigationActivity.java:140)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
       at android.app.Activity.performResume(Activity.java:6977)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3455)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3518)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1566)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6205)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

Any help? @mobitar

**Comment by jaimeagudo** [comment]
Same bug under different circumstances, I believe it's because some race condition. When I boot the app I call `startSingleScreenApp` while in parallel search for a cached auth token, if found I call `startTabBasedApp`.


```
-04 16:18:03.837  8030  8030 E AndroidRuntime: java.util.EmptyStackException
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at java.util.Stack.peek(Stack.java:102)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at com.reactnativenavigation.screens.ScreenStack.peek(ScreenStack.java:245)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at com.reactnativenavigation.layouts.BottomTabsLayout.getCurrentScreen(BottomTabsLayout.java:346)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at com.reactnativenavigation.layouts.BottomTabsLayout.getCurrentlyVisibleScreenId(BottomTabsLayout.java:239)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at com.reactnativenavigation.controllers.NavigationActivity.getCurrentlyVisibleScreenId(NavigationActivity.java:491)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at com.reactnativenavigation.controllers.NavigationCommandsHandler$35.run(NavigationCommandsHandler.java:546)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-04 16:18:03.837  8030  8030 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
06-04 16:15:41.862  2014  4867 I ActivityManager: START u0 {flg=0x10008000 cmp=nl.nedapstaffingsolutions.pepapp/com.reactnativenavigation.controllers.NavigationActivity (has extras)} from uid 10095
06-04 16:18:03.840  2014  4867 W ActivityManager:   Force finishing activity nl.nedapstaffingsolutions.pepapp/com.reactnativenavigation.controllers.NavigationActivity
```

**Comment by dpkshrma** [comment]
What worked for me was disabling livereload in debug options and only keeping hot reload option enabled
