### ISSUE TITLE
stuck at using react native navigation

### ISSUE THREAD

**Issue by moeinrahimi** [wix/react-native-navigation#2132]
### Issue Description
hello, so i installed the package followed the steps for android setup in official website and when i try to run the project via run-android in process of building i get this output message : 
```
E:\projects\wishlist2\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.M
aterial.Widget.Button.Borderless.Colored'.

E:\projects\wishlist2\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.M
aterial.Widget.Button.Colored'.

E:\projects\wishlist2\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.
Material.Widget.Button.Borderless.Colored'.

E:\projects\wishlist2\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.
Material.Widget.Button.Colored'.


:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```
there maybe issue from my side where it says :
Make sure that isDebug and createAdditionalReactPackages methods are implemented.
I don't understand this part should i import them ?
and also i'm using
```
  compileSdkVersion 23
    buildToolsVersion "23.0.1"
```
in app.java, is it ok or i have to use sdkversion 25 ?

---
### Environment
* React Native Navigation version: 1.1.261
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by fmorato** [comment]
The [install instructions](https://wix.github.io/react-native-navigation/#/installation-android) work. =] 
It says that SDK and buildtools should be version 25, not 23.
Just replace the whole MainApplication.java for what the instructions provide.

Implemented = exists in programming context. You just have to copy and paste. The code in the instructions already implements them.

**Comment by moeinrahimi** [comment]
@fmorato 
ok now i have built my app successfully but it's a blank white screen which shouldn't be .
i think it's because of mainApplication 👍 
my mainApplication : 
```
 public class MainApplication extends NavigationApplication {

     @Override
     public boolean isDebug() {
         // Make sure you are using BuildConfig from your own application
         return BuildConfig.DEBUG;
     }

     protected List<ReactPackage> getPackages() {
         // Add additional packages you require here
         // No need to add RnnPackage and MainReactPackage
         return Arrays.<ReactPackage>asList(
             // eg. new VectorIconsPackage()
         );
     }

     @Override
     public List<ReactPackage> createAdditionalReactPackages() {
         return getPackages();
     }
 }
```
which was this before 👍 
```
//public class MainApplication extends Application implements ReactApplication {
//
//  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
//    @Override
//    public boolean getUseDeveloperSupport() {
//      return BuildConfig.DEBUG;
//    }
//
//    @Override
//    protected List<ReactPackage> getPackages() {
//      return Arrays.<ReactPackage>asList(
//          new MainReactPackage(),
//            new VectorIconsPackage()
//      );
//    }
//  };
//
//  @Override
//  public ReactNativeHost getReactNativeHost() {
//    return mReactNativeHost;
//  }
//
//  @Override
//  public void onCreate() {
//    super.onCreate();
//    SoLoader.init(this, /* native exopackage */ false);
//  }
//}
```

**Comment by fmorato** [comment]
@moeinrahimi, you are right. Actually those functions should be added. So replacing the whole thing is not correct. =]
This is how it should be:
```
package com.your.package.name;

import com.reactnativenavigation.NavigationApplication;

import com.facebook.react.ReactApplication;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

 public class MainApplication extends NavigationApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new VectorIconsPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }

  @Override
  public boolean isDebug() {
      // Make sure you are using BuildConfig from your own application
      return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
      // Add additional packages you require here
      // No need to add RnnPackage and MainReactPackage
      return Arrays.<ReactPackage>asList(
          // eg. new VectorIconsPackage()
      );
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
      return getPackages();
  }
}
```

**Comment by moeinrahimi** [comment]
@fmorato 
ok i have replaced the whole code in mainApplication and rebuilt my app but nothing has changed and it's still a blank screen

**Comment by fmorato** [comment]
You mean the mainActivity.java, right?

Also remember to have `package com.your.package.name;` as the first line in both files.

If it is not working, create the project again and read the instructions a few times. Maybe there is something you missed. I can't help you more than that without seeing the whole thing.

BTW, if you know nothing about Java and Android with Java, I would recommend you to learn something before using react native, or at least any libraries that include native code. You can also try Ionic Framework, in which you won't have to touch native code. Only JS and HTML.

**Comment by moeinrahimi** [comment]
@fmorato ok I managed to solve my issue, just one question about startSingleScreenApp, how can i hide title of screens in my case i don't need it at all

**Comment by fmorato** [comment]
@moeinrahimi, `navigatorStyle: { navBarHidden: true }`

**Comment by moeinrahimi** [comment]
@fmorato 
thanks, my issue have been solved

**Comment by 4bb3** [comment]
@moeinrahimi 
what was your issue ? ran in the same problem with android and startSingleScreenApp

**Comment by Nisthar** [comment]
@moeinrahimi I am having the same issue. how did you fix it?

**Comment by Noitidart** [comment]
@fmorato I tried your code, Im on android. I get error "DeltaPatcher should receive a fresh Delta when being initialized". I am on RN 0.54.2:

```
error: bundling failed: Error
    at DependencyGraph.getAbsolutePath (C:\Users\Mercurius\Documents\GitHub\wix\node_modules\metro\src\node-haste\DependencyGraph.js:316:11)
    at C:\Users\Mercurius\Documents\GitHub\wix\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:280:416
    at Generator.next (<anonymous>)
    at step (C:\Users\Mercurius\Documents\GitHub\wix\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:11:445)
    at C:\Users\Mercurius\Documents\GitHub\wix\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:11:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```


And my `MainApplication.java` is:

```
package com.wix;


import com.reactnativenavigation.NavigationApplication;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

 public class MainApplication extends NavigationApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }

  @Override
  public boolean isDebug() {
      // Make sure you are using BuildConfig from your own application
      return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
      // Add additional packages you require here
      // No need to add RnnPackage and MainReactPackage
      return Arrays.<ReactPackage>asList(
          // eg. new VectorIconsPackage()
      );
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
      return getPackages();
  }
}
```

Thanks for your support!

**Comment by Noitidart** [comment]
@fmorato it seems from the bootstrap example, we don't need to "add" all this original stuff, it seems it can just be  - https://github.com/wix/react-native-navigation-bootstrap/blob/master/android/app/src/main/java/com/react_native_navigation_bootstrap/MainApplication.java

Is this true?

**Comment by Noitidart** [comment]
Oh wow I found the solution. It seems its the android debug mode timing bug.

When you see the blank screen on startup in android:

1) hit the "square" button to show all open apps
2) Then press on your app
3) voila it renders

Here is screenshots of steps:

![](https://i.imgur.com/MuNJ81n.png)

**Comment by Noitidart** [comment]
Also @moeinrahimi and @fmorato this is all we need in `MainApplication.java`:

```
package com.wix; /////// this is the only line that is custom for each app

import com.reactnativenavigation.NavigationApplication;

import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication {

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(

    );
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }

	@Override
	public String getJSMainModuleName() {
		return "index";
  }

}
```

**Comment by Noitidart** [comment]
This is the bug that was affecting us - https://github.com/wix/react-native-navigation/issues/2180
