### ISSUE TITLE
Abort in shared element transition if the image is deleted

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#2233]
### Issue Description

We are using shared element transition to show full screen profile images from avatar sized images. In the full image scree, user can delete the profile photo which causes the photo to be deleted and the we pop the screen. The app crashes when the screen is popped after the user profile photo is deleted with below stack:

```java
11-28 12:33:58.673 6939-6939/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.myapp, PID: 6939
                                                             java.lang.ClassCastException: com.facebook.drawee.drawable.ScalingUtils$ScaleTypeFitCenter cannot be cast to com.facebook.drawee.drawable.ScalingUtils$InterpolatingScaleType
                                                                 at com.reactnativenavigation.views.sharedElementTransition.SharedElementTransition.setMatrixTransform(SharedElementTransition.java:116)
                                                                 at android.animation.PropertyValuesHolder.nCallFloatMethod(Native Method)
                                                                 at android.animation.PropertyValuesHolder.-wrap4(PropertyValuesHolder.java)
                                                                 at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:1388)
                                                                 at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:990)
                                                                 at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1262)
                                                                 at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1310)
                                                                 at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
                                                                 at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
                                                                 at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                 at android.view.Choreographer.doFrame(Choreographer.java:618)
                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### Steps to Reproduce / Code Snippets / Screenshots
Add SET to two screens. In the second screen, add an action to delete the image which results in popping the screen after the image is deleted.

---
### Environment
* React Native Navigation version: 1.1.295
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device

**Comment by varungupta85** [comment]
After some more investigation, I have found that this issue happens only when the `animateClipBounds` is set to true.
