### ISSUE TITLE
Application getting crashed on tapping notification when app is in background

### ISSUE THREAD

**Issue by swaroop03** [wix/react-native-navigation#2253]
Application is put in background and a notification is received by the app.
After tapping notification, app gets stuck on a launch screen and after tapping any soft buttons on phone app gets exited forcefully.
I am using react-native-fcm for notifications.

```
Crashed: main: 0 0 0x0000000000000000
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3746)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3712)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3686)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3660)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1485)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

--

Fatal Exception: java.lang.RuntimeException: Unable to pause activity {com.grup/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3746)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3712)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3686)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3660)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1485)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
       at com.evollu.react.fcm.FIRMessagingModule.onHostResume(FIRMessagingModule.java:143)
       at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:210)
       at com.facebook.react.ReactInstanceManager.moveToBeforeResumeLifecycleState(ReactInstanceManager.java:635)
       at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:518)
       at com.reactnativenavigation.react.NavigationReactGateway.onPauseActivity(NavigationReactGateway.java:79)
       at com.reactnativenavigation.controllers.NavigationActivity.onPause(NavigationActivity.java:138)
       at android.app.Activity.performPause(Activity.java:6812)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1344)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3735)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3712)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3686)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3660)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1485)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

#0. Crashed: main: 0 0 0x0000000000000000
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3746)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3712)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3686)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3660)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1485)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

#1. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2127)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:519)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

How can I fix this issue?
Thanks

### Environment
* React Native Navigation version: 1.1.236
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All devices on both Debug and Release

**Comment by swaroop03** [comment]
This is happening due to FCM issue. When application is in background notification service(react-native-fcm) does not receive any notification which results in notification is sent to system tray. When notification is clicked, it launches new instance of `NavigationActivity` in which case
```
/**
   * Trigger react context initialization asynchronously in a background async task. This enables
   * applications to pre-load the application JS, and execute global code before
   * {@link ReactRootView} is available and measured. This should only be called the first time the
   * application is set up, which is enforced to keep developers from accidentally creating their
   * application multiple times without realizing it.
   *
   * Called from UI thread.
   */
  public void createReactContextInBackground() 
```
method gets called (which should not have).
If I send a data message, it gets received in background and app works fine.
But problem with this is, it will not work as intended when application is killed.
So I want to receive notifications in background to resolve this issue(which I can't do).
Could you please tell me approach to fix this? This need to go in production ASAP. 
Please help me to solve this issue as early as possible.

Thanks.

**Comment by swaroop03** [comment]
Just found that data message is also received when app is killed. Will fix it by my end.
