### ISSUE TITLE
[Help] Android application has stopped when release

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#231]
Hi all,

i've generate a signed apk [using this tutorial](https://facebook.github.io/react-native/docs/signed-apk-android.html). Then i installed the release using gradlew installRelease and the installation was successful but when i run the apk it says : "unfortunately, application has stopped" after loaded First screen apps. (On first screen i've call api, then start app using Navigation.startTabBasedApp...) 
but when i install and tun it using react-native run-android command it will work perfectly . 

Do any one have any idea what i'm doing wrong?
This log device report:

> java.lang.NullPointerException
> at com.aurelhubert.ahbottomnavigation.AHHelper.getTintDrawable(AHHelper.java:37)
> at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createSmallItems(AHBottomNavigation.java:447)
> at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(AHBottomNavigation.java:236)
> at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeChanged(AHBottomNavigation.java:132)
> at android.view.View.sizeChange(View.java:14960)
> at android.view.View.setFrame(View.java:14933)
> at android.view.View.layout(View.java:14841)
> at android.view.ViewGroup.layout(ViewGroup.java:4631)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
> at android.view.View.layout(View.java:14845)
> at android.view.ViewGroup.layout(ViewGroup.java:4631)
> at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1191)
> at android.view.View.layout(View.java:14845)
> at android.view.ViewGroup.layout(ViewGroup.java:4631)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
> at android.view.View.layout(View.java:14845)
> at android.view.ViewGroup.layout(ViewGroup.java:4631)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
> at android.view.View.layout(View.java:14845)
> at android.view.ViewGroup.layout(ViewGroup.java:4631)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
> at android.view.View.layout(View.java:14845)
> at android.view.ViewGroup.layout(ViewGroup.java:4631)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
> at android.view.View.layout(View.java:14845)
> at android.view.ViewGroup.layout(ViewGroup.java:4631)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
> at android.view.View.layout(View.java:14845)
> at android.view.ViewGroup.layout(ViewGroup.java:4631)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
> at android.view.View.layout(View.java:14845)
> at android.view.ViewGroup.layout(ViewGroup.java:4631)
> at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2026)
> at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1783)
> at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1039)
> at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5648)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
> at android.view.Choreographer.doCallbacks(Choreographer.java:574)
> at android.view.Choreographer.doFrame(Choreographer.java:544)
> at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
> at android.os.Handler.handleCallback(Handler.java:733)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:136)
> at android.app.ActivityThread.main(ActivityThread.java:5049)
> at java.lang.reflect.Method.invokeNative(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:515)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
> at dalvik.system.NativeStart.main(Native Method)

**Comment by agumack** [comment]
Log: 

> react native Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

**Comment by guyca** [comment]
On what device are you trying to run? What OS version?

**Comment by agumack** [comment]
@guyca 
seem i found a reason. 

my apps using Navigation.startTabBasedApp
It work perfectly when tun using react-native run-android
But error when installed the release using gradlew installRelease 
This is log:

> Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

Then, I tried instead Navigation.startTabBasedApp by Navigation.startSingleScreenApp = > work perfectly with installRelease and run-android.

I think have problem with "startTabBasedApp" 

Hope help from you, thank you!

**Comment by guyca** [comment]
@agumack What RN version are you running?

**Comment by agumack** [comment]
@guyca 
"react": "15.2.1",
"react-native": "0.31.0",

**Comment by guyca** [comment]
@agumack The app crashes only when you call `startTabBasedApp` because there seems to be an issue with drawing BottomTab icons on your pre-Lollipop device.

1. Try to run on a device with Lollipop or higher, let me know if it works.
2. What version of Android support library do you have installed on your machine?

**Comment by agumack** [comment]
thanks @guyca

I do not have a device Lollipop to test now, 
on machine:

<img width="710" alt="screen shot 2016-08-25 at 6 52 50 pm" src="https://cloud.githubusercontent.com/assets/19372005/17968103/3745a248-6af5-11e6-808a-bf119e243f03.png">

**Comment by guyca** [comment]
You can create an emulator with Lollipop OS.

Support library is under `extras` section.
<img width="705" alt="screen shot 2016-08-25 at 3 06 34 pm" src="https://cloud.githubusercontent.com/assets/12352397/17968458/a28c5954-6ad5-11e6-87de-68c1f814c6c9.png">

**Comment by agumack** [comment]
@guyca Lollipop device work perfectly

**Comment by agumack** [comment]
@guyca 
this issue because i have using [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons)

I instead icon-vector by image as your example and work now. :)

**Comment by agumack** [comment]
@guyca  vector icons doesn't work with setButtons, too.
react-native run-android: work
release: not display
