### ISSUE TITLE
 when push a new screen and pop it out many times,it will lead to crash

### ISSUE THREAD

**Issue by yechunxi** [wix/react-native-navigation#2316]
### Issue Description
 

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

When the push to a new screen, and then pop it out, repeat the operation, will lead to app crash

### Steps to Reproduce / Code Snippets / Screenshots

1. first push to a new screen
2. pop it out
3. repeat much times

[FILL THIS OUT - It will be extremely helpful]
this is the log info 
Exception in native call
                                                java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.facebook.react.uimanager.ReactShadowNode.isLayoutOnly()' on a null object reference
                                                    at com.facebook.react.uimanager.NativeViewHierarchyOptimizer.addNodeToNode(NativeViewHierarchyOptimizer.java:263)
                                                    at com.facebook.react.uimanager.NativeViewHierarchyOptimizer.handleManageChildren(NativeViewHierarchyOptimizer.java:181)
                                                    at com.facebook.react.uimanager.UIImplementation.manageChildren(UIImplementation.java:358)
                                                    at com.facebook.react.uimanager.UIManagerModule.manageChildren(UIManagerModule.java:291)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
                                                    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166)
                                                    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                    at android.os.Looper.loop(Looper.java:154)
                                                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                    at java.lang.Thread.run(Thread.java:761)

---
### Environment
* React Native Navigation version: v1.1.299
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):  ALL

**Comment by fauzzi** [comment]
this problem has resolved?
