### ISSUE TITLE
Redirect to Home after taking Photo

### ISSUE THREAD

**Issue by Thadeu** [wix/react-native-navigation#2383]
### Issue Description

I'm using react-native-image-picker and then after take(select) a photo the app redirects to home and I get the following log.

### Steps to Reproduce / Code Snippets / Screenshots
```
12-20 11:04:03.916 7010-8702/com.rn_navigation_imagepicker I/ReactNativeJS: Running application "TakePhoto" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID3","navigatorID":"navigatorID1_nav","navigatorEventID":"screenInstanceID3_events"},"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
12-20 11:04:04.621 7010-8702/com.rn_navigation_imagepicker I/ReactNativeJS: [ Debugger ] Open Select Photo
12-20 11:04:05.524 7010-7031/com.rn_navigation_imagepicker E/Surface: getSlotFromBufferLocked: unknown buffer: 0xba0f78e0
12-20 11:04:06.077 7010-8702/com.rn_navigation_imagepicker I/ReactNativeJS: [ Debugger ] componentWillUmmount ReactNative launched..............................
12-20 11:04:11.929 7010-8702/com.rn_navigation_imagepicker I/ReactNativeJS: Running application "Home" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID2","navigatorID":"navigatorID1_nav","navigatorEventID":"screenInstanceID2_events"},"rootTag":21}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
12-20 11:04:11.997 7010-7025/com.rn_navigation_imagepicker W/unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
12-20 11:04:11.997 7010-7010/com.rn_navigation_imagepicker W/unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
12-20 11:04:11.998 7010-7089/com.rn_navigation_imagepicker W/unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
12-20 11:04:12.055 7010-7021/com.rn_navigation_imagepicker I/TAG: Finished scanning /storage/emulated/0/Android/data/com.rn_navigation_imagepicker/files/Pictures/image-bfef3f0b-33c8-42da-acf2-5db075c9ae02.jpg
````

MainApplication.java

````
package com.rn_navigation_imagepicker;

import android.app.Application;
import android.content.Intent;
import android.os.Bundle;

import com.facebook.react.ReactApplication;
import com.imagepicker.ImagePickerPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
 import com.reactnativenavigation.NavigationApplication;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication implements ReactApplication {

  // @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }
  
  @Override
  public boolean clearHostOnActivityDestroy() {
    return false;
  }
  
  public boolean getUseDeveloperSupport() {
    return BuildConfig.DEBUG;
  }

  // @Override
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new ImagePickerPackage()
    );
  }

  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }

  @Override
  public void onCreate() {
    super.onCreate();
  }
}

```

MainActivity.java

````
package com.rn_navigation_imagepicker;

import android.content.Intent;
import android.os.Bundle;

import com.facebook.react.ReactActivity;
import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    protected String getMainComponentName() {
        return "rn_navigation_imagepicker";
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
    }
}

```

Picker Method

```
openPicker() {
    const options = {
      quality: 1.0,
      maxWidth: 100,
      maxHeight: 100,
      storageOptions: {
        skipBackup: true
      }
    };
    
    console.log('[ Debugger ] Open Select Photo')

    ImagePicker.showImagePicker(options, (response) => {
      if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else {
        source = { uri: response.uri, isStatic: true };    
        
        this.setName()
        this.updatePhotos(source)
      }
    });
  }
```

Any idea how to solve it?

---
### Environment
* React Native Navigation version: 1.1.314
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/Debug

**Comment by Thadeu** [comment]
When I remove the code below

```java
@Override
public boolean clearHostOnActivityDestroy() {
  return false;
}
```

I get the following log and crash

```
12-20 11:21:12.078 24309-24374/com.rn_navigation_imagepicker I/ReactNativeJS: Running application "TakePhoto" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID3","navigatorID":"navigatorID1_nav","navigatorEventID":"screenInstanceID3_events"},"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
12-20 11:21:12.813 24309-24374/com.rn_navigation_imagepicker I/ReactNativeJS: [ Debugger ] Open Select Photo
12-20 11:21:13.736 24309-24345/com.rn_navigation_imagepicker E/Surface: getSlotFromBufferLocked: unknown buffer: 0xba085398
12-20 11:21:14.261 24309-24374/com.rn_navigation_imagepicker W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
12-20 11:21:14.263 24309-24374/com.rn_navigation_imagepicker W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {5f7fe7f} sending message to a Handler on a dead thread
                                                                             java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {5f7fe7f} sending message to a Handler on a dead thread
                                                                                 at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                                 at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                                 at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                                 at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                                 at android.os.Handler.post(Handler.java:326)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                 at android.os.Handler.handleCallback(Handler.java:746)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                                 at java.lang.Thread.run(Thread.java:818)
12-20 11:21:14.265 24309-24374/com.rn_navigation_imagepicker W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
12-20 11:21:14.266 24309-24374/com.rn_navigation_imagepicker W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {5f7fe7f} sending message to a Handler on a dead thread
                                                                             java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {5f7fe7f} sending message to a Handler on a dead thread
                                                                                 at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                                 at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                                 at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                                 at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                                 at android.os.Handler.post(Handler.java:326)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                 at android.os.Handler.handleCallback(Handler.java:746)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                                 at java.lang.Thread.run(Thread.java:818)
12-20 11:21:14.266 24309-24374/com.rn_navigation_imagepicker W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
12-20 11:21:14.267 24309-24374/com.rn_navigation_imagepicker W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {5f7fe7f} sending message to a Handler on a dead thread
                                                                             java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {5f7fe7f} sending message to a Handler on a dead thread
                                                                                 at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                                 at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                                 at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                                 at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                                 at android.os.Handler.post(Handler.java:326)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                 at android.os.Handler.handleCallback(Handler.java:746)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                                 at java.lang.Thread.run(Thread.java:818)
12-20 11:21:21.601 24309-24309/com.rn_navigation_imagepicker W/unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
12-20 11:21:21.607 24309-24380/com.rn_navigation_imagepicker W/unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
12-20 11:21:21.608 24309-24535/com.rn_navigation_imagepicker W/unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
12-20 11:21:21.660 24309-24309/com.rn_navigation_imagepicker W/unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
12-20 11:21:21.666 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
12-20 11:21:21.667 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
12-20 11:21:21.669 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
12-20 11:21:21.670 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
12-20 11:21:21.673 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
12-20 11:21:21.674 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
12-20 11:21:21.675 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
12-20 11:21:21.685 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
12-20 11:21:21.696 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
12-20 11:21:21.700 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
12-20 11:21:21.700 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
12-20 11:21:21.707 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
12-20 11:21:21.711 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
12-20 11:21:21.712 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
12-20 11:21:21.717 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
12-20 11:21:21.720 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
12-20 11:21:21.721 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
12-20 11:21:21.725 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
12-20 11:21:21.725 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
12-20 11:21:21.730 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
12-20 11:21:21.735 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
12-20 11:21:21.743 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
12-20 11:21:21.744 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
12-20 11:21:21.745 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
12-20 11:21:21.745 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
12-20 11:21:21.747 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
12-20 11:21:21.752 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
12-20 11:21:21.754 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
12-20 11:21:21.755 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
12-20 11:21:21.764 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
12-20 11:21:21.769 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
12-20 11:21:21.784 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
12-20 11:21:21.785 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
12-20 11:21:21.786 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
12-20 11:21:21.792 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
12-20 11:21:21.793 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
12-20 11:21:21.793 24309-24688/com.rn_navigation_imagepicker W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.reactnativenavigation.views.managers.SharedElementTransitionManager
                                                                                                   
                                                                                                   --------- beginning of crash
12-20 11:21:21.801 24309-24688/com.rn_navigation_imagepicker E/AndroidRuntime: FATAL EXCEPTION: Thread-2547
                                                                               Process: com.rn_navigation_imagepicker, PID: 24309
                                                                               java.lang.RuntimeException: java.lang.InterruptedException
                                                                                   at com.facebook.react.common.futures.SimpleSettableFuture.getOrThrow(SimpleSettableFuture.java:102)
                                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl.startNewBackgroundThread(MessageQueueThreadImpl.java:199)
                                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl.create(MessageQueueThreadImpl.java:146)
                                                                                   at com.facebook.react.bridge.queue.ReactQueueConfigurationImpl.create(ReactQueueConfigurationImpl.java:87)
                                                                                   at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:101)
                                                                                   at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:41)
                                                                                   at com.facebook.react.bridge.CatalystInstanceImpl$Builder.build(CatalystInstanceImpl.java:569)
                                                                                   at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:979)
                                                                                   at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
                                                                                   at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:743)
                                                                                   at java.lang.Thread.run(Thread.java:818)
                                                                                Caused by: java.lang.InterruptedException
                                                                                   at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1276)
                                                                                   at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:203)
                                                                                   at com.facebook.react.common.futures.SimpleSettableFuture.get(SimpleSettableFuture.java:66)
                                                                                   at com.facebook.react.common.futures.SimpleSettableFuture.getOrThrow(SimpleSettableFuture.java:100)
                                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl.startNewBackgroundThread(MessageQueueThreadImpl.java:199) 
                                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl.create(MessageQueueThreadImpl.java:146) 
                                                                                   at com.facebook.react.bridge.queue.ReactQueueConfigurationImpl.create(ReactQueueConfigurationImpl.java:87) 
                                                                                   at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:101) 
                                                                                   at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:41) 
                                                                                   at com.facebook.react.bridge.CatalystInstanceImpl$Builder.build(CatalystInstanceImpl.java:569) 
                                                                                   at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:979) 
                                                                                   at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109) 
                                                                                   at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:743) 
                                                                                   at java.lang.Thread.run(Thread.java:818) 
12-20 11:21:22.012 24309-24345/com.rn_navigation_imagepicker E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb9de1b48
12-20 11:21:27.246 24309-24363/com.rn_navigation_imagepicker A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 24363 (HybridData Dest)
```

**Comment by Thadeu** [comment]
@guyca

**Comment by Thadeu** [comment]
@varungupta85

**Comment by Thadeu** [comment]
I'm testing on device Motorola X2 and I get following log by crash.
Only in this type device I get error, in the samsung device I dont get error

```
12-20 13:30:25.811 30238-30238/net.consisti.vvbrasil E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: net.consisti.vvbrasil, PID: 30238
                                                                       java.lang.RuntimeException: Unable to resume activity {net.consisti.vvbrasil/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://media/external/images/media/6052 flg=0x1 }} to activity {net.consisti.vvbrasil/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Activity com.facebook.react.bridge.ReactContext.getCurrentActivity()' on a null object reference
                                                                           at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3121)
                                                                           at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                        Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://media/external/images/media/6052 flg=0x1 }} to activity {net.consisti.vvbrasil/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Activity com.facebook.react.bridge.ReactContext.getCurrentActivity()' on a null object reference
                                                                           at android.app.ActivityThread.deliverResults(ActivityThread.java:3720)
                                                                           at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3107)
                                                                           at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Activity com.facebook.react.bridge.ReactContext.getCurrentActivity()' on a null object reference
                                                                           at com.reactnativenavigation.react.NavigationReactGateway.onActivityResult(NavigationReactGateway.java:91)
                                                                           at com.reactnativenavigation.controllers.NavigationActivity.onActivityResult(NavigationActivity.java:185)
                                                                           at android.app.Activity.dispatchActivityResult(Activity.java:6442)
                                                                           at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
                                                                           at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3107) 
                                                                           at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

My MainApplication.java now

```java
import android.app.Application;
import com.evollu.react.fcm.FIRMessagingPackage;
import com.learnium.RNDeviceInfo.RNDeviceInfo;

import com.facebook.react.ReactApplication;
import com.azendoo.reactnativesnackbar.SnackbarPackage;
import com.microsoft.codepush.react.CodePush;
import cl.json.RNSharePackage;
import com.imagepicker.ImagePickerPackage;
import com.oblador.vectoricons.VectorIconsPackage;

import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

import com.reactnativenavigation.NavigationApplication;

public class MainApplication extends NavigationApplication {

  @Override
  public boolean isDebug() {
      return BuildConfig.DEBUG;
  }

  @Override
  public String getJSBundleFile() {
    return CodePush.getJSBundleFile();
  }

  // @Override
  // public boolean clearHostOnActivityDestroy() {
  //   return false;
  // }

  protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new RNDeviceInfo(),
          new VectorIconsPackage(),
          new ImagePickerPackage(),
          new SnackbarPackage(),
          new RNSharePackage(),
          new FIRMessagingPackage(),
          new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG)
      );
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
      return getPackages();
  }
}
```

**Comment by aspidvip** [comment]
me to, this error
