### ISSUE TITLE
Can't get Android app to compile.

### ISSUE THREAD

**Issue by aidenwallis** [wix/react-native-navigation#2519]
### Issue Description

Can't seem to get the app booting from Android studio, just get this screen when trying:

From this error:
```01-13 15:06:25.278 6559-6559/com.epicsmobile E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.epicsmobile, PID: 6559
                                                               java.lang.RuntimeException: Unable to resume activity {com.epicsmobile/com.epicsmobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.react.ReactGateway com.reactnativenavigation.NavigationApplication.getReactGateway()' on a null object reference
                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.react.ReactGateway com.reactnativenavigation.NavigationApplication.getReactGateway()' on a null object reference
                                                                   at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:42)
                                                                   at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
                                                                   at android.app.Activity.performResume(Activity.java:6312)
                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481) 
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
### Steps to Reproduce / Code Snippets / Screenshots

Everything is basically the generic setup.

MainApplication.java
``` package com.epicsmobile;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.react.rnspinkit.RNSpinkitPackage;
import com.reactnativenavigation.bridge.NavigationReactPackage;
import com.airbnb.android.react.maps.MapsPackage;
import com.BV.LinearGradient.LinearGradientPackage;
import dk.madslee.imageSequence.RCTImageSequencePackage;
import com.imagepicker.ImagePickerPackage;
import com.dylanvann.fastimage.FastImageViewPackage;
import com.lwansbrough.RCTCamera.RCTCameraPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNSpinkitPackage(),
            new NavigationReactPackage(),
            new MapsPackage(),
            new LinearGradientPackage(),
            new RCTImageSequencePackage(),
            new ImagePickerPackage(),
            new FastImageViewPackage(),
            new RCTCameraPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

build.gradle
```apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.3"

    defaultConfig {
        applicationId "com.epicsmobile"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-spinkit')
    compile project(':react-native-navigation')
    compile project(':react-native-maps')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-image-sequence')
    compile project(':react-native-image-picker')
    compile project(':react-native-fast-image')
    compile project(':react-native-camera')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:24.0.3"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

---
### Environment
* React Native Navigation version: 1.1.336
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): Android (works on iOS fine)
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 6 API 23 (simulator on Android Studio)

**Comment by alien3d** [comment]
new release update ?  mine still 1.1.334

**Comment by gregjw** [comment]
bump

**Comment by pqkluan** [comment]
Your MainApplication is not modified after the [Android install instruction](https://wix.github.io/react-native-navigation/#/installation-android?id=android-installation).

**Comment by skymax406** [comment]
Hello same issue, very frustrating.

My App was working since many month and now the same error : 

```
05-15 09:14:53.003 26312 26312 E AndroidRuntime: FATAL EXCEPTION: main
05-15 09:14:53.003 26312 26312 E AndroidRuntime: Process: net.solidom.fhe.appautonome, PID: 26312
05-15 09:14:53.003 26312 26312 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {net.solidom.fhe.appautonome/net.solidom.fhe.appautonome.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.react.ReactGateway com.reactnativenavigation.NavigationApplication.getReactGateway()' on a null object reference
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3535)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3575)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6316)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.react.ReactGateway com.reactnativenavigation.NavigationApplication.getReactGateway()' on a null object reference
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:43)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6861)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3512)
05-15 09:14:53.003 26312 26312 E AndroidRuntime: 	... 10 more
05-15 09:14:53.005  1524  6372 W ActivityManager:   Force finishing activity net.solidom.fhe.appautonome/.MainActivity
```

*MainActivity.java*

```
package net.solidom.fhe.appautonome;

import com.reactnativenavigation.controllers.SplashActivity;

import com.facebook.react.ReactActivity;

public class MainActivity extends SplashActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */

    /**
     * @return xml layout res id
     */
    @Override
    public int getSplashLayout() {
        return R.layout.splashpage_layout;
    }

}
```
