### ISSUE TITLE
side menu drawer is not open to ANDROID

### ISSUE THREAD

**Issue by aspidvip** [wix/react-native-navigation#2624]
![2018-02-02 16_11_58](https://user-images.githubusercontent.com/22605655/35719185-ea8722d2-0833-11e8-8fc4-6843594ad9fb.gif)
---
### Environment
* React Native Navigation version: 1.1.365
* React Native version: 0.49.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): 4.2, 6.0, 7.0

```
D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
I/ReactNativeJS: Running application "DostprSeePage" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID46","navigatorID":"navigatorID20_nav","navigatorEventID":"screenInstanceID46_events"},"rootTag":351}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
D/ReactNative: ReactInstanceManager.detachViewFromInstance()
D/ReactNative: ReactInstanceManager.detachViewFromInstance()
E/unknown:ReactNative: Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gest
![2018-02-02 16_11_58](https://user-images.githubusercontent.com/22605655/35719168-d35f60ec-0833-11e8-8eab-22e0364cea49.gif)
ure before
E/unknown:ReactNative: Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before
```

**Comment by aspidvip** [comment]
```
D/ReactNative: ReactInstanceManager.detachViewFromInstance()
E/unknown:ReactNative: Received an ACTION_CANCEL touch event for which we have no corresponding ACTION_DOWN
E/unknown:ReactNative: Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before
E/unknown:ReactNative: Received an ACTION_CANCEL touch event for which we have no corresponding ACTION_DOWN
E/unknown:ReactNative: Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before
E/unknown:ReactNative: Received an ACTION_CANCEL touch event for which we have no corresponding ACTION_DOWN
E/unknown:ReactNative: Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before
E/unknown:ReactNative: Received an ACTION_CANCEL touch event for which we have no corresponding ACTION_DOWN
E/unknown:ReactNative: Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before
D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
I/ReactNativeJS: Running application "DostoprPreview" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID70","navigatorID":"navigatorID61_nav","navigatorEventID":"screenInstanceID70_events"},"rootTag":461}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
I/ReactNativeJS: { result: 
                    [ { id: '23',
                        title: 'Fgdfgdfdg',
                        adress_city: 'Российская Федерация, Приморский край, Находка',
                        opis: 'Укеукеуе',
                        images: 
                         [ { url: 'http://publikun.com/sight/23/img/704134.jpg',
                             src: '/sight/23/img/704134.jpg' } ],
                        star: { count_users: '0', star: 0 } } ],
                   max_count_page: 1 }
E/NativeViewHierarchyManager: Unable to update properties for view tag 4040
                              com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 4040 could not be found
                                  at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:106)
                                  at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:123)
                                  at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:248)
                                  at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:69)
                                  at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:516)
                                  at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:427)
                                  at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:117)
                                  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
                                  at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                  at android.view.Choreographer.doFrame(Choreographer.java:655)
                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                  at android.os.Handler.handleCallback(Handler.java:789)
                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                  at android.os.Looper.loop(Looper.java:164)
                                  at android.app.ActivityThread.main(ActivityThread.java:6541)
                                  at java.lang.reflect.Method.invoke(Native Method)
                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
D/ReactNative: ReactInstanceManager.detachViewFromInstance()
D/EGL_emulation: eglMakeCurrent: 0xa1811de0: ver 2 0 (tinfo 0xa18a8b40)
I/ReactNativeJS: [React Transform HMR] Patching SideMenu
D/EGL_emulation: eglMakeCurrent: 0xa1811de0: ver 2 0 (tinfo 0xa18a8b40)
E/unknown:ReactNative: Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before
E/unknown:ReactNative: Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before
E/unknown:ReactNative: Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before
D/EGL_emulation: eglMakeCurrent: 0xa1811de0: ver 2 0 (tinfo 0xa18a8b40)
I/ReactNativeJS: [React Transform HMR] Patching SideMenu
D/EGL_emulation: eglMakeCurrent: 0xa1811de0: ver 2 0 (tinfo 0xa18a8b40)

```

**Comment by aspidvip** [comment]
each time in different ways

**Comment by chubakueno** [comment]
I don't think the first log describes the crashing reason, none of those errors seems fatal. The second may be an actual reason, but i am not sure about it having to do with react-native-navigation. Can you provide some code?

**Comment by aspidvip** [comment]
side_menu.js

```
<View style={{flex: 1, backgroundColor: '#363636'}}>
      {Platform.OS==='ios' &&
      <View style={{height: 25, backgroundColor: '#363636',}}>
      </View>
      }
<ScrollView>

      <View style={styles.btns_top}>
      <TouchableOpacity onPress={()=>this.props.navigation.push({screen: 'onePage', title: 'onePage'}>
          <Text style={styles.menu_text}>One Page</Text>
          </TouchableOpacity>
</View>
</ScrollView>
</View>
```
onePage.js

```
constructor(props){
      super(props);
      this.state={
        refreshing: true,
        load: true,
        data: [{
title: '11111',
id: 1,
}],
      }
    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
  }


onNavigatorEvent(event) {
    switch (event.id) {
      case 'slideMenu':
        this.OpenSlideMenu();
      break;
    }}

OpenSlideMenu(){
      this.props.navigator.toggleDrawer({
        side: 'left', 
        animated: true, 
      });

    }

render() {
      return (
        <List style={{flex: 1}}>
        <FlatList
        style={{backgroundColor: 'white',}}
        data = {this.state.data}
        renderItem={this._renerRowList.bind(this)}
        ListFooterComponent={this.renderFooter}
        keyExtractor={this._keyExtractor}
        onRefresh={this.state.load ? null : this.handleRefresh}
        refreshing={this.state.refreshing}
        />
        </List>
      )
    }
```

the code is very large. The menu works fine, but it takes a while and it stops working! The menu works well on iOS

**Comment by windydang26** [comment]
sometimes menu on android not working for me, although not display black screen. nothing change, drawer not open!
