### ISSUE TITLE
ImageLoader exception

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#266]
Getting the following on running my app with RNN v2.0 now:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mycompany.appname/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.RuntimeException: images_navicon_add
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    Caused by: java.lang.RuntimeException: images_navicon_add
    at com.reactnativenavigation.react.JsDevImageLoader.loadIcon(JsDevImageLoader.java:27)
    at com.reactnativenavigation.react.ImageLoader.loadImage(ImageLoader.java:11)
    at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser.parseSingleButton(TitleBarButtonParamsParser.java:26)
    at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser$1.parse(TitleBarButtonParamsParser.java:17)
    at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser$1.parse(TitleBarButtonParamsParser.java:14)
    at com.reactnativenavigation.params.parsers.Parser.parseBundle(Parser.java:34)
    at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser.parseButtons(TitleBarButtonParamsParser.java:14)
    at com.reactnativenavigation.params.parsers.ScreenParamsParser.parseRightButton(ScreenParamsParser.java:84)
    at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:38)
    at com.reactnativenavigation.params.parsers.ScreenParamsParser$1.parse(ScreenParamsParser.java:106)
    at com.reactnativenavigation.params.parsers.ScreenParamsParser$1.parse(ScreenParamsParser.java:103)
    at com.reactnativenavigation.params.parsers.Parser.parseBundle(Parser.java:34)
    at com.reactnativenavigation.params.parsers.ScreenParamsParser.parseTabs(ScreenParamsParser.java:103)
    at com.reactnativenavigation.params.parsers.ActivityParamsParser.parse(ActivityParamsParser.java:21)
    at com.reactnativenavigation.controllers.NavigationCommandsHandler.parseActivityParams(NavigationCommandsHandler.java:21)
    at com.reactnativenavigation.controllers.NavigationActivity.onCreate(NavigationActivity.java:51)
    at android.app.Activity.performCreate(Activity.java:6237)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    Caused by: java.net.MalformedURLException: Protocol not found: images_navicon_add
    at java.net.URL.<init>(URL.java:176)
    at java.net.URL.<init>(URL.java:125)
    at com.reactnativenavigation.react.JsDevImageLoader.tryLoadIcon(JsDevImageLoader.java:33)
at com.reactnativenavigation.react.JsDevImageLoader.loadIcon(JsDevImageLoader.java:22)
    at com.reactnativenavigation.react.ImageLoader.loadImage(ImageLoader.java:11) 
    at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser.parseSingleButton(TitleBarButtonParamsParser.java:26) 
    at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser$1.parse(TitleBarButtonParamsParser.java:17) 
    at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser$1.parse(TitleBarButtonParamsParser.java:14) 
    at com.reactnativenavigation.params.parsers.Parser.parseBundle(Parser.java:34) 
    at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser.parseButtons(TitleBarButtonParamsParser.java:14) 
    at com.reactnativenavigation.params.parsers.ScreenParamsParser.parseRightButton(ScreenParamsParser.java:84) 
    at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:38) 
    at com.reactnativenavigation.params.parsers.ScreenParamsParser$1.parse(ScreenParamsParser.java:106) 
    at com.reactnativenavigation.params.parsers.ScreenParamsParser$1.parse(ScreenParamsParser.java:103) 
    at com.reactnativenavigation.params.parsers.Parser.parseBundle(Parser.java:34) 
    at com.reactnativenavigation.params.parsers.ScreenParamsParser.parseTabs(ScreenParamsParser.java:103) 
    at com.reactnativenavigation.params.parsers.ActivityParamsParser.parse(ActivityParamsParser.java:21) 
    at com.reactnativenavigation.controllers.NavigationCommandsHandler.parseActivityParams(NavigationCommandsHandler.java:21) 
    at com.reactnativenavigation.controllers.NavigationActivity.onCreate(NavigationActivity.java:51) 
    at android.app.Activity.performCreate(Activity.java:6237) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
Seems to have just started occurring, and may be related to a [similar issue](https://github.com/wix/react-native-navigation/issues/176) I had a couple of weeks ago. 
I've tried a clean and rebuild, `react-native bundle --assets-dest`, checked the image exists, no joy so far. My previous solution was to rebuild the project.

**Comment by adamski** [comment]
Hmm this only happens in dev mode, release is fine now... strange.

**Comment by guyca** [comment]
That's because images are handled differently in dev and release. Usually restarting the packager solves it for me.

**Comment by vivekparekh8** [comment]
@adamski same issue faced only on kitkat devices. Although works fine on release mode.

**Comment by guyca** [comment]
@vivekparekh8 Which RNN version?

**Comment by vivekparekh8** [comment]
2.0.0-experimental.127 @guyca

**Comment by guyca** [comment]
Try upgrading please

**Comment by rusfearuth** [comment]
I had the same problem.

Use the next in your application instance:
```
  @Override
  public boolean isDebug()
  {
    return BuildConfig.DEBUG;
  }
```

**Comment by Manish3323** [comment]
I have the same problem
logs  : _getIntent()_ is getting called. i think the Activity is not yet started .so this is creating a circular dependency i guess .

`06-10 22:25:02.709 1621-1621/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.bet18, PID: 1621
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bet18/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.NullPointerException: uriString
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6938)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
                                                  Caused by: java.lang.NullPointerException: uriString
                                                     at android.net.Uri$StringUri.<init>(Uri.java:476)
                                                     at android.net.Uri$StringUri.<init>(Unknown Source:0)
                                                     at android.net.Uri.parse(Uri.java:438)
                                                     at com.reactnativenavigation.react.ImageLoader.loadImage(ImageLoader.java:18)
                                                     at com.reactnativenavigation.params.parsers.TabIconParser.parse(TabIconParser.java:19)
                                                     at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:57)
                                                     at com.reactnativenavigation.params.parsers.ActivityParamsParser.parse(ActivityParamsParser.java:18)
                                                     at com.reactnativenavigation.controllers.NavigationCommandsHandler.parseActivityParams(NavigationCommandsHandler.java:21)
                                                     at com.reactnativenavigation.controllers.NavigationActivity.onCreate(NavigationActivity.java:77)
                                                     at android.app.Activity.performCreate(Activity.java:7174)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6938) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) `
