### ISSUE TITLE
Properly Setting the Splash Screen

### ISSUE THREAD

**Issue by joecaraccio** [wix/react-native-navigation#2760]
I've noticed, using the activity splash screen.. it still doesn't really achieve the same desired effect of a true splashscreen.

In the splash activity, I tried setting the splashscreen that way
```

  @Override
  public LinearLayout createSplashLayout() {
        LinearLayout view = new LinearLayout(this);
         view.setBackgroundColor(Color.parseColor("#42A5F5"));
         view.setGravity(Gravity.CENTER);

}

```

However there will still be a white flash, at least on Android. My response to that was to then set the app theme to that color as well. Although, the issue with this is on certain components, or say when the keyboard opens, you can see this blue background briefly

so, I guess the TLDR is does anyone have a solution we reflects that true native splash screen feel, no white splash

**Comment by aMarCruz** [comment]
@joecaraccio , this worked for me:

android/app/src/main/res/drawable/splash.xml
```xml
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/primaryColor"/>
    <item>
        <bitmap
            android:gravity="center"
            android:src="@drawable/app_logo"/>
    </item>
</layer-list>
```

android/app/src/main/res/values/styles.xml
```xml
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/primaryColor</item>
        <item name="colorPrimaryDark">@color/primaryDarkColor</item>
        <item name="colorAccent">@color/primaryLightColor</item>
        <item name="android:statusBarColor">@color/statusbarColor</item>
        <item name="android:windowBackground">@color/primaryColor</item>
    </style>

    <style name="SplashScreen" parent="AppTheme">
        <item name="android:windowBackground">@drawable/splash</item>
    </style>

</resources>
```

android/app/src/main/AndroidManifest.xml (partial)
```xml
    <application
        android:name=".MainApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:theme="@style/SplashScreen"
   ...
```

android/app/src/main/<your-app-path>/MainActivity.java (partial)
```java
import android.view.View;
import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {

  @Override
  public View createSplashLayout() {
    return new View(this);   // <====== TO AVOID WHITE BACKGROUND
  }
  ...
```

My first screen' background is the primaryColor (#4269d2), by returning a transparent view in `createSplashLayout` we avoids the default white background and we have a pretty fade-effect.

**Comment by pqkluan** [comment]
Hey, I just wrote a detail [article](https://medium.com/@pqkluan/how-to-implement-splash-screen-in-react-native-navigation-ee2184a1a96) about implementing Splash Screen with RNN.

**Comment by echonox** [comment]
@pqkluan I followed the tutorial everything is in order but i get:

FATAL EXCEPTION: main
                                                             Process: com.chatapp, PID: 23711
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chatapp/com.chatapp.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/splash.xml from drawable resource ID #0x7f020080
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                              Caused by: android.content.res.Resources$NotFoundException: File res/drawable/splash.xml from drawable resource ID #0x7f020080
                                                                 at android.content.res.Resources.loadDrawableForCookie(Resources.java:4216)
                                                                 at android.content.res.Resources.loadDrawable(Resources.java:4085)
                                                                 at android.content.res.Resources.getDrawable(Resources.java:2005)
                                                                 at android.content.res.Resources.getDrawable(Resources.java:1987)
                                                                 at android.content.Context.getDrawable(Context.java:464)
                                                                 at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:30)
                                                                 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
                                                                 at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
                                                                 at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
                                                                 at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155)
                                                                 at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
                                                                 at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
                                                                 at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java:33)
                                                                 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:203)
                                                                 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
                                                                 at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
                                                                 at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                 at com.reactnativenavigation.controllers.SplashActivity.onCreate(SplashActivity.java:32)
                                                                 at android.app.Activity.performCreate(Activity.java:6876)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:158) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                              Caused by: android.content.res.Resources$NotFoundException: File rgba(0,0,0,0) from drawable resource ID #0x7f0d0053
                                                                 at android.content.res.Resources.loadDrawableForCookie(Resources.java:4216)
                                                                 at android.content.res.Resources.loadDrawable(Resources.java:4085)
                                                                 at android.content.res.Resources.loadDrawable(Resources.java:3935)
                                                                 at android.content.res.TypedArray.getDrawable(TypedArray.java:886)
                                                                 at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:296)
                                                                 at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:239)
                                                                 at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:164)
                                                                 at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:2549)
                                                                 at android.graphics.drawable.Drawable.createFromXml(Drawable.java:2320)
                                                                 at android.content.res.Resources.loadDrawableForCookie(Resources.java:4206)
                                                                 at android.content.res.Resources.loadDrawable(Resources.java:4085) 
                                                                 at android.content.res.Resources.getDrawable(Resources.java:2005) 
                                                                 at android.content.res.Resources.getDrawable(Resources.java:1987) 
                                                                 at android.content.Context.getDrawable(Context.java:464) 
                                                                 at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:30) 
                                                                 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372) 
                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202) 
                                                                 at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81) 
                                                                 at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131) 
                                                                 at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155) 
                                                                 at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31) 
                                                                 at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55) 
                                                                 at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java:33) 
                                                                 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:203) 
                                                                 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185) 
                                                                 at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519) 
                                                                 at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71) 
                                                                 at com.reactnativenavigation.controllers.SplashActivity.onCreate(SplashActivity.java:32) 
                                                                 at android.app.Activity.performCreate(Activity.java:6876) 
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:158) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                              Caused by: java.io.FileNotFoundException: rgba(0,0,0,0)
                                                                 at android.content.res.AssetManager.openNonAssetNative(Native Method)
                                                                 at android.content.res.AssetManager.openNonAsset(AssetManager.java:455)
                                                                 at android.content.res.Resources.loadDrawableForCookie(Resources.java:4209)

**Comment by pqkluan** [comment]
I'll close this issue, assuming the problem was solved. Feel free to re-open if needed.

**Comment by joecaraccio** [comment]
@pqkluan 
That splash screen "works", but the issue is it still be out of place with native apps.
On Android specifically, to avoid the white flash that you see before the React Native Splashscreen activity starts we set the background color of the app to the same color of our splash screen.

The big issue with that, and its not really something you'd expect, is if you are using something such as a keyboard view, when the keyboard pops up youll see a flash of color (in our case blue, our background color) as you'' briefly see the android background 

Do you think this is just unavoidable and just might be one of the few drawbacks of using react native? trying to think of a solution

**Comment by pqkluan** [comment]
@joecaraccio You are right. I don't notice the brief white flash before the splash screen shown up.

I tried to set the native background color as you said and it works perfectly. You just need to add the background color for each screen to avoid the drawback. 

```jsx
navigatorStyle: { screenBackgroundColor: "white" },
```

If you are using some kind of global style using HOC for all screens then it will be a quick fix. Good luck.

**Comment by joecaraccio** [comment]
@pqkluan Have you tried it with the keyboard?
I'm not getting the same results, when the keyboard disappears you can see white but some sort of border as well

How exactly did you set this up?

**Comment by joecaraccio** [comment]
I see like white background with a white box

**Comment by pqkluan** [comment]
I tried to add `TextInput` to test but can't find the issue. Here is the [gif](https://gfycat.com/gifs/detail/UnawareRemorsefulKusimanse)

**Comment by joecaraccio** [comment]
@pqkluan ahh, yeah but for text input you'll draw ocer the screen with the keyboard

My issue is with the keyboardavoidview for something like a chat box, you'll see a flash of the black background

**Comment by eagle-design** [comment]
where do you defined @color/primaryColor ?

**Comment by sturmenta** [comment]
@eagle-design  This may be useful to you

`const startApp = () => Navigation.startSingleScreenApp({
  screen: {
    screen: 'myschool.login',
    navigatorStyle: {
      navBarHidden: true,
      screenBackgroundColor: 'black',
    },
    animationType: 'fade'
  }
});`

https://wix.github.io/react-native-navigation/#/screen-api?id=pushparams

**Comment by sturmenta** [comment]
[White screen before and after splash screen](https://gfycat.com/AggravatingShockedKomododragon)

**Comment by tkulpa** [comment]
Hey @pqkluan you have typo in your article, in MainActivity.java at line 13, there should be 
> launch_screen 
instead
> launch_screen_bitmap
:smile_cat:

**Comment by pqkluan** [comment]
Hi @tkulpa, do you mean this line?
```java
 Drawable launch_screen_bitmap = ContextCompat.getDrawable(getApplicationContext(),R.drawable.launch_screen_bitmap);
```
`R.drawable.launch_screen_bitmap` is for the xml layout file I created in step 2, `launch_screen` is the asset file name that use as a background in `launch_screen_bitmap.xml`.

That was my thought, if I still wrong, please help me point it out.

**Comment by tkulpa** [comment]
@pqkluan yes this line, my app was crashing, errors were about not being able to find resource launch_screen_bitmap, i changed that to launch_screen and everything worked

**Comment by ikhsanalatsary** [comment]
yup, same issue as @tkulpa

**Comment by pqkluan** [comment]
@ikhsanalatsary Do you have this file in your project? 

[launch_screen_bitmap.xml](https://github.com/pqkluan/RNN-SplashScreen-Example/blob/master/Example/android/app/src/main/res/drawable/launch_screen_bitmap.xml)

**Comment by ikhsanalatsary** [comment]
@pqkluan yes i have
<img width="1280" alt="screen shot 2018-05-27 at 11 22 08" src="https://user-images.githubusercontent.com/5897415/40582422-72f3fc56-61a0-11e8-9770-53c0bfd2b714.png">

**Comment by pqkluan** [comment]
@ikhsanalatsary That is weird since my [example project](https://github.com/pqkluan/RNN-SplashScreen-Example/tree/master/Example) was set up using `launch_screen_bitmap.xml` layout.

If you using the `lauch_screen`, it's just the splash screen raw assets. If there are not assets that match the device dimension ratio, there will be white spaces at the border of the screen (default activity background color).

**Comment by crankeye** [comment]
I had the same issue with it crashing complaining about launch_screen_bitmap. I looked deeper into the stack trace and found out the issue was actually the default `rgba(0,0,0,0)` in app/src/main/res/values/colors.xml.

You have to make sure you use a hex color code instead of the default rgba:

app/src/main/res/values/colors.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item name="splashBackground" type="color">#323A4D</item>
</resources>
```

**Comment by pqkluan** [comment]
@crankeye Thanks a lot for pointing out this. I have updated the article after your insight.

**Comment by GodVampire** [comment]
splash question troubled me a few days. find here very luck.  [this](https://github.com/wix/react-native-navigation/issues/2760#issuecomment-367298422) help me. At  least is working for me.

 but like @joecaraccio  say. use keyboard have white background with a white box.  I set `navigatorStyle: { screenBackgroundColor: "white" },` the best I could. but it not  work for me.
that all. I need reslove other question as soon as possible.

**Comment by GodVampire** [comment]
splash question troubled me a few days. find here very luck. [RNN Splash Screen Example](https://github.com/pqkluan/RNN-SplashScreen-Example) help me.

but like @joecaraccio say. use keyboard have white background with a white box(I change colors.xml splashBackground to #fff). 
I set navigatorStyle: `{ screenBackgroundColor: "white" },` the best I could. but it not work for me. maybe not because of it cause. just I think

I need solve other question as soon as possible. :) 
Thanks to the open source.

**Comment by sturmenta** [comment]
Answering [my old comment ](https://github.com/wix/react-native-navigation/issues/2760#issuecomment-381780674)

When making another application I realized my old mistake. I miss putting:

```xml
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        ...
        <item name="android:windowBackground">@color/black</item>
    </style>
```

Following the steps shown in [video](https://www.youtube.com/watch?v=yFrx8HZlNtI) and with the help of @aMarCruz I was able to achieve a perfect dark splash screen in react-native-navigation

![](https://i.imgur.com/SQ6sa5V.gif)
