### ISSUE TITLE
Crash after RN31 update then starting app from background

### ISSUE THREAD

**Issue by MattDavies** [wix/react-native-navigation#280]
Hey guys,

I've just pulled in the 31 changes (during the usual cache clearing) on Android.

The app launches fine, works perfectly. If I hit home and send the app to the background, wait a while, then start the app again, I get this crash:

```
Process: ****, PID: 16966
java.lang.AssertionError: createReactContextInBackground should only be called when creating the react application for the first time. When reloading JS, e.g. from a new file, explicitlyuse recreateReactContextInBackground
	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:65)
	at com.facebook.react.XReactInstanceManagerImpl.createReactContextInBackground(XReactInstanceManagerImpl.java:348)
	at com.reactnativenavigation.react.NavigationReactGateway.startReactContextOnceInBackgroundAndExecuteJS(NavigationReactGateway.java:33)
	at com.reactnativenavigation.NavigationApplication.startReactContext(NavigationApplication.java:35)
	at com.reactnativenavigation.controllers.SplashActivity.onCreate(SplashActivity.java:18)
	at au.****.MainActivity.onCreate(MainActivity.java:18)
	at android.app.Activity.performCreate(Activity.java:6876)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
	at android.app.ActivityThread.access$1100(ActivityThread.java:222)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

I'll take a stab at figuring out why tonight, just wanted to log this incase you're already aware and have any tips.

**Comment by DanielZlotin** [comment]
@MattDavies I can't reproduce it... RN version is 31?

**Comment by agumack** [comment]
@DanielZlotin I have same problem. But can't always. after exit app and run app will work fine.

React: 0.31.0
react-native-navigation: 2.0.0-experimental.101 (100 error same)

Log:

```
createReactContextInBackground should only be called when creating the react 
            application for the first time. When reloading JS, e.g. from a new file, explicitly use recreateReactContextInBackground
```

Steps:
Firstscreen when start app i use: Navigation.startSingleScreenApp. After some setting application API called, I call Navigation.startTabBasedApp to Main screen apps. I think error here.

**Comment by MattDavies** [comment]
It turned out that for some reason, after in the background for a while and relaunching it would call onCreate for MainActivity (ie SplashActivity) again, which would try to recreate the context. I resolved by putting a finish() in SplashActivity if it isnt the root activity. Have you got a layout overridden for your MainActivity when you try to repro?

If you still have no luck I'll try to repro with the example, maybe it's something to do with my manifest.

**Comment by MattDavies** [comment]
And yep RN31.

**Comment by DanielMaly** [comment]
You can reproduce it every time when trying to relaunch the app after the user clicks on a notification. Using [this library](https://github.com/DanielMaly/react-native-system-notification), all you need to do is schedule a notification with a ten second delay, hit the home button, then wait. Once you click on the popped up notification, the app will crash instantly.

**Comment by edvinasbartkus** [comment]
:+1: 
This issue limits implementation of push notifications and deep linking on Android.

**Comment by DanielZlotin** [comment]
wow OK I'm not it

**Comment by DanielZlotin** [comment]
OK thanks to @DanielMaly I finally managed to reproduce it. This is 100% reproducible by adding this code to your Application's onCreate:
```
        NavigationApplication.instance.runOnMainThread(new Runnable() {
            @Override
            public void run() {
                String packageName = getApplicationContext().getPackageName();
                Intent launchIntent = getPackageManager().getLaunchIntentForPackage(packageName);

                launchIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

                startActivity(launchIntent);
            }
        }, 5000);
```
This will blow up after 5 seconds.

(This is what actually happens when you click on a notification in [this library](https://github.com/DanielMaly/react-native-system-notification). This is NOT what should happen if you click on a normal system notification - or the app icon for that matter.)

This is actually not a 100% correct way to start the application from the background, as it doesn't do what the Android system usually does (here we just start the launcher activity without letting the system do it itself, which actually checks and brings the app to foreground if needed without relaunching). I can PR a fix to the above lib, but I will handle these cases anyway in Navigation.

**Comment by DanielMaly** [comment]
As I am not the author of the above library (I just fixed some dependencies for RN 0.31), I'd be very grateful if you could do a PR to fix it. You should probably do it into the original repo and I'll put it into my fork if necessary. I'm not sure the author is very active.

**Comment by DanielZlotin** [comment]
fixed in v2.0.0-experimental.110

**Comment by MattDavies** [comment]
Thanks @DanielZlotin

**Comment by mbizplus** [comment]
@DanielZlotin I upgrade 110 but not working.

Old Log:
```
createReactContextInBackground should only be called when creating the react 
            application for the first time. When reloading JS, e.g. from a new file, explicitly use recreateReactContextInBackground
```

**Comment by agumack** [comment]
@DanielZlotin  I upgrade 110 but not working.

Old Log:

```
createReactContextInBackground should only be called when creating the react 
            application for the first time. When reloading JS, e.g. from a new file, explicitly use recreateReactContextInBackground
```

**Comment by DanielZlotin** [comment]
are you using the mentioned notifications library? something else? I cannot reproduce it after the fix

**Comment by DanielZlotin** [comment]
@MattDavies @DanielMaly please confirm

**Comment by DanielMaly** [comment]
@DanielZlotin I only ever saw the problem with the notifications library and that is working fine after the fix (without your PR).

**Comment by mbizplus** [comment]
@DanielZlotin i don't use library nothing. this problem when i call again Navigation.startTabBasedApp or Navigation.startSingleScreenApp (my app have some screen need startapp again)

**Comment by agumack** [comment]
@DanielZlotin 

i don't use library nothing. this problem when i call again Navigation.startTabBasedApp or Navigation.startSingleScreenApp (my app have some screen need startapp again)

**Comment by MattDavies** [comment]
@DanielZlotin your change fixed it for me.

**Comment by guyca** [comment]
Hey @agumack 
Can you please provide more info about the crash?
Do you specifically call `startApp` in Js after the app is returns from background?

**Comment by SudoPlz** [comment]
I've got the same problem!

**Comment by guyca** [comment]
@SudoPlz Can you provide stack trace?

**Comment by SudoPlz** [comment]
Sure, here's my stacktrace:

            E/AndroidRuntime: FATAL EXCEPTION: main
                              Process: com.testApp.app.android, PID: 31403
                              java.lang.AssertionError: createReactContextInBackground should only be called when creating the react application for the first time. When reloading JS, e.g. from a new file, explicitlyuse recreateReactContextInBackground
                                  at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:65)
                                  at com.facebook.react.XReactInstanceManagerImpl.createReactContextInBackground(XReactInstanceManagerImpl.java:363)
                                  at com.reactnativenavigation.react.NavigationReactGateway.startReactContextOnceInBackgroundAndExecuteJS(NavigationReactGateway.java:34)
                                  at com.reactnativenavigation.NavigationApplication.startReactContextOnceInBackgroundAndExecuteJS(NavigationApplication.java:38)
                                  at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:41)
                                  at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
                                  at android.app.Activity.performResume(Activity.java:6076)
                                  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
                                  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                  at android.os.Looper.loop(Looper.java:135)
                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                  at java.lang.reflect.Method.invoke(Native Method)
                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by guyca** [comment]
This is resolved by the new single activity design in v2 branch. Since this is only happening in debug mode, I don't think we'll address this. Sorry for any inconvenience

**Comment by SudoPlz** [comment]
Thanks for letting me know @guyca ..!

Can't wait enough for v2. Is it ready? Can we switch to it?
