### ISSUE TITLE
java.lang.ClassCastException when trying to push a new screen

### ISSUE THREAD

**Issue by giladno** [wix/react-native-navigation#2842]
```
03-10 06:31:59.239 26571 26597 W Bundle  : Key timestamp expected Double but value was a java.lang.Integer.  The default value 0.0 was returned.
03-10 06:31:59.239 26571 26597 W Bundle  : Attempt to cast generated internal exception:
03-10 06:31:59.239 26571 26597 W Bundle  : java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
03-10 06:31:59.239 26571 26597 W Bundle  : 	at android.os.BaseBundle.getDouble(BaseBundle.java:903)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at android.os.BaseBundle.getDouble(BaseBundle.java:885)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:32)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at com.reactnativenavigation.controllers.NavigationCommandsHandler.push(NavigationCommandsHandler.java:40)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at com.reactnativenavigation.bridge.NavigationReactModule.push(NavigationReactModule.java:182)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at java.lang.reflect.Method.invoke(Native Method)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at android.os.Handler.handleCallback(Handler.java:739)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at android.os.Looper.loop(Looper.java:148)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
03-10 06:31:59.239 26571 26597 W Bundle  : 	at java.lang.Thread.run(Thread.java:818)
```

This exception shows in the console when trying to push a new screen (android device only, works well on emulator).

It tries to cast from Integer to Double, but it fails:
https://github.com/wix/react-native-navigation/blob/e0a6ff2dad25c26eaa8ae1eacd3d2f185c5aebd5/android/app/src/main/java/com/reactnativenavigation/params/parsers/ScreenParamsParser.java#L32

Any suggestions?

**Comment by guyca** [comment]
@giladno hmm not sure why this would happen, but you can PR a `getNumber` method which will gracefully try to get double and fallback to integer

**Comment by rahulpandey** [comment]
Actually ReadableMap of react native internally uses the HashMap where Key is String and value is Object 
to if you pass 1 it will take Integer and if you pass 1.0 it will take double 
so in that 
 int     a = 1;
 Integer b = 1;   // unboxing requires Java 1.5+
 double  c = (double) a;   // OK
 Double  d = (Double) b;   // No way.
you can try 
Object obj=param.get(KEY_TIMESTAMP)
 if(obj instanceof Integer){ }
 if(object instanceof Double){  }

**Comment by leolusoli** [comment]
+1, same issue

**Comment by congnguyen91** [comment]
+1 (on android A5 2017)

**Comment by humodev** [comment]
I'm having this issue on Android

**Comment by mojouy** [comment]
Same Here !! is that solution working @SudoPlz ?

**Comment by SudoPlz** [comment]
I haven't thoroughly tested @mojouy but yeah it should work. I can confirm soon though.

**Comment by ChristianAyala** [comment]
This is happening for me as well. Our app will successfully load but then will crash after a few seconds with the same error. Reproduceable on the emulator configuration attached, on version 1.1.458 (https://registry.yarnpkg.com/react-native-navigation/-/react-native-navigation-1.1.458.tgz#fe0ad5f7948768a82ebe69ed4bfc319c94ff9893)

<img width="747" alt="screen shot 2018-06-15 at 2 28 11 pm" src="https://user-images.githubusercontent.com/774314/41486032-735d587e-70a8-11e8-83bd-36698b09d6be.png">

**Comment by mojouy** [comment]
I had a typo on my view breaking and causing this error. double check guys just in case.

**Comment by usfngm** [comment]
I'm having this issue on Android too. I was working with the remote debugger and had changed some of the code and wanted to reload the application. As soon as I double pressed R to reload, the app crashed with the same exception.

I'm using the following versions of react-native and RNN:
"react-native": "0.56.0",
"react-native-navigation": "^1.1.478",

**Comment by zabojad** [comment]
Having the same problem with those versions:
```
"react-native": "^0.56.0",
"react-native-navigation": "^1.1.479",
```

I do not understand what exactly is the proposed fix here. Could someone please elaborate?

**Comment by spiro-stathakis** [comment]
Having the same problem too. 
react-native-navigation@1.1.479
react-native 0.56 
Would also like some insight into what might be causing it. 
This is the code that triggers the error. 
```
this.props.navigator.push({
            screen: "myApp.IdeaScreen",
            title: selGroup.name,
            passProps: {
                selectedKey: selGroup.key
            },
            animationType:'fade'
        });

**Comment by zabojad** [comment]
Yep, it's happening at every screen push...
