### ISSUE TITLE
[  android 4.4.4 ] [ 2.0.0-experimental.97  ] crash -- can not start app

### ISSUE THREAD

**Issue by Hanruis** [wix/react-native-navigation#289]
here some log 

```

09-07 18:53:03.889 996-17624/? D/cta_dex: HookWifiService onTransact code: 15pid = 8254
09-07 18:53:03.909 996-1287/? D/cta_dex: conn HookConnectivityService onTransact code: 4
09-07 18:53:03.909 996-1287/? D/cta_dex: conn pass onTransact code: 4
09-07 18:53:03.909 996-24542/? D/cta_dex: conn HookConnectivityService onTransact code: 4
09-07 18:53:03.909 996-24542/? D/cta_dex: conn pass onTransact code: 4
                                          
                                          --------- beginning of /dev/log/system
09-07 18:53:03.949 996-996/? V/NotificationService: notifications are disabled by AppOps for com.lionmobi.powerclean
09-07 18:53:03.949 996-996/? E/NotificationService: Suppressing notification from package com.lionmobi.powerclean by user request.
09-07 18:53:04.029 21553-21553/? I/ActivityManager: Timeline: Activity_launch_request id:com.merchantssystem time:412841609
09-07 18:53:04.029 996-1007/? D/cta_dex: START_ACTIVITY_TRANSACTION
09-07 18:53:04.039 996-1007/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.merchantssystem/.MainActivity} from pid 21553
09-07 18:53:04.069 15382-15382/? D/dalvikvm: Late-enabling CheckJNI
09-07 18:53:04.069 996-25674/? I/ActivityManager: Start proc com.merchantssystem for activity com.merchantssystem/.MainActivity: pid=15382 uid=10474 gids={50474, 3003, 1028, 1015}
09-07 18:53:04.119 996-1287/? D/cta_dex: conn HookConnectivityService onTransact code: 39
09-07 18:53:04.119 996-1287/? D/cta_dex: conn pass onTransact code: 39
09-07 18:53:04.149 15382-15382/com.merchantssystem I/dalvikvm: Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
09-07 18:53:04.149 15382-15382/com.merchantssystem W/dalvikvm: VFY: unable to resolve interface method 20199: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
09-07 18:53:04.149 15382-15382/com.merchantssystem D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
09-07 18:53:04.149 15382-15382/com.merchantssystem W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
09-07 18:53:04.149 15382-15382/com.merchantssystem I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
09-07 18:53:04.149 15382-15382/com.merchantssystem W/dalvikvm: VFY: unable to resolve interface method 20201: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
09-07 18:53:04.149 15382-15382/com.merchantssystem D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
09-07 18:53:04.149 15382-15382/com.merchantssystem I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
09-07 18:53:04.149 15382-15382/com.merchantssystem W/dalvikvm: VFY: unable to resolve interface method 20205: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
09-07 18:53:04.149 15382-15382/com.merchantssystem D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
09-07 18:53:04.149 15382-15382/com.merchantssystem I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
09-07 18:53:04.149 15382-15382/com.merchantssystem W/dalvikvm: VFY: unable to resolve virtual method 556: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
09-07 18:53:04.149 15382-15382/com.merchantssystem D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
09-07 18:53:04.149 15382-15382/com.merchantssystem I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
09-07 18:53:04.149 15382-15382/com.merchantssystem W/dalvikvm: VFY: unable to resolve virtual method 578: Landroid/content/res/TypedArray;.getType (I)I
09-07 18:53:04.149 15382-15382/com.merchantssystem D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
09-07 18:53:04.159 15382-15382/com.merchantssystem E/VdcInflateDelegate: Exception while inflating <vector>
                                                                         org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
                                                                             at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
                                                                             at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
                                                                             at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
                                                                             at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:708)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:348)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
                                                                             at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                                             at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
                                                                             at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
                                                                             at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
                                                                             at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
                                                                             at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
                                                                             at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
                                                                             at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                             at com.reactnativenavigation.controllers.SplashActivity.onCreate(SplashActivity.java:16)
                                                                             at android.app.Activity.performCreate(Activity.java:5231)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:212)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
                                                                             at dalvik.system.NativeStart.main(Native Method)
09-07 18:53:04.159 15382-15382/com.merchantssystem D/AndroidRuntime: Shutting down VM
09-07 18:53:04.159 15382-15382/com.merchantssystem W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41f53d88)
09-07 18:53:04.169 15382-15382/com.merchantssystem E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.merchantssystem, PID: 15382
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.merchantssystem/com.merchantssystem.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2237)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:212)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
                                                                         at android.content.res.Resources.loadDrawable(Resources.java:2115)
                                                                         at android.content.res.Resources.getDrawable(Resources.java:708)
                                                                         at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
                                                                         at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                                         at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
                                                                         at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
                                                                         at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
                                                                         at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
                                                                         at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
                                                                         at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                         at com.reactnativenavigation.controllers.SplashActivity.onCreate(SplashActivity.java:16)
                                                                         at android.app.Activity.performCreate(Activity.java:5231)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:212) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5135) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                                         at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:958)
                                                                         at android.graphics.drawable.Drawable.createFromXml(Drawable.java:893)
                                                                         at android.content.res.Resources.loadDrawable(Resources.java:2111)
                                                                         at android.content.res.Resources.getDrawable(Resources.java:708) 
                                                                         at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354) 
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193) 
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181) 
                                                                         at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689) 
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186) 
                                                                         at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77) 
                                                                         at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41) 
                                                                         at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193) 
                                                                         at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173) 
                                                                         at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511) 
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71) 
                                                                         at com.reactnativenavigation.controllers.SplashActivity.onCreate(SplashActivity.java:16) 
                                                                         at android.app.Activity.performCreate(Activity.java:5231) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:212) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5135) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
09-07 18:53:04.169 996-4640/? D/ActivityManager: New dropbox entry: com.merchantssystem, data_app_crash, c0fa1e55-2b47-4d52-950b-beaf9d0c0350
09-07 18:53:04.169 996-4640/? W/ActivityManager:   Force finishing activity com.merchantssystem/.MainActivity
09-07 18:53:04.219 14554-15411/? I/CrashMonitor: CrashMonitorServiceBroadcastReceiver: Forwarding intent: android.intent.action.DROPBOX_ENTRY_ADDED tag: data_app_crash
09-07 18:53:04.219 14554-14554/? I/CrashMonitor: CrashMonitorService: Service started...
09-07 18:53:04.229 14554-15412/? I/CrashMonitor: CrashMonitorService: action: android.intent.action.DROPBOX_ENTRY_ADDED
09-07 18:53:04.279 9053-9053/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1527 android.content.ContextWrapper.startService:494 android.content.ContextWrapper.startService:494 com.sonymobile.phoneusage.service.plugin.crashstatus.CrashStatusReceiver.onReceiveInternal:31 com.sonymobile.phoneusage.service.DeviceUsageReceiver.onReceive:27 
09-07 18:53:04.289 14554-14554/? I/CrashMonitor: CrashMonitorService: Service stopped...
09-07 18:53:04.689 996-1027/? W/ActivityManager: Activity pause timeout for ActivityRecord{4397db68 u0 com.merchantssystem/.MainActivity t1946 f}
09-07 18:53:04.739 21553-21553/? I/ActivityManager: Timeline: Activity_idle id: android.os.BinderProxy@43749548 time:412842311
09-07 18:53:04.739 996-1513/? I/ActivityManager: Killing 11435:com.douban.book.reader:pushservice/u0a219 (adj 15): empty #17
09-07 18:53:04.909 996-1026/? I/ActivityManager: Timeline: Activity_windows_visible id: ActivityRecord{437609f0 u0 com.sonyericsson.home/com.sonymobile.home.HomeActivity t1} time:412842489
09-07 18:53:05.489 1241-1241/? D/StatusBar.NetworkController: refreshViews: Data not connected!! Set no data type icon / Roaming
09-07 18:53:05.489 433-433/? E/Parcel: Reading a NULL string not supported here.
09-07 18:53:05.489 433-433/? E/Parcel: Reading a NULL string not supported here.
09-07 18:53:05.889 996-25674/? D/cta_dex: HookWifiService onTransact code: 15pid = 8254
09-07 18:53:05.889 996-1471/? D/cta_dex: conn HookConnectivityService onTransact code: 4
09-07 18:53:05.889 996-1471/? D/cta_dex: conn pass onTransact code: 4
09-07 18:53:05.899 996-25673/? D/cta_dex: conn HookConnectivityService onTransact code: 4
09-07 18:53:05.899 996-25673/? D/cta_dex: conn pass onTransact code: 4
09-07 18:53:06.009 8254-13342/? D/dalvikvm: GC_FOR_ALLOC freed 2669K, 9% free 33618K/36928K, paused 100ms, total 102ms
09-07 18:53:06.019 996-996/? V/NotificationService: notifications are disabled by AppOps for com.lionmobi.powerclean
09-07 18:53:06.019 996-996/? E/NotificationService: Suppressing notification from package com.lionmobi.powerclean by user request.
09-07 18:53:07.889 996-1494/? D/cta_dex: HookWifiService onTransact code: 15pid = 8254
09-07 18:53:07.899 996-1530/? D/cta_dex: conn HookConnectivityService onTransact code: 4
09-07 18:53:07.899 996-1530/? D/cta_dex: conn pass onTransact code: 4
09-07 18:53:07.909 996-1007/? D/cta_dex: conn HookConnectivityService onTransact code: 4
09-07 18:53:07.909 996-1007/? D/cta_dex: conn pass onTransact code: 4
09-07 18:53:07.949 996-996/? V/NotificationService: notifications are disabled by AppOps for com.lionmobi.powerclean
09-07 18:53:07.949 996-996/? E/NotificationService: Suppressing notification from package com.lionmobi.powerclean by user request.
09-07 18:53:08.899 996-24542/? D/cta_dex: HookWifiService onTransact code: 15pid = 21682
09-07 18:53:08.899 1420-2365/? D/cta_dex: HookTelephonyService onTransact code: 43
09-07 18:53:08.899 1420-2373/? D/cta_dex: HookTelephonyService onTransact code: 35
09-07 18:53:09.889 996-6797/? D/cta_dex: HookWifiService onTransact code: 15pid = 8254
09-07 18:53:09.899 996-1513/? D/cta_dex: conn HookConnectivityService onTransact code: 4
09-07 18:53:09.899 996-1513/? D/cta_dex: conn pass onTransact code: 4
09-07 18:53:09.909 996-1546/? D/cta_dex: conn HookConnectivityService onTransact code: 4
09-07 18:53:09.909 996-1546/? D/cta_dex: conn pass onTransact code: 4
09-07 18:53:09.959 996-996/? V/NotificationService: notifications are disabled by AppOps for com.lionmobi.powerclean
09-07 18:53:09.959 996-996/? E/NotificationService: Suppressing notification from package com.lionmobi.powerclean by user request.

```

**Comment by guyca** [comment]
@Hanruis I googled `Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml` and found [this](http://stackoverflow.com/questions/35739743/file-res-drawable-abc-ic-ab-back-material-xml-from-drawable-resource-id-0x7f020) thread on SO.

/cc @sagic

**Comment by Hanruis** [comment]
@guyca  thx a lot ..

the solution is change the `android/app/build.gradle` 

from `compile "com.android.support:appcompat-v7:23.2.1"` 

to 
```

compile 'com.android.support:appcompat-v7:23.4.0'
compile 'com.android.support:support-v4:23.4.0'

```

this [issue](https://github.com/geektimecoil/react-native-onesignal/issues/37) may help ..

RN0.31

**Comment by Hanruis** [comment]
note: update gradle version to 2.0+

**Comment by rafaelcorreiapoli** [comment]
Hi! I'm still having this problem
Gradle version 2.4
react-native 0.35.0

**Comment by guyca** [comment]
@rafaelcorreiapoli What RNN version?
