### ISSUE TITLE
Android crash after updated 2.0.0-experimental.101 version

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#291]
What version of `react-native` you are using
**0.31.0**
What version of `react-native-navigation` you are using
**2.0.0-experimental.101 (100 error same)**

Logs:
```
E/AndroidRuntime(26134): FATAL EXCEPTION: main
E/AndroidRuntime(26134): Process: com.mackfirstapp, PID: 26134
E/AndroidRuntime(26134): java.lang.RuntimeException: Unable to destroy activity {com.mackfirstapp/com.reactnativenavigation.controllers.NavigationActivity}: java.util.ConcurrentModificationException

```

**Comment by edvinasbartkus** [comment]
I see that it should have been fixed with [653b071](https://github.com/wix/react-native-navigation/commit/653b0716ff7c05c6509b55229274a001ac80347e) but I still get an error.

What version of react-native you are using
**0.32.1**
What version of react-native-navigation you are using
**2.0.0-experimental.103**

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.plateculture.dev/com.reactnativenavigation.controllers.NavigationActivity}: java.util.ConcurrentModificationException
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
```

**Comment by guyca** [comment]
@edvinasbartkus I pushed 104 a few minutes ago, it should fix it once and for all.

**Comment by edvinasbartkus** [comment]
@guyca can confirm, works now! thank you! 👍

**Comment by guyca** [comment]
np 👍
