### ISSUE TITLE
NavigationReactEventEmitter.sendEvent Error cause crash

### ISSUE THREAD

**Issue by sapjax** [wix/react-native-navigation#2964]
### Issue Description

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.bridge.NavigationReactEventEmitter.sendEvent(java.lang.String, com.facebook.react.bridge.WritableMap)' on a null object reference
       at com.reactnativenavigation.bridge.EventEmitter.sendAppLaunchedEvent(EventEmitter.java:95)
       at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:48)
       at org.consenlabs.imtoken.MainActivity.onResume(MainActivity.java:45)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1266)
       at android.app.Activity.performResume(Activity.java:6446)
       at android.app.ActivityThread.performNewIntents(ActivityThread.java:2594)
       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2601)
       at android.app.ActivityThread.access$1700(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```

### Steps to Reproduce / Code Snippets / Screenshots

launch app

---
### Environment
* React Native Navigation version: 1.1.365
* React Native version: 0.51.0
* Platform(s) : Android
* Device info :  Android 6.0.1 HUAWEI  Release

**Comment by sapjax** [comment]
We also encounter another error, I'm not sure it's same as above or isn't.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactContext.getJSModule(java.lang.Class)' on a null object reference
       at com.reactnativenavigation.bridge.NavigationReactEventEmitter.<init>(NavigationReactEventEmitter.java:17)
       at com.reactnativenavigation.react.NavigationReactGateway.onReactContextInitialized(NavigationReactGateway.java:114)
       at com.reactnativenavigation.react.NavigationReactGateway.access$000(NavigationReactGateway.java:24)
       at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.onReactContextInitialized(NavigationReactGateway.java:174)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1000)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6665)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

Environment
React Native Navigation version: 1.1.365
React Native version: 0.51.0
Platform(s) : Android
Device info: Android 7.1.1 / Android 8.0.0   XIAOMI  Release

**Comment by SudoPlz** [comment]
I'm having the same issue

**Comment by sapjax** [comment]
@SudoPlz https://github.com/wix/react-native-navigation/commit/085b3c9c901107c0da1b47dea6f042f43958b206   i'm not sure did this commit have solve this issue,  maybe you could try it.

**Comment by SudoPlz** [comment]
Good catch, I can try, but since I'm not able to reproduce at will, I'll have to wait and see if I receive any such crashes from our production apps.

**Comment by sapjax** [comment]
https://github.com/wix/react-native-navigation/commit/085b3c9c901107c0da1b47dea6f042f43958b206  seems haven't fixed this issue,  we also have one hundred uses encounter this problem.
But now, I decided to upgrade our RNN version to 2.0,  hope it will work excellently.

**Comment by rengil** [comment]
@sapjax 
Does upgrading the RNN version to 2.0 made this kind of issues go away?
Thanks!

**Comment by L-Yeiser** [comment]
This is still on issue on `^2.16.0"`. Can this be re-opened?
