### ISSUE TITLE
V2: Android bottomTabs layout setting crashes on load

### ISSUE THREAD

**Issue by larryranches** [wix/react-native-navigation#3041]
### Issue Description

Using the bottom tabs layout in the Navigation.setRoot({}) function crashes Android on load.
```
  Navigation.setRoot({
      bottomTabs: {
        children: [
          {
            component: {
              name: 'App',
            },
          },
          {
            component: {
              name: 'Test',
            },
          },
        ],
      },
    });
```

If I use a single stack layout or sideMenu layout like the example below it works fine and all is working in IOS.
```
   Navigation.setRoot({
      component: {
        name: 'App',
      },

     OR
 
      sideMenu: {
        left: {
          component: {
            name: 'Test',
            passProps: {
              text: 'This is a left side menu screen',
            },
          },
        },
        center: {
          component: {
            name: 'App',
          },
        },
        right: {
          component: {
            name: 'Test',
            passProps: {
              text: 'This is a right side menu screen',
            },
          },
        },
      },
    });
```

---
### Environment
* React Native Navigation version: 2.0.2237
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by guyca** [comment]
Please include stack trace

**Comment by larryranches** [comment]
@guyca Full logs below. I upgraded to the latest rnn  ```"react-native-navigation": "^2.0.2265"```. it works on all other navigation layouts but crashes on bottomTabs layout

```
04-26 01:55:38.694   428  1088 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.testApp/.MainActivity bnds=[36,1668][310,2100]} from uid 10013
04-26 01:55:38.703  1438  1438 I zygote  : Late-enabling -Xcheck:jni
04-26 01:55:38.712   428  1068 I ActivityManager: Start proc 1438:com.testApp/u0a69 for activity com.testApp/.MainActivity
04-26 01:55:38.712  1438  1438 W zygote  : Unexpected CPU variant for X86 using defaults: x86
04-26 01:55:38.714   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:38.714   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:38.721   428   485 W System  : ClassLoader referenced unknown path:
04-26 01:55:38.737   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:38.771   428   485 D         : HostConnection::get() New Host Connection established 0xcbfcfd80, tid 485
04-26 01:55:38.771   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:38.776  1438  1454 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLES_emulation.so from the current namespace instead.
04-26 01:55:38.785   428   485 W         : Unrecognized GLES max version string in extensions:
04-26 01:55:38.789  1438  1454 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libEGL_emulation.so from the current namespace instead.
04-26 01:55:38.799  1438  1454 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLESv1_CM_emulation.so from the current namespace instead.
04-26 01:55:38.806   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:38.823  1438  1454 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLESv2_emulation.so from the current namespace instead.
04-26 01:55:38.839  1438  1438 V fb-UnpackingSoSource: locked dso store /data/user/0/com.testApp/lib-main
04-26 01:55:38.840  1438  1438 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.testApp/lib-main
04-26 01:55:38.840  1438  1438 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.testpApp/lib-main
04-26 01:55:38.847  1438  1438 D ReactNative: ReactInstanceManager.ctor()
04-26 01:55:38.857  1438  1438 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-26 01:55:38.863   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:38.864   309   489 D Sensors : batch handle 1, but there is no batch sensor in genymotion
04-26 01:55:38.871   262   262 I netd    : type=1400 audit(0.0:838): avc: denied { getopt } for path="/dev/socket/fwmarkd" scontext=u:r:netd:s0 tcontext=u:r:init:s0:c512,c768 tclass=unix_stream_socket permissive=1
04-26 01:55:38.883  1438  1461 W unknown:InspectorPackagerConnection: Couldn't connect to packager, will silently retry
04-26 01:55:38.921   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:38.926  1438  1438 D ReactNative: ReactInstanceManager.createReactContextInBackground()
04-26 01:55:38.926  1438  1438 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
04-26 01:55:38.927  1438  1438 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
04-26 01:55:38.928  1438  1438 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
04-26 01:55:38.928  1438  1438 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
04-26 01:55:38.936  1438  1463 D OpenGLRenderer: HWUI GL Pipeline
04-26 01:55:38.964  1438  1438 W unknown:ReactNative: Packager connection already open, nooping.
04-26 01:55:38.973  1438  1462 I zygote  : Thread[18,tid=1462,Native,Thread*=0xe6f11200,peer=0x143a2e48,"Thread-2"] recursive attempt to load library "/data/app/com.testApp-N3ZITx8OgS6z46QpjdYIqA==/lib/x86/libfb.so"
04-26 01:55:38.974  1438  1462 D ReactNative: ReactInstanceManager.createReactContext()
04-26 01:55:38.977  1438  1463 D         : HostConnection::get() New Host Connection established 0xddbd7800, tid 1463
04-26 01:55:38.979   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:38.982  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
04-26 01:55:38.982  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
04-26 01:55:38.984  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
04-26 01:55:38.985  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
04-26 01:55:38.986  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
04-26 01:55:38.987  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
04-26 01:55:38.988  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
04-26 01:55:38.991  1438  1463 W         : Unrecognized GLES max version string in extensions:
04-26 01:55:38.991  1438  1463 W         : Process pipe failed
04-26 01:55:38.992  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
04-26 01:55:38.996  1438  1463 I OpenGLRenderer: Initialized EGL, version 1.4
04-26 01:55:38.996  1438  1463 D OpenGLRenderer: Swap behavior 1
04-26 01:55:38.997  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
04-26 01:55:38.999  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
04-26 01:55:39.001  1438  1463 D EGL_emulation: eglCreateContext: 0xeb365340: maj 2 min 0 rcv 2
04-26 01:55:39.001  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
04-26 01:55:39.002  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
04-26 01:55:39.005  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
04-26 01:55:39.006  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
04-26 01:55:39.007  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
04-26 01:55:39.009  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
04-26 01:55:39.012  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
04-26 01:55:39.014  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
04-26 01:55:39.015  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
04-26 01:55:39.016  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
04-26 01:55:39.016  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
04-26 01:55:39.019  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
04-26 01:55:39.023  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
04-26 01:55:39.025  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
04-26 01:55:39.026  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
04-26 01:55:39.028  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
04-26 01:55:39.028  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
04-26 01:55:39.031   317   982 W         : Unrecognized GLES max version string in extensions:
04-26 01:55:39.033  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
04-26 01:55:39.036  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
04-26 01:55:39.037  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
04-26 01:55:39.037   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.037  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
04-26 01:55:39.038  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
04-26 01:55:39.040  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
04-26 01:55:39.045  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
04-26 01:55:39.048  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
04-26 01:55:39.050  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
04-26 01:55:39.051  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
04-26 01:55:39.054  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
04-26 01:55:39.056  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
04-26 01:55:39.057  1438  1462 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
04-26 01:55:39.059  1438  1438 I com.testApp: type=1400 audit(0.0:843): avc: denied { read } for comm=4173796E635461736B202333 name="cache" dev="sdb3" ino=81920 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
04-26 01:55:39.059  1438  1438 I com.testApp: type=1400 audit(0.0:844): avc: denied { open } for comm=4173796E635461736B202333 path="/data/data/com.testApp/cache" dev="sdb3" ino=81920 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
04-26 01:55:39.065  1438  1462 D ReactNative: Initializing React Xplat Bridge.
04-26 01:55:39.066  1438  1462 D ReactNative: Initializing React Xplat Bridge before initializeBridge
04-26 01:55:39.084   428   443 I ActivityManager: Waited long enough for: ServiceRecord{52fa7c6 u0 com.android.calendar/.alerts.InitAlarmsService}
04-26 01:55:39.095   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.100  1438  1463 E EGL_emulation: tid 1463: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
04-26 01:55:39.100  1438  1463 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xd8c9e2a0, error=EGL_BAD_MATCH
04-26 01:55:39.123  1438  1462 D ReactNative: Initializing React Xplat Bridge after initializeBridge
04-26 01:55:39.123  1438  1462 D ReactNative: CatalystInstanceImpl.runJSBundle()
04-26 01:55:39.131  1438  1469 D ReactNative: ReactInstanceManager.setupReactContext()
04-26 01:55:39.132  1438  1469 D ReactNative: CatalystInstanceImpl.initialize()
04-26 01:55:39.135  1438  1438 W unknown:ReactNative: Packager connection already open, nooping.
04-26 01:55:39.153   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.216   320   345 I chatty  : uid=1041(audioserver) FastMixer identical 1 line
04-26 01:55:39.269   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.324  1438  1469 I WebViewFactory: Loading com.android.webview version 58.0.3029.125 (code 303012510)
04-26 01:55:39.327   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.387   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.422  1438  1469 I cr_LibraryLoader: Time to load native libraries: 12 ms (timestamps 6851-6863)
04-26 01:55:39.439  1438  1469 I chromium: [INFO:library_loader_hooks.cc(140)] Chromium logging enabled: level = 0, default verbosity = 0
04-26 01:55:39.439  1438  1469 I cr_LibraryLoader: Expected native library version number "58.0.3029.125", actual native library version number "58.0.3029.125"
04-26 01:55:39.443   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.491   262   262 I netd    : type=1400 audit(0.0:845): avc: denied { accept } for path="/dev/socket/fwmarkd" scontext=u:r:netd:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
04-26 01:55:39.501   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.539  1438  1438 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-26 01:55:39.557  1438  1468 I ReactNativeJS: Running application "ROOT" with appParams: {"initialProps":{"componentId":"Component1"},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
04-26 01:55:39.559   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.618   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.649  1438  1438 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-26 01:55:39.649  1438  1468 I ReactNativeJS: Running application "App" with appParams: {"initialProps":{"componentId":"Component4"},"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
04-26 01:55:39.651   428   485 I Choreographer: Skipped 54 frames!  The application may be doing too much work on its main thread.
04-26 01:55:39.668   428   452 I ActivityManager: Displayed com.testApp/.MainActivity: +961ms
04-26 01:55:39.672  1438  1438 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-26 01:55:39.674  1438  1438 D AndroidRuntime: Shutting down VM
04-26 01:55:39.676   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
--------- beginning of crash
04-26 01:55:39.678  1438  1438 E AndroidRuntime: FATAL EXCEPTION: main
04-26 01:55:39.678  1438  1438 E AndroidRuntime: Process: com.testApp, PID: 1438
04-26 01:55:39.678  1438  1438 E AndroidRuntime: java.lang.RuntimeException: BottomTab must have an icon
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.createTab(BottomTabsController.java:116)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.setTabs(BottomTabsController.java:109)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at com.reactnativenavigation.parse.LayoutFactory.createBottomTabs(LayoutFactory.java:151)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at com.reactnativenavigation.parse.LayoutFactory.create(LayoutFactory.java:55)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at com.reactnativenavigation.react.NavigationModule.lambda$setRoot$0$NavigationModule(NavigationModule.java:46)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at com.reactnativenavigation.react.NavigationModule$$Lambda$0.run(Unknown Source:6)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
04-26 01:55:39.678  1438  1438 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
04-26 01:55:39.680   428   639 W ActivityManager:   Force finishing activity com.testApp/.MainActivity
04-26 01:55:39.685   428   444 I ActivityManager: Showing crash dialog for package com.testApp u0
04-26 01:55:39.700  1438  1468 I ReactNativeJS: Running application "Test" with appParams: {"initialProps":{"componentId":"Component6"},"rootTag":21}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
04-26 01:55:39.733   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.755   428  1180 I OpenGLRenderer: Initialized EGL, version 1.4
04-26 01:55:39.755   428  1180 D OpenGLRenderer: Swap behavior 1
04-26 01:55:39.757   428  1180 D EGL_emulation: eglCreateContext: 0xe6f32020: maj 2 min 0 rcv 2
04-26 01:55:39.790   428  1180 E EGL_emulation: tid 1180: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
04-26 01:55:39.790   428  1180 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xc744ee60, error=EGL_BAD_MATCH
04-26 01:55:39.792   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.850   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.876   317   983 E SurfaceFlinger: Failed to find layer (Splash Screen com.testApp#0) in layer parent (no-parent).
04-26 01:55:39.908   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:39.921   428   444 W Looper  : Dispatch took 133ms on android.ui, h=Handler (android.view.Choreographer$FrameHandler) {5665cc} cb=android.view.Choreographer$FrameDisplayEventReceiver@f95b015 msg=0
04-26 01:55:40.182   428   443 W ActivityManager: Activity pause timeout for ActivityRecord{9a72655 u0 com.testApp/.MainActivity t48 f}
04-26 01:55:40.198   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:40.255   428   443 D         : HostConnection::get() New Host Connection established 0xca98cfc0, tid 443
04-26 01:55:40.256   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:40.272   428   443 W         : Unrecognized GLES max version string in extensions:
04-26 01:55:40.279   317   317 E EGL_emulation: tid 317: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
04-26 01:55:40.310   428   444 W Looper  : Dispatch took 115ms on android.ui, h=Handler (com.android.server.am.ActivityManagerService$UiHandler) {5551f7c} cb=null msg=30
04-26 01:55:40.314   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:40.372   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:40.413  1100  1187 E EGL_emulation: tid 1187: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
04-26 01:55:40.413  1100  1187 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xcb07d380, error=EGL_BAD_MATCH
04-26 01:55:40.431   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:40.445   556   581 D         : HostConnection::get() New Host Connection established 0xddea30c0, tid 581
04-26 01:55:40.472   556   581 W         : Unrecognized GLES max version string in extensions:
04-26 01:55:40.482   556   572 D         : HostConnection::get() New Host Connection established 0xddea3180, tid 572
04-26 01:55:40.488   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:40.497   556   572 W         : Unrecognized GLES max version string in extensions:
04-26 01:55:40.546   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:40.895   320   345 I chatty  : uid=1041(audioserver) FastMixer identical 6 lines
04-26 01:55:40.953   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:40.961  1100  1187 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
04-26 01:55:41.014   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:41.418   320   345 I chatty  : uid=1041(audioserver) FastMixer identical 7 lines
04-26 01:55:41.475   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:41.515   621   621 I m.android.phone: type=1400 audit(0.0:852): avc: denied { sendto } for path="/dev/socket/logdw" scontext=u:r:radio:s0 tcontext=u:r:init:s0 tclass=unix_dgram_socket permissive=1
04-26 01:55:41.533   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:41.707   320   345 I chatty  : uid=1041(audioserver) FastMixer identical 3 lines
04-26 01:55:41.766   320   345 E AudioStreamOutSink: Error while writing data to HAL: -32
04-26 01:55:48.704   428   515 E HalDeviceManager: getAllChipInfo: called but mWifi is null!?
04-26 01:55:48.704   428   515 E HalDeviceManager: getSupportedIfaceTypesInternal: no chip info found
04-26 01:55:48.704   428   448 E BluetoothAdapter: Bluetooth binder is null
04-26 01:55:48.705   428   448 E BatteryStatsService: no controller energy info supplied
04-26 01:55:48.707   428   448 E BatteryStatsService: Power Hal not loaded
04-26 01:55:48.707   428   448 E KernelUidCpuFreqTimeReader: Failed to read /proc/uid_time_in_state: java.io.FileNotFoundException: /proc/uid_time_in_state (No such file or directory)
04-26 01:55:48.708   428   448 E BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
04-26 01:55:50.055   263   263 I main    : type=1400 audit(0.0:853): avc: denied { read } for path="/dev/socket/zygote" scontext=u:r:zygote:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
04-26 01:55:50.062  1487  1487 W zygote  : Unexpected CPU variant for X86 using defaults: x86
04-26 01:55:50.065   428   451 I ActivityManager: Start proc 1487:android.ext.services/u0a10 for service android.ext.services/.storage.CacheQuotaServiceImpl
04-26 01:55:50.073   428  1068 I ActivityManager: Killing 1119:com.android.quicksearchbox/u0a60 (adj 906): empty #17
04-26 01:55:50.074   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:50.074   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:50.084   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:50.084   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:50.095  1487  1487 I android.ext.services: type=1400 audit(0.0:858): avc: denied { write } for comm=45474C20496E6974 name="property_service" dev="tmpfs" ino=9371 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=1
04-26 01:55:50.096  1487  1502 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLES_emulation.so from the current namespace instead.
04-26 01:55:50.096  1487  1502 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libEGL_emulation.so from the current namespace instead.
04-26 01:55:50.098   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:50.098   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:50.099  1487  1502 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLESv1_CM_emulation.so from the current namespace instead.
04-26 01:55:50.107   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:50.107   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:50.115  1487  1502 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLESv2_emulation.so from the current namespace instead.
04-26 01:55:50.123   428  1084 I ActivityManager: Killing 1153:com.android.keychain/1000 (adj 906): empty #17
04-26 01:55:50.461   428   443 W ActivityManager: Activity destroy timeout for ActivityRecord{9a72655 u0 com.testApp/.MainActivity t48 f}
04-26 01:55:50.711   311   311 I batteryd: type=1400 audit(0.0:859): avc: denied { write } for name="status" dev="tmpfs" ino=9196 scontext=u:r:init:s0 tcontext=u:object_r:device:s0 tclass=fifo_file permissive=1
04-26 01:55:51.711  1506  1506 W zygote  : Unexpected CPU variant for X86 using defaults: x86
04-26 01:55:51.716   428   638 I ActivityManager: Start proc 1506:com.android.keychain/1000 for service com.android.keychain/.KeyChainService
04-26 01:55:51.722   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:51.722   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:51.730  1506  1520 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLES_emulation.so from the current namespace instead.
04-26 01:55:51.733  1506  1520 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libEGL_emulation.so from the current namespace instead.
04-26 01:55:51.743  1506  1520 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLESv1_CM_emulation.so from the current namespace instead.
04-26 01:55:51.749  1506  1520 I vndksupport: sphal namespace is not configured for this process. Loading /system/lib/egl/libGLESv2_emulation.so from the current namespace instead.
04-26 01:55:51.755   428  1088 I ActivityManager: Killing 1257:com.android.contacts/u0a7 (adj 906): empty #17
04-26 01:55:54.131  1235  1272 D InitAlarmsService: Clearing and rescheduling alarms.
04-26 01:55:54.133   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:54.133   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:55.132  1487  1501 I zygote  : Waiting for a blocking GC ProfileSaver
04-26 01:55:59.137   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:59.137   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:59.146   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:59.146   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:59.153   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:59.153   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:59.161   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:59.161   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:59.169   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:59.169   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:59.176   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:59.176   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:59.183   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:59.183   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:59.190   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:59.190   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:59.198   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:59.198   428   442 W android.os.Debug: failed to get memory consumption info: -1
04-26 01:55:59.205   428   442 E memtrack: Couldn't load memtrack module
04-26 01:55:59.205   428   442 W android.os.Debug: failed to get memory consumption info: -1
```

**Comment by guyca** [comment]
@larryranches - yes, tabs must have icons - as described in the RunTimeException that is thrown.
