### ISSUE TITLE
NPE on navigation Drawer (Android)

### ISSUE THREAD

**Issue by sytolk** [wix/react-native-navigation#3058]
This NPE is very rare
```
04-16 21:24:24.682 7318-7360/? E/unknown:ReactNative: Exception in native call
                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
                                                          at com.reactnativenavigation.views.SideMenu$Side.fromString(SideMenu.java:33)
                                                          at com.reactnativenavigation.bridge.NavigationReactModule.toggleSideMenuVisible(NavigationReactModule.java:149)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                                                          at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                          at android.os.Looper.loop(Looper.java:154)
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                          at java.lang.Thread.run(Thread.java:761)
```
maybe this will fix issue:
```java
package com.reactnativenavigation.views;

public class SideMenu extends DrawerLayout {
//line 33 with added default Left side
public static Side fromString(String side) {
if(side != null && "right".equals(side.toLowerCase())) return Right;
return Left;
}
```

**Comment by sytolk** [comment]
duplicate: https://github.com/wix/react-native-navigation/issues/2853
