### ISSUE TITLE
[V2][Android] IndexOutOfBoundsException

### ISSUE THREAD

**Issue by andresesfm** [wix/react-native-navigation#3074]
### Issue Description

When creating a bottom tabs navigation with no default tab selected, the app crashes with exception. Looking a the logs it seems like the default passed is '-1'
### Steps to Reproduce / Code Snippets / Screenshots
index.js:
```js
    Navigation.registerComponent(A.navigationId, () => AScene);
    Navigation.registerComponent(B.navigationId, () => BScene);
```
AScene,BScene
```js
static get options(): NavigationOptions {
        return {
            topBar: {
               ....
            },
            bottomTab: {
                title: "A",
                icon: iconA,
            }
        };
    }
```
This is the actual stacktrace:
```
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
        at java.util.ArrayList.get(ArrayList.java:310)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.getCurrentView(BottomTabsController.java:158)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.selectTabAtIndex(BottomTabsController.java:153)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.onTabSelected(BottomTabsController.java:95)
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.updateSmallItems(AHBottomNavigation.java:763)
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setCurrentItem(AHBottomNavigation.java:1209)
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setCurrentItem(AHBottomNavigation.java:1190)
        at com.reactnativenavigation.views.BottomTabs.setCurrentItem(BottomTabs.java:31)
        at com.reactnativenavigation.presentation.BottomTabsOptionsPresenter.applyBottomTabsOptions(BottomTabsOptionsPresenter.java:41)
        at com.reactnativenavigation.presentation.BottomTabsOptionsPresenter.present(BottomTabsOptionsPresenter.java:23)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:55)
        at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:150)
        at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:189)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1969)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:606)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

### Proposed solution 
~~https://github.com/wix/react-native-navigation/pull/3072~~
https://github.com/wix/react-native-navigation/pull/3082

---
### Environment
* React Native Navigation version: V2
* React Native version: 0.53.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator

**Comment by andresesfm** [comment]
Hello @guyca I simplified the PR. This should be a lot easier to review: https://github.com/wix/react-native-navigation/pull/3082 :)
