### ISSUE TITLE
[V2][Android] Reloading app (using RR) causes a crash

### ISSUE THREAD

**Issue by andresesfm** [wix/react-native-navigation#3087]
### Issue Description

Running app on Debug and trying to refresh using RR key, causes the app to crash
### Steps to Reproduce / Code Snippets / Screenshots
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactContext.getJSModule(java.lang.Class)' on a null object reference
       at com.reactnativenavigation.react.NavigationEvent.<init>(NavigationEvent.java:21)
       at com.reactnativenavigation.react.NavigationReactInitializer.emitAppLaunched(NavigationReactInitializer.java:55)
       at com.reactnativenavigation.react.NavigationReactInitializer.prepareReactApp(NavigationReactInitializer.java:49)
       at com.reactnativenavigation.react.NavigationReactInitializer.onActivityResumed(NavigationReactInitializer.java:28)
       at com.reactnativenavigation.react.ReactGateway.onActivityResumed(ReactGateway.java:39)
       at com.reactnativenavigation.NavigationActivity.onResume(NavigationActivity.java:25)
```

### Proposed Fix
https://github.com/wix/react-native-navigation/pull/3128
---
### Environment
* React Native Navigation version: V2
* React Native version:  0.53.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator / Debug

**Comment by guyca** [comment]
Hey @andresesfm 
Does the crash reproduce consistently in the playground app?

**Comment by andresesfm** [comment]
Hello @guyca It's been hard to reproduce, since it looks like this caused by recreating the context multiple times. In our case it was caused by the integration with CodePush and sometimes refreshing at the right time would cause the context to be null. Although an edge case, this is still something that should be addressed. Here is my proposed fix for your consideration: https://github.com/wix/react-native-navigation/pull/3128
