### ISSUE TITLE
startTabBasedApp have limit 5 tabs only

### ISSUE THREAD

**Issue by sytolk** [wix/react-native-navigation#3095]
### Issue Description
I have array with 6 tabs (they are with hidden style).
```
Navigation.startTabBasedApp({
        tabs,
        tabsStyle: { // optional, **iOS Only** add this if you want to style the tab bar beyond the defaults
            tabBarHidden: true,
        },
        appStyle: {
            tabBarHidden: true,
        }
});

export const tabs = [{
    screen: containerNames.H_SCREEN,
    // todo https://github.com/wix/react-native-navigation/issues/425
    icon: require('../../assets/dummy.png'),
    navigatorButtons: { leftButtons, rightButtons: [{ ...rightButtons, id: 'home' }] }
}, {
    screen: containerNames.T_SCREEN,
    icon: require('../../assets/dummy.png'),
    navigatorButtons: { leftButtons, rightButtons: [{ ...rightButtons, id: 'tr' }] }
}, {
    screen: containerNames.EXPORT_SCREEN,
    icon: require('../../assets/dummy.png'),
    navigatorButtons: { leftButtons, rightButtons: [{ ...rightButtons, id: 'export' }] }
}, {
    screen: containerNames.FEEDBACK_SCREEN,
    icon: require('../../assets/dummy.png'),
    navigatorButtons: { leftButtons }
}, {
    screen: containerNames.IMP_SCREEN,
    icon: require('../../assets/dummy.png'),
    navigatorButtons: { leftButtons, rightButtons: [{ ...rightButtons, id: 'imp' }] }
}, {
    screen: containerNames.DEV_SCREEN,
    icon: require('../../assets/dummy.png'),
    navigatorButtons: { leftButtons, rightButtons: [{ ...rightButtons, id: 'devs' }] }
}];
```

### Steps to Reproduce / Code Snippets 

 The exception occurred if I click on the last tab `this.props.navigator.switchToTab({ 5 })` (other tabs click work). It appears that RNN strip my tabs array to 5 elements.
```
10451-10451/de.drivelog.triplog E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: de.drivelog.triplog, PID: 10451
                                                                     java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
                                                                         at com.reactnativenavigation.layouts.BottomTabsLayout.showNewStack(BottomTabsLayout.java:529)
                                                                         at com.reactnativenavigation.layouts.BottomTabsLayout.switchTab(BottomTabsLayout.java:502)
                                                                         at com.reactnativenavigation.layouts.BottomTabsLayout.selectBottomTabByTabIndex(BottomTabsLayout.java:352)
                                                                         at com.reactnativenavigation.controllers.NavigationActivity.selectBottomTabByTabIndex(NavigationActivity.java:367)
                                                                         at com.reactnativenavigation.controllers.NavigationCommandsHandler$23.run(NavigationCommandsHandler.java:358)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

```

---
### Environment
* React Native Navigation version: 1.1.444
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator

**Comment by guyca** [comment]
The BottomTabs design pattern supported max 5 tabs on both platforms by design by design, no way around this.

**Comment by eliaskotov** [comment]
Do you think they will drop the restriction in RNN 2.0 and allow for 6 tabs?

**Comment by mths0x5f** [comment]
Nope. 5 tabs still the UX rational limit.

**Comment by abury** [comment]
Sorry @guyca but that's incorrect. iOS has natively supported more than 5 tabs for years and years with the 'more' pattern, and multiple high profile apps support the UX pattern of having more than 5 screens available from the tab bar (Facebook being a prime example). This is a pretty common scenario for a tab based app with any serious level of complexity.

At the very least there should be some type of warning about this in the documentation. There is a pretty simple way around it by making the fifth screen a 'more' screen with your own list, but a warning to people using a tab-based navigation scheme would be really helpful.

I still love RNN and what you guys are doing, but this was a really nasty shock.

**Comment by TimurAsayonok** [comment]
@abury About which Facebook app did you talk? Could you show some examples?
