### ISSUE TITLE
RNN1 ClassCastException

### ISSUE THREAD

**Issue by sytolk** [wix/react-native-navigation#3104]
```
04-25 12:58:04.159 31271-31271/de.drivelog.triplog W/Bundle: Key timestamp expected Double but value was a java.lang.Integer.  The default value 0.0 was returned.
04-25 12:58:04.160 31271-31271/de.drivelog.triplog W/Bundle: Attempt to cast generated internal exception:
                                                             java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
                                                                 at android.os.BaseBundle.getDouble(BaseBundle.java:1069)
                                                                 at android.os.BaseBundle.getDouble(BaseBundle.java:1051)
                                                                 at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:32)
                                                                 at com.reactnativenavigation.controllers.NavigationCommandsHandler$9.run(NavigationCommandsHandler.java:159)
                                                                 at android.os.Handler.handleCallback(Handler.java:789)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:172)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6637)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by guyca** [comment]
Duplicates #2842
