### ISSUE TITLE
RNN V1 Unable to launch redbox because react activity is not available

### ISSUE THREAD

**Issue by qiepeipei** [wix/react-native-navigation#3121]
### Issue Description

[RNN V1 Unable to launch redbox because react activity is not available]

Configure by document Try multiple react native version Nothing works .  
react native Initialization project normal    

04-28 15:23:32.545 7807-7857/? E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:33)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:234)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1113)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920)
        at java.lang.Thread.run(Thread.java:764)
04-28 15:23:32.545 7807-7807/? E/unknown:ReactNative: Unable to launch redbox because react activity is not available, here is the error that redbox would've displayed: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
04-28 15:23:39.073 7807-7807/com.meijia_new_var54 E/unknown:ReactNative: Unable to launch dev options menu because react activity isn't available
04-28 15:23:40.141 7807-7807/com.meijia_new_var54 E/unknown:ReactNative: Unable to launch dev options menu because react activity isn't available

![111](https://user-images.githubusercontent.com/16110628/39393629-1ec7c598-4afa-11e8-9b27-dd9f2bdcf399.png)

---
### Environment
* React Native Navigation version: 1.1.451
* React Native version: 0.54.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by iarambula** [comment]
Not sure if this helps but this is the error I get.
```

**Comment by krystofcelba** [comment]
Fixed in #2801 but waits to merge.

**Comment by qiepeipei** [comment]
@krystofcelba  android 8.0 Problem reproduction

**Comment by emadbayat** [comment]
i have a same problem. please open the issue.

**Comment by maoge8274** [comment]
I have the same problem

**Comment by jaimeagudo** [comment]
Still active, temporary workaround at https://github.com/wix/react-native-navigation/pull/2801#issuecomment-394278656
