### ISSUE TITLE
navigator.push crashes on android [error]

### ISSUE THREAD

**Issue by shivekkhurana** [wix/react-native-navigation#318]
Dear community, 
### When we try to push a new screen to the stack, the app crashes.

We use a custom redux implementation, where the navigator is saved inside the state. When I tried to `push` a new screen to the existing stack, I get the following error. 

```
09-18 17:22:24.198 19054-19054/com.buildbuy E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.buildbuy, PID: 19054
                                                              com.reactnativenavigation.layouts.BottomTabsLayout$ScreenStackNotFoundException: Stack navigatorID1_nav not found
                                                                  at com.reactnativenavigation.layouts.BottomTabsLayout.getScreenStackIndex(BottomTabsLayout.java:309)
                                                                  at com.reactnativenavigation.layouts.BottomTabsLayout.getScreenStack(BottomTabsLayout.java:291)
                                                                  at com.reactnativenavigation.layouts.BottomTabsLayout.push(BottomTabsLayout.java:211)
                                                                  at com.reactnativenavigation.controllers.NavigationActivity.push(NavigationActivity.java:151)
                                                                  at com.reactnativenavigation.controllers.NavigationCommandsHandler$1.run(NavigationCommandsHandler.java:47)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

### Steps to Reproduce

Reproduction of error will be hard as we have incorporated many custom techniques, rnn is a part of our framework. However, here's the gist of it.
 
1. In the componentWillMount function of the screen, dispatch `saveNavigatorToState(this.props.navigator)`. This saves the current navigator in the state.
2. On card press, an action with relevant screen id and props is dispatched. 
3. A screen reducer catches the action and starts a new single page app, tab based app or pushes onto existing stack.

#### Reducer : 
```js
  case actionTypes.app.screens.newOrderDetail:
    // this ain't working, need to fix
    state.navigator.push({
      screen: 'orders.details.New',
      title: action.payload.props.order.code,
      passProps: action.payload.props,
      animated: true,
      backButtonTitle: 'Back',
      backButtonHidden: false,
      navigatorStyle: navBarStyle
    });
    return {...state, currentScreen: 'orders.details.New'};
```
---

#### Environment
* React Native Navigation version: ^2.0.0-experimental.105
* React Native version: ^0.32.0
* Platform: Android only
* Device info: Nexus Simulator with api 23 | Debug

Thanks in advance.

------

PS: Thanks for building and open sourcing this great lib. We use it on iOs and Android projects and this works like a charm !

**Comment by DanielZlotin** [comment]
The problem is you're probably communicating with the wrong `navigator` instance. Currently (subject to change) each screen is created with its own navigator object.
Furthermore, in redux you should only keep serializable data in the state. The `navigator` object is not serializable.
What you are probably looking for is a way to push a screen statically, without reference to the screen's navigator. This is part of the current milestone #169 .
In the meantime, don't save the navigator in the state, pass it around.

**Comment by shivekkhurana** [comment]
Waiting for v2.0.0 😊

And after reading your response, we figured out the point where the wrong navigator was being passed around and fixed it.

Thanks

**Comment by DanielZlotin** [comment]
Nice. I would like to commend you on the thorough issue description!

**Comment by shivekkhurana** [comment]
Thank you :)
