### ISSUE TITLE
Android app crash when "Debug JS remotely" is enabled

### ISSUE THREAD

**Issue by Crash--** [wix/react-native-navigation#332]
### Issue Description

Trying to debug my application on Android but everytime I enable "Debug JS Remotely" the app crashes (it works fine on iOS)

My app is a tab one with two tabs. When I enable remote debug, the APP displays the tab but not the content inside it. And when I click on a tab, the app crashes. 

Here is some logs : 
````
Stream muted, skip playback
09-22 11:50:06.303 30748 30748 D AndroidRuntime: Shutting down VM
09-22 11:50:06.304 30748 30748 E AndroidRuntime: FATAL EXCEPTION: main
09-22 11:50:06.304 30748 30748 E AndroidRuntime: Process: com.inteach, PID: 30748
09-22 11:50:06.304 30748 30748 E AndroidRuntime: Theme: themes:{}
09-22 11:50:06.304 30748 30748 E AndroidRuntime: java.util.EmptyStackException
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at java.util.Stack.peek(Stack.java:57)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at com.reactnativenavigation.screens.ScreenStack.hide(ScreenStack.java:273)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at com.reactnativenavigation.layouts.BottomTabsLayout.hideCurrentStack(BottomTabsLayout.java:293)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at com.reactnativenavigation.layouts.BottomTabsLayout.onTabSelected(BottomTabsLayout.java:275)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.updateSmallItems(AHBottomNavigation.java:607)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.access$100(AHBottomNavigation.java:40)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at com.aurelhubert.ahbottomnavigation.AHBottomNavigation$3.onClick(AHBottomNavigation.java:454)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at android.view.View.performClick(View.java:5204)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at android.view.View$PerformClick.run(View.java:21158)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:739)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5461)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-22 11:50:06.304 30748 30748 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-22 11:50:06.307  1103  3868 W ActivityManager:   Force finishing activity 
```

And before that I had: 
```React: Calling JS function after bridge has been destroyed.```


---
### Environment
* React Native Navigation version: 2.exp
* React Native version: 0.31
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device on the same network / Debug

**Comment by guyca** [comment]
JS debugging is not working on RN 0.31, more info in #281 
@DanielZlotin What are your thoughts in this matter? I think we should consider upgrading to 0.34 where this issue is fixed.

**Comment by Crash--** [comment]
2 issues, 2 issues already reported! And yet I've done some search. 

Thanks.

**Comment by guyca** [comment]
lol no problem. Keep opening issues 👍
