### ISSUE TITLE
[v2] Failed resolution of: Lcom/reactnativenavigation/react/NavigationReactInitializer

### ISSUE THREAD

**Issue by birkir** [wix/react-native-navigation#3494]
I am getting this error after upgrading to the bottomTabs refactor. Using the CodePush method to find JS.

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/reactnativenavigation/react/NavigationReactInitializer;
	at com.reactnativenavigation.react.ReactGateway.<init>(ReactGateway.java:27)
	at is.pipe.hekla.MainApplication.createReactGateway(MainApplication.java:50)
	at com.reactnativenavigation.NavigationApplication.onCreate(NavigationApplication.java:28)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5858)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6642)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.reactnativenavigation.react.NavigationReactInitializer" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/is.pipe.hekla-8-tAT-2rkVvvEKd8VUyo7Q==/base.apk"],nativeLibraryDirectories=[/data/app/is.pipe.hekla-8-tAT-2rkVvvEKd8VUyo7Q==/lib/x86, /system/fake-libs, /data/app/is.pipe.hekla-8-tAT-2rkVvvEKd8VUyo7Q==/base.apk!/lib/x86, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:126)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 13 more
```

```java

    @Override
    protected ReactGateway createReactGateway() {
        ReactNativeHost host = new NavigationReactNativeHost(this, isDebug(), createAdditionalReactPackages()) {
            @javax.annotation.Nullable
            @Override
            protected String getJSBundleFile() {
                return CodePush.getJSBundleFile();
            }
        };
        return new ReactGateway(this, isDebug(), host);
    }

```

**Comment by birkir** [comment]
False alarm. Solved when I did `gradlew clean`.
