### ISSUE TITLE
0.56 crash Android

### ISSUE THREAD

**Issue by aspidvip** [wix/react-native-navigation#3698]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.479
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android 4.3
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Debug/Release

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.google.gms:google-services:4.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26//27
                buildToolsVersion "26.0.3"//"27.0.3"
            }
        }
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven { url "https://jitpack.io" }
    }
}



ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}

```

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.RuntimeException: Unable to resume activity {com.publikun/com.publikun.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2793)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2822)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269)
                                                       at android.app.ActivityThread.access$600(ActivityThread.java:144)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5136)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:525)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
                                                       at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:87)
                                                       at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:226)
                                                       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:278)
                                                       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:91)
                                                       at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.createReactInstanceManager(NavigationReactGateway.java:180)
                                                       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:44)
                                                       at com.reactnativenavigation.react.NavigationReactGateway.getReactInstanceManager(NavigationReactGateway.java:82)
                                                       at com.reactnativenavigation.react.NavigationReactGateway.hasStartedCreatingContext(NavigationReactGateway.java:69)
                                                       at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:43)
                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
                                                       at android.app.Activity.performResume(Activity.java:5211)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2783)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2822) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269) 
                                                       at android.app.ActivityThread.access$600(ActivityThread.java:144) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5136) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:525) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                       at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:78)
                                                       at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:226) 
                                                       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:278) 
                                                       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:91) 
                                                       at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.createReactInstanceManager(NavigationReactGateway.java:180) 
                                                       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:44) 
                                                       at com.reactnativenavigation.react.NavigationReactGateway.getReactInstanceManager(NavigationReactGateway.java:82) 
                                                       at com.reactnativenavigation.react.NavigationReactGateway.hasStartedCreatingContext(NavigationReactGateway.java:69) 
                                                       at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:43) 
                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192) 
                                                       at android.app.Activity.performResume(Activity.java:5211) 
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2783) 
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2822) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269) 
                                                       at android.app.ActivityThread.access$600(ActivityThread.java:144) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5136) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:525) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.NoClassDefFoundError: okio.Buffer
                                                       at okhttp3.ResponseBody.create(ResponseBody.java:209)
                                                       at okhttp3.internal.Util.<clinit>(Util.java:51)
                                                       at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:128)
                                                       at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:477)
                                                       at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:126)
                                                       at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:217)
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                       at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:78) 
                                                       at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:226) 
                                                       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:278) 
                                                       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:91) 
                                                       at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.createReactInstanceManager(NavigationReactGateway.java:180) 
                                                       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:44) 
                                                       at com.reactnativenavigation.react.NavigationReactGateway.getReactInstanceManager(NavigationReactGateway.java:82) 
                                                       at com.reactnativenavigation.react.NavigationReactGateway.hasStartedCreatingContext(NavigationReactGateway.java:69) 
                                                       at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:43) 
                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192) 
                                                       at android.app.Activity.performResume(Activity.java:5211) 
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2783) 
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2822) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269) 
                                                       at android.app.ActivityThread.access$600(ActivityThread.java:144) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5136) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:525) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                       at dalvik.system.NativeStart.main(Native Method) 

```

**Comment by yasinugrl** [comment]
@aspidvip  can you solve this issue?
