### ISSUE TITLE
[V2] [Android] Tapping outside an overlay causes crash

### ISSUE THREAD

**Issue by Iamsamwhoami** [wix/react-native-navigation#3776]
### Issue Description
Tapping outside an overlay makes Android crash.

Stacktrace:

```
08-16 17:38:58.521 15753 15753 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getHitRect(android.graphics.Rect)' on a null object reference
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at com.reactnativenavigation.views.touch.OverlayTouchDelegate.getTouchLocation(OverlayTouchDelegate.java:48)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at com.reactnativenavigation.views.touch.OverlayTouchDelegate.handleDown(OverlayTouchDelegate.java:37)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at com.reactnativenavigation.views.touch.OverlayTouchDelegate.onInterceptTouchEvent(OverlayTouchDelegate.java:27)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at com.reactnativenavigation.views.ComponentLayout.onInterceptTouchEvent(ComponentLayout.java:122)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.View.dispatchPointerEvent(View.java:12752)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.os.MessageQueue.nativePollOnce(Native Method)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.os.MessageQueue.next(MessageQueue.java:326)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:160)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-16 17:38:58.521 15753 15753 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Steps to Reproduce / Code Snippets / Screenshots
1. Show an overlay that has a component that renders null. For example `() => null`
2. Tap anywhere and the app crashes

---
### Environment
* React Native Navigation version: 2.0.2475
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): API 28, Debug

**Comment by stefanc96** [comment]
same problem
