### ISSUE TITLE
Facebook Login for Android Not working

### ISSUE THREAD

**Issue by VamshikBellurDayanand** [wix/react-native-navigation#3850]
Hello,

I am trying to develop an android app which supports facebook login.
However i am getting error.

08-24 14:55:28.713 2231-2231/com.example.vamshikbd.facebooksignin E/Login: failedSERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: null
08-24 14:55:28.713 2231-2231/com.example.vamshikbd.facebooksignin W/System.err: SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: null
08-24 14:55:28.717 2231-2231/com.example.vamshikbd.facebooksignin W/System.err:     at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:219)
        at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:174)
08-24 14:55:28.718 2231-2231/com.example.vamshikbd.facebooksignin W/System.err:     at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:95)
        at com.example.vamshikbd.facebooksignin.LoginActivity.onActivityResult(LoginActivity.java:57)
        at android.app.Activity.dispatchActivityResult(Activity.java:7295)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4516)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Can somebody please help me resolve this issue.

**Comment by henrikra** [comment]
Not related to this repo. Please close ping @guyca
