### ISSUE TITLE
[V2] Android crash on startup

### ISSUE THREAD

**Issue by preko96** [wix/react-native-navigation#3950]
### Issue Description

Just installed react-native-navigation v2 on a totally blank RN project.
For some reason when I start the app it's crashing immediately, because it's can't find the MainActivity. 

```
09-11 14:07:55.033 23312-23312/com.sigmamobileapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sigmamobileapp, PID: 23312
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.sigmamobileapp/com.sigmamobileapp.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.sigmamobileapp.MainActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.sigmamobileapp-OIG07bjfCSAKhZdID2Tr3Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.sigmamobileapp-OIG07bjfCSAKhZdID2Tr3Q==/lib/x86, /data/app/com.sigmamobileapp-OIG07bjfCSAKhZdID2Tr3Q==/base.apk!/lib/x86, /system/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sigmamobileapp.MainActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.sigmamobileapp-OIG07bjfCSAKhZdID2Tr3Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.sigmamobileapp-OIG07bjfCSAKhZdID2Tr3Q==/lib/x86, /data/app/com.sigmamobileapp-OIG07bjfCSAKhZdID2Tr3Q==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```
### Steps to Reproduce / Code Snippets / Screenshots

1.) Create a new RN project
2.) Install react-native-navigation@alpha module
3.) Follow the steps: [https://wix.github.io/react-native-navigation/v2/#/](url)
4.) Start the package manager: (yarn start)
5.) Start android: (yarn run android)
6.) Try to open the builded app.

---
### Environment
* Yarn: 1.9.4
* Node: 8.11.4
* JDK: 8
* React Native Navigation version: 2.0.2538
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 5X API 28 x86

P.S: Tried on both create-react-native-app (0.55) and on react-native init (0.56).

**Comment by hadimostafapour** [comment]
@preko96 This may caused by wrong setup, not related to RNN.
Checkout your package name and AndroidManifest.

**Comment by preko96** [comment]
<img width="579" alt="screen shot 2018-09-11 at 18 44 05 pm" src="https://user-images.githubusercontent.com/35433203/45377797-8f42cc00-b5f3-11e8-8e13-fb96995bda15.png">
<img width="457" alt="screen shot 2018-09-11 at 18 44 39 pm" src="https://user-images.githubusercontent.com/35433203/45377798-8f42cc00-b5f3-11e8-9d15-dfd55340a89a.png">
<img width="632" alt="screen shot 2018-09-11 at 18 44 52 pm" src="https://user-images.githubusercontent.com/35433203/45377799-8f42cc00-b5f3-11e8-8ca5-30fc89ebd860.png">
<img width="423" alt="screen shot 2018-09-11 at 18 47 23 pm" src="https://user-images.githubusercontent.com/35433203/45377800-8fdb6280-b5f3-11e8-9079-6af74277d7f8.png">
<img width="588" alt="screen shot 2018-09-11 at 18 43 36 pm" src="https://user-images.githubusercontent.com/35433203/45377801-8fdb6280-b5f3-11e8-82e2-99410c93ea8a.png">
<img width="632" alt="screen shot 2018-09-11 at 18 41 57 pm" src="https://user-images.githubusercontent.com/35433203/45377802-8fdb6280-b5f3-11e8-9a69-ee965b7a49cf.png">
<img width="646" alt="screen shot 2018-09-11 at 18 41 51 pm" src="https://user-images.githubusercontent.com/35433203/45377804-9073f900-b5f3-11e8-8032-b29c9cf01d3a.png">
<img width="798" alt="screen shot 2018-09-11 at 18 41 45 pm" src="https://user-images.githubusercontent.com/35433203/45377805-9073f900-b5f3-11e8-9020-66c02e3d543b.png">

**Comment by hadimostafapour** [comment]
Just add `package com.sigmamobileapp;` to MainActivity.java file

**Comment by preko96** [comment]
I am just so silly LOL!

Why am I getting even stuck with such a small thing?
Thanks mate, you are a life saver! 👍 :)
