### ISSUE TITLE
Ability to use side menu in specific components and replace content

### ISSUE THREAD

**Issue by reganperkins** [wix/react-native-navigation#4013]
I am having trouble finding the best way to do the following. I want to have it where a side menu is only on two pages and the content depends on which of the two pages I am on.

In another post I saw a suggestion to use a stack not a push https://github.com/wix/react-native-navigation/issues/3477 following that advice I can replace the content but I cant seem to open the sideMenu via a button, only gestures are working. Also I cant seem to completely remove the side menu for the pages I don't want

```

Navigation.setRoot({
	 root: {
	 	 sideMenu: {
	 	 	 center: {
	 	 	 	 stack: {
	 	 	 	 	 options: {
	 	 	 	 	 	 popGesture: false,
	 	 	 	 	 },
	 	 	 		   children: [{
	 	 	 	 	 	 component: {
						 	 name: 'WaitForAuth',
				 		  },
					  } ],
		 	 	  },
		 	  },
		 	 left: {
				  enabled: SessionStatus.LOGGED_IN,
			 	 	visible: false,
			 	 	component: {
			 	 		id: 'drawer',
			 	 		name: 'drawer',
			 	 	},
			  },
			  right: {
			 	 stack: {
			 	 	id: 'SIDE_MENU_RIGHT',
			 	 }
	 		  },
	 	 },
	 },
});

Navigation.setStackRoot('SIDE_MENU_RIGHT', {
	component: { name: 'RightPanel', passProps: props, options: {visible: true, enabled: true} },
	options: {visible: true, enabled: true},
	visible: true,
	enabled: true,
}) 

```

Due to way I want my application to look and act it would be preferable to set the side menu from the component using this.Navigation.push as the other linked question originally wanted to and be able to replace the content when needed using merge options. This however simply did not work for me, should this be possible? Something like the following:

```
		return Navigation.push(
			componentId || screen.props.componentId,
			{
				component: {
					name: component,
					passProps: props || {},
					options: {
						sideMenu: {
							right: {
								component: {
									name: 'RightPanel',
								},
							},
						},
					},
				},
			}
		);


       Navigation.mergeOptions(componentId, {
		sideMenu: {
			right: {
				passProps: props,
				visible: true,
				enabled: true,
				component: {
					name: 'RightPanel',
					options: {
						visible: true,
						enabled: true,
					},
				},
			},
		},
	});

```

however it does not seem to add a sideMenu (even when I have visibility and enabled set to true), whats more when I trigger mergeOptions it leads to the following error:

```

 Uncaught native exception java.lang.IllegalArgumentException: No drawer view found with gravity RIGHT
	at android.support.v4.widget.DrawerLayout.openDrawer(DrawerLayout.java:1639)
	at android.support.v4.widget.DrawerLayout.openDrawer(DrawerLayout.java:1625)
	at com.reactnativenavigation.presentation.SideMenuOptionsPresenter.present(SideMenuOptionsPresenter.java:25)
	at com.reactnativenavigation.viewcontrollers.sidemenu.SideMenuController.mergeChildOptions(SideMenuController.java:83)
	at com.reactnativenavigation.viewcontrollers.stack.StackController.lambda$mergeChildOptions$1$StackController(StackController.java:101)
	at com.reactnativenavigation.viewcontrollers.stack.StackController$$Lambda$2.run(Unknown Source)
	at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentController(ViewController.java:130)
	at com.reactnativenavigation.viewcontrollers.stack.StackController.mergeChildOptions(StackController.java:100)
	at com.reactnativenavigation.viewcontrollers.ComponentViewController.lambda$mergeOptions$0$ComponentViewController(ComponentViewController.java:67)
	at com.reactnativenavigation.viewcontrollers.ComponentViewController$$Lambda$0.run(Unknown Source)
	at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentController(ViewController.java:130)
	at com.reactnativenavigation.viewcontrollers.ComponentViewController.mergeOptions(ComponentViewController.java:67)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.mergeOptions(Navigator.java:142)
	at com.reactnativenavigation.react.NavigationModule.lambda$mergeOptions$3$NavigationModule(NavigationModule.java:79)
	at com.reactnativenavigation.react.NavigationModule$$Lambda$3.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

react-native-navigation V2

**Comment by acollazomayer** [comment]
@reganperkins Having the same issue how did you solve it

**Comment by EskelCz** [comment]
I need the same thing, can we have this reopened? I've tried passProps with mergeOptions and it didn't work.

**Comment by AKACC** [comment]
@acollazomayer @EskelCz @reganperkins I solved the problem. In my case, I was using `Navigation.mergeoptions` trying to control left sidemenu which has not been set and there was no component inside.
