### ISSUE TITLE
[v2] Android release "index.android.bundle" not found

### ISSUE THREAD

**Issue by stefanc96** [wix/react-native-navigation#4125]
### Issue Description
I've made a build for release , then I've installed it on my phone but the app won't open. On debug app works perfectly fine.
 
### Steps to Reproduce / Code Snippets / Screenshots

Process: com.mindclash, PID: 5640
    java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:243)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1117)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916)
        at java.lang.Thread.run(Thread.java:764)

---
### Environment
* React Native Navigation version: 2.0.2580
* React Native version: 0.56
* Platform(s) : Android
* Device info : Device Release

**Comment by sinhpn92** [comment]
I have same issue. In the debug env, don't have this issue. Only have in release env

**Comment by gusoskar** [comment]
I also have this exact same issue. The project is working just fine on iOS, and Android is working fine when running it from the console with 'react-native run-android'. The project is not however able to be run from Android Studio (I get this error when I do) and I get this error if I detach my android device from my computer and run it.

**Comment by gusoskar** [comment]
@stefanc96 Did you find a solution to this? Did you post your question on stackoverflow?

**Comment by yizhew** [comment]
I have same issue after I upgrade RNN from v1 to v2, I found a solution that use the old way to create assets manually. Switch to your project root folder and execute "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle" before "./gradlew assembleRelease".
