### ISSUE TITLE
[v2] Crash setting bottom tabs as root NullPointerException: int com.reactnativenavigation.views.BottomTabs.getCurrentItem()' on a null object reference

### ISSUE THREAD

**Issue by byroncortez** [wix/react-native-navigation#4130]
### Issue Description

App crashes when i setStackRoot to bottom tab. From the android logs: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.reactnativenavigation.views.BottomTabs.getCurrentItem()' on a null object reference

### Steps to Reproduce / Code Snippets / Screenshots

I start my app with a welcome screen:
Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setRoot({
        root: {
            stack: {
                id: 'mainNavigationStackId',
                children: [
                    {
                        component: {
                            name: 'app.welcome',
                        }
                    }
                ],
            }
        }
    });
});

And i set stack root like this:
Navigation.setStackRoot('mainNavigationStackId', {
                        bottomTabs: {
                            id: 'mainTabsId',
                            children: [
                                {
                                    component: {
                                        name: 'app.events',
                                        options: {
                                            bottomTab: {
                                                fontSize: 12,
                                                text: 'Events',
                                                icon: ic_events,
                                            }
                                        }
                                    }
                                }
                            ],
                        }
                    });

This works if I use setRoot({})

---
### Environment
* React Native Navigation version: 2.0.2467
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Any Android Device

**Comment by LRNZ09** [comment]
This is also happening in the latest release with RN 0.57

**Comment by LRNZ09** [comment]
This still happens in version 2.1.3

**Comment by TylerNRobertson** [comment]
This is still present. Please remove from stale.

- Currently still an issue with:
RNN - 2.1.3
RN - 0.57.7
React - 16.6.1

**Comment by ItsNoHax** [comment]
You should be setting the root again, not the root stack.

**Comment by LRNZ09** [comment]
This is still present in `2.5.0`
@ItsNoHax what you're saying is wrong, it's not the same thing.

**Comment by rf1804** [comment]
@guyca  @ItsNoHax  It is still happening 
In my app after completing login i have to switch to bottomTabApp for that i am calling setStackRoot with bottomTabs but it crashes with this error
This is only happening on Android, for IOS it is working fine 

- React Native Navigation version: 2.7.1
- React Native version: 0.57.8

`
FATAL EXCEPTION: main
Process: com.frizbee, PID: 8706
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.reactnativenavigation.views.BottomTabs.getCurrentItem()' on a null object reference
	at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.getCurrentChild(BottomTabsController.java:135)
	at com.reactnativenavigation.viewcontrollers.ParentController.resolveCurrentOptions(ParentController.java:43)
	at com.reactnativenavigation.viewcontrollers.ParentController.resolveCurrentOptions(ParentController.java:44)
	at com.reactnativenavigation.viewcontrollers.ParentController.resolveCurrentOptions(ParentController.java:52)
	at com.reactnativenavigation.viewcontrollers.stack.StackController.push(StackController.java:158)
	at com.reactnativenavigation.viewcontrollers.stack.StackController.setRoot(StackController.java:197)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$setStackRoot$1$Navigator(Navigator.java:158)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator$$Lambda$1.run(Unknown Source:6)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$applyOnStack$5$Navigator(Navigator.java:221)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator$$Lambda$5.run(Unknown Source:2)
	at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentStack(ViewController.java:145)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.applyOnStack(Navigator.java:221)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.setStackRoot(Navigator.java:158)
	at com.reactnativenavigation.react.NavigationModule.lambda$setStackRoot$5$NavigationModule(NavigationModule.java:101)
	at com.reactnativenavigation.react.NavigationModule$$Lambda$5.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6798)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by mtzfactory** [comment]
No plan for a solution?

**Comment by Apostata** [comment]
Not Woking in RNN 2.15.0 yet.

**Comment by Findiglay** [comment]
I'm still finding this bug on v6.3.1 for Android.
