### ISSUE TITLE
app hang stuck splsh screen

### ISSUE THREAD

**Issue by ziyad2009** [wix/react-native-navigation#4302]
### when i install app in android device and run 
 I get error show below  from adb and from  Android vitals

if i tray to run in my android Emulator it run OK without an problems 
 but in real device story is different is not work 
just splash screen stack and not show the screen

E/AndroidRuntime( 8392): FATAL EXCEPTION: main
E/AndroidRuntime( 8392): Process: com.proog1, PID: 8392
E/AndroidRuntime( 8392): java.lang.RuntimeException: Unable to start activity Co                                                    mponentInfo{com.proog1/com.reactnativenavigation.controllers.NavigationActivity}                                                    : java.lang.NullPointerException: uriString
E/AndroidRuntime( 8392):        at android.app.ActivityThread.performLaunchActiv                                                    ity(ActivityThread.java:2447)
E/AndroidRuntime( 8392):        at android.app.ActivityThread.handleLaunchActivi                                                    ty(ActivityThread.java:2507)
E/AndroidRuntime( 8392):        at android.app.ActivityThread.access$900(Activit                                                    yThread.java:172)
E/AndroidRuntime( 8392):        at android.app.ActivityThread$H.handleMessage(Ac                                                    tivityThread.java:1308)
E/AndroidRuntime( 8392):        at android.os.Handler.dispatchMessage(Handler.ja                                                    va:102)
E/AndroidRuntime( 8392):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime( 8392):        at android.app.ActivityThread.main(ActivityThrea                                                    d.java:5692)
E/AndroidRuntime( 8392):        at java.lang.reflect.Method.invokeNative(Native                                                     Method)
E/AndroidRuntime( 8392):        at java.lang.reflect.Method.invoke(Method.java:5                                                    15)
E/AndroidRuntime( 8392):        at com.android.internal.os.ZygoteInit$MethodAndA                                                    rgsCaller.run(ZygoteInit.java:1291)
E/AndroidRuntime( 8392):        at com.android.internal.os.ZygoteInit.main(Zygot                                                    eInit.java:1107)
E/AndroidRuntime( 8392):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 8392): Caused by: java.lang.NullPointerException: uriString
E/AndroidRuntime( 8392):        at android.net.Uri$StringUri.<init>(Uri.java:468                                                    )
E/AndroidRuntime( 8392):        at android.net.Uri$StringUri.<init>(Uri.java:458                                                    )
E/AndroidRuntime( 8392):        at android.net.Uri.parse(Uri.java:430)
E/AndroidRuntime( 8392):        at com.reactnativenavigation.react.ImageLoader.l                                                    oadImage(ImageLoader.java:18)
E/AndroidRuntime( 8392):        at com.reactnativenavigation.params.parsers.TabI                                                    conParser.parse(TabIconParser.java:19)
E/AndroidRuntime( 8392):        at com.reactnativenavigation.params.parsers.Scre                                                    enParamsParser.parse(ScreenParamsParser.java:57)
E/AndroidRuntime( 8392):        at com.reactnativenavigation.params.parsers.Acti                                                    vityParamsParser.parse(ActivityParamsParser.java:18)
E/AndroidRuntime( 8392):        at com.reactnativenavigation.controllers.Navigat                                                    ionCommandsHandler.parseActivityParams(NavigationCommandsHandler.java:21)
E/AndroidRuntime( 8392):        at com.reactnativenavigation.controllers.Navigat                                                    ionActivity.onCreate(NavigationActivity.java:77)
E/AndroidRuntime( 8392):        at android.app.Activity.performCreate(Activity.j                                                    ava:5541)
E/AndroidRuntime( 8392):        at android.app.Instrumentation.callActivityOnCre                                                    ate(Instrumentation.java:1093)
E/AndroidRuntime( 8392):        at android.app.ActivityThread.performLaunchActiv                                                    ity(ActivityThread.java:2411)
E/AndroidRuntime( 8392):        ... 11 more

---
### Environment
* React Native Navigation version:  "react-native-navigation": "^1.1.478",
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): android device

**Comment by ziyad2009** [comment]
i solve it 
first flow  #3688 issues

make sure from u r AndroidManifest update (sdk vireson )
