### ISSUE TITLE
Android application terminates with exception

### ISSUE THREAD

**Issue by lyubo** [wix/react-native-navigation#454]
### Issue Description

When  a bad color value is specified (ex. navBarTextColor: '#fff'), android application terminates with the following exception:
```
11-18 09:07:16.846 29624 29624 D AndroidRuntime: Shutting down VM
11-18 09:07:16.846 29624 29624 E AndroidRuntime: FATAL EXCEPTION: main
11-18 09:07:16.846 29624 29624 E AndroidRuntime: Process: xxxxx, PID: 29624
11-18 09:07:16.846 29624 29624 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{xxxxx/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.IllegalArgumentException: Unknown color
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unknown color
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.graphics.Color.parseColor(Color.java:226)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at com.reactnativenavigation.params.StyleParams$Color.parse(StyleParams.java:34)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.StyleParamsParser.getColor(StyleParamsParser.java:190)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.StyleParamsParser.parse(StyleParamsParser.java:31)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:30)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.ActivityParamsParser.parse(ActivityParamsParser.java:16)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at com.reactnativenavigation.controllers.NavigationCommandsHandler.parseActivityParams(NavigationCommandsHandler.java:24)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at com.reactnativenavigation.controllers.NavigationActivity.onCreate(NavigationActivity.java:54)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6237)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-18 09:07:16.846 29624 29624 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
```
Application keeps terminating this way even after fixing the bad color value in JS source. Problem resolves after recompiling and reinstalling application with **react-native run-android**

### Steps to Reproduce / Code Snippets / Screenshots

```
const nav= {
  screen: {
    screen: 'Welcome',
    title: 'Welcome',
    navigatorStyle: {
      navBarTextColor: '#fff',
      statusBarTextColorScheme: 'light'
    }
  }
}
Navigation.startSingleScreenApp(nav)
```
### Environment
* React Native Navigation version: 2.0.0-experimental.141@18/11/2016
* React Native version: 0.37.0
* Platform(s): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Android 6.0, Debug

**Comment by richardmillen94** [comment]
Android also won't support the 'rgb(RR, GG, BB)' color format (or anything besides the hex values supported by android.graphics.Color.parseColor()).
