### ISSUE TITLE
Floating action button doesn't appear on the screen

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#457]
### Issue Description

I can't seem to get the FAB to show on the screen. I followed the instructions present on the wiki but I don't see any button on the screen. I am using a single screen application with top tabs. I specify the `fab` like this in the screen which is one of the screens in the top tab bar.

```js
  static navigatorButtons = {
    rightButtons: getRightButtonsForAlarmList(),
    fab: {
      collapsedId: 'share',
      collapsedIcon: require('../../img/navicon_add.png'),
      backgroundColor: '#607D8B'
    }
  }

  onTabActive = () => {
    this.props.navigator.setButtons({
      rightButtons: getRightButtonsForAlarmList(),
      fab: {
        collapsedId: 'share',
        collapsedIcon: require('../../img/navicon_add.png'),
        backgroundColor: '#607D8B'
      }
    })
  }
```

`onTabActive` is called on `tabSelected` event. I also tried to just use the screen which contains the `fab` as the main screen of the app and comment out the `topTabs` section to check if the issue has something to do with top tabs but I don't see the `fab` even then.

Is there anything extra that needs to be done for the `fab` to show up?

### Environment
* React Native Navigation version: 2.0.0.experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug Simulator

**Comment by guyca** [comment]
Thanks for reporting, I'll look into it.

**Comment by guyca** [comment]
Seems like it's caused by this commit 0863bff91da920fbdcd25295f0ad590653c554c8
JS + RN === <3 😞

**Comment by varungupta85** [comment]
@guyca Thanks for the response. If I remember correctly, [0863bff](https://github.com/wix/react-native-navigation/commit/0863bff91da920fbdcd25295f0ad590653c554c8) fixed the problem where re-opening a modal was causing a crash. Do you want me to check that if I revert this commit, am I able to see the `fab` or not?

**Comment by varungupta85** [comment]
I just tried it after reverting the commit and the app crashed as soon as it is mounted with the below call stack

```java
11-19 02:34:56.290 21657-21657/com.xyz E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.xyz, PID: 21657
                                                               java.lang.NoSuchMethodError: No direct method <init>(Landroid/widget/ImageView;Landroid/support/v7/widget/AppCompatDrawableManager;)V in class Landroid/support/v7/widget/AppCompatImageHelper; or its super classes (declaration of 'android.support.v7.widget.AppCompatImageHelper' appears in /data/data/com.xyz/files/instant-run/dex/slice-com.android.support-appcompat-v7-25.0.0_4c07d55631914661ce6eeb781a57368f0bcb852e-classes.dex)
                                                                   at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:170)
                                                                   at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:147)
                                                                   at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:143)
                                                                   at com.reactnativenavigation.views.FloatingActionButtonCoordinator.createFab(FloatingActionButtonCoordinator.java:117)
                                                                   at com.reactnativenavigation.views.FloatingActionButtonCoordinator.createCollapsedFab(FloatingActionButtonCoordinator.java:87)
                                                                   at com.reactnativenavigation.views.FloatingActionButtonCoordinator.add(FloatingActionButtonCoordinator.java:47)
                                                                   at com.reactnativenavigation.views.SnackbarAndFabContainer$1.run(SnackbarAndFabContainer.java:63)
                                                                   at com.reactnativenavigation.views.FloatingActionButtonCoordinator.remove(FloatingActionButtonCoordinator.java:57)
                                                                   at com.reactnativenavigation.views.SnackbarAndFabContainer.updateFab(SnackbarAndFabContainer.java:59)
                                                                   at com.reactnativenavigation.views.SnackbarAndFabContainer.onScreenChange(SnackbarAndFabContainer.java:48)
                                                                   at com.reactnativenavigation.views.SnackbarAndFabContainer.onEvent(SnackbarAndFabContainer.java:42)
                                                                   at com.reactnativenavigation.events.EventBus.post(EventBus.java:35)
                                                                   at com.reactnativenavigation.layouts.SingleScreenLayout.sendScreenChangedEventAfterInitialPush(SingleScreenLayout.java:83)
                                                                   at com.reactnativenavigation.layouts.SingleScreenLayout.createLayout(SingleScreenLayout.java:53)
                                                                   at com.reactnativenavigation.layouts.SingleScreenLayout.<init>(SingleScreenLayout.java:42)
                                                                   at com.reactnativenavigation.layouts.LayoutFactory.createSingleScreenLayout(LayoutFactory.java:20)
                                                                   at com.reactnativenavigation.layouts.LayoutFactory.create(LayoutFactory.java:15)
                                                                   at com.reactnativenavigation.controllers.NavigationActivity.createLayout(NavigationActivity.java:73)
                                                                   at com.reactnativenavigation.controllers.NavigationActivity.onCreate(NavigationActivity.java:57)
                                                                   at android.app.Activity.performCreate(Activity.java:6237)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-19 02:34:58.625 21657-21657/com.xyz I/Process: Sending signal. PID: 21657 SIG: 9
```

But it looks like it did try to show the `fab` after the reverting the commit.

**Comment by guyca** [comment]
#458 fixes the initial bug you reported.
The stack trace you posted seems to be caused by something else, since as you observed RNN does try to show the fab.
I'll try to publish a version on Sunday and if you have other problems feel free to open another issue.
Thanks 👍

**Comment by varungupta85** [comment]
@guyca The stack trace happened due to incompatible versions of android `appcompat` and `design` library. I am using `25.0.0` for `appcompat` library and since I was not including the `design` library, it was using an older version. I specified the `design` library as well as `25.0.0` in gradle file and picked up the commit from 458 and I was able to see the `fab`. Thanks!
