### ISSUE TITLE
Release version keeps crashing

### ISSUE THREAD

**Issue by janziemba** [wix/react-native-navigation#4591]
### Issue Description
On both platforms, iOS and Android, the release version of my app keeps crashing on startup. Debug version is ok, it works well.

### Steps to Reproduce / Code Snippets / Screenshots
```sh
react-native run-ios --configuration Release
```

I have set everything up correctly according to installation instructions: https://wix.github.io/react-native-navigation/#/docs/Installing

There are similar issues:
- https://github.com/wix/react-native-navigation/issues/4395 
- https://github.com/wix/react-native-navigation/issues/4146

#### My index.js in a project's root:
```js
import React from 'react';
import { Navigation } from 'react-native-navigation';

import GameLevelScreen from './src/app/gameLevel/GameLevelScreen';
import GameModeScreen from './src/app/gameMode/GameModeScreen';
import GameScreen from './src/app/game/GameScreen';
import MainMenuScreen from './src/app/mainMenu/MainMenuScreen';
import ScoreScreen from './src/app/score/ScoreScreen';
import WelcomeScreen from './src/app/welcome/WelcomeScreen';
import ErrorBoundary from './src/app/ErrorBoundary';
import { AppContainer } from './src/ui/components';
import ThemeContext from './src/ui/themes/themeContext';

const screens = [
    GameLevelScreen,
    GameModeScreen,
    GameScreen,
    MainMenuScreen,
    ScoreScreen,
    WelcomeScreen,
];

const registerComponent = (Component) => {
    Navigation.registerComponent(Component.name, () => props => (
        <ThemeContext.Provider>
            <ErrorBoundary>
                <AppContainer>
                    <Component
                        {...props}
                    />
                </AppContainer>
            </ErrorBoundary>
        </ThemeContext.Provider>
    ), () => Component);
};

screens.map(item => registerComponent(item));

Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setDefaultOptions({
        topBar: {
            visible: false,
        },
        popGesture: true,
    });

    Navigation.setRoot({
        root: {
            stack: {
                children: [
                    {
                        component: {
                            name: 'MainMenuScreen',
                        },
                    },
                ],
            },
        },
    });
});
```

---
### Environment
* React Native Navigation version: 2.6.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): both simulator and device, all OS versions, but release version only

### Additional information
- No, I don't have a Metro Bundler running in a different folder.
- `MainMenuScreen` is my root component.
- It says: 
> **Application MainMenuScreen has not been registered.**

#### Xcode log:
```bat
2019-01-16 12:21:44.566165+0100 ResPublica[73498:932115] Simulator user has requested new graphics quality: 10
2019-01-16 12:21:44.565 [error][tid:com.facebook.react.JavaScript] Application MainMenuScreen has not been registered.

Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').

This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.


2019-01-16 12:21:44.567518+0100 ResPublica[73498:932217] Application MainMenuScreen has not been registered.

Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').

This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
2019-01-16 12:21:44.573 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Application MainMenuScreen has not been registered.

Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').

This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.


2019-01-16 12:21:44.575824+0100 ResPublica[73498:932205] Unhandled JS Exception: Application MainMenuScreen has not been registered.

Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').

This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
2019-01-16 12:21:44.638746+0100 ResPublica[73498:932205] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Application MainMenuScreen has not been registered.

Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').

This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.

', reason: 'Unhandled JS Exception: Application MainMenuScreen has not been registered.

Hint: This error often happens when you're running the packager (local dev server) from a wrong fo..., stack:
runApplication@319:1375
value@38:3311
<unknown>@38:822
value@38:2565
value@38:794
'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001113371bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010fa1c735 objc_exception_throw + 48
	2   ResPublica                          0x000000010ee94bd7 RCTFormatError + 0
	3   ResPublica                          0x000000010ee9048c -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 507
	4   CoreFoundation                      0x000000011133e03c __invoking___ + 140
	5   CoreFoundation                      0x000000011133b4d5 -[NSInvocation invoke] + 325
	6   CoreFoundation                      0x000000011133b926 -[NSInvocation invokeWithTarget:] + 54
	7   ResPublica                          0x000000010eea8661 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 612
	8   ResPublica                          0x000000010eef0dab _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 255
	9   ResPublica                          0x000000010eef0b29 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 78
	10  libdispatch.dylib                   0x000000011454f4e1 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x000000011455054b _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000011455701c _dispatch_lane_serial_drain + 720
	13  libdispatch.dylib                   0x0000000114557b5f _dispatch_lane_invoke + 401
	14  libdispatch.dylib                   0x00000001145609a8 _dispatch_workloop_worker_thread + 645
	15  libsystem_pthread.dylib             0x000000011493961c _pthread_wqthread + 409
	16  libsystem_pthread.dylib             0x0000000114939415 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

#### Android simulator log:
```bat
01-16 12:02:24.951  2110  2231 W OpenGLRenderer: Incorrectly called buildLayer on View: SuperGContainerView, destroying layer...
01-16 12:02:27.380  1352  1377 W audio_hw_generic: Not supplying enough data to HAL, expected position 1579753 , only wrote 1579680
01-16 12:02:27.381  1656  2232 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.respublica/.MainActivity bnds=[27,273][283,603] (has extras)} from uid 10021 on display 0
01-16 12:02:27.438  1656  1668 I ActivityManager: Start proc 4417:com.respublica/u0a103 for activity com.respublica/.MainActivity
01-16 12:02:27.445  1302  1313 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8294400
01-16 12:02:27.492  4417  4417 W art     : Unexpected CPU variant for X86 using defaults: x86
01-16 12:02:27.530  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:27.546  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:27.561  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:27.576  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:27.591  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:27.606  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:27.620  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:27.635  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:27.651  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:27.652  4417  4417 D SoLoader: init start
01-16 12:02:27.652  4417  4417 D SoLoader: adding system library source: /vendor/lib
01-16 12:02:27.652  4417  4417 D SoLoader: adding system library source: /system/lib
01-16 12:02:27.652  4417  4417 D SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.respublica-1/lib/x86 flags = 0]
01-16 12:02:27.654  4417  4417 D SoLoader: adding backup  source: com.facebook.soloader.ApkSoSource[root = /data/data/com.respublica/lib-main flags = 1]
01-16 12:02:27.654  4417  4417 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
01-16 12:02:27.654  4417  4417 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/vendor/lib flags = 2]
01-16 12:02:27.654  4417  4417 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.respublica-1/lib/x86 flags = 0]
01-16 12:02:27.654  4417  4417 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.respublica/lib-main flags = 1]
01-16 12:02:27.655  4417  4417 V fb-UnpackingSoSource: locked dso store /data/user/0/com.respublica/lib-main
01-16 12:02:27.659  4417  4417 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.respublica/lib-main
01-16 12:02:27.659  4417  4417 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.respublica/lib-main
01-16 12:02:27.659  4417  4417 D SoLoader: init finish: 4 SO sources prepared
01-16 12:02:27.659  4417  4417 D SoLoader: init exiting
01-16 12:02:27.666  4417  4417 D ReactNative: ReactInstanceManager.ctor()
01-16 12:02:27.666  4417  4417 D SoLoader: init exiting
01-16 12:02:27.681  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:27.707  4417  4417 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-16 12:02:27.763  4417  4417 D ReactNative: ReactInstanceManager.createReactContextInBackground()
01-16 12:02:27.763  4417  4417 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
01-16 12:02:27.763  4417  4417 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
01-16 12:02:27.763  4417  4417 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
01-16 12:02:27.763  4417  4417 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
01-16 12:02:27.766  4417  4432 D SoLoader: About to load: libreactnativejni.so
01-16 12:02:27.767  4417  4432 D SoLoader: libreactnativejni.so not found on /data/data/com.respublica/lib-main
01-16 12:02:27.767  4417  4432 D SoLoader: libreactnativejni.so found on /data/app/com.respublica-1/lib/x86
01-16 12:02:27.767  4417  4432 D SoLoader: Not resolving dependencies for libreactnativejni.so
01-16 12:02:27.801  4417  4432 D SoLoader: Loaded: libreactnativejni.so
01-16 12:02:27.802  4417  4432 D SoLoader: About to load: libfb.so
01-16 12:02:27.802  4417  4432 D SoLoader: libfb.so not found on /data/data/com.respublica/lib-main
01-16 12:02:27.802  4417  4432 D SoLoader: libfb.so found on /data/app/com.respublica-1/lib/x86
01-16 12:02:27.802  4417  4432 D SoLoader: Not resolving dependencies for libfb.so
01-16 12:02:27.809  4417  4432 D SoLoader: About to load: libfb.so
01-16 12:02:27.809  4417  4432 D SoLoader: libfb.so not found on /data/data/com.respublica/lib-main
01-16 12:02:27.810  4417  4432 D SoLoader: libfb.so found on /data/app/com.respublica-1/lib/x86
01-16 12:02:27.810  4417  4432 D SoLoader: Not resolving dependencies for libfb.so
01-16 12:02:27.810  4417  4432 I art     : Thread[12,tid=4432,Native,Thread*=0xe439e300,peer=0x12c80ca0,"Thread-2"] recursive attempt to load library "/data/app/com.respublica-1/lib/x86/libfb.so"
01-16 12:02:27.810  4417  4432 D SoLoader: Loaded: libfb.so
01-16 12:02:27.810  4417  4432 D SoLoader: Loaded: libfb.so
01-16 12:02:27.813  1302  1941 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
01-16 12:02:27.814  4417  4432 D ReactNative: ReactInstanceManager.createReactContext()
01-16 12:02:27.854  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.reactnativenavigation.react.ElementViewManager
01-16 12:02:27.882  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
01-16 12:02:27.911  4417  4433 D         : HostConnection::get() New Host Connection established 0xe43ade80, tid 4433
01-16 12:02:27.912  4417  4433 I OpenGLRenderer: Initialized EGL, version 1.4
01-16 12:02:27.912  4417  4433 D OpenGLRenderer: Swap behavior 1
01-16 12:02:27.913  4417  4433 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
01-16 12:02:27.913  4417  4433 D OpenGLRenderer: Swap behavior 0
01-16 12:02:27.927  4417  4433 D EGL_emulation: eglCreateContext: 0xd8984660: maj 3 min 0 rcv 3
01-16 12:02:27.933  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
01-16 12:02:27.935  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
01-16 12:02:27.935  2110  2122 I art     : Background sticky concurrent mark sweep GC freed 7870(563KB) AllocSpace objects, 14(1420KB) LOS objects, 10% free, 13MB/14MB, paused 1.663ms total 115.326ms
01-16 12:02:27.946  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
01-16 12:02:27.946  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
01-16 12:02:27.946  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
01-16 12:02:27.947  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
01-16 12:02:27.967  4417  4433 D EGL_emulation: eglMakeCurrent: 0xd8984660: ver 3 0 (tinfo 0xe43f0980)
01-16 12:02:27.968  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
01-16 12:02:27.991  2110  2231 D EGL_emulation: eglMakeCurrent: 0x7ec3fa8928a0: ver 3 0 (tinfo 0x7ec3fc9f00e0)
01-16 12:02:28.011  4417  4433 D EGL_emulation: eglMakeCurrent: 0xd8984660: ver 3 0 (tinfo 0xe43f0980)
01-16 12:02:28.017  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
01-16 12:02:28.032  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
01-16 12:02:28.034  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
01-16 12:02:28.035  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
01-16 12:02:28.049  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
01-16 12:02:28.051  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
01-16 12:02:28.055  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
01-16 12:02:28.057  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
01-16 12:02:28.070  1656  1677 I ActivityManager: Displayed com.respublica/.MainActivity: +675ms
01-16 12:02:28.075  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
01-16 12:02:28.082  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
01-16 12:02:28.083  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
01-16 12:02:28.085  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
01-16 12:02:28.086  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
01-16 12:02:28.095  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
01-16 12:02:28.101  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
01-16 12:02:28.112  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
01-16 12:02:28.113  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
01-16 12:02:28.114  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
01-16 12:02:28.115  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
01-16 12:02:28.116  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
01-16 12:02:28.126  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
01-16 12:02:28.130  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
01-16 12:02:28.133  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
01-16 12:02:28.134  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
01-16 12:02:28.135  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
01-16 12:02:28.147  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
01-16 12:02:28.152  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
01-16 12:02:28.168  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
01-16 12:02:28.180  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
01-16 12:02:28.183  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
01-16 12:02:28.185  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
01-16 12:02:28.185  4417  4432 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
01-16 12:02:28.235  4417  4432 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-16 12:02:28.251  4417  4432 D ReactNative: Initializing React Xplat Bridge.
01-16 12:02:28.259  4417  4432 D ReactNative: Initializing React Xplat Bridge before initializeBridge
01-16 12:02:28.277  4417  4432 D ReactNative: Initializing React Xplat Bridge after initializeBridge
01-16 12:02:28.277  4417  4432 D ReactNative: CatalystInstanceImpl.runJSBundle()
01-16 12:02:28.286  4417  4437 D ReactNative: ReactInstanceManager.setupReactContext()
01-16 12:02:28.286  4417  4437 D ReactNative: CatalystInstanceImpl.initialize()
01-16 12:02:28.308  4417  4437 D SoLoader: init exiting
01-16 12:02:28.321  1302  1302 W SurfaceFlinger: couldn't log to binary event log: overflow.
01-16 12:02:28.615  4417  4417 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
01-16 12:02:28.615  4417  4417 D SoLoader: About to load: libyoga.so
01-16 12:02:28.616  4417  4417 D SoLoader: libyoga.so not found on /data/data/com.respublica/lib-main
01-16 12:02:28.616  4417  4417 D SoLoader: libyoga.so found on /data/app/com.respublica-1/lib/x86
01-16 12:02:28.616  4417  4417 D SoLoader: Not resolving dependencies for libyoga.so
01-16 12:02:28.616  4417  4417 D SoLoader: Loaded: libyoga.so
01-16 12:02:28.620  4417  4436 I ReactNativeJS: Running application "MainMenuScreen" with appParams: {"initialProps":{"componentId":"Component2"},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
01-16 12:02:28.620  4417  4436 E ReactNativeJS: Application MainMenuScreen has not been registered.
01-16 12:02:28.620  4417  4436 E ReactNativeJS: 
01-16 12:02:28.620  4417  4436 E ReactNativeJS: Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
01-16 12:02:28.620  4417  4436 E ReactNativeJS: If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').
01-16 12:02:28.620  4417  4436 E ReactNativeJS: 
01-16 12:02:28.620  4417  4436 E ReactNativeJS: This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
01-16 12:02:28.620  4417  4436 E ReactNativeJS: 
01-16 12:02:28.630  4417  4437 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-16 12:02:28.630  4417  4437 E AndroidRuntime: Process: com.respublica, PID: 4417
01-16 12:02:28.630  4417  4437 E AndroidRuntime: com.facebook.react.common.JavascriptException: Application MainMenuScreen has not been registered.
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 
01-16 12:02:28.630  4417  4437 E AndroidRuntime: Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
01-16 12:02:28.630  4417  4437 E AndroidRuntime: If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 
01-16 12:02:28.630  4417  4437 E AndroidRuntime: This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 
01-16 12:02:28.630  4417  4437 E AndroidRuntime: , stack:
01-16 12:02:28.630  4417  4437 E AndroidRuntime: runApplication@315:1375
01-16 12:02:28.630  4417  4437 E AndroidRuntime: value@38:3449
01-16 12:02:28.630  4417  4437 E AndroidRuntime: <unknown>@38:960
01-16 12:02:28.630  4417  4437 E AndroidRuntime: value@38:2703
01-16 12:02:28.630  4417  4437 E AndroidRuntime: value@38:932
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
01-16 12:02:28.630  4417  4437 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
01-16 12:02:28.633  1656  2232 W ActivityManager:   Force finishing activity com.respublica/.MainActivity
01-16 12:02:28.686  1302  1941 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 2650112
01-16 12:02:28.748  1656  2054 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.google.android.apps.nexuslauncher:10021?v=0 pkg=com.google.android.googlequicksearchbox } U=0: not found
01-16 12:02:28.806  1352  1377 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
01-16 12:02:28.856  2110  2231 D EGL_emulation: eglMakeCurrent: 0x7ec3fa8928a0: ver 3 0 (tinfo 0x7ec3fc9f00e0)
01-16 12:02:28.868  1656  4337 I OpenGLRenderer: Initialized EGL, version 1.4
01-16 12:02:28.868  1656  4337 D OpenGLRenderer: Swap behavior 1
01-16 12:02:28.869  1656  4337 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
01-16 12:02:28.869  1656  4337 D OpenGLRenderer: Swap behavior 0
01-16 12:02:28.883  1656  4337 D EGL_emulation: eglCreateContext: 0x7ec3e3d93b80: maj 3 min 0 rcv 3
01-16 12:02:28.894  1656  4337 D EGL_emulation: eglMakeCurrent: 0x7ec3e3d93b80: ver 3 0 (tinfo 0x7ec3e3c31d80)
01-16 12:02:28.940  1656  4337 D EGL_emulation: eglMakeCurrent: 0x7ec3e3d93b80: ver 3 0 (tinfo 0x7ec3e3c31d80)
01-16 12:02:28.941  4417  4433 D EGL_emulation: eglMakeCurrent: 0xd8984660: ver 3 0 (tinfo 0xe43f0980)
01-16 12:02:28.963  1656  1664 I art     : Background partial concurrent mark sweep GC freed 53634(2MB) AllocSpace objects, 0(0B) LOS objects, 22% free, 13MB/17MB, paused 764us total 230.321ms
01-16 12:02:28.997  2367  2367 W art     : Long monitor contention with owner GAC_Executor[0] (2805) at boolean mjd.a(mjc, android.content.ServiceConnection, java.lang.String)(:com.google.android.gms@11947480:15) waiters=0 in void mje.onServiceConnected(android.content.ComponentName, android.os.IBinder) for 178ms
01-16 12:02:29.037  1732  1757 I art     : Background partial concurrent mark sweep GC freed 15881(501KB) AllocSpace objects, 1(20KB) LOS objects, 29% free, 9MB/13MB, paused 1.627ms total 117.667ms
01-16 12:02:29.242  1656  1670 I ActivityManager: Killing 3361:com.google.android.talk:matchstick/u0a52 (adj 906): empty #17
01-16 12:02:29.264  4417  4417 D ReactNative: ReactInstanceManager.detachViewFromInstance()
01-16 12:02:29.349  1656  2245 D ActivityManager: cleanUpApplicationRecord -- 3361
01-16 12:02:29.360  2110  2231 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
01-16 12:02:30.593  1352  1378 W audio_hw_generic: Not supplying enough data to HAL, expected position 1886002 , only wrote 1733760
01-16 12:02:48.450  3961  4036 I Babel_ConcService: Stopping service, as no more tasks are running.
```

**Comment by janziemba** [comment]
I have found out what has been causing this issue. The `Component.name` is somehow not recognized in a release version (probably caused by minification) and so the component is not registered as `MainMenuScreen`. It works if I define screen names manually.

```js
const screens = [
    { name: 'GameLevelScreen', component: GameLevelScreen },
    { name: 'GameModeScreen', component: GameModeScreen },
    { name: 'GameScreen', component: GameScreen },
    { name: 'MainMenuScreen', component: MainMenuScreen },
    { name: 'ScoreScreen', component: ScoreScreen },
    { name: 'WelcomeScreen', component: WelcomeScreen },
];

const registerComponent = (item) => {
    const Component = item.component;

    Navigation.registerComponent(item.name, () => props => (
        <ThemeContext.Provider>
            <ErrorBoundary>
                <AppContainer>
                    <Component
                        {...props}
                    />
                </AppContainer>
            </ErrorBoundary>
        </ThemeContext.Provider>
    ), () => Component);
};
```
