### ISSUE TITLE
Android application crashes intermittently if there is a fab on some but not all of the top tabs

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#460]
### Issue Description

I have a single screen application with 3 top tabs. I have a `fab` on two of them. By default screen with a `fab` button is rendered. When I go to a tab which doesn't contain a `fab` button, application crashes with the below call stack

```java
11-19 09:01:51.386 25235-25235/com.xyz E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.xyz, PID: 25235
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.View.getY()' on a null object reference
                                                                   at com.reactnativenavigation.views.FloatingActionButtonCoordinator$ActionBehaviour.calculateY(FloatingActionButtonCoordinator.java:213)
                                                                   at com.reactnativenavigation.views.FloatingActionButtonCoordinator$ActionBehaviour.onDependentViewChanged(FloatingActionButtonCoordinator.java:198)
                                                                   at com.reactnativenavigation.views.FloatingActionButtonCoordinator$ActionBehaviour.onDependentViewChanged(FloatingActionButtonCoordinator.java:179)
                                                                   at android.support.design.widget.CoordinatorLayout.offsetChildToAnchor(CoordinatorLayout.java:1566)
                                                                   at android.support.design.widget.CoordinatorLayout.onChildViewsChanged(CoordinatorLayout.java:1228)
                                                                   at android.support.design.widget.CoordinatorLayout$HierarchyChangeListener.onChildViewRemoved(CoordinatorLayout.java:2868)
                                                                   at android.view.ViewGroup.dispatchViewRemoved(ViewGroup.java:4220)
                                                                   at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4621)
                                                                   at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4576)
                                                                   at android.view.ViewGroup.removeView(ViewGroup.java:4507)
                                                                   at com.reactnativenavigation.views.FloatingActionButtonCoordinator.removeAllViews(FloatingActionButtonCoordinator.java:77)
                                                                   at com.reactnativenavigation.views.FloatingActionButtonCoordinator.access$000(FloatingActionButtonCoordinator.java:25)
                                                                   at com.reactnativenavigation.views.FloatingActionButtonCoordinator$1.onAnimationEnd(FloatingActionButtonCoordinator.java:65)
                                                                   at com.reactnativenavigation.views.FloatingActionButtonAnimator$3.onAnimationEnd(FloatingActionButtonAnimator.java:100)
                                                                   at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1114)
                                                                   at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                                                                   at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                                                                   at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

If I add the `fab` to all of the tabs, then the crash doesn't happen. I saw this crash twice. Then I added the `fab` button to all the tabs and like I mentioned the crash didn't happen. Then I removed the `fab` button from one of the tabs and tried it again and the crash didn't happen this time. So, the crash is intermittent but I definitely saw it a couple of times with the above call stack before it disappeared with no apparent code change. So, I just wanted to share the call stack with you guys in case it rings any bells.

### Environment
* React Native Navigation version: 2.0.0.experimental.141 including the commit to fix fab
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug Simulator

**Comment by guyca** [comment]
I didn't encounter this when testing the fab fix commit... will have to check this further

**Comment by guyca** [comment]
@varungupta85 Any updates regarding this one? I checked again today an weren't able to reproduce the issue

**Comment by varungupta85** [comment]
@guyca I didn't see the crash today. I am not sure what caused the crashed earlier. I am closing it. I will reopen if I encounter the issue again. Thanks!
