### ISSUE TITLE
pop stack NullPointerException

### ISSUE THREAD

**Issue by swabbass** [wix/react-native-navigation#4694]
### Issue Description

crash on Null pointer exception when pop called

### Steps to Reproduce / Code Snippets / Screenshots

the flow that mostly this issue occurs like follows:
1- open modal
2- close modal and push a view
3- showing something like progress dialog (over the pushed view)
4- after the dialog dismissed pop the view 

exception stack trace:
```JAVA
 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.ViewController.onViewWillAppear()' on a null object reference
        at com.reactnativenavigation.viewcontrollers.stack.StackController.pop(StackController.java:248)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$pop$2(Navigator.java:162)
        at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$snu0zowFhpNNrG6DTlYojmpj2RE.run(Unknown Source:6)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$applyOnStack$5(Navigator.java:221)
        at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$BztKRmJef9zlTqPlTta6T7nWHGw.run(Unknown Source:2)
        at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentStack(ViewController.java:145)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.applyOnStack(Navigator.java:221)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.pop(Navigator.java:162)
        at com.reactnativenavigation.react.NavigationModule.lambda$pop$6(NavigationModule.java:107)
        at com.reactnativenavigation.react.-$$Lambda$NavigationModule$-Ih4m-qT9jnEZhcJhxie3zjjHTs.run(Unknown Source:10)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

---
### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.508
* Platform(s) (iOS, Android, or both?): Android 9 (Not tested on ios)
* Device info (Simulator/Device? OS version? Debug/Release?):device Pixel 3xl android 9 debug

**Comment by aminosman** [comment]
Any updates on this?

**Comment by andreek** [comment]
I got this exception in an app, if push or showModal functions are called multiple times before pop. It was possible to touch buttons multiple times without locking the handler. After preventing button handlers to execute multiple push/showModal for the same screen this error seems to be gone.

**Comment by dgobaud** [comment]
we're seeing this too unfortunately little info on where / what is causing it. error comes into sentry with no breadcrumbs :(

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.ViewController.onViewWillAppear()' on a null object reference
    at com.reactnativenavigation.viewcontrollers.stack.StackController.pop(StackController.java:256)
    at com.reactnativenavigation.viewcontrollers.stack.StackController.handleBack(StackController.java:335)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.handleBack(Navigator.java:103)
    at com.reactnativenavigation.NavigationActivity.invokeDefaultOnBackPressed(NavigationActivity.java:80)
    at com.facebook.react.ReactInstanceManager.invokeDefaultOnBackPressed(ReactInstanceManager.java:449)
    at com.facebook.react.ReactInstanceManager.access$000(ReactInstanceManager.java:125)
    at com.facebook.react.ReactInstanceManager$1.invokeDefaultOnBackPressed(ReactInstanceManager.java:254)
    at com.facebook.react.modules.core.DeviceEventManagerModule$1.run(DeviceEventManagerModule.java:40)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6592)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

```
Family | XT1635-02
-- | --
Model | XT1635-02 (OPNS27.76-12-22-9)
Architecture | armeabi-v7a
Battery Level | 58%
Orientation | portrait
Memory | Total: 2.8 GB / Free: 739.1 MB
Capacity | Total: 23.9 GB / Free: 13.0 GB
Simulator | False
brand | motorola
charging | False
low_memory | False
manufacturer | motorola
online | True
screen_density | 2.55
screen_dpi | 408
screen_resolution | 1798x1080
```

**Comment by thebylito** [comment]
see https://github.com/wix/react-native-navigation/issues/3981

**Comment by dgobaud** [comment]
in #5688 posted many more instances of same type of crash with patch file we're using that I fear stops the crash but probably leaves app not working...

**Comment by guyca** [comment]
Closing as the particular flow reported in this issue seems to be fixed by now.
