### ISSUE TITLE
[V2] Installed app with bottom tabs crashes on startup

### ISSUE THREAD

**Issue by holparb** [wix/react-native-navigation#4724]
### Issue Description

The app runs without problems when run with the react-native cli using `react-native run-android`.
**However when starting the already installed app on the phone (not with the react-native cli) the app crashes with the following NullPointerException**:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable.mutate()' on a null object reference
        at com.aurelhubert.ahbottomnavigation.AHHelper.getTintDrawable(AHHelper.java:36)
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createSmallItems(AHBottomNavigation.java:584)
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(AHBottomNavigation.java:292)
        at com.reactnativenavigation.views.BottomTabs.superCreateItems(BottomTabs.java:48)
        at com.reactnativenavigation.views.BottomTabs.createItems(BottomTabs.java:36)
        at com.reactnativenavigation.views.BottomTabs.enableItemsCreation(BottomTabs.java:24)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:91)
        at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:204)
        at com.reactnativenavigation.viewcontrollers.ChildController.onViewAppeared(ChildController.java:34)
        at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:257)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2273)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1421)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6842)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6699)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

### Steps to Reproduce / Code Snippets / Screenshots

The bottom tab navigation is set up this way:

```
root: {
        bottomTabs: {
            children: [{
                stack: {
                    children: [{
                        component: {
                            name: "Tab1",
                            passProps: {
                                text: "Tab1"
                            }
                        } 
                    }],
                    options: {
                        bottomTab: {
                            text: "Tab1",
                            icon: require("../../assets/icons/dummy_icon.png"),
                            testID: "TAB_1"
                        }
                    }
                }
            },
            {
                stack: {
                    children: [{
                        component: {
                            name: "Tab2",
                            passProps: {
                                text: "Tab2"
                            }
                        } 
                    }],
                    options: {
                        bottomTab: {
                            text: "Tab2",
                            icon: require("../../assets/icons/dummy_icon.png"),
                            testID: "TAB_2"
                        }
                    }
                }
            },
            {
                stack: {
                    children: [{
                        component: {
                            name: "Tab3",
                            passProps: {
                                text: "Tab3"
                            }
                        } 
                    }],
                    options: {
                        bottomTab: {
                            text: "Tab3",
                            icon: require("../../assets/icons/dummy_icon.png"),
                            testID: "TAB_3"
                        }
                    }
                }
            }]
        }
    }
```
I tried clearing the npm cache and also cleaning and rebuilding the project but the issue still persists.

---
### Environment
* React Native Navigation version: 2.11.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Xiaomi Mi6 Android 8.0

**Comment by guyca** [comment]
Hey @holparb, can you try reproducing this in the playground app?

**Comment by holparb** [comment]
Hi @guyca , I'll try reproducing in the playground app.
I only tested this on my own phone, haven't run it on any other Android devices yet.

**Comment by JohnnyDevX** [comment]
same here! It worked before but now crashes with rn 0.58

**Comment by sii2jeng** [comment]
I got the same issue, the bottom tabs are crashes with rn 0.58

**Comment by guyca** [comment]
@holparb Don't clone `v2` branch, use master: `git clone git@github.com:wix/react-native-navigation.git`

**Comment by opiruyan** [comment]
**imageLoader.loadIcon(**) is called with url to **localhost:8081**.
 But when you install apk on a device there is no Bundler running which produces crash

**Comment by holparb** [comment]
> @holparb Don't clone `v2` branch, use master: `git clone git@github.com:wix/react-native-navigation.git`

@guyca I tried with master as well, `install-android` still fails:

```
cd playground/android && ./gradlew installDebug
'.' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:640
    throw err;
    ^

Error: Command failed: cd playground/android && ./gradlew installDebug
    at checkExecSyncError (child_process.js:600:11)
    at Object.execSync (child_process.js:637:13)
    at Object.execSync (D:\Development\ReactNative\rnn-test\react-native-navigat
ion\node_modules\shell-utils\src\exec.js:8:6)
    at run (D:\Development\ReactNative\rnn-test\react-native-navigation\scripts\
install-android.js:9:8)
    at Object.<anonymous> (D:\Development\ReactNative\rnn-test\react-native-navi
gation\scripts\install-android.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
Pretty sure it's me doing something wrong, should I be running a different script for Android perhaps...?

**Comment by guyca** [comment]
Well, I would suggest opening the project (playground/android) with Android Studio.

```
cd playground/android
./graldew app:assembleDebug
install the apk
```

**Comment by holparb** [comment]
> Well, I would suggest opening the project (playground/android) with Android Studio.
> 
> ```
> cd playground/android
> ./graldew app:assembleDebug
> install the apk
> ```

Thanks for the suggestion @guyca , I managed to install the Playground app.

I checked the "Tab based app" in the installed app and it crashes with the same exception as in my project, it seems to be a general issue.

**Comment by opiruyan** [comment]
@holparb 
could you check if you have preceding java.io.FileNotFoundException?

**Comment by holparb** [comment]
There's no FileNotFoundException prior to the NullPointerException, however I have this warning, could be related although I'm not sure:

```
com.reactnativenavigation.playground W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at java.net.URL.openStream(URL.java:1059)
        at com.reactnativenavigation.utils.ImageLoader.remoteUrl(ImageLoader.java:124)
        at com.reactnativenavigation.utils.ImageLoader.openStream(ImageLoader.java:120)
        at com.reactnativenavigation.utils.ImageLoader.readJsDevImage(ImageLoader.java:85)
        at com.reactnativenavigation.utils.ImageLoader.getDrawable(ImageLoader.java:75)
        at com.reactnativenavigation.utils.ImageLoader.loadIcon(ImageLoader.java:38)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.lambda$createTabs$3(BottomTabsController.java:155)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.-$$Lambda$BottomTabsController$hVDDSxSvqNX-4DhQHls8ynB4x2w.map(Unknown Source:4)
        at com.reactnativenavigation.utils.CollectionUtils.map(CollectionUtils.java:42)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.createTabs(BottomTabsController.java:151)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.createView(BottomTabsController.java:75)
        at com.reactnativenavigation.viewcontrollers.ViewController.getView(ViewController.java:163)
        at com.reactnativenavigation.viewcontrollers.ParentController.getView(ParentController.java:60)
        at com.reactnativenavigation.viewcontrollers.navigator.RootPresenter.setRoot(RootPresenter.java:29)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.setRoot(Navigator.java:133)
        at com.reactnativenavigation.react.NavigationModule.lambda$setRoot$1(NavigationModule.java:70)
        at com.reactnativenavigation.react.-$$Lambda$NavigationModule$IfiDeOnYfgJADKZUxIVN9Zforsw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6699)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

**Comment by opiruyan** [comment]
@holparb 
It is absolutely related. Cos its still **ImageLoader.loadIcon()** method which leads to the exception.
Basically you are setting TintColor on null - the image which wasn't found.

**Comment by holparb** [comment]
@opiruyan 
So practically the image needs to be loaded by Uri, this cannot be done due to some connection issue and it will be null?

By the way, here are the connection warnings from before:

```
com.reactnativenavigation.playground W/System.err:     at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
```

```
com.reactnativenavigation.playground W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
```

**Comment by opiruyan** [comment]
@holparb 
Depends. When bundler is running RNN tries to fetch it from there.
Otherwise its looking for static image.  The issue is how RNN resolves the way of looking for the image.

**Comment by WASHSWATDAVID** [comment]
+1

**Comment by holparb** [comment]
@guyca maybe you have also a good overview of the image resolving mechanism and how to fix this?
Although I'm not an expert but if we could locate where this issue is in the RNN logic I could also try fixing it.

**Comment by varungupta85** [comment]
@holparb I am using the bottom tabs in my Android app. I was looking at the root configuration and I think the options are not defined at the right place for each bottom tab. The `options` should be a part of the component configuration. For e.g., the first children should look like

```javascript
                  stack: {
                    children: [{
                        component: {
                            name: "Tab1",
                            passProps: {
                                text: "Tab1"
                            },
                            options: {
                              bottomTab: {
                                  text: "Tab1",
                                  icon: require("../../assets/icons/dummy_icon.png"),
                                  testID: "TAB_1"
                              }
                          }
                        } 
                    }]
                  }
```

I am not sure if options could be defined in multiple ways but that is how I have it.

**Comment by opiruyan** [comment]
@varungupta85 But does this order fix the issue? Im afraid it doesn't. Cos I have a kind of configuration you present. And I guess original playground app by wix has right configuration as well but it still crashes.

**Comment by holparb** [comment]
@varungupta85  I agree with @opiruyan , based on the error logs the configuration order is not the cause of the issue, and if you check the BottomTabs documentation the example there also specifies the options in the same way as my example in the issue description does.

**Comment by opiruyan** [comment]
@holparb I did some. 
All happens in this method
```java
private Drawable getDrawable(Context context, String source) throws IOException {
        if (isLocalFile(...)) {
            drawable = loadFile(source);
        } else {
        <...>
                drawable = readJsDevImage(context, source);
            }
        <...>
    }
```
**isLocalFile()** takes uri of image
```java
private boolean isLocalFile(Uri uri) {
        return FILE_SCHEME.equals(uri.getScheme());
    }
```
and compares it to FILE_SCHEME, which hardcoded to be 
```java
private static final String FILE_SCHEME = "file";
```
**readJsDevImage()** in its turn calls openStream() method which also compares to hardcoded string:
```java
private static InputStream openStream(Context context, String uri) throws IOException {
        return uri.contains("http") ? remoteUrl(uri) : localFile(context, uri);
    }
```

SO, the question is _uri_ we get which is _String source_ in  **getDrawable**:
```java
private Drawable getDrawable(Context context, String source)
There are scenarios when it resolved to be _http://<smth>_ but its not

**Comment by varungupta85** [comment]
@holparb @opiruyan Surprisingly I also ran into this problem on the emulator when I was trying to test my app in offline mode i.e. without any network connection. Are you guys also observing it when the emulator has no internet connection? It works fine when there is internet connection.

Are you guys also observing it when there is no internet connection?

**Comment by medelman17** [comment]
I'm basically observing it in all cases. Meaning, I start a new project, it builds and runs fine on emulator, I immediately install react-native-navigation and configure as described in docs, it appears to build fine, but crashes immediately on load. No hit to my bundler.

**Comment by holparb** [comment]
@opiruyan 
You followed the thread pretty well. But like you I really wonder why the Uri is getting to be http://... format instead of a string of a local path...? @guyca do you have an idea where this behavior could come from?

@varungupta85 I'm not sure internet connection has anything to do with it, for me it crashes regardles of connection both for my own and the playground app.

**Comment by holparb** [comment]
Any updates on this topic?
@guyca  
It's also strange that relatively few people indicated to have this issue, could it be RNN or RN version related?

**Comment by frederickalcantara** [comment]
Following this thread because I am dealing what a similar issue.

**Comment by guyca** [comment]
@holparb Which RNN versions are you using?

**Comment by frederickalcantara** [comment]
@guyca Here are the versions that I am using:

**Comment by holparb** [comment]
@guyca 2.11

**Comment by charpeni** [comment]
We had the exact same crash in our Android app with RNN 2.8.

We use Bottom Tabs with icons specified by uri, and the crash happened when the resource was not found even if it should.

After an investigation, the issue was located here:

https://github.com/wix/react-native-navigation/blob/b422dd0761183edc5f6e5006ba5d5e9b06b9561b/lib/android/app/src/main/java/com/reactnativenavigation/utils/ImageLoader.java#L70-L77

It was not a local file, so we load the resource, but then it was overridden by `readJsDevImage`.

Fixed by @guyca in #4769, I'd recommend you retry with RNN 2.13.

**Comment by FTD-ZF** [comment]
I've tried, and if I use the release package, the problem won't happen

**Comment by MakhouT** [comment]
I am having this exact issue. 
I am on RNN version 2.20
and on RN 0.59.8

Has this been fixed?

I am importing my images in the tabs as so:

`icon: require("./home.png"),`

**Comment by MakhouT** [comment]
When the bundler is connected all is working as expected. But without the bundler the app crashes on startup

**Comment by MakhouT** [comment]
Link to repo to reproduce this
https://github.com/MakhouT/herro

**Comment by MakhouT** [comment]
I just tried on the playground app. Same result. Let me know if you need something from my side. Do we reopen it or do I create a new issue?

**Comment by MakhouT** [comment]
Looked more into it and it isn't a RNN issue!
It's android itself!

See this for the fix: https://github.com/facebook/react-native/issues/22076#issuecomment-484981830

**Comment by saisaran96** [comment]
I had this same issue I solved it by using 
icon : {
uri: 'URI_of_the_Icon'  
}
 put your png file in all the drawable folders inside  android\app\src\main\res

**Comment by muhammadwafa** [comment]
Same issue here with react-native 0.61.5
