### ISSUE TITLE
[v2] Android The key must be an application-specific resource id.

### ISSUE THREAD

**Issue by saleksandras** [wix/react-native-navigation#4812]
### Issue Description

Android app crash on setting testID of BottomTab.

Android log:
```
java.lang.IllegalArgumentException: The key must be an application-specific resource id.
03-03 19:38:32.875 14063 14063 E AndroidRuntime:     at android.view.View.setTag(View.java:19661)
03-03 19:38:32.875 14063 14063 E AndroidRuntime:     at com.reactnativenavigation.presentation.BottomTabPresenter.applyOptions(BottomTabPresenter.java:57)
03-03 19:38:32.875 14063 14063 E AndroidRuntime:     at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:90)
...
```

Error line in code:

https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabPresenter.java#L57

This issue was introduce with this commit:
https://github.com/wix/react-native-navigation/commit/bfdd41fcb4a3f9cd95fa29828d8dc0b7d2450404#diff-fe7845e05fe8da4f48d10c4da23403e5

### Code Snippets

```js
Navigation.setRoot({
  root: {
    bottomTabs: {
        children: [
          {
            stack: {
              children: [
                {
                  component: {
                    name: COMPONENT,
                  },
                },
              ],
              options: {
                bottomTab: {
                  text: 'Tab name',
                  testID: 'TAB_ID',
                  icon: tabIcon,
                },
              },
            },
          },
        ]
      }
    }
});
```

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.56.0 - 0.58.6
* Platform(s) (iOS, Android, or both?): Android

**Comment by minhtrungaa** [comment]
Just update the version few minutes ago, this happens.

**Comment by stockrel** [comment]
+1, seems to happen also when not setting any testID for bottomTabs

**Comment by holparb** [comment]
Happens to me as well with testIDs defined for tabs.
Issue is not present in  RNN v2.11, but is there in v2.13.1.

**Comment by charpeni** [comment]
cc @guyca

**Comment by NweThazin** [comment]
I also encounter this issue on RNN version "^2.13.1".
thanks

**Comment by djnsu** [comment]
same here

**Comment by skumarcm** [comment]
I am facing the same issue with version 2.14.0 as well.

**Comment by jinshin1013** [comment]
This is blocking few people to upgrade to the latest version of RNN. If anyone could make a PR, that'd be so helpful.

**Comment by guyca** [comment]
Hey guys, I'm was unable to reproduce this crash in the playground app. Could anyone post a root declaration which crashes in the playground app?

**Comment by Oguntoye** [comment]
> Hey guys, I'm was unable to reproduce this crash in the playground app. Could anyone post a root declaration which crashes in the playground app?

2019-03-24 12:24:29.001 6079-6079/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wizlinkerapp, PID: 6079
    java.lang.IllegalArgumentException: The key must be an application-specific resource id.
        at android.view.View.setTag(View.java:19478)
        at com.reactnativenavigation.presentation.BottomTabPresenter.applyOptions(BottomTabPresenter.java:57)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:90)
        at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:206)
        at com.reactnativenavigation.viewcontrollers.ChildController.onViewAppeared(ChildController.java:34)
        at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:259)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2107)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
2019-03-24 12:24:29.318 6

**Comment by Oguntoye** [comment]
> ```js
> testID: 'TAB_ID',
> ```

i discovered a fix for now.
The fix for now is to downgrade to 2.11.0

npm install --save react-native-navigation@2.11.0

**Comment by trungthanhnt** [comment]
You can fix by comment this line:  bottomTabs.setTag(i, tab.testId.get(null)); 
in this file:line  (BottomTabPresenter.java:57)

**Comment by jinshin1013** [comment]
It's really weird, I just tried the same configuration on the playground app, but everything seems to be working fine. We must be missing something here.
