### ISSUE TITLE
ConcurrentModificationException in Android

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [wix/react-native-navigation#484]
### Issue Description

In android when I attempt to reload I get ConcurrentModificationException. There is no pattern to it, it is random and intermittent. 

### Steps to Reproduce / Code Snippets / Screenshots

I got two exceptions with different stack traces. 

```
11-22 15:02:15.903 27298-27298/xyz.diceapp.dice E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: xyz.diceapp.dice, PID: 27298
                                                                  java.util.ConcurrentModificationException
                                                                      at java.util.AbstractList$SimpleListIterator.next(AbstractList.java:62)
                                                                      at com.reactnativenavigation.events.EventBus.post(EventBus.java:32)
                                                                      at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl$1.onJsDevReload(NavigationReactGateway.java:140)
                                                                      at com.reactnativenavigation.react.JsDevReloadListenerReplacer$DevCommandsHandlerProxy.onReloadWithJSDebugger(JsDevReloadListenerReplacer.java:54)
                                                                      at com.facebook.react.devsupport.DevSupportManagerImpl.reloadJSInProxyMode(DevSupportManagerImpl.java:720)
                                                                      at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:647)
                                                                      at com.facebook.react.devsupport.RedBoxDialog$3.onClick(RedBoxDialog.java:282)
                                                                      at android.view.View.performClick(View.java:5198)
                                                                      at android.view.View$PerformClick.run(View.java:21147)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```
One more 
```

11-22 21:53:09.748 13005-13005/xyz.diceapp.dice E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
11-22 21:53:09.749 13005-13005/xyz.diceapp.dice E/MessageQueue-JNI: java.util.ConcurrentModificationException
                                                                        at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                        at com.reactnativenavigation.events.EventBus.post(EventBus.java:30)
                                                                        at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl$1.onJsDevReload(NavigationReactGateway.java:140)
                                                                        at com.reactnativenavigation.react.JsDevReloadListenerReplacer$DevCommandsHandlerProxy.onReloadWithJSDebugger(JsDevReloadListenerReplacer.java:54)
                                                                        at com.facebook.react.devsupport.DevSupportManagerImpl.reloadJSInProxyMode(DevSupportManagerImpl.java:720)
                                                                        at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:647)
                                                                        at com.reactnativenavigation.react.JsDevReloadHandler.onKeyUp(JsDevReloadHandler.java:30)
                                                                        at com.reactnativenavigation.controllers.NavigationActivity.onKeyUp(NavigationActivity.java:171)
                                                                        at android.view.KeyEvent.dispatch(KeyEvent.java:2664)
                                                                        at android.app.Activity.dispatchKeyEvent(Activity.java:2730)
                                                                        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:547)
                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:57)
                                                                        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:315)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4127)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4089)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3820)
                                                                        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3981)
                                                                        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
                                                                        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
                                                                        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
                                                                        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
                                                                        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                        at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                        at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```
---
### Environment
* React Native Navigation version:  2.0.0-experimental.142
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device Debug

**Comment by guyca** [comment]
Any additional info you can provide? We weren't able to reproduce this in various configurations.

**Comment by chaitanya0bhagvan** [comment]
This is happening on repeated reloads and hot reloads. As I mentioned initially it is random. I will be on the look out for any pattern that would be of help.

**Comment by guyca** [comment]
Try disabling hot reload and see if it reoccurs. We don't use hot reload...

**Comment by tafty** [comment]
I've been experiencing this issue consistently. I've patched up the register, unregister and subscribe methods of `events\EventBus.java` by wrapping their contents in:

```java
  synchronized(subscribers) {
    ...
  }
```

This isn't an ideal fix but it is allowing me to continue work for now.

**Comment by guyca** [comment]
@tafty What version of rnn are you using?

**Comment by tafty** [comment]
We're currently on 1.1.3. We're looking to update to latest so I'll update again once we have...

**Comment by guyca** [comment]
I asked because #1103 should have fixed this bug

**Comment by tafty** [comment]
It looks as though it did - thanks for your responses and apologies for the false alarm.

**Comment by guyca** [comment]
No worries 👍
