### ISSUE TITLE
"Aapt2Exception: Android resource linking failed" with React Native 0.59

### ISSUE THREAD

**Issue by Flavien** [wix/react-native-navigation#4859]
### Issue Description

I am getting the following build error when upgrading to RN 0.59:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:verifyReactNative57ReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values/values.xml:3058: error: resource android:attr/fontVariationSettings not found.
  /Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values/values.xml:3059: error: resource android:attr/ttcIndex not found.
  error: failed linking references.


* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-navigation:verifyReactNative57ReleaseResources'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.UncheckedException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values/values.xml:3058: error: resource android:attr/fontVariationSettings not found.
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values/values.xml:3059: error: resource android:attr/ttcIndex not found.
error: failed linking references.

	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 31 more
Caused by: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values/values.xml:3058: error: resource android:attr/fontVariationSettings not found.
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values/values.xml:3059: error: resource android:attr/ttcIndex not found.
error: failed linking references.

	at com.android.ide.common.workers.ExecutorServiceAdapter.close(ExecutorServiceAdapter.kt:56)
	at kotlin.io.CloseableKt.closeFinally(Closeable.kt:53)
	at com.android.build.gradle.tasks.VerifyLibraryResourcesTask.compileAndVerifyResources(VerifyLibraryResourcesTask.kt:130)
	at com.android.build.gradle.tasks.VerifyLibraryResourcesTask.doFullTaskAction(VerifyLibraryResourcesTask.kt:110)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 42 more
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values/values.xml:3058: error: resource android:attr/fontVariationSettings not found.
/Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative57/release/values/values.xml:3059: error: resource android:attr/ttcIndex not found.
error: failed linking references.

	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create(Aapt2Exception.kt:45)
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create$default(Aapt2Exception.kt:39)
	at com.android.builder.internal.aapt.v2.Aapt2DaemonImpl.doLink(Aapt2DaemonImpl.kt:188)
	at com.android.builder.internal.aapt.v2.Aapt2Daemon.link(Aapt2Daemon.kt:103)
	at com.android.builder.internal.aapt.v2.Aapt2DaemonManager$LeasedAaptDaemon.link(Aapt2DaemonManager.kt:176)
	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:839)
	at com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable$run$1.invoke(Aapt2ProcessResourcesRunnable.kt:34)
	at com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable$run$1.invoke(Aapt2ProcessResourcesRunnable.kt:28)
	at com.android.build.gradle.internal.res.namespaced.Aapt2DaemonManagerService.useAaptDaemon(Aapt2DaemonManagerService.kt:71)
	at com.android.build.gradle.internal.res.namespaced.Aapt2DaemonManagerService.useAaptDaemon$default(Aapt2DaemonManagerService.kt:69)
	at com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable.run(Aapt2ProcessResourcesRunnable.kt:33)
	at com.android.ide.common.workers.ExecutorServiceAdapter$submit$submission$1.run(ExecutorServiceAdapter.kt:39)
	... 48 more


* Get more help at https://help.gradle.org

BUILD FAILED in 5m 1s
281 actionable tasks: 281 executed
AAPT2 aapt2-3.3.1-5013011-osx Daemon #0: shutdown
AAPT2 aapt2-3.3.1-5013011-osx Daemon #1: shutdown
AAPT2 aapt2-3.3.1-5013011-osx Daemon #2: shutdown
Error: /Users/vsts/agent/2.148.0/work/1/s/trezeo-mobile/android/gradlew failed with return code: 1
    at ChildProcess.<anonymous> (/Users/vsts/agent/2.148.0/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.148.0/node_modules/vsts-task-lib/toolrunner.js:639:25)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
```

### Steps to Reproduce / Code Snippets / Screenshots

Running a release build (`assembleRelease`).

This is the versions I am using:

```
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }
```

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.59.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Release build

**Comment by crobinson42** [comment]
@Flavien any luck on this? I'm running into the same when upgrading to react-native 0.59

**Comment by zazagag** [comment]
the same

**Comment by Andarius** [comment]
Any update on this ?

**Comment by Flavien** [comment]
@guyca Has RNN been tested with React Native 0.59?

**Comment by Andarius** [comment]
After upgrading to the last version of RNN and putting `missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5"  and android/app/src/build.gradle` seems to work
