### ISSUE TITLE
The key must be an application-specific resource id. 

### ISSUE THREAD

**Issue by Oguntoye** [wix/react-native-navigation#4905]
### Issue Description

[The key must be an application-specific resource id. ]

### Steps to Reproduce / Code Snippets / Screenshots

FATAL EXCEPTION: main
    Process: com.wizlinkerapp, PID: 16564
    java.lang.IllegalArgumentException: The key must be an application-specific resource id.
        at android.view.View.setTag(View.java:19478)
        at com.reactnativenavigation.presentation.BottomTabPresenter.applyOptions(BottomTabPresenter.java:57)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:90)
        at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:206)
        at com.reactnativenavigation.viewcontrollers.ChildController.onViewAppeared(ChildController.java:34)
        at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:259)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2107)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by Oguntoye** [comment]
i discovered a fix for now.
The fix for now is to downgrade to 2.11.0

npm install --save react-native-navigation@2.11.0

**Comment by sorin-f-wiredelta** [comment]
#4812
