### ISSUE TITLE
[v2] Android. Crash on Navigation.dismissModal

### ISSUE THREAD

**Issue by loga4** [wix/react-native-navigation#5087]
### Issue Description

Crash application on Android on Navigation.dismissAllModals() or Navigation.dismissModal(this.props.componentId);

### Steps to Reproduce / Code Snippets / Screenshots
open modal
```
Navigation.showModal({
            component: {
                name: 'MediaPlayer',
                passProps: {
                    media_format: media_format,
                    media_path: media_path,
                },
                options: {
                    statusBar: {visible:false},
                    topBar: {visible:false}
                }
            }
        });
```

when try to close via Navigation.dismissAllModals()
```java
05-09 02:42:04.837 28898-28898/com.storiesgain E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.storiesgain, PID: 28898
    java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setTitleInactiveTextSizeInSp(AHBottomNavigation.java:1184)
        at com.reactnativenavigation.presentation.BottomTabPresenter.applyOptions(BottomTabPresenter.java:55)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:90)
        at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:208)
        at com.reactnativenavigation.viewcontrollers.ChildController.onViewAppeared(ChildController.java:34)
        at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:261)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2273)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1318)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6728)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:802)
        at android.view.Choreographer.doCallbacks(Choreographer.java:605)
        at android.view.Choreographer.doFrame(Choreographer.java:574)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:788)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5898)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
```

---
### Environment
* React Native Navigation version: 2.18.5
* React Native version: 0.57
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): simulator && device, debug and release

**Comment by loga4** [comment]
dublicate https://github.com/wix/react-native-navigation/issues/4921
