### ISSUE TITLE
[V2]Android NPException thrown in various navigation events

### ISSUE THREAD

**Issue by samratshekhar** [wix/react-native-navigation#5093]
So far, the exceptions have been thrown in:
- dismissModal
- dismiaaAllModals
- mergeOptions
- setDefaultOptions

### Steps to Reproduce / Code Snippets / Screenshots
Crash random in nature. Attaching few crash logs:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.f.e.j com.reactnativenavigation.NavigationActivity.o()' on a null object reference
       at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:157)
       at com.reactnativenavigation.react.NavigationModule.lambda$dismissAllModals$11(NavigationModule.java:139)
       at com.reactnativenavigation.react.g.run(g.java:8)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.f.e.j com.reactnativenavigation.NavigationActivity.o()' on a null object reference
       at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:157)
       at com.reactnativenavigation.react.NavigationModule.lambda$dismissModal$10(NavigationModule.java:132)
       at com.reactnativenavigation.react.l.run(l.java:10)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.f.e.j com.reactnativenavigation.NavigationActivity.o()' on a null object reference
       at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:157)
       at com.reactnativenavigation.react.NavigationModule.lambda$mergeOptions$3(NavigationModule.java:81)
       at com.reactnativenavigation.react.o.run(o.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.f.e.j com.reactnativenavigation.NavigationActivity.o()' on a null object reference
       at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:157)
       at com.reactnativenavigation.react.NavigationModule.lambda$setDefaultOptions$2(NavigationModule.java:76)
       at com.reactnativenavigation.react.h.run(h.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6946)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```
---
### Environment
* React Native Navigation version: v2.13.1
* React Native version: v0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Android 4/6/8, Release

**Comment by samratshekhar** [comment]
Upon closer inspection of native code, it seems that the crash originates from `navigator()` which in turn calls `activity().getNavigator()` in `NavigationModule.java`. 
Odd thing about this crash is that all such calls are guarded by `handle` which checks for nullability of `activity()`
@guyca this crash is rampant ever since we upgraded to V2. Will appreciate any insights on how to mitigate it.

**Comment by guyca** [comment]
Hey @samratshekhar 
Thanks for reporting, I'll need more info in order for me to able to help you. Could you please add a reproduction? Thanks.

**Comment by samratshekhar** [comment]
We haven't been able to reproduce this crash in-house. But will add few instrumentations in our release app and will update with the info here.
