### ISSUE TITLE
App Crash when trying to push to a new screen while using bottomTabs

### ISSUE THREAD

**Issue by Nextt1** [wix/react-native-navigation#5183]
### Issue Description

I have a stack view with bottom tabs and when I try to push to a new screen from my initial/first tab, the app keeps crashing.  I have registered the screen and it works when I put the same button in the 2nd tab screen.

### Steps to Reproduce / Code Snippets / Screenshots

```
onPress = () => {
        Navigation.push(this.props.componentId, {
            component:{
                name: "NewScreen"
            }
        })
    }

<Button title="GOTO" onPress={this.onPress} />
```

I am getting the following error.
`java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setTitleInactiveTextSizeInSp(AHBottomNavigation.java:1184)
        at com.reactnativenavigation.presentation.BottomTabPresenter.applyOptions(BottomTabPresenter.java:55)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:90)
        at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:208)
        at com.reactnativenavigation.viewcontrollers.ChildController.onViewAppeared(ChildController.java:34)
        at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:261)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2357)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`

---
### Environment
* React Native Navigation version: 2.20.2
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android Virtual Machine
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

UPDATE
 Now, push is not working from any other tabs for the same screen.

**Comment by fedu44** [comment]
same to me

**Comment by Nextt1** [comment]
@ItsNoHax  I believe It's not working. The app is crashing. I read the documentation and followed everything mentioned but not helpful. If this thing doesn't work I don't see a point using this library since I'm using bottomButtons for navigation in my app
