### ISSUE TITLE
Java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator on a null object reference

### ISSUE THREAD

**Issue by vikassahutech** [wix/react-native-navigation#5264]
### Issue Description

App is crashing when user is navigating from login to search screen and user taps on device's home button

### Steps to Reproduce / Code Snippets / Screenshots
App going from foreground to background 

Crash Report
```
/com.abcd E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.abcd, PID: 4106
java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference
at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:157)
at com.reactnativenavigation.react.NavigationModule.lambda$setDefaultOptions$2(NavigationModule.java:76)
at com.reactnativenavigation.react.-$$Lambda$NavigationModule$NGh1jOPsjVaJFuXpmhvZ2fRZu-M.run(lambda)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Code Snippet 
1. To initiate navigation  - 
```
Navigation.setRoot({
        root: {
            stack: {
                id: Stackid.authentication,
                children: [
                    {
                        component: {
                            name: ScreenId.LoginScreen,  
                        },
                    },
                ],  
                options: {
                    topBar: {
                        drawBehind: true,
                        visible: false,
                        animate: false,
                    },
                    statusBar: {
                        visible: true,
                        // backgroundColor: '#412F52',
                        drawBehind: false,
                        style: "light" //Or dark
                    },
                }
            }
        }
    })
```

2. Calling next screen (Crash happens in below line of code)
```
Navigation.push(Stackid.authentication, {
                        component: {
                          name: ScreenId.SearchScreen,
                          options: {
                            statusBar: {
                              visible: true,
                              backgroundColor: this.props.customeTheme.primaryBrandColor,
                              drawBehind: false,
                            },
                          }
                        }
                      })
```

---
### Environment

* React Native version: "0.56.0"
* Platform(s) (iOS, Android, or both?): Android
* React Native Navigation version: 2.3.0
* Device info (Simulator/Device? OS version? Debug/Release?): Device | Nexus 5 | Android 6.0.1

**Comment by donkasun** [comment]
Any solution ?

**Comment by vikassahutech** [comment]
No yet.

**Comment by ridik1803** [comment]
Any solution ?
