### ISSUE TITLE
[v2.26.1] The app will run and shut down immediately on the screen where navigation has been implemented.

### ISSUE THREAD

**Issue by wonjong85** [wix/react-native-navigation#5331]
### Issue Description

java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable.mutate()' on a null object reference
        at com.aurelhubert.ahbottomnavigation.AHHelper.getTintDrawable(AHHelper.java:48)
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createSmallItems(AHBottomNavigation.java:568)
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(AHBottomNavigation.java:295)
        at com.reactnativenavigation.views.BottomTabs.superCreateItems(BottomTabs.java:46)
        at com.reactnativenavigation.views.BottomTabs.createItems(BottomTabs.java:34)
        at com.reactnativenavigation.views.BottomTabs.enableItemsCreation(BottomTabs.java:23)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:91)
        at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:208)
        at com.reactnativenavigation.viewcontrollers.ChildController.onViewAppeared(ChildController.java:34)
        at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:261)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2357)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Steps to Reproduce / Code Snippets / Screenshots

```
1. Launch App.
2. Navigation Implemented Screen.
3. End App.
```

---
### Environment
* React Native Navigation version: 2.26.1
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Emulator, Android OS 9.0, Debug

**Comment by ItsNoHax** [comment]
Make sure you are passing valid image's for the icons in bottom tabs. Going to close this issue.
