### ISSUE TITLE
[V3] App crash on reload - TopTabs related

### ISSUE THREAD

**Issue by Damar95** [wix/react-native-navigation#5376]
### Issue Description

I have topTabs in my app and if they are visable(mounted) and i try to reload the app it crashes.
Its just in v3 reproducable not in v2, its fine there i think.

The navigation hierachie isnt relevant. it crashes as the first component in the navigation hierachie or nested in a stack or bottomtabs.

Error:
```js
2019-08-13 23:42:45.641 1414-1414/com.dummy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dummy, PID: 1414
    java.lang.RuntimeException: Tried to create view after it has already been destroyed
        at com.reactnativenavigation.viewcontrollers.ViewController.getView(ViewController.java:173)
        at com.reactnativenavigation.viewcontrollers.ChildController.getView(ChildController.java:33)
        at com.reactnativenavigation.viewcontrollers.ParentController.getView(ParentController.java:75)
        at com.reactnativenavigation.viewcontrollers.toptabs.TopTabsController.getCurrentChild(TopTabsController.java:43)
        at com.reactnativenavigation.viewcontrollers.ParentController.resolveCurrentOptions(ParentController.java:46)
        at com.reactnativenavigation.viewcontrollers.ParentController.resolveCurrentOptions(ParentController.java:47)
        at com.reactnativenavigation.viewcontrollers.ParentController.resolveCurrentOptions(ParentController.java:47)
        at com.reactnativenavigation.viewcontrollers.ChildController.onViewBroughtToFront(ChildController.java:59)
        at com.reactnativenavigation.viewcontrollers.ChildControllersRegistry.onViewDisappear(ChildControllersRegistry.java:17)
        at com.reactnativenavigation.viewcontrollers.ChildController.onViewDisappear(ChildController.java:55)
        at com.reactnativenavigation.viewcontrollers.ComponentViewController.onViewDisappear(ComponentViewController.java:57)
        at com.reactnativenavigation.viewcontrollers.ViewController.destroy(ViewController.java:248)
        at com.reactnativenavigation.viewcontrollers.ChildController.destroy(ChildController.java:81)
        at com.reactnativenavigation.viewcontrollers.ComponentViewController.destroy(ComponentViewController.java:126)
        at com.reactnativenavigation.viewcontrollers.-$$Lambda$SgkVrfcEcNuD_linqHpoypkiKnI.on(Unknown Source:2)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:93)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:76)
        at com.reactnativenavigation.viewcontrollers.ParentController.destroy(ParentController.java:137)
        at com.reactnativenavigation.viewcontrollers.-$$Lambda$SgkVrfcEcNuD_linqHpoypkiKnI.on(Unknown Source:2)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:93)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:76)
        at com.reactnativenavigation.viewcontrollers.ParentController.destroy(ParentController.java:137)
        at com.reactnativenavigation.viewcontrollers.-$$Lambda$SgkVrfcEcNuD_linqHpoypkiKnI.on(Unknown Source:2)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:93)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:76)
        at com.reactnativenavigation.viewcontrollers.ParentController.destroy(ParentController.java:137)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.destroyRoot(Navigator.java:124)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.destroyViews(Navigator.java:120)
        at com.reactnativenavigation.NavigationActivity.onReload(NavigationActivity.java:124)
        at com.reactnativenavigation.react.-$$Lambda$UtHdUQOoKfw1YtEpkLp6kg8alck.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6610)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

### Steps to Reproduce / Code Snippets / Screenshots
Every TopTab in v3 crashes on reload.
```js
Navigation.setRoot({
            root: {
                stack: {
                    children: [{
                        topTabs: {
                            children: [{
                                stack: {
                                    children: [{
                                        component: {
                                            name: "AppScreen",
                                        }
                                    }],
                                    options: {
                                        topTab: {
                                            title: 'FirstTopTab',
                                        },
                                    },
                                }
                            },
                            {
                                stack: {
                                    children: [{
                                        component: {
                                            name: "AppScreen",
                                        }
                                    }],
                                    options: {
                                        topTab: {
                                            title: 'SecondTopTab',
                                        },
                                    },
                                }
                            }],
                        },
                    }],
                    options: {
                        topBar: {
                            title: {
                                text: 'TopTabNavigator',
                            },
                            height: 100,
                        },
                    }
                }
            }
        });
```

### Environment
* React Native Navigation version: 3.0.0-alpha.11
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by syedabuthahirm** [comment]
Can you try this one
```js
Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      stack: {
        options: {
          topBar: {
            buttonColor: '#ffffff',
            title: {
              text: "WhatsApp",
              fontSize: 22,
              color: 'white'
            },
            background: {
                color: '#128c7e'
            }
          },
          topTabs: {
            selectedTabColor: "#ffffff",
            unselectedTabColor: "#e4e4e4"
          },
          fab: {
            backgroundColor: '#25d366'
          }
        },
        children: [
          {
            topTabs: {
              children: [
                {
                  component: {
                    name: SCREENS.CHATS,
                    options: {
                      topTab: {
                        title: "CHATS"
                      }
                    }
                  }
                },
                {
                  component: {
                    name: SCREENS.STATUS,
                    options: {
                      topTab: {
                        title: "STATUS"
                      }
                    }
                  }
                },
                {
                  component: {
                    name: SCREENS.CALLS,
                    options: {
                      topTab: {
                        title: "CALLS"
                      }
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    }
  });
});
```

**Comment by Damar95** [comment]
@syedabuthahirm I need to wrap the components inside the topTabs with a stack, otherwise it does not work as described in #5375 

its also crashing, but that is not suprising because its very similar to my provided example. 
Does it not crash on your device/emulator? 

My device uses API 26 and my emulator API 28.

**Comment by Damar95** [comment]
The app also crashes if it gets closed while topTabs are visable.
