### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference

### ISSUE THREAD

**Issue by arabscimitar** [wix/react-native-navigation#5476]
### Issue Description

side menu layout will break the app if center stack has more than two components with error

```console
Process: com.project, PID: 3414
    java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference
        at com.reactnativenavigation.presentation.ComponentPresenterBase.applyTopInsets(ComponentPresenterBase.java:10)
        at com.reactnativenavigation.viewcontrollers.ComponentViewController.applyTopInset(ComponentViewController.java:95)
        at com.reactnativenavigation.viewcontrollers.-$$Lambda$wlwFhgHcAClBnwsp5rN0pxte4i4.on(Unknown Source:2)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:93)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:76)
        at com.reactnativenavigation.viewcontrollers.ParentController.applyTopInset(ParentController.java:166)
        at com.reactnativenavigation.viewcontrollers.-$$Lambda$wlwFhgHcAClBnwsp5rN0pxte4i4.on(Unknown Source:2)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:93)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:76)
        at com.reactnativenavigation.viewcontrollers.ParentController.applyTopInset(ParentController.java:166)
        at com.reactnativenavigation.viewcontrollers.-$$Lambda$vVglzgYrWmnbpKcV_M9VjZiqrVQ.run(Unknown Source:2)
        at com.reactnativenavigation.utils.ObjectUtils.perform(ObjectUtils.java:10)
        at com.reactnativenavigation.viewcontrollers.ViewController.onMeasureChild(ViewController.java:330)
        at com.reactnativenavigation.views.BehaviourDelegate.onMeasureChild(BehaviourDelegate.java:22)
        at com.reactnativenavigation.views.BehaviourDelegate.onMeasureChild(BehaviourDelegate.java:7)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:813)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
2019-09-12 10:18:44.040 3414-3414/com.project E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
### Steps to Reproduce / Code Snippets / Screenshots

```js

export const auth = async () => {
  await Navigation.setRoot({
    root: {
      stack: {
        children: [
          {
            component: {
              name: 'Component1',
            },
          },
          {
            component: {
              name: 'Component2',
            },
          },
          {
            // if removed the third component in stack it will not give the error
            component: {
              name: 'Component3',
            },
          },
        ],
      },
    },
  });
};

```
---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device Debug/Release

**Comment by rokasgg** [comment]
Got the same error, any updates?

**Comment by arabscimitar** [comment]
I created a repo to reproduce this bug please check
[https://github.com/arabscimitar/react-native-navigation-bug](url)

**Comment by heroic** [comment]
I am hitting this same error, when the screen is pushed for the second time.

Screen 1 pushes Screen 2. All is okay
Gi back to screen 1
Screen 1 pushes Screen 2. App crashes with above error.

**Comment by arabscimitar** [comment]
yes @heroic  it is the same because I think that stack is pushes all screens on the children list

**Comment by heroic** [comment]
@arabscimitar I got a hack working. Not sure if it is a good solution or not, but it's working for me at least. Check my PR.

**Comment by arthur-vargas** [comment]
I am experiencing a similar problem when I try to `setRoot` with two children components. My app crashes on the second or third consecutive attempt to navigate this way...

I am getting this error
`java.lang.NullPointerException Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference 
    ComponentPresenterBase.java:10 com.reactnativenavigation.presentation.ComponentPresenterBase.applyTopInsets
    ComponentViewController.java:95 com.reactnativenavigation.viewcontrollers.ComponentViewController.applyTopInset
    Unknown:2 com.reactnativenavigation.viewcontrollers.-$$Lambda$wlwFhgHcAClBnwsp5rN0pxte4i4.on
    CollectionUtils.java:93 com.reactnativenavigation.utils.CollectionUtils.forEach
    CollectionUtils.java:76 com.reactnativenavigation.utils.CollectionUtils.forEach
    ParentController.java:166 com.reactnativenavigation.viewcontrollers.ParentController.applyTopInset
    Unknown:2 com.reactnativenavigation.viewcontrollers.-$$Lambda$wlwFhgHcAClBnwsp5rN0pxte4i4.on
    CollectionUtils.java:93 com.reactnativenavigation.utils.CollectionUtils.forEach
    CollectionUtils.java:76 com.reactnativenavigation.utils.CollectionUtils.forEach
    ParentController.java:166 com.reactnativenavigation.viewcontrollers.ParentController.applyTopInset
    Unknown:2 com.reactnativenavigation.viewcontrollers.-$$Lambda$vVglzgYrWmnbpKcV_M9VjZiqrVQ.run
    ObjectUtils.java:10 com.reactnativenavigation.utils.ObjectUtils.perform
    ViewController.java:330 com.reactnativenavigation.viewcontrollers.ViewController.onMeasureChild
    BehaviourDelegate.java:22 com.reactnativenavigation.views.BehaviourDelegate.onMeasureChild
    BehaviourDelegate.java:7 com.reactnativenavigation.views.BehaviourDelegate.onMeasureChild
    CoordinatorLayout.java:813 androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure
    View.java:23407 android.view.View.measure
    ViewGroup.java:6967 android.view.ViewGroup.measureChildWithMargins
    FrameLayout.java:185 android.widget.FrameLayout.onMeasure
    ContentFrameLayout.java:143 androidx.appcompat.widget.ContentFrameLayout.onMeasure
    View.java:23407 android.view.View.measure
    ViewGroup.java:6967 android.view.ViewGroup.measureChildWithMargins
    LinearLayout.java:1514 android.widget.LinearLayout.measureChildBeforeLayout
    LinearLayout.java:806 android.widget.LinearLayout.measureVertical
    LinearLayout.java:685 android.widget.LinearLayout.onMeasure
    View.java:23407 android.view.View.measure
    ViewGroup.java:6967 android.view.ViewGroup.measureChildWithMargins
    FrameLayout.java:185 android.widget.FrameLayout.onMeasure
    View.java:23407 android.view.View.measure
    ViewGroup.java:6967 android.view.ViewGroup.measureChildWithMargins
    LinearLayout.java:1514 android.widget.LinearLayout.measureChildBeforeLayout
    LinearLayout.java:806 android.widget.LinearLayout.measureVertical
    LinearLayout.java:685 android.widget.LinearLayout.onMeasure
    View.java:23407 android.view.View.measure
    ViewGroup.java:6967 android.view.ViewGroup.measureChildWithMargins
    FrameLayout.java:185 android.widget.FrameLayout.onMeasure
    DecorView.java:909 com.android.internal.policy.DecorView.onMeasure
    View.java:23407 android.view.View.measure
    ViewRootImpl.java:3017 android.view.ViewRootImpl.performMeasure
    ViewRootImpl.java:1997 android.view.ViewRootImpl.measureHierarchy
    ViewRootImpl.java:2286 android.view.ViewRootImpl.performTraversals
    ViewRootImpl.java:1863 android.view.ViewRootImpl.doTraversal
    ViewRootImpl.java:8072 android.view.ViewRootImpl$TraversalRunnable.run
    Choreographer.java:911 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:723 android.view.Choreographer.doCallbacks
    Choreographer.java:658 android.view.Choreographer.doFrame
    Choreographer.java:897 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:790 android.os.Handler.handleCallback
    Handler.java:99 android.os.Handler.dispatchMessage
    Looper.java:164 android.os.Looper.loop
    ActivityThread.java:7000 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:441 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:1408 com.android.internal.os.ZygoteInit.main`

And my navigation function looks like this:

`export const switchHomeStack = screen => {
  Navigation.setRoot({
    root: {
      sideMenu: {
        id: 'sideMenu',
        left: {
          component: {
            id: 'Drawer',
            options: {
              topBar: {
                visible: false,
                height: 0,
              },
            },
            name: SCREENS.SIDEBAR,
          },
        },
        center: {
          stack: {
            id: 'AppRoot',
            children: [
              {
                component: {
                  id: 'App',
                  name: SCREENS.HOME,
                  options: {
                    topBar: {
                      visible: false,
                      height: 0,
                    },
                    animations: {
                      setRoot: {
                        enabled: true,
                        waitForRender: true,
                      },
                    },
                  },
                },
              },
              {
                component: {
                  id: screen,
                  name: screen,
                  options: {
                    topBar: {
                      visible: false,
                      height: 0,
                    },
                    animations: {
                      setRoot: {
                        enabled: true,
                        waitForRender: true,
                      },
                    },
                  },
                },
              },
            ],
          },
        },
      },
    },
  });
};`

Any updates on this issue?

**Comment by dgobaud** [comment]
we're having this problem too used @heroic's patch and it does seem to work!

**Comment by SMJ93** [comment]
Thanks @heroic you fix works for me too! I've created a little bash script to update the file and added it to my postinstall:

scripts/fix-react-native-navigation.sh
```
#!/bin/bash

echo -e "------------- Fix react-native-navigation android crash bug -------------\n"

# Issue: https://github.com/wix/react-native-navigation/issues/5476

BROKEN_FILE_PATH="node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/presentation/ComponentPresenterBase.java";

# Original lines:
# if (lp.topMargin != topInsets) {
# to:
# if (lp != null && lp.topMargin != topInsets) {
BROKEN_LINE_1="lp.topMargin != topInsets"
FIX_TO_LINE_1="lp != null \&\&"

# if (lp.bottomMargin!= bottomInset) {
# to:
# if (lp != null && lp.bottomMargin!= bottomInset) {
BROKEN_LINE_2="lp.bottomMargin!= bottomInset"
FIX_TO_LINE_2="lp != null \&\&"

sed -i "" "s/$BROKEN_LINE_1/$FIX_TO_LINE_1 &/" $BROKEN_FILE_PATH
sed -i "" "s/$BROKEN_LINE_2/$FIX_TO_LINE_2 &/" $BROKEN_FILE_PATH
```

package.json
```
    "fix-react-native-navigation": "./scripts/fix-react-native-navigation.sh",
    "postinstall": "yarn fix-react-native-navigation"
```

**Comment by dgobaud** [comment]
@SMJ93 you should use https://www.npmjs.com/package/patch-package

**Comment by SMJ93** [comment]
Thanks @dgobaud, will take a look
