### ISSUE TITLE
[Android] "Tried to get null value" Error when using bottomTabs layout with icon

### ISSUE THREAD

**Issue by nastarfan** [wix/react-native-navigation#5483]
### Issue Description
I am new to RNN, after finishing the setup and manage to make it work, I thought everything will get easier, but apparently it's not. I am trying to create tabbed navigation with configuration like below to understand how to use RNN better:

```
registerScreens(); // register screens
  Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setRoot({
      root: {
        bottomTabs: {
          children: [
            {
              stack: {
                children: [
                  {
                    component: {
                      name: 'WelcomeScreen',
                    },
                  },
                  {
                    component: {
                      name: 'GreetScreen',
                    },
                  },
                ],
                options: {
                  bottomTab: {
                    text: 'Welcome',
                    icon: require('./assets/images/user.png'),
                    fontSize: 10,
                  },
                },
              },
            },
            {
              stack: {
                children: [
                  {
                    component: {
                      name: 'HelloScreen',
                    },
                  },
                  {
                    component: {
                      name: 'YoScreen',
                    },
                  },
                ],
                options: {
                  bottomTab: {
                    text: 'Hello',
                    icon: require('./assets/images/user.png'),
                    fontSize: 10,
                  },
                },
              },
            },
            {
              component: {
                name: 'AboutScreen',
              },
              options: {
                bottomTab: {
                  text: 'About',
                  icon: require('./assets/images/user.png'),
                  fontSize: 10,
                },
              },
            },
          ],
        },
      },
    });
  });
```
But then i got the following error in my logcat:
```
2019-09-14 17:02:08.367 5293-5293/com.testproject E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testproject, PID: 5293
    java.lang.RuntimeException: Tried to get null value!
        at com.reactnativenavigation.parse.params.Param.get(Param.java:16)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.lambda$createTabs$3(BottomTabsController.java:157)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.-$$Lambda$BottomTabsController$hVDDSxSvqNX-4DhQHls8ynB4x2w.map(Unknown Source:4)
        at com.reactnativenavigation.utils.CollectionUtils.map(CollectionUtils.java:45)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.createTabs(BottomTabsController.java:153)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.createView(BottomTabsController.java:75)
        at com.reactnativenavigation.viewcontrollers.ViewController.getView(ViewController.java:167)
        at com.reactnativenavigation.viewcontrollers.ParentController.getView(ParentController.java:60)
        at com.reactnativenavigation.presentation.RootPresenter.setRoot(RootPresenter.java:33)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.setRoot(Navigator.java:143)
        at com.reactnativenavigation.react.NavigationModule.lambda$setRoot$0(NavigationModule.java:88)
        at com.reactnativenavigation.react.-$$Lambda$NavigationModule$t-qP4peMa7q7-e5wwxed0CVSRl4.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7116)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
```
I have read and follow suggestion in https://github.com/wix/react-native-navigation/issues/4510 by running ```react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/```
but no luck, the issue still persist.
I've read this also, https://github.com/wix/react-native-navigation/issues/4534

---
### Environment
I'm on
"react-native": "0.59.10",
"react-native-navigation": "2.27.5",

**Comment by nastarfan** [comment]
Updating the last child to `stack` layout fixes my problem. Apparently `bottomTabs` layout has to use `stack` layout in order for it to work. It's not explained anywhere in the official documentation.

Please see https://github.com/wix/react-native-navigation/issues/5096
