### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String com.reactnativenavigation.viewcontrollers.ViewController.getId()' on a null object reference

### ISSUE THREAD

**Issue by LaVielle** [wix/react-native-navigation#5607]
### Issue Description

I'm getting Android crash reports with the following error: `NullPointerException : Attempt to invoke virtual method 'java.lang.String com.reactnativenavigation.viewcontrollers.ViewController.getId()' on a null object reference`

I cannot reproduce this error in debug mode so I don't know what might be causing it.
Any suggestions?

### Trace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.reactnativenavigation.viewcontrollers.ViewController.getId()' on a null object reference
    at com.reactnativenavigation.viewcontrollers.stack.StackController.popToRoot(StackController.java:312)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$popToRoot$3(Navigator.java:177)
    at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$spJ9tP2s3m8vo4liPDa8JpBljqM.run
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$applyOnStack$5(Navigator.java:232)
    at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$BztKRmJef9zlTqPlTta6T7nWHGw.run
    at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentStack(ViewController.java:154)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.applyOnStack(Navigator.java:232)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.popToRoot(Navigator.java:177)
    at com.reactnativenavigation.react.NavigationModule.lambda$popToRoot$7$NavigationModule(NavigationModule.java:139)
    at com.reactnativenavigation.react.-$$Lambda$NavigationModule$ak6fhLVnG4pjb9NVFqcU0ewBsPI.run
    at android.os.Handler.handleCallback(Handler.java:874)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:198)
    at android.app.ActivityThread.main(ActivityThread.java:6729)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

---
### Environment
* React Native Navigation version: 2.27.9
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Devices SM-J330F, Nokia 7 plus (maybe others). Release mode.

**Comment by codazzo** [comment]
I've reproduced this by having the same screen twice in the stack.

```
UsersList
  AddUser
    UserInformation <--
      UserDetails
        EditUser
          UserInformation <--
```

Calling (pseudocode) `popTo(userDetails)` would work, but subsequently calling `popTo(usersList)` would throw this exception.

**Comment by dpungaliya** [comment]
Did anyone find the answer/solution to this error?
