### ISSUE TITLE
[V3][Android] crash with setStackRoot

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#5621]
### Issue Description

I just updated from RN 0.59.10 and RNN 2.26.5 to RN 0.61.3 and RNN 3.3.0.

I'm now experiencing a crash on the following call:

```js
Navigation.setStackRoot(
    "my-stack",
    [
        {
            component : { name : "Home"}
        },
        {
            component : { name : "Recipe", passProps : { recipeId : recipeId}}
        },
        {
            component : { name : "RecipeSteps", passProps : { recipeId : recipeId, index : index + 1}}
        }
    ]
);
```

Here is the log of the crash:

```
2019-11-01 12:51:03.466 29252-29252/my.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.app, PID: 29252
    java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference
        at com.reactnativenavigation.presentation.ComponentPresenterBase.applyTopInsets(ComponentPresenterBase.java:10)
        at com.reactnativenavigation.viewcontrollers.ComponentViewController.applyTopInset(ComponentViewController.java:94)
        at com.reactnativenavigation.viewcontrollers.-$$Lambda$wlwFhgHcAClBnwsp5rN0pxte4i4.on(Unknown Source:2)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:93)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:76)
        at com.reactnativenavigation.viewcontrollers.ParentController.applyTopInset(ParentController.java:166)
        at com.reactnativenavigation.viewcontrollers.-$$Lambda$wlwFhgHcAClBnwsp5rN0pxte4i4.on(Unknown Source:2)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:93)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:76)
        at com.reactnativenavigation.viewcontrollers.ParentController.applyTopInset(ParentController.java:166)
        at com.reactnativenavigation.viewcontrollers.-$$Lambda$vVglzgYrWmnbpKcV_M9VjZiqrVQ.run(Unknown Source:2)
        at com.reactnativenavigation.utils.ObjectUtils.perform(ObjectUtils.java:10)
        at com.reactnativenavigation.viewcontrollers.ViewController.onMeasureChild(ViewController.java:330)
        at com.reactnativenavigation.views.BehaviourDelegate.onMeasureChild(BehaviourDelegate.java:22)
        at com.reactnativenavigation.views.BehaviourDelegate.onMeasureChild(BehaviourDelegate.java:7)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:813)
        at android.view.View.measure(View.java:24966)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:24966)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:24966)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:24966)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:24966)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:992)
        at android.view.View.measure(View.java:24966)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3301)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2028)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2330)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1888)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8511)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
2019-11-01 12:51:03.466 29252-29252/my.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

It was not happening in v2 so I guess we are having a bug in RNN v3 here?

---
### Environment
* React Native Navigation version: 3.3.0
* React Native version: 0.61.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android 9 device / debug

**Comment by guyca** [comment]
Hey @zabojad Are you able to reproduce it in the playground app?

**Comment by zabojad** [comment]
Hey @guyca . I've tried to setup a reproducer based on the playground app but I end up with another error (on js side this time) : https://github.com/zabojad/react-native-navigation/tree/issue_5621

The error is : `2019-11-05 11:18:38.602 22341-25553/com.reactnativenavigation.playground E/ReactNativeJS: undefined is not an object (evaluating 'self.props.componentId')`

And is happening when calling `Navigation.setStackRoot(...)`

**Comment by zabojad** [comment]
@guyca Can you help on this one? Why is the `setStackRoot` so capricious in V3?
