### ISSUE TITLE
Navigation.mergeOptions() updating bottomTab text often crashes on Android

### ISSUE THREAD

**Issue by dgobaud** [wix/react-native-navigation#5683]
Crashes on Android
version - "react-native-navigation": "3.2.0",

`Navigation.mergeOptions(consts.componentId.PORTFOLIO_ID, { bottomTab: { text: t('bottomBar.portfolio') } });`

problem seems to be it causes destroy() to be called in `node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsAttacher.java` which calls `attachStrategy.destroy();` without making sure it exists. I'm trying below patch

```java
    public void destroy() {
        if (attachStrategy) {
            attachStrategy.destroy();
        }
    }
```

"Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.bottomtabs.AttachMode.destroy()' on a null object reference"

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.bottomtabs.AttachMode.destroy()' on a null object reference
    at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsAttacher.destroy(BottomTabsAttacher.java:32)
    at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.destroy(BottomTabsController.java:197)
    at com.reactnativenavigation.viewcontrollers.-$$Lambda$SgkVrfcEcNuD_linqHpoypkiKnI.on
    at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:93)
    at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:76)
    at com.reactnativenavigation.viewcontrollers.ParentController.destroy(ParentController.java:137)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.destroyPreviousRoot(Navigator.java:130)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.access$100(Navigator.java:31)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator$1.onSuccess(Navigator.java:150)
    at com.reactnativenavigation.presentation.RootPresenter.animateSetRootAndReportSuccess(RootPresenter.java:61)
    at com.reactnativenavigation.presentation.RootPresenter.setRoot(RootPresenter.java:53)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.setRoot(Navigator.java:145)
    at com.reactnativenavigation.react.NavigationModule.lambda$setRoot$0$NavigationModule(NavigationModule.java:91)
    at com.reactnativenavigation.react.-$$Lambda$NavigationModule$t-qP4peMa7q7-e5wwxed0CVSRl4.run
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by guyca** [comment]
Hey @dgobaud Can you reproduce this in the playground app?

**Comment by dgobaud** [comment]
no havent tried what is that?

**Comment by wongp** [comment]
> no havent tried what is that?

It's the react native app they created to test and showcase the features of the navigation. https://wix.github.io/react-native-navigation/#/docs/showcases

**Comment by dgobaud** [comment]
it is still broken

**Comment by alejo-lapix** [comment]
@guyca I can reproduce this one. In my case I'm using a **side bar** and **bottom tabs**, this will lead to the error.

1. In the application entry point this is how we set the navigation root.

```js
Navigation.setRoot({
  root: {
    sideMenu: {
      center: {
        stack: {
          children: [
            // The first child will have bottom tabs.
            {
              bottomTabs: {
                children: [
                  {
                    component: {
                      name: GUEST_HOME,
                      options: {
                        bottomTab: {
                          icon: 'menu',
                        },
                      },
                    },
                  },
                ],
              },
            },
            // The second child can come from a deeplink 
            // or something like that. This component will change the 
            // application root.
            {
              component: {
                name: TERMS,
              },
            },
          ],
        },
      },
    },
  },
});
```
2. This component will change the application root.
```jsx
import React, {useEffect} from 'react';
import AppContent from './AppContent';

const TermsScreen = () => {
  useEffect(() => {
    setTimeout(() => pushOtherStack(), 5000);
  });
  return <AppContent render={'terms'} />;
};

export default TermsScreen;
```
3. **BOOM**!

Don't know if this is not the way that the library should be used. Is there any other way to handle things like deeplinks that keep navigation stack in the correct order?
