### ISSUE TITLE
Android popTo() NullPointerException

### ISSUE THREAD

**Issue by dgobaud** [wix/react-native-navigation#5688]
don't know how to reproduce concretely - comes into Sentry a lot never any helpful info other than native call stack seems to be a fatal error :(

"react-native-navigation": "3.2.0",

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.reactnativenavigation.viewcontrollers.ViewController.getId()' on a null object reference
    at com.reactnativenavigation.viewcontrollers.stack.StackController.popTo(StackController.java:287)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$popTo$4(Navigator.java:181)
    at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$6Dbpov-DtFHLKxms2Mpj62NzD-8.run(lambda)
    at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentStack(ViewController.java:164)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.popTo(Navigator.java:181)
    at com.reactnativenavigation.react.NavigationModule.lambda$popTo$6$NavigationModule(NavigationModule.java:137)
    at com.reactnativenavigation.react.-$$Lambda$NavigationModule$8x2wy4PLlSbyjyfHtJeZ_V7TPts.run(lambda)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5910)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

```
Family | SM-G531M
-- | --
Model | SM-G531M (LMY48B)
Architecture | armeabi-v7a
Battery Level | 57%
Orientation | portrait
Memory | Total: 902.4 MB / Free: 166.7 MB
Capacity | Total: 4.8 GB / Free: 422.8 MB
Simulator | False
brand | samsung
charging | False
low_memory | False
manufacturer | samsung
online | True
screen_density | 1.5
screen_dpi | 240
screen_resolution | 960x540
```

**Comment by guyca** [comment]
@dgobaud Any info you have would help me debug this. I tried reproducing this error by calling popTo in different scenarios with no luck.

**Comment by dgobaud** [comment]
@thebylito do you think #3981 explains this too? popping something pushed multiple times is a problem.

So must pop() before every push() to be safe? still a bug right?

**Comment by dgobaud** [comment]
We actually get many NullPointExceptions huge problem - impacting at least 6% of users.

Below are more crashes do you think they are all the same problem? Hoping the library gets more robust seems weird pushing same thing multiple times will causes crashes like this? Seems to be connected broadly to button races too - users tapping quickly causing these double pushes (we're fixing this but still would hope it wouldn't crash like this - why doesn't iOS?)
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.bottomtabs.AttachMode.destroy()' on a null object reference
    at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsAttacher.destroy(BottomTabsAttacher.java:32)
    at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.destroy(BottomTabsController.java:198)
    at com.reactnativenavigation.viewcontrollers.-$$Lambda$SgkVrfcEcNuD_linqHpoypkiKnI.on(lambda)
    at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:93)
    at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:76)
    at com.reactnativenavigation.viewcontrollers.ParentController.destroy(ParentController.java:137)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.destroyPreviousRoot(Navigator.java:130)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.access$100(Navigator.java:31)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator$1.onSuccess(Navigator.java:150)
    at com.reactnativenavigation.presentation.RootPresenter.animateSetRootAndReportSuccess(RootPresenter.java:61)
    at com.reactnativenavigation.presentation.RootPresenter.setRoot(RootPresenter.java:53)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.setRoot(Navigator.java:145)
    at com.reactnativenavigation.react.NavigationModule.lambda$setRoot$0$NavigationModule(NavigationModule.java:97)
    at com.reactnativenavigation.react.-$$Lambda$NavigationModule$t-qP4peMa7q7-e5wwxed0CVSRl4.run(lambda)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6165)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.reactnativenavigation.views.BottomTabs.getHeight()' on a null object reference
    at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.getBottomInset(BottomTabsController.java:180)
    at com.reactnativenavigation.viewcontrollers.ViewController.lambda$getBottomInset$3$ViewController(ViewController.java:352)
    at com.reactnativenavigation.viewcontrollers.-$$Lambda$ViewController$bTB9m7aibgK7y21hRA42dtwi5Ao.run(lambda)
    at com.reactnativenavigation.utils.ObjectUtils.perform(ObjectUtils.java:14)
    at com.reactnativenavigation.viewcontrollers.ViewController.getBottomInset(ViewController.java:352)
    at com.reactnativenavigation.viewcontrollers.ComponentViewController.applyBottomInset(ComponentViewController.java:105)
    at com.reactnativenavigation.presentation.BottomTabsPresenter.mergeDrawBehind(BottomTabsPresenter.java:110)
    at com.reactnativenavigation.presentation.BottomTabsPresenter.mergeChildOptions(BottomTabsPresenter.java:63)
    at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.mergeChildOptions(BottomTabsController.java:125)
    at com.reactnativenavigation.viewcontrollers.ChildController.lambda$mergeOptions$0$ChildController(ChildController.java:75)
    at com.reactnativenavigation.viewcontrollers.-$$Lambda$ChildController$lPkeKb1f3ceZicaDgwhuTS47BrI.run(lambda)
    at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentController(ViewController.java:150)
    at com.reactnativenavigation.viewcontrollers.ChildController.mergeOptions(ChildController.java:75)
    at com.reactnativenavigation.viewcontrollers.ComponentViewController.mergeOptions(ComponentViewController.java:89)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.mergeOptions(Navigator.java:158)
    at com.reactnativenavigation.react.NavigationModule.lambda$mergeOptions$2$NavigationModule(NavigationModule.java:112)
    at com.reactnativenavigation.react.-$$Lambda$NavigationModule$Kz75rfJiWxNOhqKQxoQpIgp5gvE.run(lambda)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6946)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.bottomtabs.AttachMode.destroy()' on a null object reference
    at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsAttacher.destroy(BottomTabsAttacher.java:32)
    at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.destroy(BottomTabsController.java:198)
    at com.reactnativenavigation.viewcontrollers.-$$Lambda$SgkVrfcEcNuD_linqHpoypkiKnI.on
    at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:93)
    at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:76)
    at com.reactnativenavigation.viewcontrollers.ParentController.destroy(ParentController.java:137)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.destroyRoot(Navigator.java:125)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.destroyViews(Navigator.java:121)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.destroy(Navigator.java:114)
    at com.reactnativenavigation.NavigationActivity.onDestroy(NavigationActivity.java:74)
    at android.app.Activity.performDestroy(Activity.java:7241)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1271)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4484)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4515)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4789)
    at android.app.ActivityThread.-wrap18
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1636)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6626)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
java.lang.RuntimeException: Unable to destroy activity {com.passfolio.app/com.passfolio.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.bottomtabs.AttachMode.destroy()' on a null object reference
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4497)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4515)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4789)
    at android.app.ActivityThread.-wrap18
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1636)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6626)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.ViewController.onViewWillAppear()' on a null object reference
    at com.reactnativenavigation.viewcontrollers.stack.StackController.pop(StackController.java:256)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$pop$2(Navigator.java:171)
    at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$snu0zowFhpNNrG6DTlYojmpj2RE.run(lambda)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$applyOnStack$5(Navigator.java:230)
    at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$BztKRmJef9zlTqPlTta6T7nWHGw.run(lambda)
    at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentStack(ViewController.java:164)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.applyOnStack(Navigator.java:230)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.pop(Navigator.java:171)
    at com.reactnativenavigation.react.NavigationModule.lambda$pop$5$NavigationModule(NavigationModule.java:132)
    at com.reactnativenavigation.react.-$$Lambda$NavigationModule$E0IsE1KTZ6QyyPB84sQPAxBdxKg.run(lambda)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6351)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
```

```
diff --git a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsAttacher.java b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsAttacher.java
index 3031d9e..75a4dd3 100644
--- a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsAttacher.java
+++ b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsAttacher.java
@@ -29,7 +29,9 @@ public class BottomTabsAttacher {
     }
 
     public void destroy() {
-        attachStrategy.destroy();
+        if (attachStrategy != null) {
+          attachStrategy.destroy();
+        }
     }
 
     void onTabSelected(ViewController tab) {
diff --git a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
index 68fb950..929f22e 100644
--- a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
+++ b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
@@ -177,7 +177,7 @@ public class BottomTabsController extends ParentController<BottomTabsLayout> imp
 
     @Override
     public int getBottomInset(ViewController child) {
-        int bottomTabsInset = resolveChildOptions(child).bottomTabsOptions.isHiddenOrDrawBehind() ? 0 : bottomTabs.getHeight();
+        int bottomTabsInset = bottomTabs == null || resolveChildOptions(child).bottomTabsOptions.isHiddenOrDrawBehind() ? 0 : bottomTabs.getHeight();
         return bottomTabsInset + perform(getParentController(), 0, p -> p.getBottomInset(this));
     }
 
diff --git a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
index 7e74c4b..dc8de39 100644
--- a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
+++ b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
@@ -252,6 +252,11 @@ public class StackController extends ParentController<StackLayout> {
         final ViewController disappearing = stack.pop();
         final ViewController appearing = stack.peek();
 
+        if (appearing == null || disappearing == null) {
+           listener.onError("Nothing to pop");
+           return;
+        }
+
         disappearing.onViewWillDisappear();
         appearing.onViewWillAppear();
 
@@ -276,7 +281,7 @@ public class StackController extends ParentController<StackLayout> {
     }
 
     public void popTo(ViewController viewController, Options mergeOptions, CommandListener listener) {
-        if (!stack.containsId(viewController.getId()) || peek().equals(viewController)) {
+        if (viewController == null || !stack.containsId(viewController.getId()) || peek().equals(viewController)) {
             listener.onError("Nothing to pop");
             return;
         }
@@ -284,14 +289,21 @@ public class StackController extends ParentController<StackLayout> {
         animator.cancelPushAnimations();
         String currentControlId;
         for (int i = stack.size() - 2; i >= 0; i--) {
+            if (stack.get(i) == null) {
+                continue;
+            }
+
             currentControlId = stack.get(i).getId();
             if (currentControlId.equals(viewController.getId())) {
                 break;
             }
 
             ViewController controller = stack.get(currentControlId);
-            stack.remove(controller.getId());
-            controller.destroy();
+            
+            if (controller != null) {
+                stack.remove(controller.getId());
+                controller.destroy();
+            }
         }
 
         pop(mergeOptions, listener);
@@ -308,7 +320,7 @@ public class StackController extends ParentController<StackLayout> {
         iterator.next();
         while (stack.size() > 2) {
             ViewController controller = stack.get(iterator.next());
-            if (!stack.isTop(controller.getId())) {
+            if (controller != null && !stack.isTop(controller.getId())) {
                 stack.remove(iterator, controller.getId());
                 controller.destroy();
             }
@@ -381,12 +393,16 @@ public class StackController extends ParentController<StackLayout> {
 
     @Override
     public void setupTopTabsWithViewPager(ViewPager viewPager) {
-        topBarController.initTopTabs(viewPager);
+        if (topBarController != null) {
+            topBarController.initTopTabs(viewPager);
+        }
     }
 
     @Override
     public void clearTopTabs() {
-        topBarController.clearTopTabs();
+        if (topBarController != null) {
+            topBarController.clearTopTabs();
+        }
     }
 
     @Override
@@ -397,7 +413,7 @@ public class StackController extends ParentController<StackLayout> {
 
     @Override
     public int getTopInset(ViewController child) {
-        return resolveChildOptions(child).topBar.isHiddenOrDrawBehind() ? 0 : topBarController.getHeight();
+        return topBarController == null || resolveChildOptions(child).topBar.isHiddenOrDrawBehind() ? 0 : topBarController.getHeight();
     }
 
     @RestrictTo(RestrictTo.Scope.TESTS)
```

**Comment by dgobaud** [comment]
4 more today - it seems it just moves around

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
    at com.reactnativenavigation.viewcontrollers.stack.StackController.popTo(StackController.java:284)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$popTo$4(Navigator.java:181)
    at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$6Dbpov-DtFHLKxms2Mpj62NzD-8.run(lambda)
    at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentStack(ViewController.java:164)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.popTo(Navigator.java:181)
    at com.reactnativenavigation.react.NavigationModule.lambda$popTo$6$NavigationModule(NavigationModule.java:143)
    at com.reactnativenavigation.react.-$$Lambda$NavigationModule$8x2wy4PLlSbyjyfHtJeZ_V7TPts.run(lambda)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:7406)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.reactnativenavigation.viewcontrollers.ViewController.isDestroyed()' on a null object reference
    at com.reactnativenavigation.viewcontrollers.stack.StackController.isRendered(StackController.java:65)
    at com.reactnativenavigation.viewcontrollers.ParentController.isRendered(ParentController.java:157)
    at com.reactnativenavigation.viewcontrollers.ViewController.isViewShown(ViewController.java:308)
    at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:276)
    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:959)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2891)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1893)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8539)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
    at android.view.Choreographer.doFrame(Choreographer.java:696)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7073)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference
    at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:182)
    at com.reactnativenavigation.react.NavigationModule.lambda$dismissOverlay$12$NavigationModule(NavigationModule.java:178)
    at com.reactnativenavigation.react.-$$Lambda$NavigationModule$hbXRvyvINGxcY8UagR9tTTyqlug.run
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6923)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.ViewController.mergeOptions(com.reactnativenavigation.parse.Options)' on a null object reference
    at com.reactnativenavigation.viewcontrollers.stack.StackController.pop(StackController.java:249)
    at com.reactnativenavigation.viewcontrollers.stack.StackController.handleBack(StackController.java:347)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.handleBack(Navigator.java:103)
    at com.reactnativenavigation.NavigationActivity.invokeDefaultOnBackPressed(NavigationActivity.java:80)
    at com.facebook.react.ReactInstanceManager.invokeDefaultOnBackPressed(ReactInstanceManager.java:449)
    at com.facebook.react.ReactInstanceManager.access$000(ReactInstanceManager.java:125)
    at com.facebook.react.ReactInstanceManager$1.invokeDefaultOnBackPressed(ReactInstanceManager.java:254)
    at com.facebook.react.modules.core.DeviceEventManagerModule$1.run(DeviceEventManagerModule.java:40)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6810)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by manuhook** [comment]
I'm having the same issue, 5% of my users. Unfortunately I didn't found a way to reproduce the crash. It seems only Huawei phones on Android 9 are impacted.

```
java.lang.NullPointerException: 
  at com.reactnativenavigation.react.NavigationModule.navigator (NavigationModule.java:189)
  at com.reactnativenavigation.react.NavigationModule.lambda$mergeOptions$2 (NavigationModule.java:113)
  at com.reactnativenavigation.react.-$$Lambda$NavigationModule$Kz75rfJiWxNOhqKQxoQpIgp5gvE.run (Unknown Source:6)
  at android.os.Handler.handleCallback (Handler.java:907)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```

P20 lite (HWANE) 35,7 %
P30 Pro (HWVOG) 14,3 %
HUAWEI P30 lite (HWMAR)  14,3 %
Mate 20 Pro (HWLYA)  14,3 %
P20 Pro (HWCLT) 14,3 %
Honor 10 (HWCOL) 7,1 %

**Comment by thebylito** [comment]
> I'm having the same issue, 5% of my users. Unfortunately I didn't found a way to reproduce the crash. It seems only Huawei phones on Android 9 are impacted.
> 
> ```
> java.lang.NullPointerException: 
>   at com.reactnativenavigation.react.NavigationModule.navigator (NavigationModule.java:189)
>   at com.reactnativenavigation.react.NavigationModule.lambda$mergeOptions$2 (NavigationModule.java:113)
>   at com.reactnativenavigation.react.-$$Lambda$NavigationModule$Kz75rfJiWxNOhqKQxoQpIgp5gvE.run (Unknown Source:6)
>   at android.os.Handler.handleCallback (Handler.java:907)
>   at android.os.Handler.dispatchMessage (Handler.java:105)
>   at android.os.Looper.loop (Looper.java:216)
>   at android.app.ActivityThread.main (ActivityThread.java:7625)
>   at java.lang.reflect.Method.invoke (Method.java)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
> ```
> 
> P20 lite (HWANE) 35,7 %
> P30 Pro (HWVOG) 14,3 %
> HUAWEI P30 lite (HWMAR) 14,3 %
> Mate 20 Pro (HWLYA) 14,3 %
> P20 Pro (HWCLT) 14,3 %
> Honor 10 (HWCOL) 7,1 %

Hi, this happens when you "push" two components with the same "componentId", and then try to pop with "componentId" used by the two screens.
