### ISSUE TITLE
RuntimeException Tried to create view after it has already been destroyed

### ISSUE THREAD

**Issue by dgobaud** [wix/react-native-navigation#5689]
version 3.2.0. i see the exception what would cause it? it is in getView()  src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java

```java
    public T getView() {
        if (view == null) {
            if (isDestroyed) {
                throw new RuntimeException("Tried to create view after it has already been destroyed");
            }
            view = createView();
            view.setOnHierarchyChangeListener(this);
            view.getViewTreeObserver().addOnGlobalLayoutListener(this);
        }
        return view;
    }
```

```
java.lang.RuntimeException: Tried to create view after it has already been destroyed
    at com.reactnativenavigation.viewcontrollers.ViewController.getView(ViewController.java:173)
    at com.reactnativenavigation.viewcontrollers.ChildController.getView(ChildController.java:33)
    at com.reactnativenavigation.viewcontrollers.ParentController.getView(ParentController.java:75)
    at com.reactnativenavigation.viewcontrollers.stack.StackController.lambda$push$4$StackController(StackController.java:164)
    at com.reactnativenavigation.viewcontrollers.stack.-$$Lambda$StackController$06hFigyLWXXMellTVVP0d0y7blk.run
    at com.reactnativenavigation.anim.NavigationAnimator$1.onAnimationEnd(NavigationAnimator.java:65)
    at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
    at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1294)
    at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1079)
    at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
    at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
    at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
    at android.view.Choreographer.doFrame(Choreographer.java:693)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6912)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
USER
```

**Comment by dgobaud** [comment]
its a huge problem we are switching to react-native because react native navigation crashes constantly

**Comment by jinshin1013** [comment]
Can you reproduce this problem, if you could provide a minimal reproduction it'd be helpful to debug

**Comment by dgobaud** [comment]
We are working on figuring out the exact cause but it seems to be related to the prior issues of pushing the same thing multiple times perhaps

**Comment by jinshin1013** [comment]
Do you perhaps push a screen with a custom id?

**Comment by dgobaud** [comment]
hmm what do you mean? I think so - double push of same component id?

**Comment by jinshin1013** [comment]
No sorry when you push do you pass a custom id:

Navigation.push({
  ...omitted
  id: COMPONENT_ID,
  name: COMPONENT_Name
})

**Comment by dgobaud** [comment]
yes

**Comment by jinshin1013** [comment]
Yeah, each screen should have a unique id so if you push multiple screens with the same id, it can cause a problem.

**Comment by dgobaud** [comment]
it is the same screen getting pushed I think - either way it should not crash. React Navigation just doesn't push again if it is the same screen in the stack

**Comment by jinshin1013** [comment]
Yeah maybe RNN could also add an option where if user is trying to push a screen with the same id, it could stop it. In the meantime though, you could avoid this by not providing a custom id or preventing double pushing of the same screen on your side.

**Comment by ayouidaniel** [comment]
I think this reference might be useful: https://github.com/wix/react-native-navigation/issues/3767

 `React Native Navigation automation moved this from Selected for Development to Done 18 days ago`

**Comment by AlphaJuliettOmega** [comment]
> Yeah, each screen should have a unique id so if you push multiple screens with the same id, it can cause a problem.

If duplicate ID's being pushed can cause an issue, it should log a warning when it happens.

Related:
https://github.com/wix/react-native-navigation/issues/5157

Total number of my users impacted: 7
Devices impacted: Samsung Galaxy S10+, Huawei P30 Lite, Google Pixel 4a

Can't reproduce, 
crash logs to Google Play, an exception from:
```
com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.getView
```
