### ISSUE TITLE
android navigation push concurrency problem

### ISSUE THREAD

**Issue by charlesluo2014** [wix/react-native-navigation#576]
### Issue Description

hi，when I read the code ，it use Eventbus to handle the event。
but when one button click many times in a short time。
it will have some bug。
RNN code like this
 ```
@Override
    public void push(ScreenParams params) {
        ScreenStack screenStack = getScreenStack(params.getNavigatorId());
        screenStack.push(params, createScreenLayoutParams(params));
        if (isCurrentStack(screenStack)) {
            bottomTabs.setStyleFromScreen(params.styleParams);
            EventBus.instance.post(new ScreenChangedEvent(params));
        }
    }
```

### Steps to Reproduce / Code Snippets / Screenshots

1. add a button to a navbar。
2. add push screen event handle by button
3. click the button many times in a short time

---
### Environment
* React Native Navigation version: 2.0.0-experimental.155
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?):android
* Device info (Simulator/Device? OS version? Debug/Release?):all

**Comment by charlesluo2014** [comment]
```
java.util.ConcurrentModificationException
                                                                      at java.util.AbstractList$SimpleListIterator.next(AbstractList.java:62)
                                                                      at com.reactnativenavigation.events.EventBus.post(EventBus.java:32)
                                                                      at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl$1.onJsDevReload(NavigationReactGateway.java:140)
                                                                      at com.reactnativenavigation.react.JsDevReloadListenerReplacer$DevCommandsHandlerProxy.onJSBundleLoadedFromServer(JsDevReloadListenerReplacer.java:60)
                                                                      at com.facebook.react.devsupport.DevSupportManagerImpl$20$1.run(DevSupportManagerImpl.java:778)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by zuoge85** [comment]
还是我那个建议，任何人都不要轻易使用这个项目！！！！
