### ISSUE TITLE
StackController.popToRoot() - NoSuchElementException error

### ISSUE THREAD

**Issue by dgobaud** [wix/react-native-navigation#5805]
See below the while loop has a bug.

1. We had to add the controller != null check because that was another crash that was happening see #5688 

2. There is a bug in the while loop see below it executes while stack.size() > 2 with no check to see if anything is left in the iterator and we just got a fatal NoSuchElementException. Assume stack of 3 elements there is no guarantee in the loop it removes any of them and if it doesn't it is guaranteed to crash. It seems the idea must be items in the stack after the second one are guaranteed to be !isTop() so they will all get removed guaranteeing the loop exits as soon as there are <= 2 items left. Perhaps the extra null controller check we added is what messes this up but then it would crash anyway on null controller....

I'm changing it to `while (iterator.hasNext() && stack.size() > 2) {` but not sure this is really the correct fix - given #5688 and the numerous NullPointException crashes (4 new ones just today - we fix in one place it just seems to move the crash somewhere else)  it seems the Android code has a lot of fatal crashes (perhaps all related to the same general problem so maybe easy to fix but I'm not sure what it is). The crashes are so bad we're switching to React Navigation because it is causing a lot of 1 star reviews (all on Android) because the app keeps crashing :(

### Environment
* React Native Navigation version: 4.0.4
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android

```java
    public void popToRoot(Options mergeOptions, CommandListener listener) {
        if (!canPop()) {
            listener.onError("Nothing to pop");
            return;
        }

        animator.cancelPushAnimations();
        Iterator<String> iterator = stack.iterator();
        iterator.next();
        while (stack.size() > 2) {
            ViewController controller = stack.get(iterator.next());
            if (controller != null && !stack.isTop(controller.getId())) {
                stack.remove(iterator, controller.getId());
                controller.destroy();
            }
        }

        pop(mergeOptions, listener);
    }
```

```
java.util.NoSuchElementException: null
    at java.util.ArrayList$Itr.next(ArrayList.java:863)
    at com.reactnativenavigation.viewcontrollers.stack.StackController.popToRoot(StackController.java:322)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$popToRoot$3(Navigator.java:175)
    at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$spJ9tP2s3m8vo4liPDa8JpBljqM.run
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$applyOnStack$5(Navigator.java:230)
    at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$BztKRmJef9zlTqPlTta6T7nWHGw.run
    at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentStack(ViewController.java:164)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.applyOnStack(Navigator.java:230)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.popToRoot(Navigator.java:175)
    at com.reactnativenavigation.react.NavigationModule.lambda$popToRoot$7$NavigationModule(NavigationModule.java:148)
    at com.reactnativenavigation.react.-$$Lambda$NavigationModule$ak6fhLVnG4pjb9NVFqcU0ewBsPI.run
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7058)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by renhongguang** [comment]
same issues

**Comment by nikolajordanovski** [comment]
same issue

**Comment by yedidyak** [comment]
Closing this as part of a maintainer cleanup of open issues older than one year.

Decision: Closed: stale/non-critical; no evidence it is a critical current-version RNN issue.

If this still reproduces on the latest React Native Navigation with a minimal reproduction, please open a new issue with current RN/RNN versions and repro steps.
