### ISSUE TITLE
(Android Only) Navigation.DismissModal() and Navigation.dismissAllModals() crashes on Android Only on a pushed screen

### ISSUE THREAD

**Issue by rezasazesh** [wix/react-native-navigation#5914]
### Issue Description
Everything works fine on android when a modal is created on a screen on a main stack, however if a screen is pushed on android and you add a modal on top of that, if you try to close the modal or use the back button the app crashes.

### Steps to Reproduce / Code Snippets / Screenshots

Created a root stack with bottom tabs -> push an screen -> show modal

````
Navigation.showModal({
    stack: {
      children: [
        {
          component: {
            name: screenName,
            passProps: passToProps,
            options: {
              topBar: {
                visible: false,
                height: 0,
              },
            },
          },
        },
      ],
    },
  });
````

Then I try to close the modal by a button or press back button when app crashes

````
<TouchableOpacity
              style={{width: 50, paddingVertical: 15}}
              onPress={() => Navigation.dismissAllModals()}>
              <Icon name="md-close" type="ionicon" color="white" />
</TouchableOpacity>

// OR

<TouchableOpacity
              style={{width: 50, paddingVertical: 15}}
              onPress={() => Navigation.dismissModal(this.props.componentId)}>
              <Icon name="md-close" type="ionicon" color="white" />
</TouchableOpacity>

````

Below is the crash report I got from adb logcat

`````
02-10 19:18:26.367 30951 30951 E AndroidRuntime: FATAL EXCEPTION: main
02-10 19:18:26.367 30951 30951 E AndroidRuntime: Process: com.thewalkiesapp.www, PID: 30951
02-10 19:18:26.367 30951 30951 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setTitleInactiveTextSizeInSp(AHBottomNavigation.java:1246)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.reactnativenavigation.presentation.BottomTabPresenter.lambda$applyOptions$0$BottomTabPresenter(BottomTabPresenter.java:60)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.reactnativenavigation.presentation.-$$Lambda$BottomTabPresenter$KEQrb_qe4n_D2VsSxgUwyRRy85A.run(Unknown Source:4)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.reactnativenavigation.utils.LateInit.perform(LateInit.java:19)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.reactnativenavigation.presentation.BottomTabPresenter.applyOptions(BottomTabPresenter.java:52)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:94)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:226)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.reactnativenavigation.viewcontrollers.ChildController.onViewAppeared(ChildController.java:49)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:279)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:959)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2909)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1911)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8528)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:696)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7091)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-10 19:18:26.367 30951 30951 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: mainjava.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setTitleInactiveTextSizeInSp(AHBottomNavigation.java:1246)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.reactnativenavigation.presentation.BottomTabPresenter.lambda$applyOptions$0$BottomTabPresenter(BottomTabPresenter.java:60)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.reactnativenavigation.presentation.-$$Lambda$BottomTabPresenter$KEQrb_qe4n_D2VsSxgUwyRRy85A.run(Unknown Source:4)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.reactnativenavigation.utils.LateInit.perform(LateInit.java:19)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.reactnativenavigation.presentation.BottomTabPresenter.applyOptions(BottomTabPresenter.java:52)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:94)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:226)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.reactnativenavigation.viewcontrollers.ChildController.onViewAppeared(ChildController.java:49)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:279)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:959)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2909)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1911)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8528)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.view.Choreographer.doFrame(Choreographer.java:696)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.os.Handler.handleCallback(Handler.java:873)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.os.Looper.loop(Looper.java:214)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at android.app.ActivityThread.main(ActivityThread.java:7091)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at java.lang.reflect.Method.invoke(Native Method)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-10 19:18:26.371 30951 30951 E com.marianhello.logging.UncaughtExceptionLogger:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

`````

---
### Environment
* React Native Navigation version: "^4.8.3"
* React Native version: "0.61.2"
* Platform(s) (iOS, Android, or both?): Android Only
* Device info (Simulator/Device? OS version? Debug/Release?): Physical Device, Debug

**Comment by rezasazesh** [comment]
So after some tests I found out the issue weirdly was that I cannot set `fontSize` in bottomTab inside of the options in the component, I can confirm that this did not cause crash in previous versions of RNN. Thank you!

```
stack: {
  children: [
    {
      component: {
        name: 'PetOwnersMenu',
        options: {
          bottomTab: {
            fontSize: 12, // <----- CANNOT SET FONT SIZE HERE
            icon: sources[iconId],
            text: text,
          },
          topBar: {
            visible: true,
            height: 0,
          },
        },
      },
    },
  ],
},
```

**Comment by technoplato** [comment]
> inside of the options in the component

@rezasazesh I just ran into this same issue. Where **can** you set the `fontSize` of the bottomTab if not within the `component`?
