### ISSUE TITLE
[5.0.0] - Show overlay Android crash

### ISSUE THREAD

**Issue by pontusab** [wix/react-native-navigation#5915]
```
02-10 11:49:35.035 14048 14048 E AndroidRuntime: FATAL EXCEPTION: main
02-10 11:49:35.035 14048 14048 E AndroidRuntime: Process: com.example, PID: 14048
02-10 11:49:35.035 14048 14048 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View)' on a null object reference
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at ljb.a(OverlayManager.java:25)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at pmb.b(Navigator.java:202)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at com.reactnativenavigation.react.NavigationModule.c(NavigationModule.java:179)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at sjb.run(lambda)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at com.reactnativenavigation.react.NavigationModule.a(NavigationModule.java:200)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at zjb.run(lambda)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-10 11:49:35.035 14048 14048 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-10 11:49:35.041  2276  2292 W ActivityManager:   Force finishing activity com.example/.MainActivity
02-10 11:49:35.120  2276 11470 I OpenGLRenderer: Initialized EGL, version 1.4
02-10 11:49:35.121  2276 11470 D OpenGLRenderer: Swap behavior 1
02-10 11:49:35.122  2276 11470 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
02-10 11:49:35.122  2276 11470 D OpenGLRenderer: Swap behavior 0
02-10 11:49:35.125  2276 11470 D EGL_emulation: eglCreateContext: 0x7e0971517560: maj 3 min 0 rcv 3
02-10 11:49:35.128  2276 11470 D EGL_emulation: eglMakeCurrent: 0x7e0971517560: ver 3 0 (tinfo 0x7e096fa94ac0)
02-10 11:49:35.134  2276 11470 D EGL_emulation: eglMakeCurrent: 0x7e0971517560: ver 3 0 (tinfo 0x7e096fa94ac0)
02-10 11:49:35.556  2276  2297 W ActivityManager: Activity pause timeout for ActivityRecord{7a05da5 u0 com.example/.MainActivity t92 f}
02-10 11:49:35.628  1315  1338 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3080192
02-10 11:49:35.766  3035  3177 D EGL_emulation: eglMakeCurrent: 0xdfbddc40: ver 3 0 (tinfo 0xc9314be0)
02-10 11:49:35.946  2958  3045 D EGL_emulation: eglMakeCurrent: 0x7e096e66f120: ver 3 0 (tinfo 0x7e096e69c6a0)
02-10 11:49:36.086  2471  2592 D EGL_emulation: eglMakeCurrent: 0x7e0980664320: ver 3 0 (tinfo 0x7e098060cb20)
02-10 11:49:36.273  3035  3035 I OptInState: There is a new client and it does not support opt-in. Dropping request.
```

**Comment by guyca** [comment]
Fixed in alpha.11, Thanks for reporting @pontusab 👍
