### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: getNavigator()' on a null object reference

### ISSUE THREAD

**Issue by ridik1803** [wix/react-native-navigation#5996]
### Issue Description

From Firebase Crashlytics

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference
       at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:189)
       at com.reactnativenavigation.react.NavigationModule.lambda$mergeOptions$2$NavigationModule(NavigationModule.java:113)
       at com.reactnativenavigation.react.-$$Lambda$NavigationModule$Kz75rfJiWxNOhqKQxoQpIgp5gvE.run(:6)
       at android.os.Handler.handleCallback(Handler.java:809)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7555)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

### Steps to Reproduce / Code Snippets / Screenshots

No idea

---
### Environment
* React Native Navigation version: 4.8.4
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Release
![image](https://user-images.githubusercontent.com/3540152/75856426-64f75680-5e05-11ea-90bf-de4a26b52ff5.png)
![image](https://user-images.githubusercontent.com/3540152/75856453-6f195500-5e05-11ea-8a9b-e74a241cf627.png)

From Play Google Console:
![image](https://user-images.githubusercontent.com/3540152/75856939-6aa16c00-5e06-11ea-803d-d11410b6a208.png)

`java.lang.NullPointerException: 
  at com.reactnativenavigation.react.NavigationModule.navigator (NavigationModule.java:189)
  at com.reactnativenavigation.react.NavigationModule.lambda$mergeOptions$2$NavigationModule (NavigationModule.java:113)
  at com.reactnativenavigation.react.-$$Lambda$NavigationModule$Kz75rfJiWxNOhqKQxoQpIgp5gvE.run (Unknown Source:6)
  at android.os.Handler.handleCallback (Handler.java:809)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7555)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:963)`

According to the Firebase: **99% devices in background mode**

**Comment by ItsNoHax** [comment]
@guyca has this been fixed in any version leading up to V6?

**Comment by guyca** [comment]
This should be fixed in 5.0.0. Please upgrade and let me know if it's not fixed 👍

**Comment by ridik1803** [comment]
Thanks. I updated to version 6.1.0 (latest) and, when there are results, I will inform you

**Comment by ridik1803** [comment]
@guyca now I have an error: 
`TypeError: null is not an object (evaluating 'this.nativeCommandsModule.setDefaultOptons')`

**Comment by ys-sherzad** [comment]
Hi guys, any solution to still, it still popup quite often on Android with `7.30.3`

**Comment by harleenarora** [comment]
@ys-sherzad same error, are you find any solution?

**Comment by ys-sherzad** [comment]
@harleenarora Unfortunately no, it's still happening on the latest version `7.37.0` as well and the logs showing many crashes now.

**Comment by thuongtv-vn** [comment]
@ys-sherzad is app crashed with this error? and can you reproduce it?

**Comment by Japoncio3k** [comment]
Having this issue in `7.32.1`

**Comment by aattalla** [comment]
Can you provide an update on this issue if it is going to get resolved or if it will always remain this way?
