### ISSUE TITLE
OneSignal integration

### ISSUE THREAD

**Issue by akilbekov** [wix/react-native-navigation#607]
### Issue Description

I am trying to integrate OneSignal in my application, following this guide https://github.com/geektimecoil/react-native-onesignal#rn--029-1

### Steps to Reproduce / Code Snippets / Screenshots

here is my MainApplication.java
```
package com.navapp;

import java.util.Arrays;
import java.util.List;

import android.support.annotation.Nullable;

import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;
import com.airbnb.android.react.maps.MapsPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.geektime.reactnativeonesignal.ReactNativeOneSignalPackage;

public class MainApplication extends NavigationApplication {
    @Override
    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }

    @Nullable
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return Arrays.<ReactPackage>asList(
            new MapsPackage(),
            new VectorIconsPackage()
            new ReactNativeOneSignalPackage()
        );
    }
}
```

With this setup application complies, but when launching it in a simulator I am getting this error:
**Unfortunately NavApp has stopped android app**

Not sure were to go from here.

---
### Environment
* React Native Navigation version: 2.0.0-alpha.1
* React Native version: 0.39
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Android 6.0, 23.0.2

**Comment by guyca** [comment]
@akilbekov A stack trace would be helpful
open terminal and type `adb shell logcat`

**Comment by akilbekov** [comment]
@guyca strangely after downgrading react-native to 0.37 it works.
thank you.

**Comment by arshavinho** [comment]
Could it be a missing "," here:
```
return Arrays.<ReactPackage>asList(
            new MapsPackage(),
            new VectorIconsPackage(), <-----
            new ReactNativeOneSignalPackage()
        );
```

**Comment by akilbekov** [comment]
```
   35  12-27 19:41:55.112  8498  8498 I Radio-JNI: register_android_hardware_Radio DONE
   36  12-27 19:41:55.121  8498  8498 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
   37: 12-27 19:41:55.739  1559  1583 I PackageManager.DexOptimizer: Running dexopt (dex2oat) on: /data/app/vmdl2085420943.tmp/base.apk pkg=co.itbeaver.zapravka isa=x86 vmSafeMode=false debuggable=true oatDir = /data/app/vmdl2085420943.tmp/oat
   38  12-27 19:41:55.748  8508  8508 W dex2oat : Unexpected CPU variant for X86 using defaults: dalvik.vm.isa.x86.features=default
   39  12-27 19:41:55.748  8508  8508 W dex2oat : Mismatch between dex2oat instruction set features (ISA: X86 Feature string: smp,-ssse3,-sse4.1,-sse4.2,-avx,-avx2) and those of dex2oat executable (ISA: X86 Feature string: smp,ssse3,sse4.1,sse4.2,-avx,-avx2) for the command line:
   ..
   43  12-27 19:41:56.018  8508  8508 W dex2oat : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
   44  12-27 19:41:59.566  8508  8508 I dex2oat : dex2oat took 3.817s (threads: 2) arena alloc=2MB java alloc=7MB native alloc=37MB free=3MB
   45: 12-27 19:41:59.658  1559  1573 I ActivityManager: Force stopping co.itbeaver.zapravka appid=10060 user=-1: uninstall pkg
   46: 12-27 19:41:59.658  1559  1573 I ActivityManager: Killing 8420:co.itbeaver.zapravka/u0a60 (adj 9): stop co.itbeaver.zapravka
   47: 12-27 19:41:59.673  1559  1583 I PackageManager: Package co.itbeaver.zapravka codePath changed from /data/app/co.itbeaver.zapravka-1 to /data/app/co.itbeaver.zapravka-2; Retaining data and using new
   48: 12-27 19:41:59.674  1559  1583 W PackageManager: Code path for co.itbeaver.zapravka changing from /data/app/co.itbeaver.zapravka-1 to /data/app/co.itbeaver.zapravka-2
   49: 12-27 19:41:59.674  1559  1583 W PackageManager: Resource path for co.itbeaver.zapravka changing from /data/app/co.itbeaver.zapravka-1 to /data/app/co.itbeaver.zapravka-2
   50: 12-27 19:41:59.695  1559  1583 W PackageManager: Unknown permission com.sec.android.provider.badge.permission.READ in package co.itbeaver.zapravka
   51: 12-27 19:41:59.695  1559  1583 W PackageManager: Unknown permission com.sec.android.provider.badge.permission.WRITE in package co.itbeaver.zapravka
   52: 12-27 19:41:59.695  1559  1583 W PackageManager: Unknown permission com.htc.launcher.permission.READ_SETTINGS in package co.itbeaver.zapravka
   53: 12-27 19:41:59.695  1559  1583 W PackageManager: Unknown permission com.htc.launcher.permission.UPDATE_SHORTCUT in package co.itbeaver.zapravka
   54: 12-27 19:41:59.695  1559  1583 W PackageManager: Unknown permission com.sonyericsson.home.permission.BROADCAST_BADGE in package co.itbeaver.zapravka
   55: 12-27 19:41:59.695  1559  1583 W PackageManager: Unknown permission com.anddoes.launcher.permission.UPDATE_COUNT in package co.itbeaver.zapravka
   56: 12-27 19:41:59.695  1559  1583 W PackageManager: Unknown permission com.majeur.launcher.permission.UPDATE_BADGE in package co.itbeaver.zapravka
   57  12-27 19:41:59.709  1559  1570 D GraphicsStats: Buffer count: 4
   58: 12-27 19:41:59.714  1559  1573 I ActivityManager: Force stopping co.itbeaver.zapravka appid=10060 user=-1: replace pkg
   59: 12-27 19:41:59.719  1559  2683 W ActivityManager: Spurious death for ProcessRecord{84195f1 0:co.itbeaver.zapravka/u0a60}, curProc for 8420: null
   60  12-27 19:41:59.725  1559  2901 E Surface : getSlotFromBufferLocked: unknown buffer: 0x7f39a374c540
   61  12-27 19:41:59.731  1559  1571 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 8420 uid 10060
   ..
   63  12-27 19:41:59.740  1559  1583 I art     : Starting a blocking GC Explicit
   64  12-27 19:41:59.754  1559  1583 I art     : Explicit concurrent mark sweep GC freed 54263(2MB) AllocSpace objects, 10(360KB) LOS objects, 31% free, 8MB/12MB, paused 432us total 14.301ms
   65: 12-27 19:41:59.762  1559  1583 W PackageManager: Couldn't remove dex file for package:  at location /data/app/co.itbeaver.zapravka-1/base.apk, retcode=-1
   66  12-27 19:41:59.763  1254  1254 E installd: Couldn't opendir /data/app/vmdl2085420943.tmp: No such file or directory
   67: 12-27 19:41:59.770  1559  1583 I ActivityManager: Force stopping co.itbeaver.zapravka appid=10060 user=0: pkg removed
   68  12-27 19:41:59.773  8498  8498 I art     : System.exit called, status: 0
   69  12-27 19:41:59.773  8498  8498 I AndroidRuntime: VM exiting with result code 0.
   ..
   87  12-27 19:42:00.121  1932  1932 D CarrierServiceBindHelper: mHandler: 3
   88  12-27 19:42:00.121  1932  1932 D CarrierConfigLoader: mHandler: 9 phoneId: 0
   89: 12-27 19:42:00.229  2297  2652 E Drive.UninstallOperation: Package still installed co.itbeaver.zapravka
   90: 12-27 19:42:00.257  2039  8532 I UpdateIcingCorporaServi: Updating corpora: APPS=co.itbeaver.zapravka, CONTACTS=MAYBE
   91  12-27 19:42:00.308  8535  8535 I art     : Not late-enabling -Xcheck:jni (already on)
   92: 12-27 19:42:00.316  1559  1714 I ActivityManager: Start proc 8535:co.itbeaver.zapravka/u0a60 for broadcast co.itbeaver.zapravka/com.onesignal.UpgradeReceiver
   93  12-27 19:42:00.322  1559  2063 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
   94  12-27 19:42:00.325  2297  8525 I PeopleContactsSync: triggerPendingContactsCleanup: no accounts
   ..
  111  12-27 19:42:00.560  8551  8551 I Radio-JNI: register_android_hardware_Radio DONE
  112  12-27 19:42:00.568  8551  8551 D AndroidRuntime: Calling main entry com.android.commands.am.Am
  113: 12-27 19:42:00.571  1559  1748 I ActivityManager: START u0 {flg=0x10000000 cmp=co.itbeaver.zapravka/.MainActivity} from uid 0 on display 0
  114  12-27 19:42:00.586  8551  8551 D AndroidRuntime: Shutting down VM
  115  12-27 19:42:00.603  8535  8535 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
  116  12-27 19:42:00.605  1240  1453 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x933 imply creation of host color buffer
  117  12-27 19:42:00.610  1559  1578 D         : HostConnection::get() New Host Connection established 0x7f3991e48e40, tid 1578
  118: 12-27 19:42:00.635  8535  8535 V fb-UnpackingSoSource: locked dso store /data/user/0/co.itbeaver.zapravka/lib-main
  119  12-27 19:42:00.636  8535  8535 V fb-UnpackingSoSource: deps mismatch on deps store: regenerating
  120  12-27 19:42:00.636  8535  8535 V fb-UnpackingSoSource: so store dirty: regenerating
  ...
  132  12-27 19:42:00.649  8535  8535 V fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
  133  12-27 19:42:00.649  8535  8535 V fb-UnpackingSoSource: starting syncer worker
  134: 12-27 19:42:00.656  8535  8535 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/co.itbeaver.zapravka/lib-main (from syncer thread)
  135: 12-27 19:42:00.656  8535  8535 V fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/co.itbeaver.zapravka/lib-main (syncer thread started)
  136  12-27 19:42:00.685  1240  1453 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
  137  12-27 19:42:00.686  8535  8565 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
  ...
  145  12-27 19:42:01.010  1240  1954 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
  146  12-27 19:42:01.014  1240  1954 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
  147: 12-27 19:42:01.064  1559  1578 I ActivityManager: Displayed co.itbeaver.zapravka/.MainActivity: +479ms
  148  12-27 19:42:01.106  1240  1317 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
  149  12-27 19:42:01.123  8535  8565 E EGL_emulation: tid 8565: eglSurfaceAttrib(1165): error 0x3009 (EGL_BAD_MATCH)
  ...
  152  12-27 19:42:01.129  1240  1453 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
  153  12-27 19:42:01.218  8535  8565 E Surface : getSlotFromBufferLocked: unknown buffer: 0xeeeb1620
  154: 12-27 19:42:01.236  8535  8535 I art     : Thread[1,tid=8535,Native,Thread*=0xf40b4500,peer=0x737a6258,"main"] recursive attempt to load library "/data/app/co.itbeaver.zapravka-2/lib/x86/libfb.so"
  155  12-27 19:42:01.247  8535  8574 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLng>
  156  12-27 19:42:01.247  8535  8574 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLng>
  ...
  167  12-27 19:42:01.255  1559  1964 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@ca2c1ce attribute=null, token = android.os.BinderProxy@f6611ff
  168  12-27 19:42:01.257  8535  8574 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
  169: 12-27 19:42:01.257  8535  8574 E AndroidRuntime: Process: co.itbeaver.zapravka, PID: 8535
  170  12-27 19:42:01.257  8535  8574 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
  171  12-27 19:42:01.257  8535  8574 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
  ...
  193  12-27 19:42:01.257  8535  8574 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  194  12-27 19:42:01.257  8535  8574 E AndroidRuntime: 	... 3 more
  195: 12-27 19:42:01.257  1559  2684 W ActivityManager:   Force finishing activity co.itbeaver.zapravka/.MainActivity
  196  12-27 19:42:01.263  1240  1317 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x333 imply creation of host color buffer
  197  12-27 19:42:01.266  1559  2684 D         : HostConnection::get() New Host Connection established 0x7f398c57d0c0, tid 2684
  ...
  211  12-27 19:42:01.421  1240  1954 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
  212  12-27 19:42:01.423  1240  1954 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
  213: 12-27 19:42:01.434  1559  1578 W AppOps  : Finishing op nesting under-run: uid 10060 pkg co.itbeaver.zapravka code 24 time=0 duration=0 nesting=0
  214  12-27 19:42:01.457  1559  1748 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
  215  12-27 19:42:01.538  2297  2652 I Icing   : Indexing 5B5C8DCF75C6339B718BF21F4351FCE8DA136905 from com.google.android.googlequicksearchbox
  ...
  227  12-27 19:42:16.710  1559  2901 E Surface : getSlotFromBufferLocked: unknown buffer: 0x7f39a374c1c0
  228  12-27 19:42:16.717  1559  2221 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@353ed30 attribute=null, token = android.os.BinderProxy@30466f3
  229: 12-27 19:42:16.760  1559  1963 I ActivityManager: Process co.itbeaver.zapravka (pid 8535) has died
  230  12-27 19:42:16.906  1559  1578 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
```

**Comment by akilbekov** [comment]
I found the problem, and its not related to the react-native-navigation 🤓 

https://github.com/airbnb/react-native-maps/search?q=onesignal&type=Issues&utf8=%E2%9C%93

I was using other router and everything worked, and after migration to RNN this happened.
