### ISSUE TITLE
Android Build failed while trying to build from the command line using gradle build 

### ISSUE THREAD

**Issue by karthikeyan-kandasamy** [wix/react-native-navigation#6129]
### Issue Description

react-native-navigation library@2.22.3 caused build error 
while trying to build using gradle build --stacktrace from the command line it throws an error 
but when running the project from Android Studio it won't throw any error

### Steps to Reproduce / Code Snippets / Screenshots
Add react-native-navigation@2.22.3 in a starter project
Try build from the command line using gradle build --stacktrace

[FILL THIS OUT]

```
> Task :react-native-navigation:compileReactNative56DebugUnitTestJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-navigation:testReactNative56DebugUnitTest

com.reactnativenavigation.anim.ViewAnimationSetBuilderTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.parse.parsers.JSONParserTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.parse.parsers.BoolParserTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.parse.OrientationOptionsTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.parse.LayoutNodeParserTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.parse.OptionsTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.EnvironmentTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.utils.NativeCommandListenerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.utils.UiThreadTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.utils.UiUtilsTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.utils.StringUtilsTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.utils.TypefaceLoaderTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.utils.ReflectionUtilsTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.utils.CompatUtilsTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.FloatingActionButtonTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.TopBarButtonControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.bottomtabs.attachmode.TogetherTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.bottomtabs.attachmode.AfterInitialTabTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.bottomtabs.attachmode.OnSwitchToTabTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsAttacherTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.IdStackTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.ParentControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.YellowBoxDelegateTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.ExternalComponentViewControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.BottomTabsPresenterTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.TitleBarReactViewControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.TopTabsViewControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.button.NavigationIconResolverTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.sidemenu.SideMenuControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.navigator.NavigatorTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.navigator.RootPresenterTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.StackPresenterTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.ViewControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.ComponentViewControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.stack.BackButtonHelperTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.stack.StackControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.TitleBarTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.OptionsApplyingTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.modal.ModalStackTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.modal.ModalPresenterTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.BottomTabPresenterTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.overlay.OverlayManagerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.child.ChildControllerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.viewcontrollers.child.ChildControllersRegistryTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.views.TopBarTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.views.element.TransitionAnimatorCreatorTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.views.element.ElementTransitionManagerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.views.element.TransitionValidatorTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.views.TouchDelegateTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.react.NavigationReactNativeHostTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.react.ReloadListenerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.react.ElementViewManagerTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.react.ReactGatewayTest > initializationError FAILED
    java.lang.NullPointerException

com.reactnativenavigation.presentation.RenderCheckerTest > initializationError FAILED
    java.lang.NullPointerException


--------------------------------------------------------
      FAILURE (0 successes, 55 failures, 0 skipped)     
--------------------------------------------------------

see report at file:///Users/sample/Desktop/Test/node_modules/react-native-navigation/lib/android/app/build/reports/tests/testReactNative56DebugUnitTest/index.html

55 tests completed, 55 failed

> Task :react-native-navigation:testReactNative56DebugUnitTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:testReactNative56DebugUnitTest'.
> There were failing tests. See the report at: file:///Users/sample/Desktop/Test/node_modules/react-native-navigation/lib/android/app/build/reports/tests/testReactNative56DebugUnitTest/index.html

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-navigation:testReactNative56DebugUnitTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:141)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
```
---
### Environment
* React Native Navigation version: 0.59.5
* React Native version: 16.8.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by karthikeyan-kandasamy** [comment]
Tried with the latest version 6.4.0 

Getting the following errors. Command am trying 

`gradle clean build --stacktrace`

```
> Task :react-native-navigation:compileReactNative62DebugJavaWithJavac FAILED
/Users/priya/Desktop/TestDevops/node_modules/react-native-navigation/lib/android/app/src/reactNative62/java/reactnativenavigation/react/JsDevRe
loadHandlerFacade.java:7: error: JsDevReloadHandlerFacade is not abstract and does not override abstract method onSuccess(NativeDeltaClient) in
 DevBundleDownloadListener
public class JsDevReloadHandlerFacade implements DevBundleDownloadListener, NavigationDevBundleDownloadListener {
       ^
/Users/priya/Desktop/TestDevops/node_modules/react-native-navigation/lib/android/app/src/reactNative62/java/reactnativenavigation/react/ReloadHandlerFacade.java:8: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/priya/Desktop/TestDevops/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/ReloadHandler.java:3: error: ReloadHandler is not abstract and does not override abstract method onSuccess(NativeDeltaClient) in DevBundleDownloadListener
public class ReloadHandler extends ReloadHandlerFacade implements JsDevReloadHandler.ReloadListener {
       ^
/Users/priya/Desktop/TestDevops/node_modules/react-native-navigation/lib/android/app/src/reactNative62/java/reactnativenavigation/react/DevBundleDownloadListenerAdapter.java:7: error: DevBundleDownloadListenerAdapter is not abstract and does not override abstract method onSuccess(NativeDeltaClient) in DevBundleDownloadListener
public class DevBundleDownloadListenerAdapter implements DevBundleDownloadListener, NavigationDevBundleDownloadListener {
       ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative62DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-navigation:compileReactNative62DebugJavaWithJavac'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:141)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
```

**Comment by GuardianWC** [comment]
Same issue here. Any luck yet?

**Comment by karthikeyan-kandasamy** [comment]
@GuardianWC Have deleted the test files in the project as Temporary fix
