### ISSUE TITLE
[V6] Navbar button with showAsAction crashes on Android 

### ISSUE THREAD

**Issue by Rybachello** [wix/react-native-navigation#6204]
### Steps to Reproduce / Code Snippets / Screenshots

- Define buttons with `showAsAction` prop
- Press on button

Result: `RuntimeException: Tried to get null value!`

---
### Environment
* React Native Navigation version: 6.5.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator -Android 10 (API 29) - Both on debug and release

**Comment by aspidvip** [comment]
hello) me to

`Process: ru.tvil.guest, PID: 6391
    java.lang.RuntimeException: Tried to get null value!
        at com.reactnativenavigation.parse.params.Param.get(Param.java:27)
        at com.reactnativenavigation.utils.ButtonSpan.apply(ButtonSpan.kt:22)
        at com.reactnativenavigation.utils.ButtonSpan.updateDrawState(ButtonSpan.kt:12)
        at android.text.TextLine.handleRun(TextLine.java:943)
        at android.text.TextLine.measureRun(TextLine.java:408)
        at android.text.TextLine.measure(TextLine.java:298)
        at android.text.TextLine.metrics(TextLine.java:272)
        at android.text.BoringLayout.isBoring(BoringLayout.java:294)`

my code:
`Navigation.push(componentId, {
      component: {
        name: SEARCH_MAP,
        options: {
          topBar: {
            title: {
              text: title,
            },
            rightButtons: [{ id: 'menuButton',  icon: menu, color: colors.WHITE, disabledColor: colors.RGBA_WHITE_1, enabled: false }],
          },
        },
      },
    });
  });`

**Comment by enahum** [comment]
Yes, I have a similar issue when I try to update the buttons (enable/disable) using the merge options. It works just fine on 6.4.0 but with 6.5.0/6.6.0 it crashes the app
