### ISSUE TITLE
[6.7.1][Android] topBar rightButtons property enabled: false crashes application

### ISSUE THREAD

**Issue by Alw3ys** [wix/react-native-navigation#6257]
### Issue Description

When creating a modal with the property `enabled: false` in the topBar rightButtons causes the application to crash.

- I know this was not happening on version 4.8.4 together with  react-native 0.61.5.
- leftButtons are fine. I tried to reproduce it too there and all seems alright.
- Only happens in modals. I tried in regular screens and it's also alright.

### Steps to Reproduce / Code Snippets / Screenshots
```javascript
  Navigation.showModal({
    stack: {
      children: [{
        component: {
          name: 'navigation.screen.Example',
          options: {
            topBar: {
              title: {
                text: 'Example Title Text',
              },
            },
            rightButtons: [
              {
                id: 'cancel',
                enabled: false // <---
              },
            ]
          },
        },
      }],
    },
  });
```
---
### Environment
* React Native Navigation version: 6.7.1
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Nexus_5X_API_29_x86, API 29;Android 10.0(Google APIs), Debug

**Comment by guyca** [comment]
Hey @Alw3ys 
Seems like the button declaration is missing a `text` or `icon` property. Also, `rightButtons` should be declared inside the `topBar` object.

The following command works as expected in the Playground app:

```js
Navigation.showModal({
      stack: {
        children: [{
          component: {
            name: Screens.Modal,
            options: {
              topBar: {
                title: {
                  text: 'Example Title Text',
                },
                rightButtons: [
                  {
                    id: 'cancel',
                    text: 'Cancel',
                    enabled: false // <---
                  },
                ]
              },
            },
          },
        }],
      },
    })
```

**Comment by Alw3ys** [comment]
Hello @guyca 
My bad. I wanted go give an example and didn't use the options I was using.
I just tried once again how you told wrote it an as long as the `enabled` is `false` keeps crashing.
If I change it to `true` everything is alright.
```javascript
Navigation.showModal({
      stack: {
        children: [{
          component: {
            name: 'navigation.screen.Example',
            options: {
              topBar: {
                title: {
                  text: 'Example Title Text',
                },
                rightButtons: [
                  {
                    id: 'cancel',
                    text: 'Cancel',
                    enabled: false // <---
                  },
                ]
              },
            },
          },
        }],
      },
    })
```

Sorry for the misunderstanding

**Comment by guyca** [comment]
No worries. Can you paste the stack trace?
On which Android version are you checking? The code I pasted above works for me in the playground app.

**Comment by Alw3ys** [comment]
Sure! Here it is!
```
I/ReactNativeJS: Running "navigation.screen.NewPost" with {"initialProps":{"componentId":"Component6"},"rootTag":71}
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.moodeling, PID: 7161
    java.lang.RuntimeException: Tried to get null value!
        at com.reactnativenavigation.parse.params.Param.get(Param.java:27)
        at com.reactnativenavigation.utils.ButtonSpan.apply(ButtonSpan.kt:22)
        at com.reactnativenavigation.utils.ButtonSpan.updateDrawState(ButtonSpan.kt:12)
        at android.text.TextLine.handleRun(TextLine.java:1150)
        at android.text.TextLine.measureRun(TextLine.java:507)
        at android.text.TextLine.measure(TextLine.java:376)
        at android.text.TextLine.metrics(TextLine.java:305)
        at android.text.BoringLayout.isBoring(BoringLayout.java:366)
        at android.widget.TextView.onMeasure(TextView.java:9273)
        at androidx.appcompat.widget.AppCompatTextView.onMeasure(AppCompatTextView.java:551)
        at androidx.appcompat.view.menu.ActionMenuItemView.onMeasure(ActionMenuItemView.java:275)
        at android.view.View.measure(View.java:24530)
        at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:508)
        at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1182)
        at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:96)
        at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:226)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:298)
        at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1069)
        at androidx.appcompat.view.menu.MenuBuilder.onItemActionRequestChanged(MenuBuilder.java:1119)
        at androidx.appcompat.view.menu.MenuItemImpl.setShowAsAction(MenuItemImpl.java:746)
        at com.reactnativenavigation.viewcontrollers.TitleBarButtonController.applyButtonOptions(TitleBarButtonController.java:150)
        at com.reactnativenavigation.viewcontrollers.TitleBarButtonController.addToMenu(TitleBarButtonController.java:146)
        at com.reactnativenavigation.viewcontrollers.topbar.TopBarController.lambda$applyRightButtons$1$TopBarController(TopBarController.java:123)
        at com.reactnativenavigation.viewcontrollers.topbar.-$$Lambda$TopBarController$TTju2nyKJu5zIJR1E1HwgcbAsHo.run(Unknown Source:8)
        at com.reactnativenavigation.utils.CollectionUtils.forEachIndexed(CollectionUtils.java:129)
        at com.reactnativenavigation.viewcontrollers.topbar.TopBarController.applyRightButtons(TopBarController.java:123)
        at com.reactnativenavigation.presentation.StackPresenter.applyButtons(StackPresenter.java:279)
        at com.reactnativenavigation.presentation.StackPresenter.applyChildOptions(StackPresenter.java:139)
        at com.reactnativenavigation.viewcontrollers.stack.StackController.applyChildOptions(StackController.java:110)
        at com.reactnativenavigation.viewcontrollers.ViewController.lambda$onViewAppeared$2$ViewController(ViewController.java:244)
        at com.reactnativenavigation.viewcontrollers.-$$Lambda$ViewController$7NvZYkKSEhrDzEOl1ghm8_c9QVM.run(Unknown Source:4)
        at com.reactnativenavigation.viewcontrollers.ViewController.performOnParentController(ViewController.java:166)
        at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:242)
        at com.reactnativenavigation.viewcontrollers.ChildController.onViewAppeared(ChildController.java:50)
        at com.reactnativenavigation.viewcontrollers.ComponentViewController.onViewAppeared(ComponentViewController.java:61)
        at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:294)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1056)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2628)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process: Sending signal. PID: 7161 SIG: 9
Disconnected from the target VM, address: 'localhost:8630', transport: 'socket'
```
Android Version: 10.0

**Comment by Alw3ys** [comment]
Hello @guyca 
I've found some useful information in regards to the debug.
Aparently I set `rightButtonColor` with `Navigation.setDefaultOptions();`
```javascript
Navigation.setDefaultOptions({
  topBar: {
    rightButtonColor: primary,
  },
});
```
If I do not set this prop. The application won't crash.
I hope that helps.

**Comment by Alw3ys** [comment]
Thanks you very much!
