### ISSUE TITLE
Android: Occasional crash when returning from camera (ReactContext null when onActivityResult)

### ISSUE THREAD

**Issue by mikkoj** [wix/react-native-navigation#686]
### Issue Description

We are using `react-native-navigation` together with `react-native-image-picker`.

When taking a photo and returning back to application, we occasionally get a crash:

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13001, result=-1, data=null} to activity {com.edukit.staging/com.reactnativenavigation.controllers.PortraitNavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Activity com.facebook.react.bridge.ReactContext.getCurrentActivity()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3798)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3841)
       at android.app.ActivityThread.access$1400(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:234)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Activity com.facebook.react.bridge.ReactContext.getCurrentActivity()' on a null object reference
       at com.reactnativenavigation.react.NavigationReactGateway.onActivityResult(NavigationReactGateway.java:78)
       at com.reactnativenavigation.controllers.NavigationActivity.onActivityResult(NavigationActivity.java:174)
       at android.app.Activity.dispatchActivityResult(Activity.java:6490)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3794)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3841)
       at android.app.ActivityThread.access$1400(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:234)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Here's our MainApplication.java:
```
package com.edukit;

import android.content.Intent;
import android.app.Application;
import android.app.Activity;
import android.util.Log;
import android.support.annotation.Nullable;

import com.crashlytics.android.Crashlytics;
import com.facebook.react.ReactApplication;
import com.chirag.RNMail.RNMail;
import com.joshblour.reactnativepermissions.ReactNativePermissionsPackage;
import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;
import com.RNFetchBlob.RNFetchBlobPackage;
import com.imagepicker.ImagePickerPackage;
import com.reactnative.photoview.PhotoViewPackage;
import com.learnium.RNDeviceInfo.RNDeviceInfo;
import com.oblador.vectoricons.VectorIconsPackage;
import com.reactnativenavigation.NavigationApplication;
import com.reactnativenavigation.controllers.ActivityCallbacks;
import com.microsoft.codepush.react.CodePush;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import io.fabric.sdk.android.Fabric;
import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication {

    @Override
    public String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }

    @Override
    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }

    @Nullable
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
      return Arrays.<ReactPackage>asList(
        new RNMail(),
        new RNHTMLtoPDFPackage(),
        new ReactNativePermissionsPackage(),
        new ReactNativeConfigPackage(),
        new RNFetchBlobPackage(),
        new ImagePickerPackage(),
        new PhotoViewPackage(),
        new RNDeviceInfo(),
        new VectorIconsPackage(),
        new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG)
      );
    }

    @Override
    public void onCreate() {
      super.onCreate();
      Fabric.with(this, new Crashlytics());
      SoLoader.init(this, /* native exopackage */ false);

      setActivityCallbacks(new ActivityCallbacks() {
          @Override
          public void onActivityResult(int requestCode, int resultCode, Intent data) {
            super.onActivityResult(requestCode, resultCode, data);
          }
      });
    }
}
```

It is quite clear where the null reference occurs, but it's hard to pin point why the ReactContext is null. Are we missing something?

It's worth mentioning that we get this most with Sony phones which have slightly different camera.

Adding a null-check here helps in that the application doesn't crash anymore:
[https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java#L77](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java#L77)
But even with the null check it still results in app restart.

### Environment
* React Native Navigation version: 2.0.0-experimental.179
* React Native version: 0.39.2
* Platform(s): Android
* Device info: Release mode, repeats with Sony cameras

**Comment by knapeto** [comment]
Any solution? @DanielZlotin

**Comment by DanielZlotin** [comment]
Also,
4. can you reproduce it each time or just occasionally?

**Comment by elliotstokes** [comment]
I've just hit this same error returning from the image picker. It appears to happen when the device is low on memory and the app gets backrounded/killed

**Comment by swaroop03** [comment]
`08-01 07:20:10.774 26109-26109/com.grup E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.grup, PID: 26109
                                                          java.lang.RuntimeException: Unable to pause activity {com.grup/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
                                                              at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4664)
                                                              at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4623)
                                                              at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4598)
                                                              at android.app.ActivityThread.access$1300(ActivityThread.java:229)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
                                                              at com.evollu.react.fcm.FIRMessagingModule.onHostResume(FIRMessagingModule.java:143)
                                                              at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:210)
                                                              at com.facebook.react.ReactInstanceManager.moveToBeforeResumeLifecycleState(ReactInstanceManager.java:635)
                                                              at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:518)
                                                              at com.reactnativenavigation.react.NavigationReactGateway.onPauseActivity(NavigationReactGateway.java:72)
                                                              at com.reactnativenavigation.controllers.NavigationActivity.onPause(NavigationActivity.java:137)
                                                              at android.app.Activity.performPause(Activity.java:7061)
                                                              at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1340)
                                                              at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4650)
                                                              at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4623) 
                                                              at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4598) 
                                                              at android.app.ActivityThread.access$1300(ActivityThread.java:229) 
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                              at android.os.Looper.loop(Looper.java:148) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) `

I am getting this exception every time I try to select an image or take a photo on android device..

**Comment by elliotstokes** [comment]
I think this is still an issue bit our problem was exacerbated by one of the developer options on the phone `Don't keep activities` disabling that improves things a lot. There is still an issue though when the app is reconstructed after a pause.

**Comment by Thadeu** [comment]
+1

**Comment by Asleepace** [comment]
I'm also seeing this error, any update on this?

**Comment by guyca** [comment]
@Asleepace This issue is pretty old and most communication here is not relevant anymore. I suggest you open a new issue with a your findings 👍
