### ISSUE TITLE
After upgrading to 7.8.4 app is crashing on Android because of iconBackground prop

### ISSUE THREAD

**Issue by madandrija** [wix/react-native-navigation#6938]
## 🐛 Bug Report

After going from 7.6.0 to 7.8.4 we noticed that the default icon color on iOS was changed to blue. While fixing the issue, we've noticed that on Android, anywhere you use the `iconBackground` prop, the app crashes.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

Add the `iconBackground` prop and open the screen on Android simulator, e.g.  this works:

```
topBar: {
      rightButtons: [
        {
          id: premiumScreenTestIDs.close,
          testID: premiumScreenTestIDs.close,
          icon: iconsList.topBarCloseFill,
        }
      ],
      backButton: { visible: false }
    }
```

this doesn't:

```
topBar: {
      rightButtons: [
        {
          id: premiumScreenTestIDs.close,
          testID: premiumScreenTestIDs.close,
          icon: iconsList.topBarCloseFill,
          iconBackground: { color: theme.COLOR_DEFAULT_ICON_BACKGROUND }
        }
      ],
      backButton: { visible: false }
    }
```

## Expected behavior

I would expect the app not to crash

## Actual Behavior

The app crashes with

```
FATAL EXCEPTION: main
Process: com.madbarz.madbarzApp, PID: 20367
java.lang.RuntimeException: Tried to get null value!
	at com.reactnativenavigation.options.params.Param.get(Param.java:27)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.ButtonPresenter.getBackgroundColor(ButtonPresenter.kt:156)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.ButtonPresenter.access$getBackgroundColor(ButtonPresenter.kt:27)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.ButtonPresenter$applyIcon$1.onComplete(ButtonPresenter.kt:82)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.ButtonPresenter$loadIcon$1.run(ButtonPresenter.kt:126)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.ButtonPresenter$loadIcon$1.run(ButtonPresenter.kt:27)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.IconResolver$1.onComplete(IconResolver.java:30)
	at com.reactnativenavigation.utils.ImageLoader.loadIcon(ImageLoader.kt:44)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.IconResolver.resolve(IconResolver.java:27)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.ButtonPresenter.loadIcon(ButtonPresenter.kt:126)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.ButtonPresenter.applyIcon(ButtonPresenter.kt:79)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.ButtonPresenter.applyOptions(ButtonPresenter.kt:48)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.button.ButtonController.addToMenu(ButtonController.kt:84)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.TopBarController.lambda$applyRightButtons$1$TopBarController(TopBarController.java:125)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.-$$Lambda$TopBarController$rlIV_MYFMKIvSNp70rm34RXTfHA.run(Unknown Source:8)
	at com.reactnativenavigation.utils.CollectionUtils.forEachIndexed(CollectionUtils.java:130)
	at com.reactnativenavigation.viewcontrollers.stack.topbar.TopBarController.applyRightButtons(TopBarController.java:125)
	at com.reactnativenavigation.viewcontrollers.stack.StackPresenter.applyButtons(StackPresenter.java:288)
	at com.reactnativenavigation.viewcontrollers.stack.StackPresenter.applyChildOptions(StackPresenter.java:148)
	at com.reactnativenavigation.viewcontrollers.stack.StackController.applyChildOptions(StackController.java:108)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.lambda$onViewWillAppear$2$ViewController(ViewController.java:243)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.-$$Lambda$ViewController$tTJ1L0GkoDe04ReQATFeLMWfk2A.run(Unknown Source:4)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.performOnParentController(ViewController.java:169)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.onViewWillAppear(ViewController.java:241)
	at com.reactnativenavigation.viewcontrollers.child.ChildController.onViewWillAppear(ChildController.java:52)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.onGlobalLayout(ViewController.java:297)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2980)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
```

## Your Environment

- React Native Navigation version: 7.8.4
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator Nexus 6, API level 30, Debug

**Comment by madandrija** [comment]
Reproduced on the playground app as well, just add the prop to `rightButtons`, e.g.

```
topBar: {
                  title: {
                    text: 'Default Title',
                  },
                  rightButtons: [
                    {
                      id: 'closeMe',
                      testID: 'closeMe',
                      icon: require('../img/star.png'),
                      iconBackground: { color: 'green' },
                    },
                  ],
                },
```
