### ISSUE TITLE
Android crashes

### ISSUE THREAD

**Issue by remigijusbalc** [wix/react-native-navigation#6940]
### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

Upgrade to 7.8.0 or 7.8.4 version

## Expected behavior

Not to crash

(Write what you thought would happen.)

## Actual Behavior

It complies fine, but after js bundle loads - Android crashes

FATAL EXCEPTION: main
Process: x.x.x*, PID: 30304 
android.content.res.Resources$NotFoundException: Resource ID #0x7f070052 type #0x10 is not valid
	at android.content.res.Resources.getDimensionPixelSize(Resources.java:747)
	at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.init(AHBottomNavigation.java:222)
	at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.<init>(AHBottomNavigation.java:153)
	at com.reactnativenavigation.views.bottomtabs.BottomTabs.<init>(BottomTabs.java:28)
	at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.createBottomTabs(BottomTabsController.java:84)
	at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.createView(BottomTabsController.java:68)
	at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.createView(BottomTabsController.java:35)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.getView(ViewController.java:198)
	at com.reactnativenavigation.viewcontrollers.child.ChildController.getView(ChildController.java:37)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.RootPresenter.setRoot(RootPresenter.java:37)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.setRoot(Navigator.java:146)
	at com.reactnativenavigation.react.NavigationModule.lambda$setRoot$0$NavigationModule(NavigationModule.java:97)
	at com.reactnativenavigation.react.-$$Lambda$NavigationModule$775WZ0Z9aNTTnpnyaMCNNiHy9cM.run(Unknown Source:8)
	at com.reactnativenavigation.react.NavigationModule.lambda$handle$14$NavigationModule(NavigationModule.java:205)
	at com.reactnativenavigation.react.-$$Lambda$NavigationModule$Aysjmc3QtzSDDcOv2kytp78pS-s.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

* replaced app id

## Your Environment

- React Native Navigation version: 7.8.4
- React Native version: 0.63.2
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Samsung S8, Debug

**Comment by remigijusbalc** [comment]
I found that downgrading 'com.github.wix-playground:ahbottomnavigation:3.2.0' to older version (3.3.0 -> 3.2.0) solves the issue

**Comment by remigijusbalc** [comment]
Fixed this and made PR to ahbottomnavigation fork: https://github.com/wix-playground/ahbottomnavigation/pull/3

**Comment by yedidyak** [comment]
Closing this as part of a maintainer cleanup of open issues older than one year.

Decision: Closed: stale/non-critical; no evidence it is a critical current-version RNN issue.

If this still reproduces on the latest React Native Navigation with a minimal reproduction, please open a new issue with current RN/RNN versions and repro steps.
