### ISSUE TITLE
[7.11.3] Android crash:  This animation is not supported: enter

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#7054]
## 🐛 Bug Report

I've just updated from 7.7.0 to 7.11.3 (latest) and cannot run my app anymore on any Android simulator I have:

2021-03-23 15:52:09.660 5736-5736/my.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.app, PID: 5736
    java.lang.IllegalArgumentException: This animation is not supported: enter
        at com.reactnativenavigation.options.AnimationOptions$Companion.getAnimProp(AnimationOptions.kt:113)
        at com.reactnativenavigation.options.AnimationOptions$Companion.access$getAnimProp(AnimationOptions.kt:99)
        at com.reactnativenavigation.options.AnimationOptions.parse(AnimationOptions.kt:33)
        at com.reactnativenavigation.options.AnimationOptions.<init>(AnimationOptions.kt:47)
        at com.reactnativenavigation.options.NestedAnimationsOptions$Companion.parse(NestedAnimationsOptions.kt:50)
        at com.reactnativenavigation.options.NestedAnimationsOptions.parse(Unknown Source:2)
        at com.reactnativenavigation.options.AnimationsOptions.parse(AnimationsOptions.java:12)
        at com.reactnativenavigation.options.Options.parse(Options.java:30)
        at com.reactnativenavigation.react.NavigationModule.parse(NavigationModule.java:199)
        at com.reactnativenavigation.react.NavigationModule.lambda$setDefaultOptions$1$NavigationModule(NavigationModule.java:104)
        at com.reactnativenavigation.react.-$$Lambda$NavigationModule$N2JlaPHmovMYN5T38Ah4GsF6njg.run(Unknown Source:4)
        at com.reactnativenavigation.react.NavigationModule.lambda$handle$14$NavigationModule(NavigationModule.java:205)
        at com.reactnativenavigation.react.-$$Lambda$NavigationModule$Aysjmc3QtzSDDcOv2kytp78pS-s.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

## To Reproduce

1. Setup a project with RNN 7.7.0 and run it
1. update RNN to 7.11.3
1. run on android, it should crash

## Expected behavior

Obviously... it should not crash ^^.

## Actual Behavior

It's crashing with stacktrace above

## Your Environment

- React Native Navigation version: 7.11.3
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): simulator debug at least

**Comment by guyca** [comment]
@zabojad Sorry for the inconvenience. Can you please add the default options you're setting? It seems like there's a regression in parsing options.

cc @swabbass

**Comment by swabbass** [comment]
@zabojad thx for the report, I encountered this, and #7046 fixes that, can you try using master, and report if it still reproduces.

**Comment by guyca** [comment]
@swabbass Perhaps you should hotfix 7.11.3

**Comment by zabojad** [comment]
So it's ok, you do not need any further information, right?

**Comment by swabbass** [comment]
> So it's ok, you do not need any further information, right?
just for the sake of being sure, can you please share with us here the default options  :]

**Comment by swabbass** [comment]
@zabojad Hey, can you check out this version please `7.12.0` :]

**Comment by zabojad** [comment]
@swabbass sorry for my late answer. 

- I confirm that `7.12.0` solves my issue.
- my default options are:
```
{
	layout : {
		componentBackgroundColor : white, 
		backgroundColor : white, 
		orientation : [portrait]
	}, 
	blurOnUnmount : true, 
	topBar : {
		animate : false, 
		hideOnScroll : false, 
		drawBehind : false, 
		background : {
			color : #FFFFFF
		}, 
		title : {
			component : {
				name : HeaderToolbar, 
				alignment : fill
			}
		}, 
		backButton : {
			visible : false
		}, 
		elevation : 0, 
		borderColor : rgba(0, 0, 0, 0.12), 
		borderHeight : 1.0909090909090908, 
		height : 55
	}, 
	sideMenu : {

	}, 
	animations : {
		setStackRoot : {
			enabled : true
		}, 
		push : {
			enabled : true, 
			content : {
				x : {
					from : <...>, 
					to : <...>, 
					duration : <...>
				}
			}
		}, 
		pop : {
			content : {
				x : {
					from : <...>, 
					to : <...>, 
					duration : <...>
				}
			}
		}
	}
}
```

**Comment by guyca** [comment]
Thanks a lot, @zabojad and sorry for the inconvenience

**Comment by navneet-bm-ai** [comment]
Hi @guyca,
I am facing the exact same issue when I updated the library from 7.6.0 to 7.18.1.
Is there something wrong with this version of the library?


<img width="925" alt="Screenshot 2021-07-27 at 4 17 23 PM" src="https://user-images.githubusercontent.com/73818710/127142761-145f9d13-3f86-49d8-bc79-2727b09725f8.png">

**Comment by navneet-bm-ai** [comment]
Hi @guyca,
I am facing the exact same issue when I updated the library from 7.6.0 to 7.18.1.
Is there something wrong with this version of the library?
<img width="718" alt="Screenshot 2021-07-27 at 4 28 44 PM" src="https://user-images.githubusercontent.com/73818710/127143006-a07371a6-00ed-48f5-9a7e-3da394b1acf4.png">

**Comment by swabbass** [comment]
> Hi @guyca,
> I am facing the exact same issue when I updated the library from 7.6.0 to 7.18.1.
> Is there something wrong with this version of the library?
> <img alt="Screenshot 2021-07-27 at 4 28 44 PM" width="718" src="https://user-images.githubusercontent.com/73818710/127143006-a07371a6-00ed-48f5-9a7e-3da394b1acf4.png">

Hey, thanks for the report :], can you kindly share more info about the animation options you are using?

**Comment by navneet-bm-ai** [comment]
@swabbass  Please find the below code snippet.
```

 options: {
          topBar: {
            visible: true,
            drawBehind: true,
            title: {
              text: SCREENS.NotifcationPrimer.NavigationTitle,
            },
          },
          statusBar: statusBarTypes.transparent1,
          bottomTabs: {
            visible: false,
          },
          animations: { setRoot: { waitForRender: true } },
          // animations: animationTypes.slideRight,
        },
```
One Add-on point is that we are using codepush as well. and when we try to get the latest codepush the app crashed immediately after the codepush is recieved.
