### ISSUE TITLE
Compilation error for React Native 0.65 for Android

### ISSUE THREAD

**Issue by VladSt90** [wix/react-native-navigation#7220]
Log:

```> SmartHomeController@0.0.1 android
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1328 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Task :react-native-navigation:compileReactNative63DebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
26 actionable tasks: 2 executed, 24 up-to-date
e: ~/projects/SmartHomeController/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ReactImageMatrixAnimator.kt: (54, 16): Type mismatch: inferred type is ScalingUtils.ScaleType? but ScalingUtils.ScaleType was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative63DebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: ~/projects/SmartHomeController/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ReactImageMatrixAnimator.kt: (54, 16): Type mismatch: inferred type is ScalingUtils.ScaleType? but ScalingUtils.ScaleType was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative63DebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

    at makeError (~/projects/SmartHomeController/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at ~/projects/SmartHomeController/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async runOnAllDevices (~/projects/SmartHomeController/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (~/projects/SmartHomeController/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
```

## To Reproduce

1. Create new React Native application using `npx react-native init`
2. Install react-native-navigation
3. Run `npm run android`

## Your Environment

- React Native version: 0.65
- Platform: Android

## Solution for me:
I fixed it by modifying file `node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ReactImageMatrixAnimator.kt`
I just changed functions return type from `ScalingUtils.ScaleType?` to `ScalingUtils.ScaleType`.
```
private fun getScaleType(child: View): ScalingUtils.ScaleType {
        return getScaleType(child as ReactImageView, child.hierarchy.actualImageScaleType!!)
    }

    private fun getScaleType(child: ReactImageView, scaleType: ScalingUtils.ScaleType): ScalingUtils.ScaleType {
        if (scaleType is InterpolatingScaleType) return getScaleType(child, scaleType.scaleTypeTo )
        return scaleType
    }
```
There is new content of the file:
```
package com.reactnativenavigation.views.element.animators

import android.animation.Animator
import android.animation.ObjectAnimator
import android.animation.TypeEvaluator
import android.graphics.PointF
import android.graphics.Rect
import android.view.View
import com.facebook.drawee.drawable.ScalingUtils
import com.facebook.drawee.drawable.ScalingUtils.InterpolatingScaleType
import com.facebook.react.views.image.ReactImageView
import com.reactnativenavigation.options.SharedElementTransitionOptions
import com.reactnativenavigation.utils.ViewUtils
import kotlin.math.max
import kotlin.math.roundToInt

class ReactImageMatrixAnimator(from: View, to: View) : PropertyAnimatorCreator<ReactImageView>(from, to) {
    override fun shouldAnimateProperty(fromChild: ReactImageView, toChild: ReactImageView): Boolean {
        return !ViewUtils.areDimensionsEqual(from, to)
    }

    override fun create(options: SharedElementTransitionOptions): Animator {
        from as ReactImageView
        with(to as ReactImageView) {
            to.hierarchy.fadeDuration = 0
            val parentScaleX = (from.parent as View).scaleX
            val parentScalyY = (from.parent as View).scaleY

            val fromBounds = calculateBounds(from, parentScaleX, parentScalyY)
            hierarchy.actualImageScaleType = InterpolatingScaleType(
                    getScaleType(from),
                    getScaleType(to),
                    fromBounds,
                    calculateBounds(to),
                    PointF(from.width * parentScaleX / 2f, from.height * parentScalyY / 2f),
                    PointF(to.width / 2f, to.height / 2f)
            )

            to.layoutParams.width = max(from.width, to.width)
            to.layoutParams.height = max(from.height, to.height)
            return ObjectAnimator.ofObject(TypeEvaluator<Float> { fraction: Float, _: Any, _: Any ->
                hierarchy.actualImageScaleType?.let {
                    (hierarchy.actualImageScaleType as? InterpolatingScaleType)?.let {
                        it.value = fraction
                        to.invalidate()
                    }
                }
                null
            }, 0, 1)
        }
    }

    private fun getScaleType(child: View): ScalingUtils.ScaleType {
        return getScaleType(child as ReactImageView, child.hierarchy.actualImageScaleType!!)
    }

    private fun getScaleType(child: ReactImageView, scaleType: ScalingUtils.ScaleType): ScalingUtils.ScaleType {
        if (scaleType is InterpolatingScaleType) return getScaleType(child, scaleType.scaleTypeTo )
        return scaleType
    }

    private fun calculateBounds(view: View, parentScaleX: Float = 1f, parentScaleY: Float = 1f) =
            Rect(
                    0,
                    0,
                    (view.width * parentScaleX).roundToInt(),
                    (view.height * parentScaleY).roundToInt()
            )
}
```

**Comment by alejandrorangel** [comment]
this is already fix [PR 7211](https://github.com/wix/react-native-navigation/pull/7211) but they haven't cut a new release yet

**Comment by swabbass** [comment]
A release is in the works. sorry for the inconvenience. (on V8 milestone we are planning to support RN64+)
