### ISSUE TITLE
[Android] navigation v.7.19.0 RN: 0.65.1  Error for Android the mergeOptions (rightButtons->component), crach app

### ISSUE THREAD

**Issue by aspidvip** [wix/react-native-navigation#7229]
## 🐛 Bug Report

about:
"react-native": "0.65.1",
"react-native-navigation": "7.19.0",

(Write your steps here:)

2. `Navigation.mergeOptions(SEARCH_MAIN, {
        topBar: {
          rightButtons: [
            {
              id: 'avatarSearchButton',
              component: {
                id: AVATAR_MAIN,
                name: AVATAR_MAIN,
                passProps: {
                  source: props.profile.avatar,
                  borderColor: colors.WHITE,
                  isStatus: false,
                  onPress: this.handleProfilePress,
                },
              },
            },
          ],
        },
      });`

error for Android
`com.facebook.react.uimanager.IllegalViewOperationException: Trying to attach a ReactRootView with an explicit id already set to [1]. React Native uses the id field to track react tags and will overwrite this field. If that is fine, explicitly overwrite the id field to View.NO_ID.
        at com.facebook.react.ReactRootView.attachToReactInstanceManager(ReactRootView.java:644)
        at com.facebook.react.ReactRootView.onMeasure(ReactRootView.java:169)
        at com.reactnativenavigation.views.stack.topbar.titlebar.TitleBarReactButtonView.onMeasure(TitleBarReactButtonView.java:27)
        at android.view.View.measure(View.java:22216)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
        at androidx.appcompat.widget.LinearLayoutCompat.measureChildBeforeLayout(LinearLayoutCompat.java:1387)
        at androidx.appcompat.widget.LinearLayoutCompat.measureHorizontal(LinearLayoutCompat.java:1034)
        at androidx.appcompat.widget.LinearLayoutCompat.onMeasure(LinearLayoutCompat.java:563)
        at androidx.appcompat.widget.ActionMenuView.onMeasure(ActionMenuView.java:173)
        at android.view.View.measure(View.java:22216)
        at androidx.appcompat.widget.Toolbar.measureChildConstrained(Toolbar.java:1645)
        at androidx.appcompat.widget.Toolbar.onMeasure(Toolbar.java:1738)
        at android.view.View.measure(View.java:22216)
        at com.reactnativenavigation.views.stack.topbar.titlebar.TitleAndButtonsContainer.measureTitleComponentExact(TitleAndButtonsContainer.kt:146)
        at com.reactnativenavigation.views.stack.topbar.titlebar.TitleAndButtonsContainer.onMeasure(TitleAndButtonsContainer.kt:138)
        at android.view.View.measure(View.java:22216)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1539)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:823)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:702)
        at android.view.View.measure(View.java:22216)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22216)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1539)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:823)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:702)
        at com.google.android.material.appbar.AppBarLayout.onMeasure(AppBarLayout.java:419)
        at android.view.View.measure(View.java:22216)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
        at android.view.View.measure(View.java:22216)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
        at android.view.View.measure(View.java:22216)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
        at android.view.View.measure(View.java:22216)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:22216)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1539)`

**Comment by keeprock** [comment]
Any updates on this? I've got similar crash on 0.65.1
