### ISSUE TITLE
Error: Unable to resolve module remx

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#7252]
## 🐛 Bug Report

Error: Unable to resolve module remx from /Users/ikokkinidis/Development/scheduling/adminApp/node_modules/react-native-navigation/lib/dist/Mock/connect.js: remx could not be found within the project or in these directories:
  node_modules/react-native-navigation/node_modules
  node_modules

```
2 | Object.defineProperty(exports, "__esModule", { value: true });
  3 | exports.connect = void 0;
> 4 | const remx_1 = require("remx");
    |                         ^
  5 | function connect(component) {
  6 |     // @ts-ignore
  7 |     return remx_1.connect()(component);
    at ModuleResolver.resolveDependency (/Users/ikokkinidis/Development/scheduling/adminApp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:129:15)
    at DependencyGraph.resolveDependency (/Users/ikokkinidis/Development/scheduling/adminApp/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/Users/ikokkinidis/Development/scheduling/adminApp/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/ikokkinidis/Development/scheduling/adminApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/ikokkinidis/Development/scheduling/adminApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/ikokkinidis/Development/scheduling/adminApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/ikokkinidis/Development/scheduling/adminApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Users/ikokkinidis/Development/scheduling/adminApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 5)
```

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## Expected behavior

The app shouldn't crash

## Actual Behavior

Launch crash

## Your Environment

- React Native Navigation version: 7.20.0
- React Native version: 0.65.1
- Platform(s) (iOS, Android, or both?): iOS (haven't tested android yet, maybe it happens there too)
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug

**Comment by SudoPlz** [comment]
I wonder if it's related to https://github.com/wix/react-native-navigation/pull/7241

**Comment by retyui** [comment]
Tested on `7.21.0`, `7.20.0`

Steps:
```bash
rn init wixRNN --template react-native-template-typescript
cd wixRNN
yarn add react-native-navigation
npx rnn-link
yarn start
react-native run-android
```

This error is not reproduced until you manually add in code mock import 
```tsx
import 'react-native-navigation/Mock';
```

--- 
@SudoPlz can you show how you using an RNN mock?

**Comment by yogevbd** [comment]
@SudoPlz yes it is related to #7241, RNN mocks needs remx as a peer dependency, to solve this install remx.
@retyui please take a look at the example [here](https://github.com/wix/react-native-navigation/pull/7140). I do need to add documentation for this, will do that soon

**Comment by SudoPlz** [comment]
@yogevbd @retyui I'm not using RNN mock anywhere afaik 😕 🤔 no idea why `remx` is needed.

**Comment by yedidyak** [comment]
Closing this as part of a maintainer cleanup of open issues older than one year.

Decision: Closed: documentation request is not a critical current issue.

If this still reproduces on the latest React Native Navigation with a minimal reproduction, please open a new issue with current RN/RNN versions and repro steps.
