### ISSUE TITLE
I git the Fatal issue on android :: This ViewTreeObserver is not alive, call getViewTreeObserver() again

### ISSUE THREAD

**Issue by harleenarora** [wix/react-native-navigation#7261]
Fatal Exception: java.lang.IllegalStateException: This ViewTreeObserver is not alive, call getViewTreeObserver() again
at android.view.ViewTreeObserver.checkIsAlive(ViewTreeObserver.java:991)
at android.view.ViewTreeObserver.addOnGlobalLayoutListener(ViewTreeObserver.java:611)
at com.wix.reactnativeuilib.keyboardinput.ReactScreenMonitor.registerWindowLayoutListener(ReactScreenMonitor.java:14)
at com.wix.reactnativeuilib.keyboardinput.ReactScreenMonitor.onHostResume(ReactScreenMonitor.java:10)
at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:34)
at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:23)
at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:8)
at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:62)
at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java)
at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:6)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
at android.os.Looper.loop(Looper.java:246)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:37)
at java.lang.Thread.run(Thread.java:923)

**Comment by swabbass** [comment]
This is not related to our library, it is related to https://github.com/wix/react-native-ui-lib.
