### ISSUE TITLE
[Android] when reused Navigation.setRoot - crash

### ISSUE THREAD

**Issue by aspidvip** [wix/react-native-navigation#7273]
"react-native-navigation": "7.21.0",
"react-native": "0.63.4",

`
function main() {
Navigation.setRoot(''''') - ok
}
`

next press to button on the load

`
function button() {
Navigation.setRoot(''''') - crash app
}
`

`
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: , PID: 10386
    java.lang.AssertionError
        at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:66)
        at com.facebook.react.uimanager.NativeViewHierarchyOptimizer.transitionLayoutOnlyViewToNativeView(NativeViewHierarchyOptimizer.java:440)
        at com.facebook.react.uimanager.NativeViewHierarchyOptimizer.handleForceViewToBeNonLayoutOnly(NativeViewHierarchyOptimizer.java:219)
        at com.facebook.react.views.text.ReactBaseTextShadowNode.spannedFromShadowNode(ReactBaseTextShadowNode.java:291)
        at com.facebook.react.views.text.ReactTextShadowNode.onBeforeLayout(ReactTextShadowNode.java:248)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:867)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:865)
        at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:628)
        at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:594)
        at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:799)
        at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:119)
        at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:171)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:166)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:784)

`

**Comment by yedidyak** [comment]
@aspidvip can I ask why you closed this? Did you find what caused this crash?
