### ISSUE TITLE
Kotlin compile daemon was not successful

### ISSUE THREAD

**Issue by sharifashraful** [wix/react-native-navigation#7285]
ompilation with Kotlin compile daemon was not successful
java.rmi.ServerError: Error occurred in server thread; nested exception is:
        java.lang.AssertionError: Could not delete caches dir E:\mobile apps\Pathabo\node_modules\react-native-navigation\lib\android\app\build\kotlin\compileReactNative63DebugKotlin
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:352)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)

## Your Environment
    "react": "17.0.2",
    "react-native": "0.66.0",
    "react-native-navigation": "^7.22.0",

**Comment by svbutko** [comment]
@sharifashraful it will be fixed soon, if you need a fix now, try applying changes made here: #7287
