### ISSUE TITLE
[Android] ConcurrentModificationException with overlays

### ISSUE THREAD

**Issue by jeremybarbet** [wix/react-native-navigation#7349]
## 🐛 Bug Report

Hi!

I'm getting a lot of the following error reported through Sentry/Play Store vitals. From what I can understand in the stack trace, it's related to the destroy method for the overlay.

~Unfortunately, I'm not able to reproduce the error on my side. I've tried many things but can't recreate it~

```bash
java.util.ConcurrentModificationException: null
    at java.util.LinkedHashMap$LinkedHashIterator.remove(LinkedHashMap.java:770)
    at com.reactnativenavigation.viewcontrollers.overlay.OverlayManager.destroy(OverlayManager.kt:50)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.destroyViews(Navigator.java:123)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.destroy(Navigator.java:117)
    at com.reactnativenavigation.NavigationActivity.onDestroy(NavigationActivity.java:88)
    at android.app.Activity.performDestroy(Activity.java:8404)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5452)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5496)
    at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:255)
    at android.app.ActivityThread.main(ActivityThread.java:8192)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
java.lang.RuntimeException: Unable to destroy activity {com.helloaurora/com.helloaurora.MainActivity}: java.util.ConcurrentModificationException
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5467)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5496)
    at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:255)
    at android.app.ActivityThread.main(ActivityThread.java:8192)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

After trying to use `Navigation.dismissAllOverlays();` ([doc](https://wix.github.io/react-native-navigation/api/overlay/#dismissalloverlays)) I was able to reproduce the crash with the stack trace above. (I will try to reproduce the issue on a vanilla repo soon).

In the meantime, I reverted the kotlin migration for the OverlayManager and reuse the java class. So far, it doesn't produce the error above.

Here is the patch I'm using:

```diff
diff --git a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.java b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.java
new file mode 100644
index 0000000..6663bd2
--- /dev/null
+++ b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.java
@@ -0,0 +1,81 @@
+package com.reactnativenavigation.viewcontrollers.overlay;
+
+import android.content.res.Configuration;
+import android.view.View;
+import android.view.ViewGroup;
+
+import com.reactnativenavigation.react.CommandListener;
+import com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController;
+import com.reactnativenavigation.views.BehaviourDelegate;
+
+import java.util.Collection;
+import java.util.HashMap;
+
+import static com.reactnativenavigation.utils.CollectionUtils.*;
+import static com.reactnativenavigation.utils.CoordinatorLayoutUtils.matchParentWithBehaviour;
+
+public class OverlayManager {
+  private final HashMap<String, ViewController> overlayRegistry = new HashMap<>();
+
+  public void show(ViewGroup overlaysContainer, ViewController overlay, CommandListener listener) {
+    overlaysContainer.setVisibility(View.VISIBLE);
+    overlayRegistry.put(overlay.getId(), overlay);
+    overlay.addOnAppearedListener(() -> {
+      overlay.onViewDidAppear();
+      listener.onSuccess(overlay.getId());
+    });
+    overlaysContainer.addView(overlay.getView(), matchParentWithBehaviour(new BehaviourDelegate(overlay)));
+  }
+
+  public void onConfigurationChanged(Configuration configuration){
+    final Collection<ViewController> values = overlayRegistry.values();
+    for(ViewController controller : values){
+      controller.onConfigurationChanged(configuration);
+    }
+  }
+
+  public void dismiss(ViewGroup overlaysContainer, String componentId, CommandListener listener) {
+    ViewController overlay = overlayRegistry.get(componentId);
+    if (overlay == null) {
+      listener.onError("Could not dismiss Overlay. Overlay with id " + componentId + " was not found.");
+    } else {
+      destroyOverlay(overlaysContainer, overlay);
+      listener.onSuccess(componentId);
+    }
+  }
+
+  public void dismissAll(ViewGroup overlaysContainer, CommandListener listener) {
+    destroy(overlaysContainer);
+    listener.onSuccess("");
+  }
+
+  public void destroy(ViewGroup overlaysContainer) {
+    forEach(overlayRegistry.values(), overlay -> destroyOverlay(overlaysContainer, overlay));
+  }
+
+  public int size() {
+    return overlayRegistry.size();
+  }
+
+  public ViewController findControllerById(String id) {
+    return overlayRegistry.get(id);
+  }
+
+  public void onHostPause() {
+    forEach(overlayRegistry.values(), overlay -> overlay.onViewDisappear());
+  }
+
+  public void onHostResume() {
+    forEach(overlayRegistry.values(), overlay -> overlay.onViewDidAppear());
+  }
+
+  private void destroyOverlay(ViewGroup overlaysContainer, ViewController overlay) {
+    overlay.destroy();
+    overlayRegistry.remove(overlay.getId());
+    if (isEmpty()) overlaysContainer.setVisibility(View.GONE);
+  }
+
+  private boolean isEmpty() {
+    return size() == 0;
+  }
+}
diff --git a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt
deleted file mode 100644
index 7ed36cb..0000000
--- a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt
+++ /dev/null
@@ -1,71 +0,0 @@
-package com.reactnativenavigation.viewcontrollers.overlay
-
-import android.content.res.Configuration
-import android.view.View
-import android.view.ViewGroup
-import com.reactnativenavigation.react.CommandListener
-import com.reactnativenavigation.utils.CoordinatorLayoutUtils
-import com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController
-import com.reactnativenavigation.views.BehaviourDelegate
-
-class OverlayManager {
-    private val overlayRegistry = mutableMapOf<String, ViewController<*>>()
-    fun show(overlaysContainer: ViewGroup, overlay: ViewController<*>, listener: CommandListener) {
-        overlaysContainer.visibility = View.VISIBLE
-        overlayRegistry[overlay.id] = overlay
-        overlay.addOnAppearedListener {
-            overlay.onViewDidAppear()
-            listener.onSuccess(overlay.id)
-        }
-        overlaysContainer.addView(
-            overlay.view,
-            CoordinatorLayoutUtils.matchParentWithBehaviour(BehaviourDelegate(overlay))
-        )
-    }
-
-    fun onConfigurationChanged(configuration: Configuration?) {
-        overlayRegistry.values.forEach { controller -> controller.onConfigurationChanged(configuration) }
-    }
-
-    fun dismiss(overlaysContainer: ViewGroup, componentId: String, listener: CommandListener) {
-        val overlay = overlayRegistry[componentId]
-        if (overlay == null) {
-            listener.onError("Could not dismiss Overlay. Overlay with id $componentId was not found.")
-        } else {
-            destroyOverlay(overlaysContainer, overlay)
-            listener.onSuccess(componentId)
-        }
-    }
-
-    fun dismissAll(overlaysContainer: ViewGroup, listener: CommandListener) {
-        destroy(overlaysContainer)
-        listener.onSuccess("")
-    }
-
-    fun destroy(overlaysContainer: ViewGroup) {
-        overlayRegistry.values.forEach { overlay -> destroyOverlay(overlaysContainer, overlay) }
-    }
-
-    fun size() = overlayRegistry.size
-
-    fun findControllerById(id: String?): ViewController<*>? {
-        return overlayRegistry[id]
-    }
-
-    private fun destroyOverlay(overlaysContainer: ViewGroup, overlay: ViewController<*>) {
-        overlay.destroy()
-        overlayRegistry.remove(overlay.id)
-        if (isEmpty) overlaysContainer.visibility = View.GONE
-    }
-
-    private val isEmpty: Boolean
-        get() = size() == 0
-
-    fun onHostPause() {
-        overlayRegistry.values.forEach(ViewController<*>::onViewDisappear)
-    }
-
-    fun onHostResume() {
-        overlayRegistry.values.forEach(ViewController<*>::onViewDidAppear)
-    }
-}
\ No newline at end of file
```

At least, when running `Navigation.dismissAllOverlays();` the app doesn't crash anymore. I'm gonna release an update on the Play Store and see if the crashes are dropping.

I'm not sure where the issue stands in the kotlin code, I'm not experienced enough with Kotlin to see it.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

I will try setup a reproduction repo very soon. Hopefully I will be able to reproduce in a minimal environment.

## Expected behavior

To not crash

## Actual Behavior

Crash when calling `Navigation.dismissAllOverlays();`

## Your Environment

- React Native Navigation version: 7.22.3
- React Native version: 0.66.0
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Android 9, 10, 11

## Reproducible Demo

See "To Reproduce" section

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by N3TC4T** [comment]
I see the same crashes, this should fixe the issue.

```
diff --git a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt
index 7ed36cb..9c71fdc 100644
--- a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt
+++ b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt
@@ -43,7 +43,10 @@ class OverlayManager {
     }
 
     fun destroy(overlaysContainer: ViewGroup) {
-        overlayRegistry.values.forEach { overlay -> destroyOverlay(overlaysContainer, overlay) }
+        val overlays: MutableList<ViewController<*>> = overlayRegistry.values.toMutableList()
+        for(overlay in overlays) {
+            destroyOverlay(overlaysContainer, overlay)
+        }
     }
 
     fun size() = overlayRegistry.size
```

**Comment by swabbass** [comment]
Thx @jeremybarbet and @N3TC4T.

Nice catch dudes :], the issue is that we are modifying the map (removing items), which is based on `LinkedHashMap` under the hood which, while in a loop that uses an iterator which in turn got changed, and that raises the exception.

[See javadoc:](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html)

**The iterators returned by the iterator method of the collections returned by all of this class's collection view methods are fail-fast: if the map is structurally modified at any time after the iterator is created, in any way except through the iterator's own remove method, the iterator will throw a ConcurrentModificationException. Thus, in the face of concurrent modification, the iterator fails quickly and cleanly, rather than risking arbitrary, non-deterministic behavior at an undetermined time in the future.**
