### ISSUE TITLE
[Android] Application crashes at codepush updates after upgrading to RNN 7.24.3

### ISSUE THREAD

**Issue by ACOSW** [wix/react-native-navigation#7419]
## 🐛 Bug Report

After upgrading to RNN 7.24.3 from 7.17.1 my application is crashing after codepush updates on Android. Crash appears at the moment when codepush update is installed and the application is trying to do a restart. 
Crash appears only when there is a downloaded codepush update that is ready to run and application is restarting, no matter how restart was triggered, automatically after update download or manually over time. Simple “Codepush.restartApp()” without an update is not causing a crash.
I’ve tried updating react-native to 0.65 and 0.66, and react-native-code-push but always had the same error after codepush update installed. I am pretty sure that problem is in react-native-navigation package because when I do a rollback with the same code to RNN 7.17.1 - everything is fine and the application is not crashing after codepush updates.

Error is **“​​android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.”**

### Stack trace
```
2022-01-04 17:27:06.239 22036-22201/com.application.test E/ReactNativeJNI: logMarker CREATE_REACT_CONTEXT_END
2022-01-04 17:27:06.239 22036-22200/com.application.test E/unknown:ReactNative: ReactInstanceManager.createReactContext: mJSIModulePackage null
2022-01-04 17:27:06.240 22036-22201/com.application.test E/ReactNativeJNI: logMarker RUN_JS_BUNDLE_START
2022-01-04 17:27:06.249 22036-22202/com.application.test E/unknown:DisabledDevSupportManager: Caught exception
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
        at android.view.ViewRootImpl.requestFitSystemWindows(ViewRootImpl.java:1742)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestApplyInsets(View.java:11840)
        at com.reactnativenavigation.viewcontrollers.component.ComponentViewController.onViewDidAppear(ComponentViewController.java:81)
        at com.reactnativenavigation.viewcontrollers.overlay.OverlayManager.onHostResume(OverlayManager.kt:74)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.onHostResume(Navigator.java:281)
        at com.reactnativenavigation.react.NavigationModule$1.onHostResume(NavigationModule.java:75)
        at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:240)
        at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:715)
        at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:750)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1079)
        at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1037)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:920)
2022-01-04 17:27:06.253 22036-22202/com.application.test E/unknown:ReactNative: ReactInstanceManager caught exception in setupReactContext
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
        at android.view.ViewRootImpl.requestFitSystemWindows(ViewRootImpl.java:1742)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestApplyInsets(View.java:11840)
        at com.reactnativenavigation.viewcontrollers.component.ComponentViewController.onViewDidAppear(ComponentViewController.java:81)
        at com.reactnativenavigation.viewcontrollers.overlay.OverlayManager.onHostResume(OverlayManager.kt:74)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.onHostResume(Navigator.java:281)
        at com.reactnativenavigation.react.NavigationModule$1.onHostResume(NavigationModule.java:75)
        at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:240)
        at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:715)
        at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:750)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1079)
        at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1037)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:920)
2022-01-04 17:27:06.253 22036-22202/com.application.test E/unknown:DisabledDevSupportManager: Caught exception
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
        at android.view.ViewRootImpl.requestFitSystemWindows(ViewRootImpl.java:1742)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestApplyInsets(View.java:11840)
        at com.reactnativenavigation.viewcontrollers.component.ComponentViewController.onViewDidAppear(ComponentViewController.java:81)
        at com.reactnativenavigation.viewcontrollers.overlay.OverlayManager.onHostResume(OverlayManager.kt:74)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.onHostResume(Navigator.java:281)
        at com.reactnativenavigation.react.NavigationModule$1.onHostResume(NavigationModule.java:75)
        at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:240)
        at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:715)
        at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:750)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1079)
        at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1037)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:920)
2022-01-04 17:27:06.253 22036-22202/com.application.test E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
        at android.view.ViewRootImpl.requestFitSystemWindows(ViewRootImpl.java:1742)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestApplyInsets(View.java:11840)
        at com.reactnativenavigation.viewcontrollers.component.ComponentViewController.onViewDidAppear(ComponentViewController.java:81)
        at com.reactnativenavigation.viewcontrollers.overlay.OverlayManager.onHostResume(OverlayManager.kt:74)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.onHostResume(Navigator.java:281)
        at com.reactnativenavigation.react.NavigationModule$1.onHostResume(NavigationModule.java:75)
        at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:240)
        at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:715)
        at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:750)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1079)
        at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1037)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:920)
2022-01-04 17:27:06.255 22036-22202/com.application.test E/unknown:DisabledDevSupportManager: Caught exception
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
        at android.view.ViewRootImpl.requestFitSystemWindows(ViewRootImpl.java:1742)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestApplyInsets(View.java:11840)
        at com.reactnativenavigation.viewcontrollers.component.ComponentViewController.onViewDidAppear(ComponentViewController.java:81)
        at com.reactnativenavigation.viewcontrollers.overlay.OverlayManager.onHostResume(OverlayManager.kt:74)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.onHostResume(Navigator.java:281)
        at com.reactnativenavigation.react.NavigationModule$1.onHostResume(NavigationModule.java:75)
        at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:240)
        at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:715)
        at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:750)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1079)
        at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1037)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:920)
2022-01-04 17:27:06.255 22036-22202/com.application.test E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.application.test, PID: 22036
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
        at android.view.ViewRootImpl.requestFitSystemWindows(ViewRootImpl.java:1742)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestFitSystemWindows(View.java:11832)
        at android.view.View.requestApplyInsets(View.java:11840)
        at com.reactnativenavigation.viewcontrollers.component.ComponentViewController.onViewDidAppear(ComponentViewController.java:81)
        at com.reactnativenavigation.viewcontrollers.overlay.OverlayManager.onHostResume(OverlayManager.kt:74)
        at com.reactnativenavigation.viewcontrollers.navigator.Navigator.onHostResume(Navigator.java:281)
        at com.reactnativenavigation.react.NavigationModule$1.onHostResume(NavigationModule.java:75)
        at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:240)
        at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:715)
        at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:750)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1079)
        at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1037)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:920)
```
### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?
 
Yes

## To Reproduce

1. Create codepush update using appcenter cli
2. Open android application and install update

## Expected behavior

Application restarts without crash

## Actual Behavior

Application crashes when it should restart with an installed update

## Your Environment

- React Native Navigation version: 7.24.3
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): device and simulator Android 12, production

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by ACOSW** [comment]
I've made a clean new project to easy reproduce of this bug
https://github.com/ACOSW/rnn7243_codepush_crash

**Comment by ACOSW** [comment]
I've investigated deeper into this problem. So looks like #7411 only made this problem visible, and this issue existed far before.
Sometimes extra navigation stack root created while codepush making `instanceManager.recreateReactContextInBackground()`. I've managed to make this reproducible with a simple `Codepush.restartApp` call.

So in the logs we can see very strange thing:
```
2022-01-11 16:08:30.210 5430-5455/com.test66 I/ReactNativeJS: Navigation.registerAppLaunchedListener - run application
2022-01-11 16:08:30.302 5430-5455/com.test66 I/ReactNativeJS: Running "com.myApp.WelcomeScreen" with {"initialProps":{"componentId":"Component1"},"rootTag":1} 
2022-01-11 16:08:30.499 5430-5455/com.test66 I/ReactNativeJS: Mount App component with ID:885 
2022-01-11 16:08:33.195 5430-5456/com.test66 D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
2022-01-11 16:08:33.195 5430-5456/com.test66 D/ReactNative: [CodePush] Restarting app
2022-01-11 16:08:33.349 5430-5473/com.test66 I/ReactNativeJS: Running "com.myApp.WelcomeScreen" with {"initialProps":{"componentId":"Component1"},"rootTag":11} 
2022-01-11 16:08:33.493 5430-5473/com.test66 I/ReactNativeJS: Mount App component with ID:865
2022-01-11 16:08:33.499 5430-5473/com.test66 I/ReactNativeJS: Navigation.registerAppLaunchedListener - run application
2022-01-11 16:08:33.512 5430-5473/com.test66 I/ReactNativeJS: Unmount App component with ID:865
2022-01-11 16:08:33.541 5430-5473/com.test66 I/ReactNativeJS: Running "com.myApp.WelcomeScreen" with {"initialProps":{"componentId":"Component1"},"rootTag":21}
2022-01-11 16:08:33.580 5430-5473/com.test66 I/ReactNativeJS: Mount App component with ID:872
```

As we see, after `instanceManager.recreateReactContextInBackground()` new root tag 11 is created with component ID: 865, then component 865 magically unmounts and new root tag 21 created again with new component 872. So when `view.requestApplyInsets` from ComponentViewController.java:81 (#7411 ) is called on this views like ID: 865 we are receiving crash.

**Comment by mcapocaccia** [comment]
I cannot say more on the reason for the crash, which we also experience, but line 81 of 

https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java

has a clear bug:

    @Override
    public void onViewDidAppear() {
        if (view != null)
            view.sendComponentWillStart();
        super.onViewDidAppear();
        view.requestApplyInsets();  <== BUG HERE
        if (view != null && lastVisibilityState == VisibilityState.Disappear) view.sendComponentStart();
        lastVisibilityState = VisibilityState.Appear;
    }

requestApplyInsets is called on view, which both above and below is tested for existence but NOT in this line.

**Comment by guyca** [comment]
The error happens because RNN tried to interact with views on the react thread, and not on the UI thread. Wrap [OverlayManager.onHostResume](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt#L145) and [OverlayManager.onHostPause](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt#L141) with [runOnMainThread](https://github.com/wix/react-native-navigation/blob/119469b8018fd0eb084f0ec6978bd93b56eb64aa/lib/android/app/src/main/java/com/reactnativenavigation/utils/UiUtils.java#L83).

**Comment by ACOSW** [comment]
@guyca thank you for your advice. I've tried to wrap [OverlayManager.onHostResume](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt#L145) and [OverlayManager.onHostPause](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManager.kt#L141) methods but it didn't work for me so i've decided to wrap a higher level call and it works now. I don't get this kind of error now. 
Pull request is ready for review. 
The only thing that I’m worried about is that after restarting an application there is an ”extra startup”. 
What i mean is when the application is started we can see in logs 
```
Running "com.myApp.WelcomeScreen" with {"initialProps":{"componentId":"Component1"},"rootTag":1}`.
```
When restart is triggered by something like react-native-codepush or react-native-restart we can see in logs:
```
Running "com.myApp.WelcomeScreen" with {"initialProps":{"componentId":"Component1"},"rootTag":11}
Running "com.myApp.WelcomeScreen" with {"initialProps":{"componentId":"Component1"},"rootTag":21}
```
Expected behavior is only one new root with rootTag 11.
I think sometimes this can produce crashes with error like this:
```
2022-02-15 16:49:58.068 26013-11908/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: test.app, PID: 26013
    com.facebook.react.common.JavascriptException: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
          This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes, stack:
    invariant@1:158513
    __callFunction@1:164996
    anonymous@1:163545
    __guard@1:164502
    callFunctionReturnFlushedQueue@1:163503
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:246)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)

```
But i thing i should crate a new issue for this problem when PR #7459 will be merged.
