### ISSUE TITLE
[Android] Crash onViewDidAppear() in ComponentViewController, due to missing existence check

### ISSUE THREAD

**Issue by mcapocaccia** [wix/react-native-navigation#7420]
## 🐛 Bug Report

**RNN 7.24.3, still present in RNN 7.25.0**

We experience several crashes when showing an animated modal.

> java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.views.component.ComponentLayout.requestApplyInsets()' on a null object reference
    at com.reactnativenavigation.viewcontrollers.component.ComponentViewController.onViewDidAppear(ComponentViewController.java:81)
    at com.reactnativenavigation.viewcontrollers.modal.ModalPresenter.onShowModalEnd(ModalPresenter.java:93)
    at com.reactnativenavigation.viewcontrollers.modal.ModalPresenter.access$000(ModalPresenter.java:20)
    at com.reactnativenavigation.viewcontrollers.modal.ModalPresenter$1.onEnd(ModalPresenter.java:82)
    at com.reactnativenavigation.viewcontrollers.modal.ModalAnimator$createShowModalAnimator$1.onAnimationEnd(ModalAnimator.kt:120)
    at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
    at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
    at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
    at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
    at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
    at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1055)
    at android.view.Choreographer.doCallbacks(Choreographer.java:875)
    at android.view.Choreographer.doFrame(Choreographer.java:772)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
    at android.os.Handler.handleCallback(Handler.java:888)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8178)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

Inspecting https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java

we noticed line 81 does NOT test for existence of "view", 
like other lines above and below in the same function correctly do:

> public void onViewDidAppear() {
    if (view != null)
        view.sendComponentWillStart();
    super.onViewDidAppear();
    view.requestApplyInsets();  **<== BUG HERE**
    if (view != null && lastVisibilityState == VisibilityState.Disappear) view.sendComponentStart();
    lastVisibilityState = VisibilityState.Appear;
}

@swabbass @yogevbd :
Probably introduced by #7411

Please add "if (view != null)" test

**Comment by swabbass** [comment]
Appreciated, really thanks, soon patch will be available!

**Comment by mcapocaccia** [comment]
You're welcome @swabbass.

If you can you could also check that the insets call, which affects the underlying android.view.ViewRootImpl, happens within an allowed thread.

See also #7419

This is the additional crash we tracked:

> android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7931)
    at android.view.ViewRootImpl.requestFitSystemWindows(ViewRootImpl.java:1275)
    at android.view.View.requestFitSystemWindows(View.java:9361)
    at android.view.View.requestFitSystemWindows(View.java:9361)
    at android.view.View.requestFitSystemWindows(View.java:9361)
    at android.view.View.requestFitSystemWindows(View.java:9361)
    at android.view.View.requestFitSystemWindows(View.java:9361)
    at android.view.View.requestFitSystemWindows(View.java:9361)
    at android.view.View.requestFitSystemWindows(View.java:9361)
    at android.view.View.requestFitSystemWindows(View.java:9361)
    at android.view.View.requestFitSystemWindows(View.java:9361)
    at android.view.View.requestApplyInsets(View.java:9369)
    at com.reactnativenavigation.viewcontrollers.component.ComponentViewController.onViewDidAppear(ComponentViewController.java:81)
    at com.reactnativenavigation.viewcontrollers.parent.ParentController.onViewDidAppear(ParentController.java:51)
    at com.reactnativenavigation.viewcontrollers.parent.ParentController.onViewDidAppear(ParentController.java:51)
    at com.reactnativenavigation.viewcontrollers.parent.ParentController.onViewDidAppear(ParentController.java:51)
    at com.reactnativenavigation.viewcontrollers.navigator.Navigator.onHostResume(Navigator.java:288)
    at com.reactnativenavigation.react.NavigationModule$1.onHostResume(NavigationModule.java:75)
    at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:263)
    at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:741)
    at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:776)
    at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1128)
    at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java:136)
    at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1086)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:166)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:784)

**Comment by geroale** [comment]
Same issue here

**Comment by marf** [comment]
We have the exact same issue. We applied the fix suggested, thanks!
Could this be fixed on the main repo too and a new version released on NPM?

Thank you!

**Comment by N3TC4T** [comment]
@yogevbd I see there was a release couple of days ago under `7.25.1` and I see the fix for this issue is already included in the https://github.com/wix/react-native-navigation/pull/7414 which already merged to the master, but it's not included in the published NPM release.

**Comment by swabbass** [comment]
Soon it will be published I think, @yogevbd  how about making 7.26.0? or do you prefer creating a patch from 7.25.1 and having a fix for this specific issue?

**Comment by SYoder1** [comment]
@swabbass Is there a ETA on when it will be published? We are running into the exact same issue.

**Comment by swabbass** [comment]
@SYoder1, I'll separate the logic inside the PR and release a version by the end of this week.

**Comment by Nikola-Andreev** [comment]
Any progress here?
