### ISSUE TITLE
StackAnimator.java line 16

### ISSUE THREAD

**Issue by DenisPostnikov** [wix/react-native-navigation#7528]
## Stack trace

> Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
       at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
       at com.reactnativenavigation.viewcontrollers.stack.StackAnimator.a(StackAnimator.java:16)
       at com.reactnativenavigation.viewcontrollers.stack.StackController.b(StackController.java:14)
       at com.reactnativenavigation.viewcontrollers.navigator.Navigator.access$100(Navigator.java)
       at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$6YHGUSLaD84rI4FDOzUBNdItzg8.run(-.java:6)
       at com.reactnativenavigation.viewcontrollers.navigator.Navigator.a(Navigator.java:2)
       at com.reactnativenavigation.viewcontrollers.navigator.-$$Lambda$Navigator$BztKRmJef9zlTqPlTta6T7nWHGw.run(-.java:2)
       at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.b(ViewController.java:8)
       at com.reactnativenavigation.viewcontrollers.navigator.Navigator.a(Navigator.java:21)
       at com.reactnativenavigation.viewcontrollers.navigator.Navigator.c(Navigator.java:5)
       at com.reactnativenavigation.react.NavigationModule.lambda$popToRoot$7(NavigationModule.java:22)
       at com.reactnativenavigation.react.-$$Lambda$NavigationModule$ak6fhLVnG4pjb9NVFqcU0ewBsPI.run(-.java:10)
       at com.reactnativenavigation.react.NavigationModule.a(NavigationModule.java:16)
       at com.reactnativenavigation.react.-$$Lambda$NavigationModule$_KMLiCFir6_k6qF7P2pzVizFOwk.run(-.java:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7868)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

## Environment

- React Native Navigation version: '6.12.2'
- React Native version: '0.63.4'
- Platform(s) Android
- Device info: Android 11, moto g stylus (2021)

**Comment by SYoder1** [comment]
I am seeing the same issues on 

"react-native-navigation": "7.28.0",
"react-native": "0.68.2",

**Comment by Japoncio3k** [comment]
I have the same issue on 
"react-native-navigation": "7.32.1"
"react-native": "0.71.2"

**Comment by bharatgupta99** [comment]
Same issue on:
"react-native-navigation": "7.31.1"
"react-native": "0.70.12"

**Comment by yedidyak** [comment]
Closing this as part of a maintainer cleanup of open issues older than one year.

Decision: Closed: stale/non-critical; no evidence it is a critical current-version RNN issue.

If this still reproduces on the latest React Native Navigation with a minimal reproduction, please open a new issue with current RN/RNN versions and repro steps.
