### ISSUE TITLE
Attempt to invoke virtual method 'dx1 bw1.g()' on a null object reference

### ISSUE THREAD

**Issue by marf** [wix/react-native-navigation#7531]
## 🐛 Bug Report

Hello, we see this crash on Android mobile devices.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'dx1 bw1.g()' on a null object reference
       at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:213)
       at com.reactnativenavigation.react.NavigationModule.access$100(NavigationModule.java:39)
       at com.reactnativenavigation.react.NavigationModule$1.lambda$onHostPause$0(NavigationModule.java:62)
       at com.reactnativenavigation.react.NavigationModule$1.$r8$lambda$188Rw-Gn_-JcbOeFEeH40BTzx_c(NavigationModule.java)
       at com.reactnativenavigation.react.NavigationModule$1$$InternalSyntheticLambda$0$b0197b1cf9fbe4d3c36c604e9bf2d7984edd8cd7c195b97aa17cf10b52497c8e$0.run(NavigationModule.java:2)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

We use RN 0.68 and RNN 7.28.0.

Any ideas on how to solve this?

Thanks!

**Comment by YazeedAsaad** [comment]
encountering same issue here after upgrading to 0.68 , the crash is also happening on RNN versions (7.21.0,7.26.0,7.27.1) (we tried downgrading to resolve the issue but it seems related to RN 0.68 with RNN mainly, the error stack is kind of the same but we get:

`java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference
        at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:213)
        at com.reactnativenavigation.react.NavigationModule.access$100(NavigationModule.java:39)
        at com.reactnativenavigation.react.NavigationModule$1.lambda$onHostResume$1$com-reactnativenavigation-react-NavigationModule$1(NavigationModule.java:75)
        at com.reactnativenavigation.react.NavigationModule$1$$ExternalSyntheticLambda1.run(Unknown:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

**Comment by marf** [comment]
Any workaround or quick fix? We see lot of crashes in our app because of this problem :(

**Comment by ali-sao** [comment]
@YazeedAsaad , you know why am here

**Comment by manuhook** [comment]
Same problem on our app.

@YazeedAsaad  what was your last working version without this issue ? (for me 7.23.1) Thanks ! 

```
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError: java.lang.RuntimeException: Tried to create view after it has already been destroyed
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.getView(ViewController.java:205)
	at com.reactnativenavigation.viewcontrollers.child.ChildController.getView(ChildController.java:38)
	at com.reactnativenavigation.viewcontrollers.stack.StackAnimator.pushWithoutElementTransitions$lambda-2(StackAnimator.kt:246)
	at com.reactnativenavigation.viewcontrollers.stack.StackAnimator.lambda$EAGGHNE2N95u0X1aoEzfvsq8NOU(Unknown Source:0)
	at com.reactnativenavigation.viewcontrollers.stack.-$$Lambda$StackAnimator$EAGGHNE2N95u0X1aoEzfvsq8NOU.run(Unknown Source:12)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.-$$Lambda$WyAR0JEWmTiz3cWwZS9qp-P3Ddg.on(Unknown Source:2)
	at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:133)
	at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:127)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.lambda$onViewWillAppear$3(ViewController.java:257)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.lambda$onViewWillAppear$3$ViewController(Unknown Source:0)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.-$$Lambda$ViewController$bfiHoKoA1KmT9QaA3BqT2KEB6CQ.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

       at .<unknown>(.java)
       at .<unknown>(.java)
       at .<unknown>(.java)
       at .com.reactnativenavigation.viewcontrollers.stack.StackAnimator.lambda$EAGGHNE2N95u0X1aoEzfvsq8NOU(Unknown(StackAnimator.java)
       at .com.reactnativenavigation.viewcontrollers.stack.-$$Lambda$StackAnimator$EAGGHNE2N95u0X1aoEzfvsq8NOU.run(Unknown(-.java)
       at .com.reactnativenavigation.viewcontrollers.viewcontroller.-$$Lambda$WyAR0JEWmTiz3cWwZS9qp-P3Ddg.on(Unknown(-.java)
       at .<unknown>(.java)
       at .<unknown>(.java)
       at .<unknown>(.java)
       at .com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.lambda$onViewWillAppear$3$ViewController(Unknown(ViewController.java)
       at .com.reactnativenavigation.viewcontrollers.viewcontroller.-$$Lambda$ViewController$bfiHoKoA1KmT9QaA3BqT2KEB6CQ.run(Unknown(-.java)
       at .<unknown>(.java)
       at .<unknown>(.java)
       at .<unknown>(.java)
       at .<unknown>(.java)
       at .<unknown>(.java)
       at .<unknown>(.java)
       at .anonymous(.java)
       at .apply(.java)
       at .__invokeCallback(.java)
       at .anonymous(.java)
       at .__guard(.java)
       at .invokeCallbackAndReturnFlushedQueue(.java)
```

**Comment by SYoder1** [comment]
I am seeing the same issue as well, across different OS versions. 6.0.1 all the way to 12. 

"react-native": "0.68.2",
"react-native-navigation": "7.28.0",

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference
        at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:213)
        at com.reactnativenavigation.react.NavigationModule.access$100(NavigationModule.java:39)
        at com.reactnativenavigation.react.NavigationModule$1.lambda$onHostPause$0$com-reactnativenavigation-react-NavigationModule$1(NavigationModule.java:62)
        at com.reactnativenavigation.react.NavigationModule$1$$ExternalSyntheticLambda0.run(Unknown:2)
        at android.os.Handler.handleCallback(Handler.java:978)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loopOnce(Looper.java:238)
        at android.os.Looper.loop(Looper.java:357)
        at android.app.ActivityThread.main(ActivityThread.java:8090)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

**Comment by manuhook** [comment]
Hi @guyca, please can you check this issue with getNavigator() ? 
seems it has been already fixed once in the past : https://github.com/wix/react-native-navigation/issues/5996

**Comment by marf** [comment]
Any thoughts or ideas on how to fix this?

**Comment by tarouboy** [comment]
We're still getting this error on production, we can't reproduce it tho.

RN 0.70.6
RNN 7.30.3

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference
com.reactnativenavigation.react.NavigationModule.navigator (NavigationModule.java:213)
com.reactnativenavigation.react.NavigationModule.access$100 (NavigationModule.java:39)
com.reactnativenavigation.react.NavigationModule$1.lambda$onHostPause$0$com-reactnativenavigation-react-NavigationModule$1 (NavigationModule.java:62)
com.reactnativenavigation.react.NavigationModule$1$$ExternalSyntheticLambda0.run (Unknown Source:2)
```

**Comment by N3TC4T** [comment]
@guyca it seems that sometime the activity is null in `onHostPause` can this https://github.com/wix/react-native-navigation/commit/910193051447c4e523896c7f6751e4e9633eba7a commit be the cause of this issue ?

we may also add the condition to check for null activity `getCurrentActivity() != null`
https://github.com/wix/react-native-navigation/blob/438e10a3ee34120096394f7604b2693b76a49c12/lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java#L62

**Comment by mcapocaccia** [comment]
Should be fixed by this patch https://github.com/wix/react-native-navigation/issues/7593#issuecomment-1245475643

**Comment by mcapocaccia** [comment]
@guyca it seems the patch I suggested in this link https://github.com/wix/react-native-navigation/issues/7593#issuecomment-1245475643 hasn't been fully applied even in the current master.

onHostPause and onHostResume are now indeed called in the main thread, but it still wrongly counts on navigator() having a valid value

**Comment by gigby** [comment]
I got the same (or almost the same issue) on Android 12L device:
`java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference`

RN: 0.68

buildToolsVersion = "31.0.0"
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 33
        
"react-native-navigation": "7.28.1",

**Comment by gigby** [comment]
> We're still getting this error on production after upgrading to latest version, couldn't reproduce it tho.
> 
> RN 0.70.6 RNN 7.30.3
> 
> ```
> Fatal Exception: java.lang.NullPointerException
> Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference
> com.reactnativenavigation.react.NavigationModule.navigator (NavigationModule.java:213)
> com.reactnativenavigation.react.NavigationModule.access$100 (NavigationModule.java:39)
> com.reactnativenavigation.react.NavigationModule$1.lambda$onHostPause$0$com-reactnativenavigation-react-NavigationModule$1 (NavigationModule.java:62)
> com.reactnativenavigation.react.NavigationModule$1$$ExternalSyntheticLambda0.run (Unknown Source:2)
> ```

Try to open your app via Samsung Galaxy Fold3/4/5 and you probably will able to see this issue.

**Comment by PaoloSalta** [comment]
We are getting a similar error, but we are not able to reproduce it.

RN 0.72.7
RNN 7.37.1

Fatal Exception: java.lang.RuntimeException
Unable to pause activity {.........}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnativenavigation.viewcontrollers.navigator.Navigator com.reactnativenavigation.NavigationActivity.getNavigator()' on a null object reference

**Comment by yedidyak** [comment]
Closing this as part of a maintainer cleanup of open issues older than one year.

Decision: Closed: stale/non-critical; no evidence it is a critical current-version RNN issue.

If this still reproduces on the latest React Native Navigation with a minimal reproduction, please open a new issue with current RN/RNN versions and repro steps.
