### ISSUE TITLE
Android SharedElementTransition crash: Unsupported ScaleType MATRIX

### ISSUE THREAD

**Issue by huynqjmango360** [wix/react-native-navigation#7549]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: au.com.jmango360.magento, PID: 26302
    java.lang.RuntimeException: Unsupported ScaleType MATRIX
        at com.reactnativenavigation.views.element.animators.FastImageMatrixAnimator.createTransformMatrix(FastImageMatrixAnimator.kt:64)
        at com.reactnativenavigation.views.element.animators.FastImageMatrixAnimator.create(FastImageMatrixAnimator.kt:32)
        at com.reactnativenavigation.views.element.SharedElementTransition.createAnimators(SharedElementTransition.kt:25)
        at com.reactnativenavigation.views.element.TransitionAnimatorCreator.createSharedElementAnimator(TransitionAnimatorCreator.kt:80)
        at com.reactnativenavigation.views.element.TransitionAnimatorCreator.createSharedElementTransitionAnimators(TransitionAnimatorCreator.kt:73)
        at com.reactnativenavigation.views.element.TransitionAnimatorCreator.createAnimator(TransitionAnimatorCreator.kt:34)
        at com.reactnativenavigation.views.element.TransitionAnimatorCreator.create(TransitionAnimatorCreator.kt:27)
        at com.reactnativenavigation.views.element.TransitionAnimatorCreator$create$1.invokeSuspend(Unknown Source:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
        at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:355)
        at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:41)
        at com.reactnativenavigation.views.element.finder.ExistingViewFinder$resumeOnImageLoad$1$1.run(ExistingViewFinder.kt:43)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by yedidyak** [comment]
Closing this as part of a maintainer cleanup of open issues older than one year.

Decision: Closed: stale/non-critical; no evidence it is a critical current-version RNN issue.

If this still reproduces on the latest React Native Navigation with a minimal reproduction, please open a new issue with current RN/RNN versions and repro steps.
