### ISSUE TITLE
Android IndexOutOfBoundsException Crash

### ISSUE THREAD

**Issue by SYoder1** [wix/react-native-navigation#7570]
## 🐛 Bug Report
After updating to `v7.28.0` and React Native `0.68.2` we started seeing Android `java.lang.IndexOutOfBoundsException:` crashes in prod.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

I am not entirely sure how to reproduce it, but looking at the breadcrumb we have, it crashes as soon as a users navigates to new a screen. It's random on what screen it is, and is not always the same screen.

## Expected behavior

The app doesn't crash

## Actual Behavior
```
java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
        at java.util.ArrayList.get(ArrayList.java:437)
        at android.view.ViewTreeObserver$CopyOnWriteArray$Access.get(ViewTreeObserver.java:1291)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1080)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4093)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
        at android.view.Choreographer.doCallbacks(Choreographer.java:866)
        at android.view.Choreographer.doFrame(Choreographer.java:797)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

The index and size change between crash to crash, but are always equal to each other. 
7, 10, 13, 18, 19, 21, 59...

## Your Environment

- React Native Navigation version: 7.28.0
- React Native version: 0.68.2
- Platform(s) (iOS, Android, or both?): Android, OS 8 - 13
- Device info (Simulator/Device? OS version? Debug/Release?): Production release, all sorts of pyshical devices

## Reproducible Demo

N/A

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pierroo** [comment]
I might be late to the party, but did you ever find a solution to this @SYoder1 ?

**Comment by hoanght1995** [comment]
I encountered this issue too. version 7.40.1, RN 0.74.5
