### ISSUE TITLE
Application crash on reload debug or release

### ISSUE THREAD

**Issue by FawadMahmood** [wix/react-native-navigation#7594]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. Press the Back button
1. Reload the app, using a debugger or any library for restart in release build (mainly we do for language change)

## Expected behavior
the app should reload and rerun, or an instant reloads in a release.

(Write what you thought would happen.)

## Actual Behavior

application crashes with following error : 

FATAL EXCEPTION: main

java.lang.StackOverflowError: stack size 8188KB

FATAL EXCEPTION: main
Process: com.rnnstarter, PID: 10218
java.lang.StackOverflowError: stack size 8188KB
	at android.app.ContextImpl.getApplicationInfo(ContextImpl.java:499)
	at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:191)
	at android.app.OplusCompactWindowAppManager.blackPackageForCompactWindowAdjustment(OplusCompactWindowAppManager.java:176)
	at android.app.OplusCompactWindowAppManager.getCompactWindowMetrics(OplusCompactWindowAppManager.java:123)
	at android.content.res.ResourcesImplExt.getCompactWindowMetrics(ResourcesImplExt.java:601)
	at android.content.res.ResourcesImpl.getDisplayMetrics(ResourcesImpl.java:210)
	at android.content.res.Resources.getDisplayMetrics(Resources.java:2130)
	at com.reactnativenavigation.options.params.DensityPixel.<init>(DensityPixel.java:10)
	at com.reactnativenavigation.options.params.NullDensityPixel.<init>(NullDensityPixel.java:5)
	at com.reactnativenavigation.options.IconBackgroundOptions.<init>(IconBackgroundOptions.java:18)
	at com.reactnativenavigation.options.ButtonOptions.<init>(ButtonOptions.java:49)
	at com.reactnativenavigation.options.BackButton.<init>(BackButton.java:36)
	at com.reactnativenavigation.options.TopBarButtons.<init>(TopBarButtons.java:34)
	at com.reactnativenavigation.options.TopBarOptions.<init>(TopBarOptions.java:60)
	at com.reactnativenavigation.options.Options.<init>(Options.java:42)
	at com.reactnativenavigation.options.Options.copy(Options.java:63)
	at com.reactnativenavigation.viewcontrollers.parent.ParentController.resolveCurrentOptions(ParentController.java:67)
	at com.reactnativenavigation.viewcontrollers.parent.ParentController.resolveCurrentOptions(ParentController.java:66)
	at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.handleBack(BottomTabsController.java:165)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.handleBack(Navigator.java:110)
	at com.reactnativenavigation.NavigationActivity.invokeDefaultOnBackPressed(NavigationActivity.java:97)
	at com.facebook.react.ReactInstanceManager.invokeDefaultOnBackPressed(ReactInstanceManager.java:526)
	at com.facebook.react.ReactInstanceManager.onBackPressed(ReactInstanceManager.java:513)
	at com.reactnativenavigation.react.ReactGateway.onBackPressed(ReactGateway.java:66)

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- React Native Navigation version: 7.30.0-alpha.1
- React Native version: 0.69.5
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): One Plus

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by FawadMahmood** [comment]
I can confirm the issue is there, on the root activity hardware back button does not work as well, also the app crashes sometimes.
