### ISSUE TITLE
Application Crashes on setRoot after navigating from another page.

### ISSUE THREAD

**Issue by FawadMahmood** [wix/react-native-navigation#7602]
## 🐛 Bug Report

Thank you so much for such amazing work. 

FATAL EXCEPTION: main

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

FATAL EXCEPTION: main
Process: com.meal, PID: 1718
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5335)
	at android.view.ViewGroup.addView(ViewGroup.java:5156)
	at android.view.ViewGroup.addView(ViewGroup.java:5096)
	at android.view.ViewGroup.addView(ViewGroup.java:5068)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.YellowBoxDelegate.destroy(YellowBoxDelegate.kt:40)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.destroy(ViewController.java:290)
	at com.reactnativenavigation.viewcontrollers.stack.StackPresenter$$ExternalSyntheticLambda2.run(Unknown Source:2)
	at com.reactnativenavigation.utils.ObjectUtils.perform(ObjectUtils.java:11)
	at com.reactnativenavigation.viewcontrollers.stack.StackPresenter.onChildDestroyed(StackPresenter.java:186)
	at com.reactnativenavigation.viewcontrollers.stack.StackController.onChildDestroyed(StackController.java:154)
	at com.reactnativenavigation.viewcontrollers.child.ChildController.lambda$destroy$1$com-reactnativenavigation-viewcontrollers-child-ChildController(ChildController.java:90)
	at com.reactnativenavigation.viewcontrollers.child.ChildController$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.performOnParentController(ViewController.java:186)
	at com.reactnativenavigation.viewcontrollers.child.ChildController.destroy(ChildController.java:90)
	at com.reactnativenavigation.viewcontrollers.component.ComponentViewController.destroy(ComponentViewController.java:183)
	at com.reactnativenavigation.viewcontrollers.parent.ParentController$$ExternalSyntheticLambda3.on(Unknown Source:2)
	at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:133)
	at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:116)
	at com.reactnativenavigation.viewcontrollers.parent.ParentController.destroy(ParentController.java:157)
	at com.reactnativenavigation.viewcontrollers.stack.StackController.destroy(StackController.java:188)
	at com.reactnativenavigation.viewcontrollers.parent.ParentController$$ExternalSyntheticLambda3.on(Unknown Source:2)
	at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:133)
	at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:116)
	at com.reactnativenavigation.viewcontrollers.parent.ParentController.destroy(ParentController.java:157)
	at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.destroy(BottomTabsController.java:262)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.destroyPreviousRoot(Navigator.java:137)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.access$200(Navigator.java:36)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator$1.onSuccess(Navigator.java:160)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.RootPresenter.animateSetRootAndReportSuccess(RootPresenter.java:75)
	at com.reactnativenavigation.viewcontrollers.viewcontroller.RootPresenter.setRoot(RootPresenter.java:54)
	at com.reactnativenavigation.viewcontrollers.navigator.Navigator.setRoot(Navigator.java:155)
	at com.reactnativenavigation.react.NavigationModule.lambda$setRoot$0$com-reactnativenavigation-react-NavigationModule(NavigationModule.java:117)
	at com.reactnativenavigation.react.NavigationModule$$ExternalSyntheticLambda8.run(Unknown Source:8)
	at com.reactnativenavigation.react.NavigationModule.lambda$handle$14$com-reactnativenavigation-react-NavigationModule(NavigationModule.java:225)
	at com.reactnativenavigation.react.NavigationModule$$ExternalSyntheticLambda12.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8210)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. set root to tabs activity
2. navigate to another page
3. go back
4. try set root again, app will crash with the error I mentioned on top.

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- React Native Navigation version:7.30.0-alpha.1 because can't use older in .70 or .69
- React Native version: .70
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Device / Debug/Release(Both)

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by FawadMahmood** [comment]
This issue is not in [7.29.0](https://github.com/wix/react-native-navigation/releases/tag/7.29.0) , require to do some changes to make it work with .90

**Comment by bayazetyan** [comment]
This bug actual in versions 7.30.*
