### ISSUE TITLE
Android:Tried to create view after it has already been destroyed

### ISSUE THREAD

**Issue by TrustDec** [wix/react-native-navigation#7608]
Error
```
java.lang.RuntimeException: Tried to create view after it has already been destroyed
        at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.getView(ViewController.java:213)
        at com.reactnativenavigation.viewcontrollers.child.ChildController.getView(ChildController.java:44)
        at com.reactnativenavigation.viewcontrollers.stack.StackAnimator$pushWithoutElementTransitions$1.run(StackAnimator.kt:246)
        at com.reactnativenavigation.viewcontrollers.viewcontroller.-$$Lambda$WyAR0JEWmTiz3cWwZS9qp-P3Ddg.on(lambda)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:133)
        at com.reactnativenavigation.utils.CollectionUtils.forEach(CollectionUtils.java:127)
        at com.reactnativenavigation.viewcontrollers.viewcontroller.ViewController.lambda$onViewWillAppear$3$ViewController(ViewController.java:265)
        at com.reactnativenavigation.viewcontrollers.viewcontroller.-$$Lambda$ViewController$bfiHoKoA1KmT9QaA3BqT2KEB6CQ.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5856)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1026)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)
```
Environment

React Native Navigation version:  7.27.1、7.28.1、7.29.0
React Native version: "0.64.0"
Platform(s): Android
Device info: Version: Android 6.0 / vivo

**Comment by TrustDec** [comment]
The reason for this problem may be that page A jumps to page B. Because Page B executes Navigation.pop(this.props.componentId) without rendering, it will lead to this problem. This scene is necessary in our business scenario. This problem usually does not occur on iOS or mobile phones with better performance, because the page rendering speed is very fast.

**Comment by aspidvip** [comment]
me to

**Comment by TrustDec** [comment]
我已经收到你的邮件啦~,表着急,待我仔细查看
