### ISSUE TITLE
A problem occurred configuring project ':react-native-navigation'.

### ISSUE THREAD

**Issue by MenaiAla** [wix/react-native-navigation#7664]
## To Reproduce

1. `npm install --save react-native-navigation`
2. Implement [basic navigation](https://wix.github.io/react-native-navigation/docs/basic-navigation)
3. `npx react-native start`
4. `npx react-native run-android`

## Expected behavior

![stack1](https://user-images.githubusercontent.com/20143684/211147205-dde7e501-d9f1-4517-8484-73b86d66ad94.png)

## Actual Behavior

![Screenshot from 2023-01-07 12-11-05](https://user-images.githubusercontent.com/20143684/211147243-ad47b6ea-3fef-44bb-924c-a8a47406ef65.png)

```
warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info JS server already running.
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 5 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/alaeddine/Apps/GitaApp/node_modules/react-native-navigation/lib/android/app/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':react-native-navigation'.
> Plugin with id 'kotlin-android' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-navigation'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/alaeddine/Apps/GitaApp/node_modules/react-native-navigation/lib/android/app/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':react-native-navigation'.
> Plugin with id 'kotlin-android' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-navigation'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

    at makeError (/home/alaeddine/Apps/GitaApp/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /home/alaeddine/Apps/GitaApp/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/home/alaeddine/Apps/GitaApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/alaeddine/Apps/GitaApp/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
```

## Your Environment

- React Native Navigation version: 7.30.3
- React Native version: 0.70
- Platform(s) (iOS, Android, or both?): Android 12L x86_32
- Device info (Simulator/Device? OS version? Debug/Release?):  Pixel 6 pro API 32

**Comment by habovh** [comment]
Not sure if related, but updating `kotlinVersion` variable in `android/build.gradle` to `1.8.0` allowed me to compile.

However, I was having another error during the "check duplicates phase" of the build process.

![Screenshot 2023-03-02 at 10 41 55](https://user-images.githubusercontent.com/4186230/222391231-71bf7c51-fe9c-4a7c-a819-0e007560f077.png)

If others can confirm this change fixes their build issues as well, I guess I could make a PR to update the docs for more recent versions of React Native.

**Comment by LYevhen** [comment]
have same issue
