### ISSUE TITLE
Android crashes with "java.lang.NullPointerException - Attempt to invoke virtual method 'id1 com.reactnativenavigation.a.f()'"

### ISSUE THREAD

**Issue by zzzkasper-1995** [wix/react-native-navigation#7688]
### What happened?

Crashlytics has detected crashes in the application with the error message 'NavigationModule.navigator java.lang.NullPointerException - Attempt to invoke virtual method 'id1 com.reactnativenavigation.a.f()' on a null object reference'.

`NavigationModule.navigator
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'id1 com.reactnativenavigation.a.f()' on a null object reference
       at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:4)
       at com.reactnativenavigation.react.NavigationModule.access$100(NavigationModule.java)
       at com.reactnativenavigation.react.NavigationModule$1.lambda$onHostPause$0(NavigationModule.java:2)
       at com.reactnativenavigation.react.NavigationModule$1.$r8$lambda$188Rw-Gn_-JcbOeFEeH40BTzx_c(NavigationModule.java)
       at com.reactnativenavigation.react.NavigationModule$1$$InternalSyntheticLambda$0$88e0549b369d71b71f394a893b6ad827bf61740ff7f499c15c59fa020d35f16a$0.run(NavigationModule.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)`

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### Help us reproduce this issue!

I was unable to determine the steps to reproduce this error.

### In what environment did this happen?

React Native Navigation version: 7.31.1
React Native version: 0.70.6
Android version: > 11

**Comment by Aitchy13** [comment]
Did you find a solution for this @zzzkasper-1995 ? We've also experienced this error for quite some time, however the past week it's spiked considerably higher than normal

- React Native Navigation version: 7.29.0
- React Native: 0.70.7
- Android version: > 7

**Comment by N3TC4T** [comment]
Duplicated https://github.com/wix/react-native-navigation/issues/7531
