### ISSUE TITLE
A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

### ISSUE THREAD

**Issue by Harisene** [wix/react-native-navigation#7818]
### What happened?

I recently updated the RN version to 0.72.7. When I try to build the Android app I get the error as mentioned below.

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### Help us reproduce this issue!

Here is the error message from the terminal

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative62DebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m
```

### In what environment did this happen?

React Native Navigation version: 7.37.2
React Native version: 0.72.7
Has Fabric (React Native's new rendering system) enabled: (yes/no) no
Node version: 18.11.0
Java version: 11
Kotlin version: 1.8.22
Gradle version: 8.0.1
Device model: 
Android version:

**Comment by HaNguyenRN** [comment]
+1

**Comment by StragelX** [comment]
Got the same issue((( any updates on this?

**Comment by Harisene** [comment]
Try changing the Kotlin version. It could work. Not sure though.

**Comment by shafikgomez** [comment]
+1

**Comment by lwazi4787** [comment]
No one has the solution yet?

**Comment by Harisene** [comment]
I could not find a solution. Updating the RN version was a dead end for me.  So then I had to create a new RN project

**Comment by lwazi4787** [comment]
Did that work?

**Comment by Harisene** [comment]
yes

**Comment by Ahmad0811** [comment]
+1

**Comment by lyoung09** [comment]
+1 flutter

**Comment by mohanft** [comment]
+1

**Comment by marcelo-conilho** [comment]
+1

**Comment by Aryaman3007** [comment]
Anyone got the solution?

**Comment by jeanmrtns** [comment]
I'm facing the same issue. I'd love some help

**Comment by davidwinograd1** [comment]
same issue. any fixes?

**Comment by ravis-farooq** [comment]
By adding these two lines in **build.gradle** fixed the problem for me 
```
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
```

**Comment by amanRathod** [comment]
+1

**Comment by Varapraveen** [comment]
Hi, i am getting same kind of error in native Android , how to solve it /

**Comment by aahilalwani25** [comment]
I am getting the same error. Does anyone know how to resolve?

**Comment by binhtruong9418** [comment]
+1

**Comment by lucianolopezz** [comment]
I am getting same error after upgrade expo sdk 50

**Comment by Ammar-Abid92** [comment]
Facing the same issue in expo 47

**Comment by safaaroua** [comment]
+1

**Comment by Shudhanshu-Appnox** [comment]
+1

**Comment by ehcorrea** [comment]
+1

**Comment by gustavos00** [comment]
+1

**Comment by ayoubechc** [comment]
+1

**Comment by AlexVz95** [comment]
+1

**Comment by SheikhSajad** [comment]
+1

**Comment by Darmolar** [comment]
+1

**Comment by artpersona** [comment]
+ 1

**Comment by ayoubechc** [comment]
for me is a problem of syntax in mainActivity.jkt ans mainApplication.jkt

**Comment by robimuller** [comment]
+1

**Comment by tiagomelilo** [comment]
+1

**Comment by victorlucss** [comment]
+1

**Comment by Elvin2019** [comment]
In my case, I forgot to update `fabricEnabled`  in MainActivity.kt.

**Comment by SergioWiesner** [comment]
Tengo el mismo problema

* Where:
Build file '/Users/user/Proyectos/pccom/android/build.gradle' line: 32

* What went wrong:
A problem occurred evaluating root project 'pccom'.
> Could not read script '/Users/user/Proyectos/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.

**Comment by Buddhaa97** [comment]
same issue

**Comment by tuanduc2904** [comment]
same issue

**Comment by romualdbrsn** [comment]
+1

**Comment by julienclaerhout** [comment]
+1

**Comment by alexarruda** [comment]
+1

**Comment by Gavru4** [comment]
+1

**Comment by shreypdev** [comment]
Any updates? having same issue

**Comment by jesuscast** [comment]
Paste more of the stack trace, it will help debug

**Comment by jesuscast** [comment]
In our specific case using Expo, the issue was the target sdk version. For expo 50 it needs to be SDK 34
in app.json
```
"targetSdkVersion": 34
```

Essentially, if the target is different, the gradle will fail to build. But it can also fail for many other reasons. But I cannot tell about your issue without a more complete stacktrace.

**Comment by iZenrix** [comment]
help :)

**Comment by ruchaliulistech** [comment]
same

**Comment by Osamasomy** [comment]
same issue

**Comment by dylansiew** [comment]
`/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:763:63: warning: Direct call to eval(), but lexical scope is not supported.
...typeof expo === "undefined" ? eval("require") : function (moduleId) {
                                 ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:843:24: warning: the variable "URL" was not declared in function "_fetch"
        props[0] = new URL(props[0], window.location?.origin).toString();
                       ^~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:865:42: warning: the variable "fetch" was not declared in anonymous function " 22#"
      value: wrapFetchWithWindowLocation(fetch)
                                         ^~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:1662:20: warning: the variable "Promise" was not declared in function "promiseMethodWrapper"
        return new Promise(function (resolve, reject) {
                   ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:2042:18: warning: the variable "DebuggerInternal" was not declared in function "__shouldPauseOnThrow"
          typeof DebuggerInternal !== 'undefined' &&
                 ^~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:4679:5: warning: the variable "setImmediate" was not declared in function "handleResolved"
    setImmediate(function () {
    ^~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:6151:9: warning: the variable "setTimeout" was not declared in anonymous function " 214#"
        setTimeout(function () {
        ^~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9033:5: warning: the variable "Headers" was not declared in anonymous function " 287#"
    Headers,
    ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9034:5: warning: the variable "Request" was not declared in anonymous function " 287#"
    Request,
    ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9035:5: warning: the variable "Response" was not declared in anonymous function " 287#"
    Response
    ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9192:24: warning: the variable "FileReader" was not declared in function "readBlobAsArrayBuffer"
      var reader = new FileReader();
                       ^~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9243:36: warning: the variable "Blob" was not declared in anonymous function " 298#"
        } else if (support.blob && Blob.prototype.isPrototypeOf(body)) {
                                   ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9245:40: warning: the variable "FormData" was not declared in anonymous function " 298#"
        } else if (support.formData && FormData.prototype.isPrototypeOf(body)) {
                                       ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9247:44: warning: the variable "URLSearchParams" was not declared in anonymous function " 298#"
...e if (support.searchParams && URLSearchParams.prototype.isPrototypeOf(body...
                                 ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9366:26: warning: the variable "AbortController" was not declared in anonymous function " 304#"
          var ctrl = new AbortController();
                         ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9500:23: warning: the variable "XMLHttpRequest" was not declared in anonymous function " 308#"
        var xhr = new XMLHttpRequest();
                      ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9045:71: warning: the variable "self" was not declared in anonymous function " 290#"
...undefined' && globalThis || typeof self !== 'undefined' && self ||
                                      ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:20612:31: warning: the variable "nativeFabricUIManager" was not declared in anonymous function " 619#"
  var _nativeFabricUIManage = nativeFabricUIManager,
                              ^~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:20640:21: warning: the variable "clearTimeout" was not declared in anonymous function " 619#"
    cancelTimeout = clearTimeout;
                    ^~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25270:30: warning: the variable "__REACT_DEVTOOLS_GLOBAL_HOOK__" was not declared in anonymous function " 619#"
  if ("undefined" !== typeof __REACT_DEVTOOLS_GLOBAL_HOOK__) {
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25385:27: warning: the variable "performance" was not declared in anonymous function " 650#"
  if ("object" === typeof performance && "function" === typeof performance.no...
                          ^~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25408:26: warning: the variable "navigator" was not declared in anonymous function " 650#"
  "undefined" !== typeof navigator && undefined !== navigator.scheduling && u...
                         ^~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25518:37: warning: the variable "MessageChannel" was not declared in anonymous function " 650#"
  };else if ("undefined" !== typeof MessageChannel) {
                                    ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:25533:34: warning: the variable "nativeRuntimeScheduler" was not declared in anonymous function " 650#"
... = "undefined" !== typeof nativeRuntimeScheduler ? nativeRuntimeScheduler....
                             ^~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:38844:34: warning: the variable "requestAnimationFrame" was not declared in function "start 9#"
...    this._animationFrame = requestAnimationFrame(this.onUpdate.bind(this));
                              ^~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:73912:11: warning: the variable "cancelAnimationFrame" was not declared in function "cleanup"
          cancelAnimationFrame(this.splashScreenAnimationFrame);
          ^~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:80558:20: warning: the variable "localStorage" was not declared in function "ColorSchemeStore"
        if (typeof localStorage !== "undefined") {
                   ^~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:80561:13: warning: the variable "document" was not declared in function "ColorSchemeStore"
            document.documentElement.classList.add("dark");
            ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:86345:100: warning: the variable "location" was not declared in function "registerSensor 1#"
...(0, _PlatformChecker.isWeb)() && location.protocol !== 'https:' ? ' Make s...
                                    ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:87611:26: warning: Direct call to eval(), but lexical scope is not supported.
            workletFun = eval('(' + initData.code + '\n)');
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:87634:112: warning: the variable "_toString" was not declared in function "valueUnpacker"
...recognized by value unpacker: "${_toString(objectToUnpack)}".`);
                                    ^~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:88488:11: warning: the variable "queueMicrotask" was not declared in anonymous function " 2845#"
          queueMicrotask(function () {
          ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:88614:33: warning: the variable "_WORKLET" was not declared in function "runOnJS"
      if (SHOULD_BE_USE_WEB || !_WORKLET) {
                                ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:105395:26: warning: the variable "structuredClone" was not declared in function "createAnimationWithExistingTransform"
      newAnimationData = structuredClone(_config.AnimationsData[animationName]);
                         ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:105689:27: warning: the variable "HTMLElement" was not declared in function "findDescendantWithExitingAnimation"
    if (!(node instanceof HTMLElement)) {
                          ^~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:105715:24: warning: the variable "MutationObserver" was not declared in function "addHTMLMutationObserver"
    var observer = new MutationObserver(function (mutationsList) {
                       ^~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:105764:41: warning: the variable "getComputedStyle" was not declared in function "fixElementPosition"
...entBorderTopValue = parseInt(getComputedStyle(parent).borderTopWidth);
                                ^~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:110120:5: warning: the variable "jest" was not declared in function "beforeTest"
    jest.useFakeTimers();
    ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:110656:26: warning: the variable "_getAnimationTimestamp" was not declared in function "computeEasingProgress"
      var elapsedTime = (_getAnimationTimestamp() - startingTimestamp) / 1000;
                         ^~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:168680:16: warning: the variable "SharedArrayBuffer" was not declared in function "from"
    if (typeof SharedArrayBuffer !== 'undefined' && (isInstance(value, Shared...
               ^~~~~~~~~~~~~~~~~
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-vision-camera:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org/.
BUILD FAILED in 5m 31s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
288 actionable tasks: 288 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.`

**Comment by GalMarkelj** [comment]
Same issue as @Osamasomy

**Comment by JaRoMasterDev** [comment]
+1

**Comment by JaRoMasterDev** [comment]
I was facing this issue in my own app:compileDebugKotlin task.
After a while I figured that I had forgotten to call the ReactActivity constructor in my MainActivity.kt file after upgrading from java to kotlin.

class MainActivity : ReactActivity() {

Forgot the "()".

Maybe this helps someone in here

**Comment by jaaywags** [comment]
I was facing this issue too. Turned out I misspelled my app name in MainApplication.kt. I used the React Native Upgrade helper tool and must have copied that files contents and didn't update the app name.

[This comment got me pointed in the right direction](https://github.com/software-mansion/react-native-screens/issues/1716#issuecomment-2021753753).

After that, I got some other errors similar to this
`MainActivity.kt:26:13 Expecting member declaration`

Going to that file, I realized I had copied some logic form the previous version for RNBootSplash. [I went to their website and got the up-to-date code](https://github.com/zoontek/react-native-bootsplash?tab=readme-ov-file#android-1).

**Comment by Osamasomy** [comment]
i solved this by adding few lines. see below attachment
<img width="1208" alt="image" src="https://github.com/wix/react-native-navigation/assets/29625742/435fbb2c-614d-4fd2-99e8-39702abcedbf">

**Comment by TROOLLER** [comment]
same issue here

**Comment by Cathyccccc** [comment]
I update file -- MainActivity.kt , like this :

`class MainActivity : NavigationActivity() {

  // override fun getMainComponentName(): String = "AwesomeProject"

  // override fun createReactActivityDelegate(): ReactActivityDelegate =
  //   DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
  }
}`

may be you can find some errors in terminal tips, such as :
`e: override nothing getMainComponentName`

you can follow the official document : [https://wix.github.io/react-native-navigation/docs/installing#2-update-mainactivityjava](url)

when i run `npx run-link`, the terminal show some errors :
![link_react-native-navigation_error](https://github.com/user-attachments/assets/01ac933d-bad4-4ae5-a047-4917cb5c0b98)
i think i should update these files manually.

**My version:**
"react-native-navigation": "^7.40.1",
"react-native": "^0.73.9",
android/build.gradle:
`
...
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.22"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle") // version 8.6
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
    }
...
`

**Comment by sudeshvs** [comment]
> Hey I solved this issue by upgrading the react-native-screensb(because my error was
> 
> > > Task :react-native-screens:compileReleaseKotlin FAILED
> 
> , i think it was the conflict in the kotlin version mentioned in the build.gradle under node moduls -> react-native-screens-> android and the one i was using in the build.gradle of the root project. (that is android -> build.gradle).

can you please elaborate ?
im facing the same issues

"react": "^17.0.2",
"react-native": "0.65.3",
"react-native-screens": "3.14.0",

**Comment by RadheSwil** [comment]
same issue

"react-native": "0.74.1",
 "react-native-vision-camera": "3.5.1"
Execution failed for task ':react-native-vision-camera:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

**Comment by gusilveiramp** [comment]
+1

**Comment by gern132** [comment]
+1

**Comment by SuyanShrestha** [comment]
In my case, I had added an onCreate method for react-native-screens, but forgot to import "android.os.Bundle"

**Comment by KrisLau** [comment]
Hardcoding these values instead of using findProperty fixed it for me:

![Image](https://github.com/user-attachments/assets/02eec01c-85ff-41ef-a8a5-98a374c9e1cc)

**Comment by huynhduc43** [comment]
I faced this issue when setting up React Native Firebase for a non-Expo project.

When creating the Android application in the Firebase console, I updated my package name from the initial project name (`com.fakename`) to my desired name (`com.realname`). I also changed the `namespace` and `applicationId` fields in `/android/app/build.gradle` to `com.realname`.

After that, I encountered this error when running `npx react-native run-android`.

I fixed it by finding and replacing all occurrences of `com.fakename` with `com.realname` in the following files:
`android/app/src/main/java/com/{project-name}/MainActivity.kt`
`android/app/src/main/java/com/{project-name}/MainApplication.kt`

Maybe you need to clean the project first by running:
```
cd android
./gradlew clean
cd ..
npx react-native run-android
```

Hope this helps someone here!

**Comment by jonelvinnaorbe** [comment]
**Try this fix:**

1. Update the **distributionUrl** at android/gradle/gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip
2. Open terminal and go to android folder and run "/.gradlew clean" and "./gradlew --stop"
 
Then run your app again.

**Comment by itsdlhqcp** [comment]
Same issue here 

Task :app:compileDebugKotlin
e: androidx.compose.compiler.plugins.kotlin.IncompatibleComposeRuntimeVersionException: The Compose Compiler requires the Compose Runtime to be on the class path, but none could be found. The compose compiler plugin you are using (version 1.5.15) expects a minimum runtime version of 1.0.0.
        at androidx.compose.compiler.plugins.kotlin.VersionChecker.noRuntimeOnClasspathError(VersionChecker.kt:195)
        at androidx.compose.compiler.plugins.kotlin.VersionChecker.check(VersionChecker.kt:168)
        at androidx.compose.compiler.plugins.kotlin.ComposeIrGenerationExtension.generate(ComposeIrGenerationExtension.kt:81)
        at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda$1(JvmIrCodegenFactory.kt:225)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:107)
        at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:255)
        at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:59)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:224)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:463)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:62)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:477)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:400)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:281)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:125)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:657)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:105)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1624)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)

                                                                                                                                                                       
> Task :app:compileDebugKotlin FAILED                                                                                                                                  

FAILURE: Build failed with an exception.                                                                                                                               

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.                                                                                                                   
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details

**Comment by odera89** [comment]
@itsdlhqcp did you fixed it? i have same issue...

**Comment by HemanshuYPatil** [comment]
please provide any solution

**Comment by maitrongnhan99** [comment]
I ran into the same issue recently and fixed it by undoing the changes in the yarn.lock file. Some dependency versions had changed unexpectedly during installation.

**Comment by Manikandan-0311** [comment]
When  run the react native application  I`m encountered  issue  


e: This version (1.3.2) of the Compose Compiler requires Kotlin version 1.7.20 but you appear to be using Kotlin version 1.9.24 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).

FAILURE: Build failed with an exception.

Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction 
   > Compilation error. See log for more details

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2m 2s

Versions:
   buildToolsVersion = "35.0.0"
        minSdkVersion = 24
        compileSdkVersion = 35
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
         kotlinVersion = "1.9.24"
        agp_version = '8.7.1'

      react native -0.76.2
    "stripe/stripe-react-native": "^0.46.0",


Anyone please provide solution to me  😢

**Comment by Aman8385** [comment]
I don't know why its working, but i tried this solution by mistake and seriously its working for me, I am Flutter person solution is--

"Whenever you want to build, run, or generate a signed APK in Flutter, remove apply false from id
 'dev.flutter.flutter-plugin-loader' version '1.0.0'. But if you're only syncing the project in Android Studio For Android only,
   keep apply false there."

**Comment by mohitkhandal-create** [comment]
Still facing the issue and no solution is helping ):
