### ISSUE TITLE
Android build failed when using react-native-video ExoPlayer

### ISSUE THREAD

**Issue by flavordaaave** [wix/react-native-navigation#867]
### Issue Description
When using `react-native-video` with ExoPlayer on a "normal" `react-native` Project everything is working fine but as soon as I try to use `react-native-navigation` build fails with following error:

```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexIndexOverflowException: Cannot merge new index 67232 into a non-jumbo instruction!
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexIndexOverflowException: Cannot merge new index 67232 into a non-jumbo instruction!
        at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:109)
        at com.android.dx.merge.InstructionTransformer.access$800(InstructionTransformer.java:26)
        at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:72)
        at com.android.dx.io.CodeReader.callVisit(CodeReader.java:114)
        at com.android.dx.io.CodeReader.visitAll(CodeReader.java:89)
        at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:49)
        at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:842)
        at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:813)
        at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:786)
        at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:682)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:542)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    
:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
```

### Steps to Reproduce / Code Snippets / Screenshots
- Init new react-native project
- Install `react-native-video` component
- Compile android
=> App is running
- Switch to ExoPlayer (see instructions below)
- Compile android
=> App is running
- Switch back to NON-ExoPlayer
- Install `react-native-navigation`
- Compile android
=> App is running
- Switch back to ExoPlayer
- Compile android
=> Build FAILS

In order to use ExoPlayer change `build.gradle` to
```
~~compile project(':react-native-video')~~
compile project(':react-native-video-exoplayer')
```
and `settings.gradle` to
```
~~include ':react-native-video'~~
~~include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')~~
include ':react-native-video-exoplayer'
project(':react-native-video-exoplayer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

### Environment
* React Native Navigation version: 2.0.0-experimental.246
* React Native version: 0.42.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Moto G4 Debug

**Comment by guyca** [comment]
Hey @flavordaaave 
Your app has hit the method count limit. Congratulations, you have lots of code (or at least your dependencies do).
You can overcome this by either enabling multi dex or by [enabling proguard in debug builds](http://stackoverflow.com/questions/16559723/is-it-possible-to-use-proguard-in-debug-mode).
I suggest you enable proguard in debug, it's easier and faster 👍

**Comment by grigored** [comment]
I couldn't get proguard to work with `react-native run-android` (was working when running from android studio). Enabling multi dex was super easy, just had to add `multiDexEnabled true` and everything worked.
