### ISSUE TITLE
app crash when not connected to packager, is possible to test app in device without running packager?

### ISSUE THREAD

**Issue by xabree** [wix/react-native-navigation#975]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

app crash when not connected to packager, is possible to test app in device without running packager?

### Steps to Reproduce / Code Snippets / Screenshots

react-native run-android
close app in device
close running packager
open again then app crash.

![screen shot 2017-04-04 at 9 21 23 am](https://cloud.githubusercontent.com/assets/24905186/24639549/afba3828-191a-11e7-81aa-29882efdf87c.png)

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version:  2.0.0-experimental.265
* React Native version: 0.42.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): device

**Comment by guyca** [comment]
The packager needs to run when running in debug mode - it's what's serving your files. Only way to run with out the packager is in release mode.

**Comment by xabree** [comment]
@guyca thx for the answer.

after I install app on android device, I want to test app without running packager. app always crash when I opened.

**I found this issue when I require asset in navigatorButton**
```
static navigatorButtons = {
        rightButtons: [
            {
                icon: require('../assets/img/navicon_edit.png'),
                id: 'compose',
                testID: 'e2e_is_awesome'
            }
        ]
    };
```
but not error when I require asset file in Image source component.

```
<Image style={{
                    width: undefined,
                    height: 100
                }} source={require('../assets/img/colors.png')}/>
```

the issue is resolve when I remove icon from static navigatorButton, thx.

**error log**

```
04-05 08:06:32.847 11446 11446 E AndroidRuntime: FATAL EXCEPTION: main
04-05 08:06:32.847 11446 11446 E AndroidRuntime: Process: com.awesomelist, PID: 11446
04-05 08:06:32.847 11446 11446 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.awesomelist/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.RuntimeException: http://192.168.10.12:8081/assets/assets/img/navicon_edit@2x.png?platform=android&hash=e9aa7685c6c2173052bc81eb22f52b6b
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:153)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5458)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: Caused by: java.lang.RuntimeException: http://192.168.10.12:8081/assets/assets/img/navicon_edit@2x.png?platform=android&hash=e9aa7685c6c2173052bc81eb22f52b6b
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.react.JsDevImageLoader.loadIcon(JsDevImageLoader.java:27)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.react.ImageLoader.loadImage(ImageLoader.java:14)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser.parseSingleButton(TitleBarButtonParamsParser.java:26)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser$1.parse(TitleBarButtonParamsParser.java:17)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser$1.parse(TitleBarButtonParamsParser.java:14)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.Parser.parseBundle(Parser.java:35)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.TitleBarButtonParamsParser.parseButtons(TitleBarButtonParamsParser.java:14)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.ButtonParser.parseRightButton(ButtonParser.java:20)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:33)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.ActivityParamsParser.parse(ActivityParamsParser.java:18)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.controllers.NavigationCommandsHandler.parseActivityParams(NavigationCommandsHandler.java:29)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.reactnativenavigation.controllers.NavigationActivity.onCreate(NavigationActivity.java:65)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6323)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	... 9 more
04-05 08:06:32.847 11446 11446 E AndroidRuntime: Caused by: java.net.ConnectException: failed to connect to /192.168.10.12 (port 8081): connect failed: ECONNREFUSED (Connection refused)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at libcore.io.IoBridge.connect(IoBridge.java:124)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at java.net.Socket.connect(Socket.java:884)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.Connection.connect(Connection.java:152)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:342)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
04-05 08:06:32.847 11446 11446 E AndroidRuntime: 	at java.net.URL.openStream(URL
04-05 08:06:32.849  1362  2558 W ActivityManager:   Force finishing activity com.awesomelist/com.reactnativenavigation.controllers.NavigationActivity

```

**Comment by guyca** [comment]
When running in debug mode images are served over the bridge as urls - they are not packaged in the apk. That's why you need to have the device connected to your computer and have the packager running.
